// @generated by rspice-veriloga; do not edit.
#![allow(dead_code, non_snake_case, unused_parens, unused_variables)]

use super::state::Instance;
use rspice_veriloga_runtime::GeneratedEvalContext;
pub use rspice_veriloga_runtime::{GeneratedNoiseComplex, GeneratedNoiseDescriptor, GeneratedNoiseEndpoint, GeneratedNoiseEvaluation, GeneratedNoiseEvaluationError, GeneratedNoiseEvaluationRef, GeneratedNoiseInjectionDescriptor, GeneratedNoiseInjectionEvaluation, GeneratedNoiseKind, GeneratedNoiseProcessDescriptor, GeneratedNoiseProcessEvaluationRef, GeneratedNoiseProcessVisitor, GeneratedNoiseVisitor};

use super::stamp::{canonical_model_preprocess, CANONICAL_MODEL_STAGE_SLOTS, canonical_instance_preprocess, CANONICAL_INSTANCE_STAGE_SLOTS, canonical_temperature_preprocess, CANONICAL_TEMPERATURE_STAGE_SLOTS};
use rspice_veriloga_runtime::install_generated_stage_values;
pub static NOISE_SOURCES: [GeneratedNoiseDescriptor; 2] = [
    GeneratedNoiseDescriptor { mechanism: "WHITE_D_S_THERMAL", label: Some("thermal"), kind: GeneratedNoiseKind::White, equation: 8, is_current: true, branch_ordinal: None, pos: GeneratedNoiseEndpoint { local_node: Some(0), name: "d", is_internal: false }, neg: GeneratedNoiseEndpoint { local_node: Some(2), name: "s", is_internal: false }, table_len: 0, table_log_interp: false },
    GeneratedNoiseDescriptor { mechanism: "FLICKER_D_S_FLICKER", label: Some("flicker"), kind: GeneratedNoiseKind::Flicker, equation: 8, is_current: true, branch_ordinal: None, pos: GeneratedNoiseEndpoint { local_node: Some(0), name: "d", is_internal: false }, neg: GeneratedNoiseEndpoint { local_node: Some(2), name: "s", is_internal: false }, table_len: 0, table_log_interp: false },
];

impl Instance {
    pub fn evaluate_noise_sources(&self, ctx: &GeneratedEvalContext<'_>, visitor: &mut dyn GeneratedNoiseVisitor) -> Result<(), GeneratedNoiseEvaluationError> {
        if !self.multiplicity.is_finite() || self.multiplicity <= 0.0 {
            return Err(GeneratedNoiseEvaluationError::InvalidMultiplicity { value: self.multiplicity });
        }
        let mut prepared = [0.0; 93];
        let produced = canonical_model_preprocess(
            &self.params.values,
            &self.param_given[..],
            self.multiplicity,
            &prepared[..],
            ctx.temperature(),
            ctx.thermal_voltage(),
        );
        install_generated_stage_values(&mut prepared[..], &produced, &CANONICAL_MODEL_STAGE_SLOTS);
        let produced = canonical_instance_preprocess(
            &self.params.values,
            &self.param_given[..],
            self.multiplicity,
            &prepared[..],
            ctx.temperature(),
            ctx.thermal_voltage(),
        );
        install_generated_stage_values(&mut prepared[..], &produced, &CANONICAL_INSTANCE_STAGE_SLOTS);
        let produced = canonical_temperature_preprocess(
            &self.params.values,
            &self.param_given[..],
            self.multiplicity,
            &prepared[..],
            ctx.temperature(),
            ctx.thermal_voltage(),
        );
        install_generated_stage_values(&mut prepared[..], &produced, &CANONICAL_TEMPERATURE_STAGE_SLOTS);
        let parameters = &self.params.values;
        let temperature = ctx.temperature();
        let staged = &prepared[..];
        let node_potentials = [ctx.node_voltage(self.nodes[0]), ctx.node_voltage(self.nodes[1]), ctx.node_voltage(self.nodes[2]), ctx.node_voltage(self.nodes[3])];
		let A=0f64;
		let B=staged[32];
		let C=staged[40];
		let D=parameters[0];
		let E=0.5f64;
		let F=staged[39];
		let G=staged[79]!=0.0;
		let I=staged[80];
		let K=staged[35];
		let L=staged[24];
		let M=1f64;
		let N=staged[27];
		let O=staged[37];
		let P=staged[19];
		let Q=staged[16];
		let R=staged[33];
		let S=staged[31];
		let T=staged[3];
		let U=staged[29];
		let V=staged[12];
		let W=node_potentials[3];
		let AC=2f64;
		let AJ=staged[26];
		let AK=0.25f64;
		let AW=1.3f64;
		let AX=1.6f64;
		let BD=1.55f64;
		let BK=1e-64f64;
		let BR=staged[28];
		let EG=staged[87]!=0.0;
		let EJ=parameters[21];
		let FQ=0f64;
		let FU=parameters[1];
		let FX=parameters[41];
		let J=if G{
		let H=temperature+ parameters[2];
		H
		}else{
		I
		};
		let X=D* (node_potentials[1]- W);
		let Y=D* (node_potentials[2]- W);
		let Z=D* (node_potentials[0]- W);
		let AA=(Z- Y)< A;
		let AF;
		let AH;
		if AA{
		AF=Z;
		AH=Y;
		}else{
		AF=Y;
		AH=Z;
		}
		let AB=(((X- staged[14])- staged[15])+ Q)+ staged[17];
		let AD=((AB* AB)+ staged[18]).sqrt();
		let AE=E* (AB+ AD);
		let AG=Q+ AF;
		let AI=Q+ AH;
		let AL=(AE+ staged[22]).sqrt();
		let AM=AE- Q;
		let AN=AL- staged[23];
		let AO=(((AM- (V* AN))+ Q)+ L).sqrt();
		let AP=(V- (staged[25]* (((E* (AG+ (((AG* AG)+ P).sqrt()))).sqrt())+ ((E* (AI+ (((AI* AI)+ P).sqrt()))).sqrt()))))+ (AJ* AO);
		let AQ=((AP* AP)+ L).sqrt();
		let AR=E* (AP+ AQ);
		let AS=(AE+ ((AK* AR)* AR)).sqrt();
		let AT=AM- (AR* (AS- (E* AR)));
		let AU=(AT- AF)* N;
		let AV=AU> -0.35f64;
		let BM;
		if AV{
		let AY=AC/ ((AW+ AU)- ((AU+ AX).ln()));
		let AZ=M+ AU;
		let BA=(AC+ AY)/ (AZ+ (AY.ln()));
		let BB=(AZ+ (BA.ln()))/ (AC+ BA);
		BM=BB;
		}else{
		let BC=AU> -15f64;
		let BN;
		if BC{
		let BE=BD+ ((-AU).exp());
		let BF=M+ AU;
		let BG=(AC+ BE)/ (BF+ (BE.ln()));
		let BH=(BF+ (BG.ln()))/ (AC+ BG);
		BN=BH;
		}else{
		let BI=AU> -23f64;
		let BO=if BI{
		let BJ=M/ (AC+ ((-AU).exp()));
		BJ
		}else{
		let BL=(AU.exp())+ BK;
		BL
		};
		BN=BO;
		}
		BM=BN;
		}
		let BP=BM* (M+ BM);
		let BQ=BP.sqrt();
		let BS=(AK+ (BQ* BR)).sqrt();
		let BT=U* (BS- E);
		let BU=E* (AH- AF);
		let BV=P* ((parameters[25]* (BQ- (BT* N)))+ 0.015625f64);
		let BW=((BT* BT)+ BV).sqrt();
		let BX=BU- BT;
		let BY=((BX* BX)+ BV).sqrt();
		let BZ=BW- BY;
		let CA=(AK+ ((BQ- (0.75f64* (BP.ln())))* BR)).sqrt();
		let CB=(U* (CA- E))+ staged[30];
		let CC=BU- CB;
		let CD=((CB* CB)+ BV).sqrt();
		let CE=((CC* CC)+ BV).sqrt();
		let CF=((((AT- BU)- AF)- CD)+ CE)* N;
		let CG=CF> -0.35f64;
		let CT;
		if CG{
		let CH=AC/ ((AW+ CF)- ((CF+ AX).ln()));
		let CI=M+ CF;
		let CJ=(AC+ CH)/ (CI+ (CH.ln()));
		let CK=(CI+ (CJ.ln()))/ (AC+ CJ);
		CT=CK;
		}else{
		let CL=CF> -15f64;
		let CU;
		if CL{
		let CM=BD+ ((-CF).exp());
		let CN=M+ CF;
		let CO=(AC+ CM)/ (CN+ (CM.ln()));
		let CP=(CN+ (CO.ln()))/ (AC+ CO);
		CU=CP;
		}else{
		let CQ=CF> -23f64;
		let CV=if CQ{
		let CR=M/ (AC+ ((-CF).exp()));
		CR
		}else{
		let CS=(CF.exp())+ BK;
		CS
		};
		CU=CV;
		}
		CT=CU;
		}
		let CW=CT* (M+ CT);
		let CX=(T- (B* ((M+ ((BU- BZ)/ S)).ln())))+ ((BU+ BZ)* R);
		let CY=((CX* CX)+ staged[34]).sqrt();
		let CZ=E* (CX+ CY);
		let DA=(AT- AH)* N;
		let DB=DA> -0.35f64;
		let DO;
		if DB{
		let DC=AC/ ((AW+ DA)- ((DA+ AX).ln()));
		let DD=M+ DA;
		let DE=(AC+ DC)/ (DD+ (DC.ln()));
		let DF=(DD+ (DE.ln()))/ (AC+ DE);
		DO=DF;
		}else{
		let DG=DA> -15f64;
		let DP;
		if DG{
		let DH=BD+ ((-DA).exp());
		let DI=M+ DA;
		let DJ=(AC+ DH)/ (DI+ (DH.ln()));
		let DK=(DI+ (DJ.ln()))/ (AC+ DJ);
		DP=DK;
		}else{
		let DL=DA> -23f64;
		let DQ=if DL{
		let DM=M/ (AC+ ((-DA).exp()));
		DM
		}else{
		let DN=(DA.exp())+ BK;
		DN
		};
		DP=DQ;
		}
		DO=DP;
		}
		let DR=AK+ BP;
		let DS=AK+ (DO* (M+ DO));
		let DT=DR.sqrt();
		let DU=DS.sqrt();
		let DV=DT+ DU;
		let DW=DV* DV;
		let DX=AT+ Q;
		let DY=DX+ 1e-6f64;
		let DZ=AC* (DY.sqrt());
		let EA=V/ DZ;
		let EB=V/ (DZ+ V);
		let EC=M+ EA;
		let ED=(-EC)* K;
		let EE=ED* (((1.33333332f64* ((DS+ (DU* DT))+ DR))/ DV)- M);
		let EF=(staged[36]* DZ)- (EB* EE);
		let EW;
		let FL;
		let FM;
		let FN;
		let FP;
		if EG{
		let EH=((AT* AT)+ O).sqrt();
		let EI=E* (AT+ EH);
		let EK=M+ (EJ* EI);
		let EL=staged[38]/ (CZ* EK);
		EW=EL;
		FL=EI;
		FM=EK;
		FN=EH;
		FP=FQ;
		}else{
		let EM=EF+ (F* EE);
		let EN=EM> A;
		let EQ=if EN{
		let EO=M+ (C* EM);
		EO
		}else{
		let EP=M- (C* EM);
		EP
		};
		let ER=staged[41]/ (CZ* EQ);
		EW=ER;
		FL=A;
		FM=A;
		FN=A;
		FP=EQ;
		}
		let ES=DX+ staged[42];
		let ET=ES.sqrt();
		let EU=M+ (V/ (AC* ET));
		let EV=BP- CW;
		let EX=(O* EU)* EW;
		let EY=EW* (EE.abs());
		let EZ=AE/ AD;
		let FA=((-(DX/ AS))* ((((AJ* (AR/ (AQ+ AQ)))* AN)/ (AL* AO))* EZ))+ ((M- (AR/ (AS+ AS)))* EZ);
		let FB=(BM* N)* FA;
		let FC=(K/ ((4f64* BS)* BQ))* FB;
		let FD=staged[44]* ((FB* (K/ (BQ+ BQ)))- FC);
		let FE=(((BT* FC)+ FD)* (M/ BW))- (((BX* (-FC))+ FD)* (M/ BY));
		let FF=((K* (BQ- 1.5f64))/ ((4f64* CA)* BP))* FB;
		let FG=(CT* N)* ((FA- (((CB* FF)+ FD)* (M/ CD)))+ (((CC* (-FF))+ FD)* (M/ CE)));
		let FH=(M/ CY)* ((-((-(B/ ((S+ BU)- BZ)))* FE))+ (FE* R));
		let FI=(ED* 0.66666666f64)/ DW;
		let FJ=(((((-EA)* EE)/ (((AC+ EA)+ EA)* DY))* FA)+ ((FI* (DT+ (AC* DU)))* FB))+ ((FI* (DU+ (AC* DT)))* ((DO* N)* FA));
		let FK=(-EB)* (((EC- (EE/ ((AC* EC)* DY)))* FA)+ FJ);
		let FS=if EG{
		let FO=(-FH)- (((EJ* FL)/ (FM* FN))* FA);
		FO
		}else{
		let FR=(-FH)+ ((C/ FP)* (FK+ (F* FJ)));
		FR
		};
		let FT=EX* ((((((staged[45]/ (((4f64* EU)* ET)* ES))* FA)+ FS)* EV)+ FB)- FG);
		let FY;
		let FZ;
		let GA;
		let GB;
		let GC;
		if FU!=0.0{
		let FV=(5.5224904e-23f64* J)* EY;
		let FW=((parameters[42]* FT)* FT)/ (((staged[10]* parameters[8])* T)* parameters[13]);
		FY=M;
		FZ=FV;
		GA=M;
		GB=FW;
		GC=FX;
		}else{
		FY=A;
		FZ=A;
		GA=A;
		GB=A;
		GC=A;
		}
        if !(FY != 0.0) {
            if !visitor.visit(0, GeneratedNoiseEvaluationRef { active: false, psd: 0.0, exponent: None, table_operands: &[] }) { return Ok(()); }
        } else {
            let psd = FZ;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 0, quantity: "psd", value: psd }); }
            let psd = psd.abs();
            let exponent: Option<f64> = None;
            let table_operands = [];
            let psd = psd * self.multiplicity;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 0, quantity: "scaled psd", value: psd }); }
            if !visitor.visit(0, GeneratedNoiseEvaluationRef { active: true, psd, exponent, table_operands: &table_operands }) { return Ok(()); }
        }
        if !(GA != 0.0) {
            if !visitor.visit(1, GeneratedNoiseEvaluationRef { active: false, psd: 0.0, exponent: None, table_operands: &[] }) { return Ok(()); }
        } else {
            let psd = GB;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 1, quantity: "psd", value: psd }); }
            let psd = psd.abs();
            let exponent: Option<f64> = Some(GC);
            if let Some(value) = exponent { if !value.is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 1, quantity: "exponent", value }); } }
            let table_operands = [];
            let psd = psd * self.multiplicity;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 1, quantity: "scaled psd", value: psd }); }
            if !visitor.visit(1, GeneratedNoiseEvaluationRef { active: true, psd, exponent, table_operands: &table_operands }) { return Ok(()); }
        }
        Ok(())
    }
}

use rspice_veriloga_runtime::{L2};

pub static GROUPED_NOISE_PROCESSES: [GeneratedNoiseProcessDescriptor; 2] = [
    GeneratedNoiseProcessDescriptor { process_id: 0, label: Some("thermal"), kind: GeneratedNoiseKind::White, table_len: 0, table_log_interp: false },
    GeneratedNoiseProcessDescriptor { process_id: 1, label: Some("flicker"), kind: GeneratedNoiseKind::Flicker, table_len: 0, table_log_interp: false },
];
pub static GROUPED_NOISE_INJECTIONS: [GeneratedNoiseInjectionDescriptor; 2] = [
    GeneratedNoiseInjectionDescriptor { process_id: 0, equation: 8, is_current: true, branch_ordinal: None, pos: GeneratedNoiseEndpoint { local_node: Some(0), name: "d", is_internal: false }, neg: GeneratedNoiseEndpoint { local_node: Some(2), name: "s", is_internal: false } },
    GeneratedNoiseInjectionDescriptor { process_id: 1, equation: 8, is_current: true, branch_ordinal: None, pos: GeneratedNoiseEndpoint { local_node: Some(0), name: "d", is_internal: false }, neg: GeneratedNoiseEndpoint { local_node: Some(2), name: "s", is_internal: false } },
];

impl Instance {
    pub fn evaluate_noise_processes_at_frequency(&self, ctx: &GeneratedEvalContext<'_>, frequency_hz: f64, visitor: &mut dyn GeneratedNoiseProcessVisitor) -> Result<(), GeneratedNoiseEvaluationError> {
        if !frequency_hz.is_finite() || frequency_hz < 0.0 {
            return Err(GeneratedNoiseEvaluationError::InvalidFrequency { value: frequency_hz });
        }
        if !self.multiplicity.is_finite() || self.multiplicity <= 0.0 {
            return Err(GeneratedNoiseEvaluationError::InvalidMultiplicity { value: self.multiplicity });
        }
        let parameters = &self.params.values;
        let parameter_given = &*self.param_given;
        let temperature = ctx.temperature();
        let thermal_voltage = ctx.thermal_voltage();
        let multiplicity = self.multiplicity;
        let time = self.time;
        let node_potentials: [f64; 4] = [ctx.node_voltage(self.nodes[0]), ctx.node_voltage(self.nodes[1]), ctx.node_voltage(self.nodes[2]), ctx.node_voltage(self.nodes[3])];
        let branch_flows: [f64; 0] = [];
        let branch_unknown_flows: [f64; 0] = [];
        let A=0f64;
        let B=1.0359399871014713e-10f64;
        let C=parameters[13];
        let F=parameters[25];
        let J=parameters[22];
        let L=parameters[30];
        let N=parameters[0];
        let P=0.5f64;
        let Q=0.3333333333333f64;
        let S=parameters[3];
        let W=parameters[4];
        let Y=298.15f64;
        let AC=0.1f64;
        let AE=1f64;
        let BB=parameters[38];
        let BC=1e-6f64;
        let BK=parameters[39];
        let BP=parameters[40];
        let BR=parameters[17];
        let BW=parameters[8];
        let CA=node_potentials[3];
        let CI=2f64;
        let CQ=0.25f64;
        let DC=1.3f64;
        let DD=1.6f64;
        let DJ=1.55f64;
        let DQ=1e-64f64;
        let GQ=parameters[21];
        let HX=0f64;
        let IB=parameters[1];
        let IE=parameters[41];
        let IL=L2([0f64;2]);
        let D=B/ C;
        let E=(D* parameters[14]).sqrt();
        let G=E* F;
        let H=(3f64* D)* parameters[28];
        let I=D* parameters[29];
        let K=C/ (B* J);
        let M=(L+ L)/ C;
        let O=N> A;
        let R=if O{
        P
        }else{
        Q
        };
        let T=S== 1e21f64;
        let AA=if T{
        let U=temperature+ parameters[2];
        U
        }else{
        let V=S+ 273.15f64;
        V
        };
        let X=W== 1e21f64;
        let AL=if X{
        Y
        }else{
        let Z=W+ 273.15f64;
        Z
        };
        let AB=AA* 8.617333262e-5f64;
        let AD=AC* AB;
        let AF=AE/ AB;
        let AG=AB+ AB;
        let AH=AG+ AG;
        let AI=AB* AB;
        let AJ=AI+ AI;
        let AK=16f64* AI;
        let AM=AA/ AL;
        let AN=parameters[15]- (parameters[16]* (AA- AL));
        let AO=parameters[19]* (AM.powf(parameters[20]));
        let AP=parameters[23]* (AM.powf(parameters[24]));
        let AQ=(((parameters[18]* AM)- ((3f64* AB)* (AM.ln())))- ((1.16f64- (((7.02e-4f64* AL)* AL)/ (AL+ 1108f64)))* AM))+ (1.16f64- (((7.02e-4f64* AA)* AA)/ (AA+ 1108f64)));
        let AR=AQ- 0.2f64;
        let AS=(P* (AR+ (((AR* AR)+ AI).sqrt())))+ 0.2f64;
        let AT=AS.sqrt();
        let AU=AE/ AP;
        let AV=E* AP;
        let AW=parameters[5]+ parameters[26];
        let AX=parameters[6]+ parameters[27];
        let AY=AP* AW;
        let AZ=AB* ((((P* AY)* AF).ln())- 0.6f64);
        let BA=AE/ ((AX* AW).sqrt());
        let CF;
        if O{
        let BD=BB!= BC;
        let BF=if BD{
        let BE=(BA* (BB- BC))+ AN;
        BE
        }else{
        AN
        };
        CF=BF;
        }else{
        let BG=BB!= BC;
        let BJ=if BG{
        let BH=(BA* (BC- BB))- AN;
        BH
        }else{
        let BI=-AN;
        BI
        };
        CF=BJ;
        }
        let BL=BK!= BC;
        let BN=if BL{
        let BM=AO* (AE+ ((BK- BC)* BA));
        BM
        }else{
        AO
        };
        let BO=AX* BN;
        let BQ=BP!= BC;
        let BT=if BQ{
        let BS=BR+ ((BP- BC)* BA);
        BS
        }else{
        BR
        };
        let BU=BT* AT;
        let BV=M== A;
        let CG=if BV{
        A
        }else{
        let BX=0.28f64* ((AW/ (parameters[31]* BW))- AC);
        let BY=AE/ (AE+ (P* (BX+ (((BX* BX)+ 0.001936f64).sqrt()))));
        let BZ=(M* BY)* BY;
        BZ
        };
        let CB=N* (node_potentials[1]- CA);
        let CC=N* (node_potentials[2]- CA);
        let CD=N* (node_potentials[0]- CA);
        let CE=(CD- CC)< A;
        let CL;
        let CN;
        if CE{
        CL=CD;
        CN=CC;
        }else{
        CL=CC;
        CN=CD;
        }
        let CH=(((CB- CF)- CG)+ AS)+ BU;
        let CJ=((CH* CH)+ (CI* AK)).sqrt();
        let CK=P* (CH+ CJ);
        let CM=AS+ CL;
        let CO=AS+ CN;
        let CP=(H* parameters[7])/ AX;
        let CR=(CK+ ((CQ* BT)* BT)).sqrt();
        let CS=CK- AS;
        let CT=CR- (P* BT);
        let CU=(((CS- (BT* CT))+ AS)+ AD).sqrt();
        let CV=(BT- (((I* BW)/ AW)* (((P* (CM+ (((CM* CM)+ AK).sqrt()))).sqrt())+ ((P* (CO+ (((CO* CO)+ AK).sqrt()))).sqrt()))))+ (CP* CU);
        let CW=((CV* CV)+ AD).sqrt();
        let CX=P* (CV+ CW);
        let CY=(CK+ ((CQ* CX)* CX)).sqrt();
        let CZ=CS- (CX* (CY- (P* CX)));
        let DA=(CZ- CL)* AF;
        let DB=DA> -0.35f64;
        let DS;
        if DB{
        let DE=CI/ ((DC+ DA)- ((DA+ DD).ln()));
        let DF=AE+ DA;
        let DG=(CI+ DE)/ (DF+ (DE.ln()));
        let DH=(DF+ (DG.ln()))/ (CI+ DG);
        DS=DH;
        }else{
        let DI=DA> -15f64;
        let DT;
        if DI{
        let DK=DJ+ ((-DA).exp());
        let DL=AE+ DA;
        let DM=(CI+ DK)/ (DL+ (DK.ln()));
        let DN=(DL+ (DM.ln()))/ (CI+ DM);
        DT=DN;
        }else{
        let DO=DA> -23f64;
        let DU=if DO{
        let DP=AE/ (CI+ ((-DA).exp()));
        DP
        }else{
        let DR=(DA.exp())+ DQ;
        DR
        };
        DT=DU;
        }
        DS=DT;
        }
        let DV=DS* (AE+ DS);
        let DW=DV.sqrt();
        let DX=AB/ AY;
        let DY=(CQ+ (DW* DX)).sqrt();
        let DZ=AY* (DY- P);
        let EA=P* (CN- CL);
        let EB=AK* ((F* (DW- (DZ* AF)))+ 0.015625f64);
        let EC=((DZ* DZ)+ EB).sqrt();
        let ED=EA- DZ;
        let EE=((ED* ED)+ EB).sqrt();
        let EF=EC- EE;
        let EG=(CQ+ ((DW- (0.75f64* (DV.ln())))* DX)).sqrt();
        let EH=(AY* (EG- P))+ AZ;
        let EI=EA- EH;
        let EJ=((EH* EH)+ EB).sqrt();
        let EK=((EI* EI)+ EB).sqrt();
        let EL=((((CZ- EA)- CL)- EJ)+ EK)* AF;
        let EM=EL> -0.35f64;
        let EZ;
        if EM{
        let EN=CI/ ((DC+ EL)- ((EL+ DD).ln()));
        let EO=AE+ EL;
        let EP=(CI+ EN)/ (EO+ (EN.ln()));
        let EQ=(EO+ (EP.ln()))/ (CI+ EP);
        EZ=EQ;
        }else{
        let ER=EL> -15f64;
        let FA;
        if ER{
        let ES=DJ+ ((-EL).exp());
        let ET=AE+ EL;
        let EU=(CI+ ES)/ (ET+ (ES.ln()));
        let EV=(ET+ (EU.ln()))/ (CI+ EU);
        FA=EV;
        }else{
        let EW=EL> -23f64;
        let FB=if EW{
        let EX=AE/ (CI+ ((-EL).exp()));
        EX
        }else{
        let EY=(EL.exp())+ DQ;
        EY
        };
        FA=FB;
        }
        EZ=FA;
        }
        let FC=EZ* (AE+ EZ);
        let FD=(AW- (G* ((AE+ ((EA- EF)/ AV)).ln())))+ ((EA+ EF)* AU);
        let FE=AC* AW;
        let FF=((FD* FD)+ (FE* FE)).sqrt();
        let FG=P* (FD+ FF);
        let FH=(CZ- CN)* AF;
        let FI=FH> -0.35f64;
        let FV;
        if FI{
        let FJ=CI/ ((DC+ FH)- ((FH+ DD).ln()));
        let FK=AE+ FH;
        let FL=(CI+ FJ)/ (FK+ (FJ.ln()));
        let FM=(FK+ (FL.ln()))/ (CI+ FL);
        FV=FM;
        }else{
        let FN=FH> -15f64;
        let FW;
        if FN{
        let FO=DJ+ ((-FH).exp());
        let FP=AE+ FH;
        let FQ=(CI+ FO)/ (FP+ (FO.ln()));
        let FR=(FP+ (FQ.ln()))/ (CI+ FQ);
        FW=FR;
        }else{
        let FS=FH> -23f64;
        let FX=if FS{
        let FT=AE/ (CI+ ((-FH).exp()));
        FT
        }else{
        let FU=(FH.exp())+ DQ;
        FU
        };
        FW=FX;
        }
        FV=FW;
        }
        let FY=CQ+ DV;
        let FZ=CQ+ (FV* (AE+ FV));
        let GA=FY.sqrt();
        let GB=FZ.sqrt();
        let GC=GA+ GB;
        let GD=GC* GC;
        let GE=CZ+ AS;
        let GF=GE+ BC;
        let GG=CI* (GF.sqrt());
        let GH=BT/ GG;
        let GI=BT/ (GG+ BT);
        let GJ=AE+ GH;
        let GK=(-GJ)* AB;
        let GL=GK* (((1.33333332f64* ((FZ+ (GB* GA))+ FY))/ GC)- AE);
        let GM=((-0.5f64* BT)* GG)- (GI* GL);
        let GN=J== A;
        let HD;
        let HS;
        let HT;
        let HU;
        let HW;
        if GN{
        let GO=((CZ* CZ)+ AJ).sqrt();
        let GP=P* (CZ+ GO);
        let GR=AE+ (GQ* GP);
        let GS=BO/ (FG* GR);
        HD=GS;
        HS=GP;
        HT=GR;
        HU=GO;
        HW=HX;
        }else{
        let GT=GM+ (R* GL);
        let GU=GT> A;
        let GX=if GU{
        let GV=AE+ (K* GT);
        GV
        }else{
        let GW=AE- (K* GT);
        GW
        };
        let GY=(BO* (AE+ (K* BU)))/ (FG* GX);
        HD=GY;
        HS=A;
        HT=A;
        HU=A;
        HW=GX;
        }
        let GZ=GE+ AH;
        let HA=GZ.sqrt();
        let HB=AE+ (BT/ (CI* HA));
        let HC=DV- FC;
        let HE=(AJ* HB)* HD;
        let HF=HD* (GL.abs());
        let HG=CK/ CJ;
        let HH=((-(GE/ CY))* ((((CP* (CX/ (CW+ CW)))* CT)/ (CR* CU))* HG))+ ((AE- (CX/ (CY+ CY)))* HG);
        let HI=(DS* AF)* HH;
        let HJ=(AB/ ((4f64* DY)* DW))* HI;
        let HK=((AH+ AH)* F)* ((HI* (AB/ (DW+ DW)))- HJ);
        let HL=(((DZ* HJ)+ HK)* (AE/ EC))- (((ED* (-HJ))+ HK)* (AE/ EE));
        let HM=((AB* (DW- 1.5f64))/ ((4f64* EG)* DV))* HI;
        let HN=(EZ* AF)* ((HH- (((EH* HM)+ HK)* (AE/ EJ)))+ (((EI* (-HM))+ HK)* (AE/ EK)));
        let HO=(AE/ FF)* ((-((-(G/ ((AV+ EA)- EF)))* HL))+ (HL* AU));
        let HP=(GK* 0.66666666f64)/ GD;
        let HQ=(((((-GH)* GL)/ (((CI+ GH)+ GH)* GF))* HH)+ ((HP* (GA+ (CI* GB)))* HI))+ ((HP* (GB+ (CI* GA)))* ((FV* AF)* HH));
        let HR=(-GI)* (((GJ- (GL/ ((CI* GJ)* GF)))* HH)+ HQ);
        let HZ=if GN{
        let HV=(-HO)- (((GQ* HS)/ (HT* HU))* HH);
        HV
        }else{
        let HY=(-HO)+ ((K/ HW)* (HR+ (R* HQ)));
        HY
        };
        let IA=HE* (((((((-BT)/ (((4f64* HB)* HA)* GZ))* HH)+ HZ)* HC)+ HI)- HN);
        let IF;
        let IG;
        let IH;
        let II;
        let IJ;
        let IK;
        if IB!=0.0{
        let IC=(5.5224904e-23f64* AA)* HF;
        let ID=((parameters[42]* IA)* IA)/ (((AX* BW)* AW)* C);
        let IM=L2([1f64,0.0])+ L2([0.0,1f64]);
        IF=AE;
        IG=IC;
        IH=AE;
        II=ID;
        IJ=IE;
        IK=IM;
        }else{
        IF=A;
        IG=A;
        IH=A;
        II=A;
        IJ=A;
        IK=IL;
        }
        let IN=IK[0];
        let IO=IK[1];
        let omega = core::f64::consts::TAU * frequency_hz;
        let process_0_active = IF != 0.0;
        let process_0_psd = (IG).abs();
        if !process_0_psd.is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 0, quantity: "psd", value: process_0_psd }); }
        let process_0_exponent: Option<f64> = None;
        if let Some(value) = process_0_exponent { if !value.is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 0, quantity: "exponent", value }); } }
        let process_0_table = [];
        let process_0_gain_0 = GeneratedNoiseComplex { re: (IN) * -1.0 * self.multiplicity.sqrt(), im: omega * (0.0) * -1.0 * self.multiplicity.sqrt() };
        if !process_0_gain_0.is_finite() { return Err(GeneratedNoiseEvaluationError::NonFiniteGain { process: 0, injection: 0, re: process_0_gain_0.re, im: process_0_gain_0.im }); }
        let process_0_injections = [GeneratedNoiseInjectionEvaluation { descriptor: 0, gain: process_0_gain_0 }];
        if !visitor.visit_process(0, GeneratedNoiseProcessEvaluationRef { active: process_0_active, psd: process_0_psd, exponent: process_0_exponent, table_operands: &process_0_table, injections: &process_0_injections }) { return Ok(()); }
        let process_1_active = IH != 0.0;
        let process_1_psd = (II).abs();
        if !process_1_psd.is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 1, quantity: "psd", value: process_1_psd }); }
        let process_1_exponent: Option<f64> = Some(IJ);
        if let Some(value) = process_1_exponent { if !value.is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 1, quantity: "exponent", value }); } }
        let process_1_table = [];
        let process_1_gain_0 = GeneratedNoiseComplex { re: (IO) * -1.0 * self.multiplicity.sqrt(), im: omega * (0.0) * -1.0 * self.multiplicity.sqrt() };
        if !process_1_gain_0.is_finite() { return Err(GeneratedNoiseEvaluationError::NonFiniteGain { process: 1, injection: 0, re: process_1_gain_0.re, im: process_1_gain_0.im }); }
        let process_1_injections = [GeneratedNoiseInjectionEvaluation { descriptor: 1, gain: process_1_gain_0 }];
        if !visitor.visit_process(1, GeneratedNoiseProcessEvaluationRef { active: process_1_active, psd: process_1_psd, exponent: process_1_exponent, table_operands: &process_1_table, injections: &process_1_injections }) { return Ok(()); }
        Ok(())
    }
}
