// intc27 -- 27-channel priority interrupt controller.
//
// Generated by rspice-conformance's Verilog scale-suite generator; edit
// the generator, not this file. Designed from the function described
// above and from nothing else -- see the generator's module documentation
// for the clean-room rule this file was written under.

// A 27-channel priority interrupt controller: request lines, a
// per-channel enable mask, and a global enable resolved to the index
// of the highest-numbered enabled request. Mapped onto true `and` and
// `or` cells.
module intc27 (req, msk, gen, id, vld, any);
  input gen;
  input [26:0] req, msk;
  output vld, any;
  output [4:0] id;
  wire arm_0, arm_1, arm_2, arm_3, arm_4, arm_5, arm_6, arm_7, arm_8, arm_9,
      arm_10, arm_11, arm_12, arm_13, arm_14, arm_15, arm_16, arm_17, arm_18,
      arm_19, arm_20, arm_21, arm_22, arm_23, arm_24, arm_25, arm_26, anyw_0,
      anyw_1, anyw_2, anyw_3, en_0, en_1, en_2, en_3, en_4, en_5, en_6, en_7,
      en_8, en_9, en_10, en_11, en_12, en_13, en_14, en_15, en_16, en_17,
      en_18, en_19, en_20, en_21, en_22, en_23, en_24, en_25, en_26, hi_0,
      hi_1, hi_2, hi_3, hi_4, hi_5, hi_6, hi_7, hi_8, hi_9, hi_10, hi_11,
      hi_12, hi_13, hi_14, hi_15, hi_16, hi_17, hi_18, hi_19, hi_20, hi_21,
      hi_22, hi_23, hi_24, nhi_0, sel_0, nhi_1, sel_1, nhi_2, sel_2, nhi_3,
      sel_3, nhi_4, sel_4, nhi_5, sel_5, nhi_6, sel_6, nhi_7, sel_7, nhi_8,
      sel_8, nhi_9, sel_9, nhi_10, sel_10, nhi_11, sel_11, nhi_12, sel_12,
      nhi_13, sel_13, nhi_14, sel_14, nhi_15, sel_15, nhi_16, sel_16, nhi_17,
      sel_17, nhi_18, sel_18, nhi_19, sel_19, nhi_20, sel_20, nhi_21, sel_21,
      nhi_22, sel_22, nhi_23, sel_23, nhi_24, sel_24, nhi_25, sel_25, enc_0,
      enc_1, enc_2, enc_3, enc_4, enc_5, enc_6, enc_7, enc_8, enc_9, enc_10,
      enc_11, enc_12, enc_13, enc_14, enc_15, enc_16, enc_17, enc_18, enc_19,
      enc_20, enc_21, enc_22, enc_23, enc_24, enc_25, enc_26, enc_27, enc_28,
      enc_29, enc_30, enc_31, enc_32, enc_33, enc_34, enc_35, enc_36, enc_37,
      enc_38, enc_39, enc_40, enc_41, enc_42, enc_43, enc_44, enc_45, enc_46,
      enc_47, enc_48, enc_49, enc_50, enc_51, enc_52, enc_53, enc_54, fob_0,
      fob_1, fob_2, fob_3, fob_4, fob_5, fob_6, fob_7, fob_8, fob_9, fob_10;

  and g0 (arm_0, req[0], msk[0]);
  and g1 (arm_1, req[1], msk[1]);
  and g2 (arm_2, req[2], msk[2]);
  and g3 (arm_3, req[3], msk[3]);
  and g4 (arm_4, req[4], msk[4]);
  and g5 (arm_5, req[5], msk[5]);
  and g6 (arm_6, req[6], msk[6]);
  and g7 (arm_7, req[7], msk[7]);
  and g8 (arm_8, req[8], msk[8]);
  and g9 (arm_9, req[9], msk[9]);
  and g10 (arm_10, req[10], msk[10]);
  and g11 (arm_11, req[11], msk[11]);
  and g12 (arm_12, req[12], msk[12]);
  and g13 (arm_13, req[13], msk[13]);
  and g14 (arm_14, req[14], msk[14]);
  and g15 (arm_15, req[15], msk[15]);
  and g16 (arm_16, req[16], msk[16]);
  and g17 (arm_17, req[17], msk[17]);
  and g18 (arm_18, req[18], msk[18]);
  and g19 (arm_19, req[19], msk[19]);
  and g20 (arm_20, req[20], msk[20]);
  and g21 (arm_21, req[21], msk[21]);
  and g22 (arm_22, req[22], msk[22]);
  and g23 (arm_23, req[23], msk[23]);
  and g24 (arm_24, req[24], msk[24]);
  and g25 (arm_25, req[25], msk[25]);
  and g26 (arm_26, req[26], msk[26]);
  or g27 (anyw_0, arm_0, arm_1, arm_2, arm_3, arm_4, arm_5, arm_6, arm_7);
  or g28 (anyw_1, arm_8, arm_9, arm_10, arm_11, arm_12, arm_13, arm_14, arm_15);
  or g29 (anyw_2, arm_16, arm_17, arm_18, arm_19, arm_20, arm_21, arm_22, arm_23);
  or g30 (anyw_3, arm_24, arm_25, arm_26);
  or g31 (any, anyw_0, anyw_1, anyw_2, anyw_3);
  and g32 (en_0, arm_0, fob_0);
  and g33 (en_1, arm_1, fob_0);
  and g34 (en_2, arm_2, fob_0);
  and g35 (en_3, arm_3, fob_0);
  and g36 (en_4, arm_4, fob_1);
  and g37 (en_5, arm_5, fob_1);
  and g38 (en_6, arm_6, fob_1);
  and g39 (en_7, arm_7, fob_1);
  and g40 (en_8, arm_8, fob_2);
  and g41 (en_9, arm_9, fob_2);
  and g42 (en_10, arm_10, fob_2);
  and g43 (en_11, arm_11, fob_2);
  and g44 (en_12, arm_12, fob_3);
  and g45 (en_13, arm_13, fob_3);
  and g46 (en_14, arm_14, fob_3);
  and g47 (en_15, arm_15, fob_3);
  and g48 (en_16, arm_16, fob_4);
  and g49 (en_17, arm_17, fob_4);
  and g50 (en_18, arm_18, fob_4);
  and g51 (en_19, arm_19, fob_4);
  and g52 (en_20, arm_20, fob_5);
  and g53 (en_21, arm_21, fob_5);
  and g54 (en_22, arm_22, fob_5);
  and g55 (en_23, arm_23, fob_5);
  and g56 (en_24, arm_24, fob_6);
  and g57 (en_25, arm_25, fob_6);
  and g58 (en_26, arm_26, fob_6);
  and g59 (vld, any, fob_6);
  or g60 (hi_0, en_25, fob_9);
  or g61 (hi_1, en_24, hi_0);
  or g62 (hi_2, en_23, hi_1);
  or g63 (hi_3, en_22, hi_2);
  or g64 (hi_4, en_21, hi_3);
  or g65 (hi_5, en_20, hi_4);
  or g66 (hi_6, en_19, hi_5);
  or g67 (hi_7, en_18, hi_6);
  or g68 (hi_8, en_17, hi_7);
  or g69 (hi_9, en_16, hi_8);
  or g70 (hi_10, en_15, hi_9);
  or g71 (hi_11, en_14, hi_10);
  or g72 (hi_12, en_13, hi_11);
  or g73 (hi_13, en_12, hi_12);
  or g74 (hi_14, en_11, hi_13);
  or g75 (hi_15, en_10, hi_14);
  or g76 (hi_16, en_9, hi_15);
  or g77 (hi_17, en_8, hi_16);
  or g78 (hi_18, en_7, hi_17);
  or g79 (hi_19, en_6, hi_18);
  or g80 (hi_20, en_5, hi_19);
  or g81 (hi_21, en_4, hi_20);
  or g82 (hi_22, en_3, hi_21);
  or g83 (hi_23, en_2, hi_22);
  or g84 (hi_24, en_1, hi_23);
  not g85 (nhi_0, hi_24);
  and g86 (sel_0, en_0, nhi_0);
  not g87 (nhi_1, hi_23);
  and g88 (sel_1, en_1, nhi_1);
  not g89 (nhi_2, hi_22);
  and g90 (sel_2, en_2, nhi_2);
  not g91 (nhi_3, hi_21);
  and g92 (sel_3, en_3, nhi_3);
  not g93 (nhi_4, hi_20);
  and g94 (sel_4, en_4, nhi_4);
  not g95 (nhi_5, hi_19);
  and g96 (sel_5, en_5, nhi_5);
  not g97 (nhi_6, hi_18);
  and g98 (sel_6, en_6, nhi_6);
  not g99 (nhi_7, hi_17);
  and g100 (sel_7, en_7, nhi_7);
  not g101 (nhi_8, hi_16);
  and g102 (sel_8, en_8, nhi_8);
  not g103 (nhi_9, hi_15);
  and g104 (sel_9, en_9, nhi_9);
  not g105 (nhi_10, hi_14);
  and g106 (sel_10, en_10, nhi_10);
  not g107 (nhi_11, hi_13);
  and g108 (sel_11, en_11, nhi_11);
  not g109 (nhi_12, hi_12);
  and g110 (sel_12, en_12, nhi_12);
  not g111 (nhi_13, hi_11);
  and g112 (sel_13, en_13, nhi_13);
  not g113 (nhi_14, hi_10);
  and g114 (sel_14, en_14, nhi_14);
  not g115 (nhi_15, hi_9);
  and g116 (sel_15, en_15, nhi_15);
  not g117 (nhi_16, hi_8);
  and g118 (sel_16, en_16, nhi_16);
  not g119 (nhi_17, hi_7);
  and g120 (sel_17, en_17, nhi_17);
  not g121 (nhi_18, hi_6);
  and g122 (sel_18, en_18, nhi_18);
  not g123 (nhi_19, hi_5);
  and g124 (sel_19, en_19, nhi_19);
  not g125 (nhi_20, hi_4);
  and g126 (sel_20, en_20, nhi_20);
  not g127 (nhi_21, hi_3);
  and g128 (sel_21, en_21, nhi_21);
  not g129 (nhi_22, hi_2);
  and g130 (sel_22, en_22, nhi_22);
  not g131 (nhi_23, hi_1);
  and g132 (sel_23, en_23, nhi_23);
  not g133 (nhi_24, hi_0);
  and g134 (sel_24, en_24, nhi_24);
  not g135 (nhi_25, fob_9);
  and g136 (sel_25, en_25, nhi_25);
  or g137 (enc_0, sel_1, sel_3);
  or g138 (enc_1, sel_5, sel_7);
  or g139 (enc_2, sel_9, sel_11);
  or g140 (enc_3, sel_13, sel_15);
  or g141 (enc_4, sel_17, sel_19);
  or g142 (enc_5, sel_21, sel_23);
  or g143 (enc_6, enc_0, enc_1);
  or g144 (enc_7, enc_2, enc_3);
  or g145 (enc_8, enc_4, enc_5);
  or g146 (enc_9, enc_6, enc_7);
  or g147 (enc_10, enc_8, sel_25);
  or g148 (enc_11, enc_9, enc_10);
  buf g149 (id[0], enc_11);
  or g150 (enc_12, sel_2, sel_3);
  or g151 (enc_13, sel_6, sel_7);
  or g152 (enc_14, sel_10, sel_11);
  or g153 (enc_15, sel_14, sel_15);
  or g154 (enc_16, sel_18, sel_19);
  or g155 (enc_17, sel_22, sel_23);
  or g156 (enc_18, enc_12, enc_13);
  or g157 (enc_19, enc_14, enc_15);
  or g158 (enc_20, enc_16, enc_17);
  or g159 (enc_21, enc_18, enc_19);
  or g160 (enc_22, enc_20, fob_9);
  or g161 (enc_23, enc_21, enc_22);
  buf g162 (id[1], enc_23);
  or g163 (enc_24, sel_4, sel_5);
  or g164 (enc_25, sel_6, sel_7);
  or g165 (enc_26, sel_12, sel_13);
  or g166 (enc_27, sel_14, sel_15);
  or g167 (enc_28, sel_20, sel_21);
  or g168 (enc_29, sel_22, sel_23);
  or g169 (enc_30, enc_24, enc_25);
  or g170 (enc_31, enc_26, enc_27);
  or g171 (enc_32, enc_28, enc_29);
  or g172 (enc_33, enc_30, enc_31);
  or g173 (enc_34, enc_33, enc_32);
  buf g174 (id[2], enc_34);
  or g175 (enc_35, sel_8, sel_9);
  or g176 (enc_36, sel_10, sel_11);
  or g177 (enc_37, sel_12, sel_13);
  or g178 (enc_38, sel_14, sel_15);
  or g179 (enc_39, sel_24, sel_25);
  or g180 (enc_40, enc_35, enc_36);
  or g181 (enc_41, enc_37, enc_38);
  or g182 (enc_42, enc_39, fob_9);
  or g183 (enc_43, enc_40, enc_41);
  or g184 (enc_44, enc_43, enc_42);
  buf g185 (id[3], enc_44);
  or g186 (enc_45, sel_16, sel_17);
  or g187 (enc_46, sel_18, sel_19);
  or g188 (enc_47, sel_20, sel_21);
  or g189 (enc_48, sel_22, sel_23);
  or g190 (enc_49, sel_24, sel_25);
  or g191 (enc_50, enc_45, enc_46);
  or g192 (enc_51, enc_47, enc_48);
  or g193 (enc_52, enc_49, fob_10);
  or g194 (enc_53, enc_50, enc_51);
  or g195 (enc_54, enc_53, enc_52);
  buf g196 (id[4], enc_54);
  buf g197 (fob_0, fob_7);
  buf g198 (fob_1, fob_7);
  buf g199 (fob_2, fob_7);
  buf g200 (fob_3, fob_7);
  buf g201 (fob_4, fob_8);
  buf g202 (fob_5, fob_8);
  buf g203 (fob_6, fob_8);
  buf g204 (fob_7, gen);
  buf g205 (fob_8, gen);
  buf g206 (fob_9, en_26);
  buf g207 (fob_10, en_26);
endmodule
