//! The options that ride on the deck's own `.OPTIONS` card.
//!
//! Every key here is a global one: the parser's package selector is not in
//! force, so these can share a card with each other and with nothing else.
//! The banners between them are the editor's own stacking order.

use super::{NumericOverrideOption, OptionPackage, OptionSpec, OverrideSection, OverrideValueKind};

pub(super) const GLOBAL: [OptionSpec; 21] = [
    // ---------------------------------------------------------- convergence
    OptionSpec {
        option: NumericOverrideOption::Reltol,
        key: "RELTOL",
        package: OptionPackage::Global,
        section: OverrideSection::Convergence,
        label: "Update bound · RELTOL",
        value_kind: OverrideValueKind::PositiveReal,
        value_hint: "positive real",
        config_field: "convergence_config.voltage_reltol",
        consumer: "engine/convergence/tolerances.rs:48 · voltage_reltol",
        time_stepped_only: false,
    },
    OptionSpec {
        option: NumericOverrideOption::Abstol,
        // `IABSTOL`, not `ABSTOL`, and the difference is load-bearing. The
        // resolver reads `opts.iabstol.or(opts.abstol)`
        // (`engine/config_resolver.rs:250`), which is *field* precedence, not
        // card order: a plan that states `IABSTOL` would win over an analysis
        // that stated `ABSTOL` however late its card came, and the departure
        // would be persisted, reported and then ignored. Both keys name the
        // one current floor, so the record states the one that wins and
        // last-card-wins does the rest.
        key: "IABSTOL",
        package: OptionPackage::Global,
        section: OverrideSection::Convergence,
        label: "Current floor · IABSTOL",
        value_kind: OverrideValueKind::PositiveReal,
        value_hint: "positive real",
        config_field: "convergence_config.current_abstol",
        consumer: "engine/convergence/tolerances.rs:63 · current_abstol",
        time_stepped_only: false,
    },
    OptionSpec {
        option: NumericOverrideOption::Vntol,
        key: "VNTOL",
        package: OptionPackage::Global,
        section: OverrideSection::Convergence,
        label: "Voltage floor · VNTOL",
        value_kind: OverrideValueKind::PositiveReal,
        value_hint: "positive real",
        config_field: "convergence_config.voltage_abstol",
        consumer: "engine/convergence/tolerances.rs:53 · voltage_abstol",
        time_stepped_only: false,
    },
    OptionSpec {
        option: NumericOverrideOption::ResidualReltol,
        key: "RESIDUAL_RELTOL",
        package: OptionPackage::Global,
        section: OverrideSection::Convergence,
        label: "Residual bound · RESIDUAL_RELTOL",
        value_kind: OverrideValueKind::PositiveReal,
        value_hint: "positive real",
        config_field: "convergence_config.residual_reltol",
        consumer: "engine/convergence/tolerances.rs:297 · residual_reltol",
        time_stepped_only: false,
    },
    OptionSpec {
        option: NumericOverrideOption::Gmin,
        key: "GMIN",
        package: OptionPackage::Global,
        section: OverrideSection::Convergence,
        label: "Junction conductance floor · GMIN",
        value_kind: OverrideValueKind::NonNegativeReal,
        value_hint: "conductance, 0 for none",
        config_field: "convergence_config.junction_gmin_target",
        consumer: "engine/convergence/stamping.rs:8 · effective_device_junction_gmin",
        time_stepped_only: false,
    },
    OptionSpec {
        option: NumericOverrideOption::Itl1,
        key: "ITL1",
        package: OptionPackage::Global,
        section: OverrideSection::Convergence,
        label: "Newton budget · ITL1",
        value_kind: OverrideValueKind::IterationCount,
        value_hint: "iteration count",
        config_field: "max_iterations",
        consumer: "engine/convergence/tolerances.rs:20 · nonlinear_iteration_budget",
        time_stepped_only: false,
    },
    OptionSpec {
        option: NumericOverrideOption::Itl4,
        key: "ITL4",
        package: OptionPackage::Global,
        section: OverrideSection::Convergence,
        label: "Iterations per step · ITL4",
        value_kind: OverrideValueKind::IterationCount,
        value_hint: "iteration count",
        config_field: "transient_max_iterations",
        consumer: "engine/transient/step_control.rs:191 · transient_max_iterations",
        time_stepped_only: true,
    },
    OptionSpec {
        option: NumericOverrideOption::GminStepping,
        key: "GMINSTEPPING",
        package: OptionPackage::Global,
        section: OverrideSection::Convergence,
        label: "Gmin stepping",
        value_kind: OverrideValueKind::Flag,
        value_hint: "on · off",
        config_field: "convergence_config.gmin_stepping",
        consumer: "engine/convergence/solve.rs:137 · gmin_stepping fallback",
        time_stepped_only: false,
    },
    OptionSpec {
        option: NumericOverrideOption::SourceStepping,
        key: "SOURCESTEPPING",
        package: OptionPackage::Global,
        section: OverrideSection::Convergence,
        label: "Source stepping",
        value_kind: OverrideValueKind::Flag,
        value_hint: "on · off",
        config_field: "convergence_config.source_stepping",
        consumer: "engine/convergence/solve.rs:154 · source_stepping fallback",
        time_stepped_only: false,
    },
    OptionSpec {
        option: NumericOverrideOption::PseudoTransient,
        key: "PSEUDOTRANSIENT",
        package: OptionPackage::Global,
        section: OverrideSection::Convergence,
        label: "Pseudo-transient",
        value_kind: OverrideValueKind::Flag,
        value_hint: "on · off",
        config_field: "convergence_config.pseudo_transient",
        consumer: "engine/convergence/solve.rs:605 · pseudo_transient fallback",
        time_stepped_only: false,
    },
    OptionSpec {
        option: NumericOverrideOption::ArcLength,
        key: "ARCLENGTH",
        package: OptionPackage::Global,
        section: OverrideSection::Convergence,
        label: "Arc-length continuation",
        value_kind: OverrideValueKind::Flag,
        value_hint: "on · off",
        config_field: "convergence_config.arc_length",
        consumer: "engine/convergence/solve.rs:607 · arc_length fallback",
        time_stepped_only: false,
    },
    OptionSpec {
        option: NumericOverrideOption::Damping,
        key: "DAMPING",
        package: OptionPackage::Global,
        section: OverrideSection::Convergence,
        label: "Damping strategy",
        value_kind: OverrideValueKind::Damping,
        value_hint: "NONE · LINESEARCH · VOLTAGELIMITING · BANKROSE · COMBINED",
        config_field: "convergence_config.damping_strategy",
        consumer: "engine/convergence/damping.rs:272 · damping_strategy",
        time_stepped_only: false,
    },
    // -------------------------------------------------------------- charge
    OptionSpec {
        option: NumericOverrideOption::Chgtol,
        key: "CHGTOL",
        package: OptionPackage::Global,
        section: OverrideSection::Charge,
        label: "Charge floor · CHGTOL",
        value_kind: OverrideValueKind::PositiveReal,
        value_hint: "charge, SI suffixes accepted",
        config_field: "convergence_config.charge_abstol",
        consumer: "engine/transient/truncation.rs:114 · charge truncation estimate",
        // Every read of `charge_abstol` outside the resolver is under
        // `engine/transient`: it floors the charge the truncation estimate
        // divides by. A DC solve never forms one.
        time_stepped_only: true,
    },
    // --------------------------------------------------------- integration
    OptionSpec {
        option: NumericOverrideOption::Trtol,
        key: "TRTOL",
        package: OptionPackage::Global,
        section: OverrideSection::Integration,
        label: "Truncation bound · TRTOL",
        value_kind: OverrideValueKind::PositiveReal,
        value_hint: "positive real",
        config_field: "transient_trtol",
        consumer: "engine/convergence/tolerances.rs:85 · transient_trtol",
        time_stepped_only: true,
    },
    OptionSpec {
        option: NumericOverrideOption::IntegrationMethod,
        key: "METHOD",
        package: OptionPackage::Global,
        section: OverrideSection::Integration,
        label: "Integration method",
        value_kind: OverrideValueKind::Method,
        value_hint: "TRAP · EULER · GEAR2 · TRAPGEAR",
        config_field: "integration_method",
        consumer: "engine/transient.rs:2451 · fixed_method",
        time_stepped_only: true,
    },
    // -------------------------------------------------------------- matrix
    OptionSpec {
        option: NumericOverrideOption::Pivrel,
        key: "PIVREL",
        package: OptionPackage::Global,
        section: OverrideSection::Matrix,
        label: "Relative pivot threshold · PIVREL",
        value_kind: OverrideValueKind::PositiveReal,
        value_hint: "positive real",
        config_field: "matrix_pivot_tolerance",
        consumer: "engine/matrix.rs:1711 · solver_options.pivot_tolerance",
        time_stepped_only: false,
    },
    OptionSpec {
        option: NumericOverrideOption::Pivtol,
        key: "PIVTOL",
        package: OptionPackage::Global,
        section: OverrideSection::Matrix,
        label: "Absolute pivot floor · PIVTOL",
        value_kind: OverrideValueKind::PositiveReal,
        value_hint: "positive real",
        config_field: "matrix_absolute_pivot_tolerance",
        consumer: "engine/matrix.rs:1712 · solver_options.absolute_pivot_tolerance",
        time_stepped_only: false,
    },
    OptionSpec {
        option: NumericOverrideOption::Solver,
        key: "SOLVER",
        package: OptionPackage::Global,
        section: OverrideSection::Matrix,
        label: "Matrix backend",
        value_kind: OverrideValueKind::Solver,
        value_hint: "KLU · FAER",
        config_field: "matrix_solver",
        consumer: "engine/matrix.rs:1708 · solver_options.real_backend",
        time_stepped_only: false,
    },
    // ------------------------------------------------------- device bypass
    OptionSpec {
        option: NumericOverrideOption::Bypass,
        key: "BYPASS",
        package: OptionPackage::Global,
        section: OverrideSection::DeviceBypass,
        label: "Device bypass",
        value_kind: OverrideValueKind::Flag,
        value_hint: "on · off",
        config_field: "bypass_config.enabled",
        consumer: "engine/builder.rs:8626 · set_b3soi_bypass_tolerances",
        time_stepped_only: false,
    },
    OptionSpec {
        option: NumericOverrideOption::BypassReltol,
        key: "BYPASSRELTOL",
        package: OptionPackage::Global,
        section: OverrideSection::DeviceBypass,
        label: "Bypass relative bound · BYPASSRELTOL",
        value_kind: OverrideValueKind::PositiveReal,
        value_hint: "positive real",
        config_field: "bypass_config.reltol",
        consumer: "engine/builder.rs:8627 · set_b3soi_bypass_tolerances",
        time_stepped_only: false,
    },
    OptionSpec {
        option: NumericOverrideOption::BypassAbstol,
        key: "BYPASSABSTOL",
        package: OptionPackage::Global,
        section: OverrideSection::DeviceBypass,
        label: "Bypass voltage floor · BYPASSABSTOL",
        value_kind: OverrideValueKind::PositiveReal,
        value_hint: "positive real",
        config_field: "bypass_config.abstol",
        consumer: "engine/builder.rs:8629 · set_b3soi_bypass_tolerances",
        time_stepped_only: false,
    },
];
