[package]
name = "rspice-model-library"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
csv.workspace = true
rspice-app-types.workspace = true
rspice-core = { path = "../rspice-core", version = "0.1.0", default-features = false }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
