[package]
name = "rspice-simulation-contract"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
rspice-app-types.workspace = true
rspice-design-model.workspace = true
rspice-results.workspace = true
rspice-core = { path = "../rspice-core", version = "0.1.0", default-features = false }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
unicode-segmentation = "1.12"
