#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum ShortcutCommand {
    FileNew,
    FileOpen,
    FileSave,
    EditUndo,
    EditRedo,
    EditCopy,
    EditPaste,
    EditCut,
    EditDelete,
    EditSelectAll,
    ToggleBrowserPanel,
    ToggleLogPanel,
    ShowShortcutsHelp,
    ToolSelect,
    ToolWire,
    PlaceGround,
    PlaceVoltageSource,
    PlaceCurrentSource,
    PlaceCapacitor,
    PlaceInductor,
    PlaceDiode,
    PlaceNmos,
    PlaceNpnBjt,
    ToolProbe,
    PlaceResistor,
    RotateSelectionOrPreview,
    MirrorSelectionHorizontal,
    MirrorSelectionVertical,
    OpenPropertiesEditor,
    EscapeCancel,
}

impl ShortcutCommand {
    pub(crate) fn display_name(self) -> &'static str {
        match self {
            ShortcutCommand::FileNew => "New",
            ShortcutCommand::FileOpen => "Open",
            ShortcutCommand::FileSave => "Save",
            ShortcutCommand::EditUndo => "Undo",
            ShortcutCommand::EditRedo => "Redo",
            ShortcutCommand::EditCopy => "Copy",
            ShortcutCommand::EditPaste => "Paste",
            ShortcutCommand::EditCut => "Cut",
            ShortcutCommand::EditDelete => "Delete",
            ShortcutCommand::EditSelectAll => "Select All",
            ShortcutCommand::ToggleBrowserPanel => "Toggle Browser",
            ShortcutCommand::ToggleLogPanel => "Toggle Log",
            ShortcutCommand::ShowShortcutsHelp => "Shortcuts Help",
            ShortcutCommand::ToolSelect => "Select Tool",
            ShortcutCommand::ToolWire => "Wire Tool",
            ShortcutCommand::PlaceGround => "Place Ground",
            ShortcutCommand::PlaceVoltageSource => "Place Voltage Source",
            ShortcutCommand::PlaceCurrentSource => "Place Current Source",
            ShortcutCommand::PlaceCapacitor => "Place Capacitor",
            ShortcutCommand::PlaceInductor => "Place Inductor",
            ShortcutCommand::PlaceDiode => "Place Diode",
            ShortcutCommand::PlaceNmos => "Place NMOS",
            ShortcutCommand::PlaceNpnBjt => "Place NPN BJT",
            ShortcutCommand::ToolProbe => "Probe Tool",
            ShortcutCommand::PlaceResistor => "Place Resistor",
            ShortcutCommand::RotateSelectionOrPreview => "Rotate",
            ShortcutCommand::MirrorSelectionHorizontal => "Mirror Horizontal",
            ShortcutCommand::MirrorSelectionVertical => "Mirror Vertical",
            ShortcutCommand::OpenPropertiesEditor => "Edit Properties",
            ShortcutCommand::EscapeCancel => "Cancel",
        }
    }

    pub(crate) fn shortcut_string(self) -> &'static str {
        match self {
            ShortcutCommand::FileNew => "Ctrl+N",
            ShortcutCommand::FileOpen => "Ctrl+O",
            ShortcutCommand::FileSave => "Ctrl+S",
            ShortcutCommand::EditUndo => "Ctrl+Z",
            ShortcutCommand::EditRedo => "Ctrl+Y / Ctrl+Shift+Z",
            ShortcutCommand::EditCopy => "Ctrl+C",
            ShortcutCommand::EditPaste => "Ctrl+V",
            ShortcutCommand::EditCut => "Ctrl+X",
            ShortcutCommand::EditDelete => "Delete",
            ShortcutCommand::EditSelectAll => "Ctrl+A",
            ShortcutCommand::ToggleBrowserPanel => "Ctrl+Shift+L",
            ShortcutCommand::ToggleLogPanel => "Ctrl+`",
            ShortcutCommand::ShowShortcutsHelp => "F1",
            ShortcutCommand::ToolSelect => "S",
            ShortcutCommand::ToolWire => "W",
            ShortcutCommand::PlaceGround => "G",
            ShortcutCommand::PlaceVoltageSource => "V",
            ShortcutCommand::PlaceCurrentSource => "I",
            ShortcutCommand::PlaceCapacitor => "C",
            ShortcutCommand::PlaceInductor => "L",
            ShortcutCommand::PlaceDiode => "D",
            ShortcutCommand::PlaceNmos => "M",
            ShortcutCommand::PlaceNpnBjt => "Q",
            ShortcutCommand::ToolProbe => "P",
            ShortcutCommand::PlaceResistor => "Shift+R",
            ShortcutCommand::RotateSelectionOrPreview => "R",
            ShortcutCommand::MirrorSelectionHorizontal => "H",
            ShortcutCommand::MirrorSelectionVertical => "Y",
            ShortcutCommand::OpenPropertiesEditor => "E",
            ShortcutCommand::EscapeCancel => "Escape",
        }
    }
}
