"""Type stubs for the rspice extension module."""

import os
from typing import Iterator, Sequence

import numpy as np
import numpy.typing as npt

__version__: str
__author__: str

class RSpiceError(Exception):
    """Base exception for all RSpice errors."""

class ParseError(RSpiceError):
    """Raised when netlist parsing fails due to syntax or semantic errors."""

class SimulationError(RSpiceError):
    """Raised when simulation fails due to circuit or solver errors."""

class ConvergenceError(SimulationError):
    """Raised when Newton-Raphson iteration fails to converge."""

class MeasurementError(RSpiceError):
    """Raised when .MEAS verification fails (see RunReport.assert_passed)."""

def ac_frequencies(
    variation: str, points: int, start_freq: float, stop_freq: float
) -> npt.NDArray[np.float64]: ...

class Netlist:
    @staticmethod
    def parse(content: str) -> Netlist: ...
    @staticmethod
    def parse_spice(content: str) -> Netlist: ...
    @staticmethod
    def parse_file(path: str | os.PathLike[str]) -> Netlist: ...
    @staticmethod
    def parse_with_includes(
        content: str, base_path: str | os.PathLike[str]
    ) -> Netlist: ...
    @property
    def num_elements(self) -> int: ...
    @property
    def num_models(self) -> int: ...
    @property
    def num_subcircuits(self) -> int: ...
    @property
    def num_analyses(self) -> int: ...
    @property
    def num_measurements(self) -> int: ...
    @property
    def title(self) -> str: ...
    @property
    def element_names(self) -> list[str]: ...
    @property
    def model_names(self) -> list[str]: ...
    @property
    def subcircuit_names(self) -> list[str]: ...
    @property
    def measurement_names(self) -> list[str]: ...
    @property
    def analyses(self) -> list[str]: ...
    def is_global(self, node: str) -> bool: ...

class DampingStrategy:
    NONE: DampingStrategy
    LINE_SEARCH: DampingStrategy
    VOLTAGE_LIMITING: DampingStrategy
    BANK_ROSE: DampingStrategy
    COMBINED: DampingStrategy

class IntegrationMethod:
    BACKWARD_EULER: IntegrationMethod
    TRAPEZOIDAL: IntegrationMethod
    GEAR2: IntegrationMethod
    TRAP_GEAR: IntegrationMethod

class BypassConfig:
    def __new__(
        cls,
        *,
        enabled: bool | None = None,
        reltol: float | None = None,
        abstol: float | None = None,
    ) -> BypassConfig: ...
    def __init__(
        self,
        *,
        enabled: bool | None = None,
        reltol: float | None = None,
        abstol: float | None = None,
    ) -> None: ...
    @staticmethod
    def with_tolerances(reltol: float, abstol: float) -> BypassConfig: ...
    enabled: bool
    reltol: float
    abstol: float

class ConvergenceConfig:
    def __new__(
        cls,
        *,
        gmin_stepping: bool | None = None,
        source_stepping: bool | None = None,
        pseudo_transient: bool | None = None,
        arc_length: bool | None = None,
        damping_strategy: DampingStrategy | None = None,
        gmin_initial: float | None = None,
        gmin_target: float | None = None,
        voltage_reltol: float | None = None,
        residual_reltol: float | None = None,
        voltage_abstol: float | None = None,
        current_abstol: float | None = None,
        charge_abstol: float | None = None,
        verbose: bool | None = None,
    ) -> ConvergenceConfig: ...
    def __init__(
        self,
        *,
        gmin_stepping: bool | None = None,
        source_stepping: bool | None = None,
        pseudo_transient: bool | None = None,
        arc_length: bool | None = None,
        damping_strategy: DampingStrategy | None = None,
        gmin_initial: float | None = None,
        gmin_target: float | None = None,
        voltage_reltol: float | None = None,
        residual_reltol: float | None = None,
        voltage_abstol: float | None = None,
        current_abstol: float | None = None,
        charge_abstol: float | None = None,
        verbose: bool | None = None,
    ) -> None: ...
    @staticmethod
    def fast() -> ConvergenceConfig: ...
    @staticmethod
    def robust() -> ConvergenceConfig: ...
    gmin_stepping: bool
    source_stepping: bool
    pseudo_transient: bool
    arc_length: bool
    damping_strategy: DampingStrategy
    gmin_initial: float
    gmin_target: float
    voltage_reltol: float
    residual_reltol: float
    voltage_abstol: float
    current_abstol: float
    charge_abstol: float
    verbose: bool

class SimulationConfig:
    def __new__(
        cls,
        *,
        tolerance: float | None = None,
        max_iterations: int | None = None,
        transient_max_iterations: int | None = None,
        min_timestep: float | None = None,
        max_timestep: float | None = None,
        temperature: float | None = None,
        integration_method: IntegrationMethod | None = None,
        transient_trtol: float | None = None,
        convergence: ConvergenceConfig | None = None,
        bypass: BypassConfig | None = None,
    ) -> SimulationConfig: ...
    def __init__(
        self,
        *,
        tolerance: float | None = None,
        max_iterations: int | None = None,
        transient_max_iterations: int | None = None,
        min_timestep: float | None = None,
        max_timestep: float | None = None,
        temperature: float | None = None,
        integration_method: IntegrationMethod | None = None,
        transient_trtol: float | None = None,
        convergence: ConvergenceConfig | None = None,
        bypass: BypassConfig | None = None,
    ) -> None: ...
    tolerance: float
    max_iterations: int
    transient_max_iterations: int
    min_timestep: float
    max_timestep: float
    temperature: float
    integration_method: IntegrationMethod
    transient_trtol: float
    convergence: ConvergenceConfig
    bypass: BypassConfig

class SimulationResult:
    def voltage(self, node: int | str) -> float: ...
    @property
    def node_voltages(self) -> npt.NDArray[np.float64]: ...
    @property
    def node_names(self) -> list[str]: ...
    def branch_current(self, name: str) -> float: ...
    @property
    def branch_currents(self) -> npt.NDArray[np.float64]: ...
    @property
    def branch_names(self) -> list[str]: ...
    @property
    def num_nodes(self) -> int: ...

class Harmonic:
    @property
    def n(self) -> int: ...
    @property
    def frequency(self) -> float: ...
    @property
    def magnitude(self) -> float: ...
    @property
    def phase(self) -> float: ...
    @property
    def phase_degrees(self) -> float: ...

class FourierResult:
    @property
    def dc_component(self) -> float: ...
    @property
    def thd(self) -> float: ...
    @property
    def thd_percent(self) -> float: ...
    @property
    def harmonics(self) -> list[Harmonic]: ...
    @property
    def magnitudes(self) -> npt.NDArray[np.float64]: ...
    @property
    def fundamental_magnitude(self) -> float | None: ...

class TransientResult:
    @property
    def time(self) -> npt.NDArray[np.float64]: ...
    def voltage_waveform(self, node: int | str) -> npt.NDArray[np.float64]: ...
    def branch_current_waveform(self, name: str) -> npt.NDArray[np.float64]: ...
    def voltage_at(self, node: int, time_index: int) -> float: ...
    def fourier(
        self, node: int | str, fundamental: float, num_harmonics: int = 9
    ) -> FourierResult: ...
    @property
    def num_points(self) -> int: ...
    @property
    def num_nodes(self) -> int: ...
    @property
    def node_names(self) -> list[str]: ...
    @property
    def branch_names(self) -> list[str]: ...
    @property
    def stop_time(self) -> float: ...

class AcResult:
    @property
    def frequencies(self) -> npt.NDArray[np.float64]: ...
    @property
    def num_frequencies(self) -> int: ...
    @property
    def node_names(self) -> list[str]: ...
    @property
    def branch_names(self) -> list[str]: ...
    def voltage_magnitude(self, node: int | str) -> npt.NDArray[np.float64]: ...
    def voltage_phase(self, node: int | str) -> npt.NDArray[np.float64]: ...
    def voltage_phase_degrees(self, node: int | str) -> npt.NDArray[np.float64]: ...
    def voltage_complex(self, node: int | str) -> npt.NDArray[np.complex128]: ...
    def voltage_db(self, node: int | str) -> npt.NDArray[np.float64]: ...
    def branch_current_complex(self, name: str) -> npt.NDArray[np.complex128]: ...
    def branch_current_magnitude(self, name: str) -> npt.NDArray[np.float64]: ...
    def magnitude_at(self, freq_index: int, node: int | str) -> float: ...
    def phase_at(self, freq_index: int, node: int | str) -> float: ...

class DcSweepResult:
    @property
    def sweep_values(self) -> npt.NDArray[np.float64]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[tuple[float, SimulationResult]]: ...
    def __getitem__(self, index: int, /) -> tuple[float, SimulationResult]: ...
    def points(self) -> list[tuple[float, SimulationResult]]: ...
    def result_at(self, index: int) -> SimulationResult: ...
    def sweep_value_at(self, index: int) -> float: ...
    def voltage(self, index: int, node: int | str) -> float: ...
    def voltage_array(self, node: int | str) -> npt.NDArray[np.float64]: ...

class NoiseContribution:
    @property
    def device_name(self) -> str: ...
    @property
    def noise_type(self) -> str: ...
    @property
    def output_contribution(self) -> float: ...
    @property
    def percentage(self) -> float: ...

class NoiseResult:
    @property
    def frequency(self) -> float: ...
    @property
    def output_noise_density(self) -> float: ...
    @property
    def input_referred_density(self) -> float: ...
    @property
    def output_noise_rms(self) -> float: ...
    @property
    def input_referred_rms(self) -> float: ...
    @property
    def output_noise_dbv(self) -> float: ...
    @property
    def contributions(self) -> list[NoiseContribution]: ...
    def dominant_source(self) -> NoiseContribution | None: ...

class VariableStatistics:
    @property
    def name(self) -> str: ...
    @property
    def mean(self) -> float: ...
    @property
    def std_dev(self) -> float: ...
    @property
    def min(self) -> float: ...
    @property
    def max(self) -> float: ...
    @property
    def samples(self) -> npt.NDArray[np.float64]: ...
    @property
    def histogram(self) -> list[int]: ...
    @property
    def bin_edges(self) -> npt.NDArray[np.float64]: ...
    def percentile(self, pct: float) -> float: ...
    @property
    def three_sigma_range(self) -> tuple[float, float]: ...
    @property
    def cv_percent(self) -> float: ...

class MonteCarloResult:
    @property
    def num_runs(self) -> int: ...
    @property
    def all_converged(self) -> bool: ...
    @property
    def num_failures(self) -> int: ...
    def get_variable(self, name: str) -> VariableStatistics | None: ...
    @property
    def variable_names(self) -> list[str]: ...
    def mean(self, name: str) -> float | None: ...
    def std_dev(self, name: str) -> float | None: ...
    def range(self, name: str) -> tuple[float, float] | None: ...
    @property
    def success_rate(self) -> float: ...

class ComplexValue:
    @property
    def real(self) -> float: ...
    @property
    def imag(self) -> float: ...
    def __complex__(self) -> complex: ...
    @property
    def magnitude(self) -> float: ...
    @property
    def phase(self) -> float: ...
    @property
    def phase_degrees(self) -> float: ...
    @property
    def is_real(self) -> bool: ...
    @property
    def frequency_hz(self) -> float: ...
    @property
    def damping_factor(self) -> float: ...
    @property
    def time_constant(self) -> float | None: ...

class PoleZeroResult:
    @property
    def poles(self) -> list[ComplexValue]: ...
    @property
    def zeros(self) -> list[ComplexValue]: ...
    @property
    def poles_array(self) -> npt.NDArray[np.complex128]: ...
    @property
    def zeros_array(self) -> npt.NDArray[np.complex128]: ...
    def real_poles(self) -> list[ComplexValue]: ...
    def complex_poles(self) -> list[ComplexValue]: ...
    @property
    def is_stable(self) -> bool: ...
    def dominant_pole(self) -> ComplexValue | None: ...
    @property
    def bandwidth_hz(self) -> float | None: ...
    @property
    def num_poles(self) -> int: ...
    @property
    def num_zeros(self) -> int: ...
    @property
    def dc_gain(self) -> float: ...
    @property
    def hf_gain(self) -> float | None: ...
    @property
    def input(self) -> str: ...
    @property
    def output(self) -> str: ...

class TransferFunctionResult:
    @property
    def output(self) -> str: ...
    @property
    def input(self) -> str: ...
    @property
    def gain(self) -> float: ...
    @property
    def gain_db(self) -> float: ...
    @property
    def input_impedance(self) -> float: ...
    @property
    def output_impedance(self) -> float: ...

class Measurement:
    @property
    def name(self) -> str: ...
    @property
    def analysis(self) -> str: ...
    @property
    def value(self) -> float | None: ...
    @property
    def error(self) -> str | None: ...
    @property
    def passed(self) -> bool: ...
    def __float__(self) -> float: ...

class AnalysisRecord:
    @property
    def kind(self) -> str: ...
    @property
    def detail(self) -> str: ...
    @property
    def skipped(self) -> bool: ...
    @property
    def reason(self) -> str | None: ...

class RunReport:
    @property
    def op(self) -> SimulationResult | None: ...
    @property
    def dc(self) -> DcSweepResult | None: ...
    @property
    def tran(self) -> TransientResult | None: ...
    @property
    def ac(self) -> AcResult | None: ...
    @property
    def noise(self) -> list[NoiseResult] | None: ...
    @property
    def tf(self) -> TransferFunctionResult | None: ...
    @property
    def fourier(self) -> list[FourierResult]: ...
    @property
    def records(self) -> list[AnalysisRecord]: ...
    @property
    def measurements(self) -> list[Measurement]: ...
    def measurement(self, name: str) -> Measurement | None: ...
    @property
    def num_measurements(self) -> int: ...
    @property
    def all_passed(self) -> bool: ...
    @property
    def failures(self) -> list[Measurement]: ...
    @property
    def analyses_run(self) -> list[str]: ...
    @property
    def skipped(self) -> list[AnalysisRecord]: ...
    def assert_passed(self) -> None: ...

class Engine:
    def __new__(cls, config: SimulationConfig | None = None) -> Engine: ...
    def __init__(self, config: SimulationConfig | None = None) -> None: ...
    def run(self, netlist: Netlist) -> RunReport: ...
    def measure(
        self, netlist: Netlist, result: TransientResult | DcSweepResult
    ) -> list[Measurement]: ...
    def run_dc_op(self, netlist: Netlist) -> SimulationResult: ...
    def run_dc_sweep(
        self,
        netlist: Netlist,
        source_name: str,
        start: float,
        stop: float,
        step: float,
    ) -> DcSweepResult: ...
    def run_ac(self, netlist: Netlist, frequencies: Sequence[float]) -> AcResult: ...
    def run_ac_sweep(
        self,
        netlist: Netlist,
        variation: str,
        points: int,
        start_freq: float,
        stop_freq: float,
    ) -> AcResult: ...
    def run_tran(
        self,
        netlist: Netlist,
        stop_time: float,
        max_step: float | None = None,
    ) -> TransientResult: ...
    def run_noise(
        self,
        netlist: Netlist,
        output_node: int | str,
        frequencies: Sequence[float],
        temperature: float | None = None,
        input_source: str | None = None,
        reference_node: int | str | None = None,
    ) -> list[NoiseResult]: ...
    def run_pz(
        self, netlist: Netlist, input_node: int | str, output_node: int | str
    ) -> PoleZeroResult: ...
    def run_monte_carlo(
        self,
        netlist: Netlist,
        num_runs: int,
        seed: int | None = None,
        distribution: str = "gaussian",
        spread: float = 0.01,
        params: Sequence[str] | None = None,
    ) -> MonteCarloResult: ...
    def run_sensitivity(
        self,
        netlist: Netlist,
        output_node: int | str,
        param_name: str,
        param_value: float,
        delta: float | None = None,
    ) -> float: ...
    def run_sensitivity_ac(
        self,
        netlist: Netlist,
        output_node: int | str,
        param_name: str,
        param_value: float,
        frequencies: Sequence[float],
        delta: float | None = None,
    ) -> npt.NDArray[np.float64]: ...
    def run_step(
        self, netlist: Netlist, param_name: str, values: Sequence[float]
    ) -> list[tuple[float, SimulationResult]]: ...
    def run_transfer_function(
        self,
        netlist: Netlist,
        output_node: str,
        input_source: str,
        output_is_current: bool = False,
        reference_node: str | None = None,
    ) -> TransferFunctionResult: ...
    @property
    def config(self) -> SimulationConfig: ...
