"""Type stubs for the rspice extension module."""

import os
from typing import Sequence

import numpy as np
import numpy.typing as npt

__version__: str
__author__: str

class RSpiceError(Exception):
    """Base exception for all RSpice errors."""

class ParseError(RSpiceError):
    """Raised when netlist parsing fails due to syntax or semantic errors."""

class SimulationError(RSpiceError):
    """Raised when simulation fails due to circuit or solver errors."""

class ConvergenceError(SimulationError):
    """Raised when Newton-Raphson iteration fails to converge."""

class Netlist:
    @staticmethod
    def parse(content: str) -> Netlist: ...
    @staticmethod
    def parse_file(path: str | os.PathLike[str]) -> Netlist: ...
    @staticmethod
    def parse_with_includes(
        content: str, base_path: str | os.PathLike[str]
    ) -> Netlist: ...
    @property
    def num_elements(self) -> int: ...
    @property
    def num_models(self) -> int: ...
    @property
    def num_subcircuits(self) -> int: ...
    @property
    def num_analyses(self) -> int: ...
    @property
    def title(self) -> str: ...
    def is_global(self, node: str) -> bool: ...

class DampingStrategy:
    NONE: DampingStrategy
    LINE_SEARCH: DampingStrategy
    VOLTAGE_LIMITING: DampingStrategy
    BANK_ROSE: DampingStrategy
    COMBINED: DampingStrategy

class BypassConfig:
    def __init__(self) -> None: ...
    @staticmethod
    def enabled() -> BypassConfig: ...
    @staticmethod
    def with_tolerances(reltol: float, abstol: float) -> BypassConfig: ...
    enabled: bool
    reltol: float
    abstol: float

class ConvergenceConfig:
    def __init__(self) -> None: ...
    @staticmethod
    def fast() -> ConvergenceConfig: ...
    @staticmethod
    def robust() -> ConvergenceConfig: ...
    gmin_stepping: bool
    source_stepping: bool
    pseudo_transient: bool
    arc_length: bool
    damping_strategy: DampingStrategy
    gmin_initial: float
    gmin_target: float
    voltage_reltol: float
    residual_reltol: float
    voltage_abstol: float
    current_abstol: float
    verbose: bool

class SimulationConfig:
    def __init__(self) -> None: ...
    tolerance: float
    max_iterations: int
    min_timestep: float
    max_timestep: float
    temperature: float
    convergence: ConvergenceConfig
    bypass: BypassConfig

class SimulationResult:
    def voltage(self, node: int | str) -> float: ...
    def voltage_by_index(self, node: int) -> float: ...
    @property
    def node_voltages(self) -> npt.NDArray[np.float64]: ...
    @property
    def node_names(self) -> list[str]: ...
    def branch_current(self, name: str) -> float | None: ...
    @property
    def branch_currents(self) -> npt.NDArray[np.float64]: ...
    @property
    def branch_names(self) -> list[str]: ...
    @property
    def num_nodes(self) -> int: ...

class TransientResult:
    @property
    def time(self) -> npt.NDArray[np.float64]: ...
    def voltage_waveform(self, node: int | str) -> npt.NDArray[np.float64]: ...
    def voltage_at(self, node: int, time_index: int) -> float: ...
    @property
    def num_points(self) -> int: ...
    @property
    def num_nodes(self) -> int: ...
    @property
    def node_names(self) -> list[str]: ...
    @property
    def stop_time(self) -> float: ...

class AcResult:
    @property
    def frequencies(self) -> npt.NDArray[np.float64]: ...
    @property
    def num_frequencies(self) -> int: ...
    def voltage_magnitude(self, node: int) -> npt.NDArray[np.float64]: ...
    def voltage_phase(self, node: int) -> npt.NDArray[np.float64]: ...
    def voltage_phase_degrees(self, node: int) -> npt.NDArray[np.float64]: ...
    def voltage_complex(self, node: int) -> npt.NDArray[np.complex128]: ...
    def voltage_db(self, node: int) -> npt.NDArray[np.float64]: ...
    def magnitude_at(self, freq_index: int, node: int) -> float: ...
    def phase_at(self, freq_index: int, node: int) -> float: ...

class DcSweepResult:
    @property
    def sweep_values(self) -> npt.NDArray[np.float64]: ...
    def __len__(self) -> int: ...
    @property
    def len(self) -> int: ...
    def points(self) -> list[tuple[float, SimulationResult]]: ...
    def __getitem__(self, index: int) -> tuple[float, SimulationResult]: ...
    def result_at(self, index: int) -> SimulationResult | None: ...
    def voltage_at(self, index: int) -> float: ...
    def voltage(self, index: int, node: int) -> float: ...
    def voltage_array(self, node: int) -> npt.NDArray[np.float64]: ...

class NoiseContribution:
    @property
    def device_name(self) -> str: ...
    @property
    def noise_type(self) -> str: ...
    @property
    def output_contribution(self) -> float: ...
    @property
    def percentage(self) -> float: ...

class NoiseResult:
    @property
    def frequency(self) -> float: ...
    @property
    def output_noise_density(self) -> float: ...
    @property
    def input_referred_density(self) -> float: ...
    @property
    def output_noise_rms(self) -> float: ...
    @property
    def input_referred_rms(self) -> float: ...
    @property
    def output_noise_dbv(self) -> float: ...
    @property
    def contributions(self) -> list[NoiseContribution]: ...
    def dominant_source(self) -> NoiseContribution | None: ...

class VariableStatistics:
    @property
    def name(self) -> str: ...
    @property
    def mean(self) -> float: ...
    @property
    def std_dev(self) -> float: ...
    @property
    def min(self) -> float: ...
    @property
    def max(self) -> float: ...
    @property
    def samples(self) -> npt.NDArray[np.float64]: ...
    @property
    def histogram(self) -> list[int]: ...
    @property
    def bin_edges(self) -> npt.NDArray[np.float64]: ...
    def percentile(self, pct: float) -> float: ...
    @property
    def three_sigma_range(self) -> tuple[float, float]: ...
    @property
    def cv_percent(self) -> float: ...

class MonteCarloResult:
    @property
    def num_runs(self) -> int: ...
    @property
    def all_converged(self) -> bool: ...
    @property
    def num_failures(self) -> int: ...
    def get_variable(self, name: str) -> VariableStatistics | None: ...
    @property
    def variable_names(self) -> list[str]: ...
    def mean(self, name: str) -> float | None: ...
    def std_dev(self, name: str) -> float | None: ...
    def range(self, name: str) -> tuple[float, float] | None: ...
    @property
    def success_rate(self) -> float: ...

class ComplexValue:
    @property
    def real(self) -> float: ...
    @property
    def imag(self) -> float: ...
    @property
    def magnitude(self) -> float: ...
    @property
    def phase(self) -> float: ...
    @property
    def phase_degrees(self) -> float: ...
    @property
    def is_real(self) -> bool: ...
    @property
    def frequency_hz(self) -> float: ...
    @property
    def damping_factor(self) -> float: ...
    @property
    def time_constant(self) -> float | None: ...

class PoleZeroResult:
    @property
    def poles(self) -> list[ComplexValue]: ...
    @property
    def zeros(self) -> list[ComplexValue]: ...
    def real_poles(self) -> list[ComplexValue]: ...
    def complex_poles(self) -> list[ComplexValue]: ...
    @property
    def is_stable(self) -> bool: ...
    def dominant_pole(self) -> ComplexValue | None: ...
    @property
    def bandwidth_hz(self) -> float | None: ...
    @property
    def num_poles(self) -> int: ...
    @property
    def num_zeros(self) -> int: ...
    @property
    def dc_gain(self) -> float: ...
    @property
    def hf_gain(self) -> float | None: ...
    @property
    def input(self) -> str: ...
    @property
    def output(self) -> str: ...

class Engine:
    def __init__(self, config: SimulationConfig | None = None) -> None: ...
    def run_dc_op(self, netlist: Netlist) -> SimulationResult: ...
    def run_dc_sweep(
        self,
        netlist: Netlist,
        source_name: str,
        start: float,
        stop: float,
        step: float,
    ) -> DcSweepResult: ...
    def run_ac(self, netlist: Netlist, frequencies: Sequence[float]) -> AcResult: ...
    def run_tran(
        self,
        netlist: Netlist,
        stop_time: float,
        max_step: float | None = None,
    ) -> TransientResult: ...
    def run_noise(
        self,
        netlist: Netlist,
        output_node: int,
        frequencies: Sequence[float],
        temperature: float | None = None,
    ) -> list[NoiseResult]: ...
    def run_pz(
        self, netlist: Netlist, input_node: int, output_node: int
    ) -> PoleZeroResult: ...
    def run_monte_carlo(
        self, netlist: Netlist, num_runs: int, seed: int
    ) -> MonteCarloResult: ...
    def run_sensitivity(
        self,
        netlist: Netlist,
        output_node: int,
        param_name: str,
        param_value: float,
        delta: float | None = None,
    ) -> float: ...
    def run_step(
        self, netlist: Netlist, param_name: str, values: Sequence[float]
    ) -> list[tuple[float, SimulationResult]]: ...
    @property
    def config(self) -> SimulationConfig: ...
