// @generated by rspice-veriloga; do not edit.
#![allow(dead_code, non_snake_case, unused_imports, unused_mut, unused_parens, unused_variables)]

use super::state::{CanonicalModelValues, Instance, PARAMETER_MODEL_FLAGS};
use rspice_veriloga_runtime::{GeneratedEvalContext, GeneratedReactiveStamper, GeneratedStamper, install_generated_stage_values, L2, L3, L4, L5, integer, arithmetic::product_div, arithmetic::product_sum_div, arithmetic::sum_products_div, arithmetic::sum_products_div_lanes, evaluate_generated_above, evaluate_generated_cross, evaluate_generated_timer, rspice_eval_ddt, rspice_eval_idt, rspice_limexp, rspice_limited_exp, rspice_limited_exp_derivative, GeneratedDdtCandidateError};
use std::collections::HashMap;
use std::sync::{Arc, Mutex, OnceLock, Weak};
pub(super) const CANONICAL_MODEL_STAGE_SLOTS: [u32; 59] = [0, 2, 8, 16, 3, 9, 17, 11, 12, 22, 1, 4, 5, 6, 7, 10, 25, 26, 13, 27, 14, 15, 28, 29, 69, 70, 19, 71, 72, 73, 74, 20, 21, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 95, 96, 97, 88, 89, 90, 91, 92, 93, 94, 98, 99, 100];
pub(super) const CANONICAL_TEMPERATURE_STAGE_SLOTS: [u32; 42] = [18, 23, 24, 34, 33, 41, 40, 42, 44, 43, 45, 55, 56, 32, 31, 57, 50, 49, 38, 39, 48, 53, 60, 35, 30, 65, 64, 63, 62, 46, 47, 52, 51, 67, 61, 66, 68, 36, 37, 54, 58, 59];

pub(super) fn canonical_model_preprocess(
    parameters: &[f64],
    parameter_given: &[bool],
    multiplicity: f64,
    staged: &[f64],
    temperature: f64,
    thermal_voltage: f64,
) -> [f64; 59] {
	let B=1.3806226e-23f64;
	let C=1.602176462e-19f64;
	let F=parameters[76];
	let G=parameters[77];
	let H=0.5f64;
	let J=parameters[78];
	let N=1f64;
	let O=parameters[87];
	let T=0f64;
	let AP=parameters[103];
	let AQ=parameters[104];
	let AR=parameters[111];
	let AV=parameters[36];
	let AY=parameters[39];
	let BO=0f64;
	let BS=0f64;
	let BW=0f64;
	let CD=0f64;
	let CG=0f64;
	let CJ=0f64;
	let CM=0f64;
	let CO=0f64;
	let CQ=0f64;
	let mut oBC=false;
	let A=parameters[108]+ 273.15f64;
	let D=(B* A)/ C;
	let E=parameters[88]* A;
	let I=H* (F+ G);
	let K=H* (F+ J);
	let L=H* (parameters[79]+ J);
	let M=3f64- ((C* parameters[80])/ B);
	let P=(M+ N)- O;
	let Q=M- 1.5f64;
	let R=(parameters[82]- parameters[81])- H;
	let S=F- G;
	let U=(parameters[21]> T)&& (parameters[41]> T);
	let V=if U{
	N
	}else{
	T
	};
	let W=(H* parameters[35])/ D;
	let X=2f64* D;
	let Y=X* (((W.exp())- ((-W).exp())).ln());
	let Z=(H* parameters[38])/ D;
	let AA=X* (((Z.exp())- ((-Z).exp())).ln());
	let AB=H* M;
	let AC=H* I;
	let AD=(H* parameters[42])/ D;
	let AE=X* (((AD.exp())- ((-AD).exp())).ln());
	let AF=O- E;
	let AG=parameters[65]> T;
	let AH=parameters[96]== N;
	let AI=O- N;
	let AJ=V== N;
	let AK=(H* parameters[46])/ D;
	let AL=X* (((AK.exp())- ((-AK).exp())).ln());
	let AM=(H* parameters[51])/ D;
	let AN=X* (((AM.exp())- ((-AM).exp())).ln());
	let AO=parameters[0]<= 200f64;
	let AS=AQ>= AR;
	let AT=(AP!= T)&& AS;
	let AU=parameters[44]< 100f64;
	let AW=if AO{
	AY
	}else{
	AV
	};
	let AX=parameters[7]== T;
	let AZ=parameters[10]== N;
	let BA=parameters[13]!= T;
	let BB=parameters[2]== T;
	if !BB{
	let BC=(parameters[9]== 1e6f64)&& (parameters[12]== 1e6f64);
	oBC=BC;
	}
	let BD=N+ ((N+ parameters[60]).sqrt());
	let BE=parameters[58]+ N;
	let BF=parameters[15]> T;
	let BG=parameters[17]> T;
	let BH=parameters[19]> T;
	let BI=parameters[30]> T;
	let BJ=parameters[32]> T;
	let BK=parameters[53]< 100f64;
	let BL=(AP== N)&& AS;
	let BM=(parameters[73]!= T)&& (parameters[54]!= T);
	let BN=parameters[28]>= AR;
	let BP;
	let BQ;
	if BN{
	BP=T;
	BQ=T;
	}else{
	BP=BO;
	BQ=N;
	}
	let BR=parameters[29]>= AR;
	let BT;
	let BU;
	if BR{
	BT=T;
	BU=T;
	}else{
	BT=BS;
	BU=N;
	}
	let BV=(parameters[23]>= AR)|| (parameters[26]>= AR);
	let BX;
	let BY;
	if BV{
	BX=T;
	BY=T;
	}else{
	BX=BW;
	BY=N;
	}
	let BZ=AP== T;
	let CA=BZ|| (parameters[107]== T);
	let CB=BZ|| (AQ< AR);
	let CC=if CB{
	N
	}else{
	T
	};
	let CF=if BV{
	let CE=T+ (-CD);
	CE
	}else{
	T
	};
	let CI=if BR{
	let CH=T+ (-CG);
	CH
	}else{
	T
	};
	let CL=if BN{
	let CK=T+ CJ;
	CK
	}else{
	T
	};
	let CN=T+ CM;
	let CP=T+ CO;
	let CR=T+ CQ;
    [A, I, K, L, M, P, Q, R, S, U as u8 as f64, Y, AA, AB, AC, AE, AF, AG as u8 as f64, AH as u8 as f64, AI, AJ as u8 as f64, AL, AN, AO as u8 as f64, AT as u8 as f64, AU as u8 as f64, AX as u8 as f64, AW, AZ as u8 as f64, BA as u8 as f64, BB as u8 as f64, oBC as u8 as f64, BD, BE, BF as u8 as f64, BG as u8 as f64, BH as u8 as f64, BI as u8 as f64, BJ as u8 as f64, BK as u8 as f64, BL as u8 as f64, BM as u8 as f64, BN as u8 as f64, BR as u8 as f64, BV as u8 as f64, CA as u8 as f64, CB as u8 as f64, CN, CP, CR, CC, BP, BT, BX, CF, CI, CL, BQ, BU, BY]
}

pub(super) fn canonical_temperature_preprocess(
    parameters: &[f64],
    parameter_given: &[bool],
    multiplicity: f64,
    staged: &[f64],
    temperature: f64,
    thermal_voltage: f64,
) -> [f64; 42] {
	let D=173.14999999999998f64;
	let H=1f64;
	let J=staged[0];
	let T=4f64;
	let U=0.5f64;
	let W=parameters[35];
	let X=parameters[34];
	let AC=parameters[38];
	let AO=parameters[83];
	let AS=parameters[64];
	let AU=staged[25]!=0.0;
	let AV=600f64;
	let AX=parameters[65];
	let BC=staged[26]!=0.0;
	let BD=staged[12];
	let BE=parameters[57];
	let BI=staged[27]!=0.0;
	let BJ=parameters[21];
	let BL=parameters[22];
	let CB=staged[28]!=0.0;
	let mut oE=false;
	let A=temperature+ parameters[109];
	let B=A+ 0f64;
	let C=B< 173.14999999999998f64;
	let F;
	if C{
	F=D;
	}else{
	let E=B> 600f64;
	oE=E;
	let AW=if E{
	AV
	}else{
	B
	};
	F=AW;
	}
	let G=(1.3806226e-23f64* F)/ 1.602176462e-19f64;
	let I=H/ G;
	let K=F- J;
	let L=F/ J;
	let M=L.ln();
	let N=I* (L- H);
	let O=H- L;
	let P=staged[2]* O;
	let Q=(staged[3]* G)* M;
	let R=((staged[1]* L)+ P)- Q;
	let S=2f64* G;
	let V=R+ (S* ((U* (H+ ((H+ (T* (((-R)* I).exp()))).sqrt()))).ln()));
	let Y=X* ((parameters[36]* ((W/ V).ln())).exp());
	let Z=(parameters[37]* V)/ W;
	let AA=((staged[4]* L)+ P)- Q;
	let AB=AA+ (S* ((U* (H+ ((H+ (T* (((-AA)* I).exp()))).sqrt()))).ln()));
	let AD=X* ((parameters[39]* ((AC/ AB).ln())).exp());
	let AE=(parameters[40]* AB)/ AC;
	let AF=parameters[15]* (((parameters[82]* M)+ (parameters[77]* N)).exp());
	let AG=parameters[17]* (((staged[5]* M)+ (staged[6]* N)).exp());
	let AH=staged[8]* O;
	let AI=((staged[7]* L)+ AH)- Q;
	let AJ=AI+ (S* ((U* (H+ ((H+ (T* (((-AI)* I).exp()))).sqrt()))).ln()));
	let AK=parameters[41]* ((parameters[43]* ((parameters[42]/ AJ).ln())).exp());
	let AL=parameters[78]* N;
	let AM=parameters[19]* (((staged[9]* M)+ AL).exp());
	let AN=parameters[1]* (((parameters[81]* M)+ (parameters[76]* N)).exp());
	let AP=parameters[9]* (((parameters[95]* M)- (AO* N)).exp());
	let AQ=parameters[62]* ((staged[10]* M).exp());
	let AR=H/ (parameters[61]* ((parameters[87]* M).exp()));
	let AT=AS* (H+ (parameters[89]* K));
	let AZ;
	let BA;
	if AU{
	let AY=AX* (H- (parameters[90]* K));
	AZ=AY;
	BA=AS;
	}else{
	AZ=AX;
	BA=AT;
	}
	let BB=parameters[54]* ((H+ (parameters[85]* K))+ ((parameters[86]* K)* K));
	let BG=if BC{
	let BF=BE* (((staged[11]* M)- (BD* N)).exp());
	BF
	}else{
	BE
	};
	let BH=parameters[59]* ((staged[13]* M).exp());
	let BN;
	let BO;
	if BI{
	let BK=BJ* ((parameters[99]* K).exp());
	let BM=BL* ((parameters[100]* K).exp());
	BN=BM;
	BO=BK;
	}else{
	BN=BL;
	BO=BJ;
	}
	let BP=parameters[23]* ((parameters[91]* M).exp());
	let BQ=((staged[14]* L)+ AH)- Q;
	let BR=BQ+ (S* ((U* (H+ ((H+ (T* (((-BQ)* I).exp()))).sqrt()))).ln()));
	let BS=parameters[45]* ((parameters[47]* ((parameters[46]/ BR).ln())).exp());
	let BT=((staged[15]* L)+ (staged[16]* O))- Q;
	let BU=BT+ (S* ((U* (H+ ((H+ (T* (((-BT)* I).exp()))).sqrt()))).ln()));
	let BV=parameters[50]* ((parameters[52]* ((parameters[51]/ BU).ln())).exp());
	let BW=staged[17]* M;
	let BX=parameters[32]* ((BW+ (parameters[79]* N)).exp());
	let BY=parameters[30]* ((BW+ AL).exp());
	let BZ=parameters[7]* ((parameters[97]* M).exp());
	let CA=parameters[6]/ (((AO* I)* (((parameters[84]* M).exp())- H)).exp());
	let CE=if CB{
	let CC=H+ (K* (parameters[101]+ (parameters[102]* K)));
	CC
	}else{
	let CD=(parameters[98]* M).exp();
	CD
	};
	let CF=parameters[12]* CE;
	let CG=(parameters[13]* CE)* ((BD* N).exp());
	let CH=parameters[29]* ((parameters[93]* M).exp());
	let CI=parameters[26]* ((parameters[92]* M).exp());
	let CJ=parameters[28]* ((parameters[94]* M).exp());
	let CK=(parameters[104]* ((parameters[105]* M).exp()))* (H+ (parameters[106]* K));
    [A, C as u8 as f64, oE as u8 as f64, G, I, V, Y, Z, AB, AD, AE, AF, AG, AJ, AK, AM, AN, AP, AQ, AR, BB, BH, BP, BR, BS, BU, BV, BX, BY, BZ, CA, CF, CG, CH, CI, CJ, CK, AZ, BA, BG, BN, BO]
}


static CANONICAL_MODEL_CACHE: OnceLock<Mutex<HashMap<Box<[u64]>, Weak<CanonicalModelValues>>>> = OnceLock::new();

fn canonical_model_cache() -> &'static Mutex<HashMap<Box<[u64]>, Weak<CanonicalModelValues>>> {
    CANONICAL_MODEL_CACHE.get_or_init(|| Mutex::new(HashMap::new()))
}

fn canonical_model_cache_lookup(key: &[u64]) -> Option<Arc<CanonicalModelValues>> {
    let mut cache = canonical_model_cache()
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner());
    let found = cache.get(key).and_then(Weak::upgrade);
    if found.is_none() {
        cache.remove(key);
    }
    found
}

fn canonical_model_cache_intern(
    key: Box<[u64]>,
    candidate: Arc<CanonicalModelValues>,
) -> Arc<CanonicalModelValues> {
    let mut cache = canonical_model_cache()
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner());
    if let Some(existing) = cache.get(key.as_ref()).and_then(Weak::upgrade) {
        return existing;
    }
    cache.retain(|_, values| values.strong_count() > 0);
    cache.insert(key, Arc::downgrade(&candidate));
    candidate
}

impl Instance {
    fn canonical_model_key(&self) -> Box<[u64]> {
        let mut key = Vec::with_capacity(222);
        for index in 0..Self::PARAMETER_COUNT {
            if PARAMETER_MODEL_FLAGS[index] {
                key.push(self.params.values[index].to_bits());
                key.push(u64::from(self.param_given[index]));
            }
        }
        key.into_boxed_slice()
    }

    fn canonical_install_model_values(&mut self, values: Arc<CanonicalModelValues>) {
        install_generated_stage_values(&mut self.canonical_staged[..], values.as_ref(), &CANONICAL_MODEL_STAGE_SLOTS);
        self.canonical_model_values = Some(values);
    }

    fn canonical_model_stage(&mut self, ctx: &GeneratedEvalContext<'_>) {
        if self.canonical_model_values.is_some() {
            return;
        }
        let key = self.canonical_model_key();
        if let Some(values) = canonical_model_cache_lookup(key.as_ref()) {
            self.canonical_install_model_values(values);
            return;
        }
        let produced: CanonicalModelValues = canonical_model_preprocess(
            &self.params.values,
            &self.param_given[..],
            self.multiplicity,
            &self.canonical_staged[..],
            ctx.temperature(),
            ctx.thermal_voltage(),
        );
        let values = canonical_model_cache_intern(key, Arc::new(produced));
        self.canonical_install_model_values(values);
    }

    fn canonical_instance_stage(&mut self, ctx: &GeneratedEvalContext<'_>) {
        if self.canonical_instance_valid {
            return;
        }
        let produced: [f64; 1] = {
            let multiplicity = self.multiplicity;
            let staged = &*self.canonical_staged;
            [0.0]
        };
        self.canonical_instance_valid = true;
    }

    fn canonical_temperature_stage(&mut self, ctx: &GeneratedEvalContext<'_>) {
        let temperature = ctx.temperature();
        let thermal_voltage = ctx.thermal_voltage();
        if self.canonical_temperature_valid
            && self.canonical_temperature == temperature
            && self.canonical_thermal_voltage == thermal_voltage
        {
            return;
        }
        let produced = canonical_temperature_preprocess(
            &self.params.values,
            &self.param_given[..],
            self.multiplicity,
            &self.canonical_staged[..],
            ctx.temperature(),
            ctx.thermal_voltage(),
        );
        install_generated_stage_values(&mut self.canonical_staged[..], &produced, &CANONICAL_TEMPERATURE_STAGE_SLOTS);
        self.canonical_temperature = temperature;
        self.canonical_thermal_voltage = thermal_voltage;
        self.canonical_temperature_valid = true;
    }

    fn canonical_timestep_stage(&mut self, ctx: &GeneratedEvalContext<'_>) {
        let produced: [f64; 1] = {
            let multiplicity = self.multiplicity;
            let staged = &*self.canonical_staged;
            [0.0]
        };
    }

    pub fn stamp(&mut self, ctx: &GeneratedEvalContext<'_>, stamper: &mut GeneratedStamper<'_>) {
        self.canonical_model_stage(ctx);
        self.canonical_instance_stage(ctx);
        self.canonical_temperature_stage(ctx);
        self.canonical_timestep_stage(ctx);
        let parameters = &self.params.values;
        let multiplicity = self.multiplicity;
        let staged = &*self.canonical_staged;
        let node_potentials = [ctx.node_voltage(self.nodes[0]), ctx.node_voltage(self.nodes[1]), ctx.node_voltage(self.nodes[2]), ctx.node_voltage(self.nodes[3]), ctx.node_voltage(self.nodes[4]), ctx.node_voltage(self.nodes[5]), ctx.node_voltage(self.nodes[6]), ctx.node_voltage(self.nodes[7]), ctx.node_voltage(self.nodes[8]), ctx.node_voltage(self.nodes[9]), ctx.node_voltage(self.nodes[10]), ctx.node_voltage(self.nodes[11]), ctx.node_voltage(self.nodes[12]), ctx.node_voltage(self.nodes[13]), ctx.node_voltage(self.nodes[14]), ctx.node_voltage(self.nodes[15]), ctx.node_voltage(self.nodes[16])];
        let ddt_scale_value = if self.ddt_coefficients.active && ctx.integration_operators_enabled() { self.ddt_coefficients.derivative_scale } else { 0.0 };
        let ddt_scale = move || ddt_scale_value;
        let ddt_state = self.stamp_state.as_mut();
        let integration_operators_enabled = ctx.integration_operators_enabled();
        let ddt_coefficients = self.ddt_coefficients;
        let mut ddt = |slot: usize, value: f64| -> f64 {
            if integration_operators_enabled {
                match rspice_eval_ddt(
                    &mut ddt_state.ddt_current,
                    &ddt_state.ddt_previous,
                    &ddt_state.ddt_older,
                    &ddt_state.ddt_initialized,
                    &mut ddt_state.ddt_derivative_current,
                    &ddt_state.ddt_derivative_previous,
                    &mut ddt_state.ddt_candidate_valid,
                    ddt_coefficients,
                    slot,
                    value,
                ) {
                    Ok(result) => result,
                    Err(source) => {
                        ctx.report_ddt_candidate_error(slot, source);
                        0.0
                    }
                }
            } else {
                if !value.is_finite() { ctx.report_ddt_candidate_error(slot, GeneratedDdtCandidateError::NonFiniteInput { field: "input" }); }
                0.0
            }
        };
		let A=node_potentials[1];
		let B=node_potentials[5];
		let C=parameters[110];
		let F=node_potentials[6];
		let K=node_potentials[7];
		let T=node_potentials[2];
		let AC=staged[25]!=0.0;
		let AD=staged[26]!=0.0;
		let AE=staged[27]!=0.0;
		let AF=staged[28]!=0.0;
		let AG=staged[29]!=0.0;
		let AH=node_potentials[4];
		let AK=staged[30];
		let AL=staged[31];
		let AM=staged[32];
		let AN=staged[33];
		let AO=staged[34];
		let AP=staged[35];
		let AQ=staged[36];
		let AR=staged[37];
		let AS=staged[38];
		let AT=staged[39];
		let AU=staged[40];
		let AV=staged[41];
		let AW=staged[42];
		let AX=staged[43];
		let AY=staged[44];
		let AZ=staged[45];
		let BA=staged[46];
		let BB=staged[47];
		let BC=staged[48];
		let BD=staged[49];
		let BE=staged[50];
		let BF=staged[51];
		let BG=staged[52];
		let BH=staged[53];
		let BI=staged[54];
		let BJ=staged[55];
		let BK=staged[56];
		let BL=staged[57];
		let BM=staged[58];
		let BN=staged[59];
		let BO=staged[60];
		let BP=staged[61];
		let BQ=staged[62];
		let BR=staged[63];
		let BS=staged[64];
		let BT=staged[65];
		let BU=staged[66];
		let BV=staged[67];
		let BW=staged[68];
		let BX=0f64;
		let EZ=173.14999999999998f64;
		let FD=1.3806226e-23f64;
		let FE=1.602176462e-19f64;
		let FH=1f64;
		let FK=staged[0];
		let FP=1f64;
		let FU=staged[1];
		let FW=-1f64;
		let FY=staged[2];
		let GB=staged[3];
		let GH=2f64;
		let GM=4f64;
		let GO=2f64;
		let GP=0.5f64;
		let GU=parameters[35];
		let GW=parameters[36];
		let GY=parameters[34];
		let HB=parameters[37];
		let HE=staged[4];
		let HO=parameters[38];
		let HQ=parameters[39];
		let HU=parameters[40];
		let HX=parameters[82];
		let HY=parameters[77];
		let IA=parameters[15];
		let ID=staged[5];
		let IE=staged[6];
		let IG=parameters[17];
		let IJ=staged[7];
		let IK=staged[8];
		let IX=parameters[43];
		let IZ=parameters[41];
		let JC=staged[9];
		let JD=parameters[78];
		let JH=parameters[19];
		let JK=parameters[81];
		let JL=parameters[76];
		let JN=parameters[1];
		let JQ=parameters[95];
		let JR=parameters[83];
		let JT=parameters[9];
		let JW=staged[10];
		let JY=parameters[62];
		let KB=parameters[87];
		let KD=parameters[61];
		let KH=parameters[89];
		let KI=parameters[64];
		let KL=600f64;
		let KM=1f64;
		let KP=parameters[90];
		let KQ=parameters[65];
		let KX=parameters[85];
		let KY=parameters[86];
		let LA=parameters[54];
		let LD=staged[11];
		let LE=staged[12];
		let LG=parameters[57];
		let LL=staged[13];
		let LN=parameters[59];
		let LQ=parameters[99];
		let LS=parameters[21];
		let LV=parameters[100];
		let LX=parameters[22];
		let ME=parameters[91];
		let MG=parameters[23];
		let MJ=staged[14];
		let MU=parameters[47];
		let MW=parameters[45];
		let MZ=staged[15];
		let NA=staged[16];
		let NL=parameters[52];
		let NN=parameters[50];
		let NQ=staged[17];
		let NT=parameters[79];
		let NV=parameters[32];
		let NZ=parameters[30];
		let OC=parameters[97];
		let OE=parameters[7];
		let OI=parameters[84];
		let OO=parameters[102];
		let OS=parameters[98];
		let OX=parameters[12];
		let PA=parameters[13];
		let PF=parameters[93];
		let PH=parameters[29];
		let PK=parameters[92];
		let PM=parameters[26];
		let PP=parameters[94];
		let PR=parameters[28];
		let PU=parameters[105];
		let PW=parameters[104];
		let PY=parameters[106];
		let QC=parameters[49];
		let QI=parameters[44];
		let QM=parameters[48];
		let QU=staged[69]!=0.0;
		let QV=0f64;
		let RA=L3([0f64;3]);
		let RH=2.4f64;
		let RU=80f64;
		let RW=L3([0f64;3]);
		let SG=0.1f64;
		let TX=1.921812f64;
		let AGP=parameters[67];
		let AGV=parameters[63];
		let AIL=L3([0f64;3]);
		let AIV=staged[70]!=0.0;
		let AJX=parameters[8];
		let AKJ=staged[19];
		let AKT=parameters[5];
		let ALB=parameters[55];
		let ALE=parameters[56];
		let ALH=staged[71]!=0.0;
		let ALW=parameters[3];
		let AML=parameters[4];
		let ANA=staged[72]!=0.0;
		let AND=parameters[11];
		let ANN=0.6666f64;
		let APA=2.004987562112089f64;
		let APD=L4([0f64;4]);
		let APG=staged[73]!=0.0;
		let APJ=staged[74]!=0.0;
		let APM=1e-20f64;
		let ARF=0.3333333333333333f64;
		let ARJ=27f64;
		let AUU=staged[20];
		let AVA=parameters[58];
		let AVD=staged[21];
		let AVH=parameters[68];
		let AVK=staged[75]!=0.0;
		let AVL=parameters[16];
		let AVS=staged[76]!=0.0;
		let AWC=parameters[18];
		let AWL=staged[77]!=0.0;
		let AWV=parameters[20];
		let BCO=parameters[24];
		let BCQ=parameters[25];
		let BDF=staged[78]!=0.0;
		let BDG=parameters[27];
		let BDX=parameters[31];
		let BEJ=L4([0f64;4]);
		let BEM=staged[79]!=0.0;
		let BEN=parameters[33];
		let BES=L3([0f64;3]);
		let BEV=staged[80]!=0.0;
		let BFJ=staged[81]!=0.0;
		let BFL=parameters[53];
		let BIZ=staged[82]!=0.0;
		let BJA=node_potentials[8];
		let BJE=parameters[71];
		let BJH=node_potentials[9];
		let BJL=parameters[72];
		let BJS=0f64;
		let BJT=0f64;
		let BKG=parameters[70];
		let BKH=parameters[69];
		let BLR=ddt_scale();
		let BML=staged[83]!=0.0;
		let BMP=L3([0f64;3]);
		let BMS=staged[84]!=0.0;
		let BMW=L3([0f64;3]);
		let BMZ=staged[85]!=0.0;
		let BND=L5([0f64;5]);
		let BNP=staged[86]!=0.0;
		let BNQ=parameters[107];
		let BNZ=staged[87]!=0.0;
		let BOM=0f64;
		let BOQ=true;
		let BPC=node_potentials[16];
		let BPE=staged[88];
		let D=C* (A- B);
		let E=(L2([1f64,0.0])- L2([0.0,1f64]))* C;
		let G=F- B;
		let H=L2([0.0,1f64])- L2([1f64,0.0]);
		let I=C* G;
		let J=H* C;
		let L=F- K;
		let M=L2([1f64,0.0])- L2([0.0,1f64]);
		let N=C* L;
		let O=M* C;
		let P=N- I;
		let Q=L3([0.0,O[0],O[1]])- L3([J[0],J[1],0.0]);
		let R=C* (node_potentials[3]- B);
		let S=(L2([1f64,0.0])- L2([0.0,1f64]))* C;
		let U=C* (A- T);
		let V=(L2([1f64,0.0])- L2([0.0,1f64]))* C;
		let W=K- T;
		let X=L2([0.0,1f64])- L2([1f64,0.0]);
		let Y=B- node_potentials[0];
		let Z=L2([0.0,1f64])- L2([1f64,0.0]);
		let AA=A- F;
		let AB=L2([1f64,0.0])- L2([0.0,1f64]);
		let BY;
		let BZ;
		let CA;
		let CB;
		let CC;
		let CD;
		let CE;
		let CF;
		let CG;
		let CH;
		let CI;
		let CJ;
		let CK;
		let CL;
		let CM;
		let CN;
		let CO;
		let CP;
		let CQ;
		let CR;
		let CS;
		let CT;
		let CU;
		let CV;
		let CW;
		let CX;
		let CY;
		let CZ;
		let DA;
		let DB;
		let DC;
		let DD;
		let DE;
		let DF;
		let DG;
		let DH;
		let DI;
		let DJ;
		let DK;
		let DL;
		let DM;
		let DN;
		let DO;
		let DP;
		let DQ;
		let DR;
		let DS;
		let DT;
		let DU;
		let DV;
		let DW;
		let DX;
		let DY;
		let DZ;
		let EA;
		let EB;
		let EC;
		let ED;
		let EE;
		let EF;
		let EG;
		let EH;
		let EI;
		let EJ;
		let EK;
		let EL;
		let EM;
		let EN;
		let EO;
		let EP;
		let EQ;
		let ER;
		let ES;
		let ET;
		let EU;
		let EV;
		let EW;
		let EX;
		if AG{
		let AI=staged[18]+ AH;
		let AJ=AI< 173.14999999999998f64;
		let FB;
		let FC;
		if AJ{
		FB=EZ;
		FC=BX;
		}else{
		let FA=AI> 600f64;
		let KN;
		let KO;
		if FA{
		KN=KL;
		KO=BX;
		}else{
		KN=AI;
		KO=KM;
		}
		FB=KN;
		FC=KO;
		}
		let FF=(FD* FB)/ FE;
		let FG=(FC* FD)/ FE;
		let FI=FH/ FF;
		let FJ=product_div(FG,(-FI),FF);
		let FL=FB- FK;
		let FM=FB/ FK;
		let FN=FC/ FK;
		let FO=FM.ln();
		let FQ=FN* (FP/ FM);
		let FR=FM- FH;
		let FS=FI* FR;
		let FT=(FJ* FR)+ (FN* FI);
		let FV=FH- FM;
		let FX=FN* FW;
		let FZ=FY* FV;
		let GA=FX* FY;
		let GC=GB* FF;
		let GD=GC* FO;
		let GE=((FG* GB)* FO)+ (FQ* GC);
		let GF=((FU* FM)+ FZ)- GD;
		let GG=((FN* FU)+ GA)- GE;
		let GI=GH* FF;
		let GJ=FG* GH;
		let GK=-GF;
		let GL=(GK* FI).exp();
		let GN=(FH+ (GM* GL)).sqrt();
		let GQ=GP* (FH+ GN);
		let GR=GQ.ln();
		let GS=GF+ (GI* GR);
		let GT=GG+ ((GJ* GR)+ (((((((((GG* FW)* FI)+ (FJ* GK))* GL)* GM)* (FP/ (GO* GN)))* GP)* (FP/ GQ))* GI));
		let GV=GU/ GS;
		let GX=(GW* (GV.ln())).exp();
		let GZ=GY* GX;
		let HA=((((product_div(GT,(-GV),GS))* (FP/ GV))* GW)* GX)* GY;
		let HC=(HB* GS)/ GU;
		let HD=(GT* HB)/ GU;
		let HF=((HE* FM)+ FZ)- GD;
		let HG=((FN* HE)+ GA)- GE;
		let HH=-HF;
		let HI=(HH* FI).exp();
		let HJ=(FH+ (GM* HI)).sqrt();
		let HK=GP* (FH+ HJ);
		let HL=HK.ln();
		let HM=HF+ (GI* HL);
		let HN=HG+ ((GJ* HL)+ (((((((((HG* FW)* FI)+ (FJ* HH))* HI)* GM)* (FP/ (GO* HJ)))* GP)* (FP/ HK))* GI));
		let HP=HO/ HM;
		let HR=(HQ* (HP.ln())).exp();
		let HS=GY* HR;
		let HT=((((product_div(HN,(-HP),HM))* (FP/ HP))* HQ)* HR)* GY;
		let HV=(HU* HM)/ HO;
		let HW=(HN* HU)/ HO;
		let HZ=((HX* FO)+ (HY* FS)).exp();
		let IB=IA* HZ;
		let IC=(((FQ* HX)+ (FT* HY))* HZ)* IA;
		let IF=((ID* FO)+ (IE* FS)).exp();
		let IH=IG* IF;
		let II=(((FQ* ID)+ (FT* IE))* IF)* IG;
		let IL=IK* FV;
		let IM=FX* IK;
		let IN=((IJ* FM)+ IL)- GD;
		let IO=((FN* IJ)+ IM)- GE;
		let IP=-IN;
		let IQ=(IP* FI).exp();
		let IR=(FH+ (GM* IQ)).sqrt();
		let IS=GP* (FH+ IR);
		let IT=IS.ln();
		let IU=IN+ (GI* IT);
		let IV=IO+ ((GJ* IT)+ (((((((((IO* FW)* FI)+ (FJ* IP))* IQ)* GM)* (FP/ (GO* IR)))* GP)* (FP/ IS))* GI));
		let IW=parameters[42]/ IU;
		let IY=(IX* (IW.ln())).exp();
		let JA=IZ* IY;
		let JB=((((product_div(IV,(-IW),IU))* (FP/ IW))* IX)* IY)* IZ;
		let JE=JD* FS;
		let JF=FT* JD;
		let JG=((JC* FO)+ JE).exp();
		let JI=JH* JG;
		let JJ=(((FQ* JC)+ JF)* JG)* JH;
		let JM=((JK* FO)+ (JL* FS)).exp();
		let JO=JN* JM;
		let JP=(((FQ* JK)+ (FT* JL))* JM)* JN;
		let JS=((JQ* FO)- (JR* FS)).exp();
		let JU=JT* JS;
		let JV=(((FQ* JQ)- (FT* JR))* JS)* JT;
		let JX=(JW* FO).exp();
		let JZ=JY* JX;
		let KA=((FQ* JW)* JX)* JY;
		let KC=(KB* FO).exp();
		let KE=KD* KC;
		let KF=FH/ KE;
		let KG=product_div((((FQ* KB)* KC)* KD),(-KF),KE);
		let KJ=KI* (FH+ (KH* FL));
		let KK=(FC* KH)* KI;
		let KT;
		let KU;
		let KV;
		let KW;
		if AC{
		let KR=KQ* (FH- (KP* FL));
		let KS=((FC* KP)* FW)* KQ;
		KT=KR;
		KU=KI;
		KV=KS;
		KW=BX;
		}else{
		KT=KQ;
		KU=KJ;
		KV=BX;
		KW=KK;
		}
		let KZ=KY* FL;
		let LB=LA* ((FH+ (KX* FL))+ (KZ* FL));
		let LC=((FC* KX)+ (((FC* KY)* FL)+ (FC* KZ)))* LA;
		let LJ;
		let LK;
		if AD{
		let LF=((LD* FO)- (LE* FS)).exp();
		let LH=LG* LF;
		let LI=(((FQ* LD)- (FT* LE))* LF)* LG;
		LJ=LH;
		LK=LI;
		}else{
		LJ=LG;
		LK=BX;
		}
		let LM=(LL* FO).exp();
		let LO=LN* LM;
		let LP=((FQ* LL)* LM)* LN;
		let MA;
		let MB;
		let MC;
		let MD;
		if AE{
		let LR=(LQ* FL).exp();
		let LT=LS* LR;
		let LU=((FC* LQ)* LR)* LS;
		let LW=(LV* FL).exp();
		let LY=LX* LW;
		let LZ=((FC* LV)* LW)* LX;
		MA=LY;
		MB=LT;
		MC=LZ;
		MD=LU;
		}else{
		MA=LX;
		MB=LS;
		MC=BX;
		MD=BX;
		}
		let MF=(ME* FO).exp();
		let MH=MG* MF;
		let MI=((FQ* ME)* MF)* MG;
		let MK=((MJ* FM)+ IL)- GD;
		let ML=((FN* MJ)+ IM)- GE;
		let MM=-MK;
		let MN=(MM* FI).exp();
		let MO=(FH+ (GM* MN)).sqrt();
		let MP=GP* (FH+ MO);
		let MQ=MP.ln();
		let MR=MK+ (GI* MQ);
		let MS=ML+ ((GJ* MQ)+ (((((((((ML* FW)* FI)+ (FJ* MM))* MN)* GM)* (FP/ (GO* MO)))* GP)* (FP/ MP))* GI));
		let MT=parameters[46]/ MR;
		let MV=(MU* (MT.ln())).exp();
		let MX=MW* MV;
		let MY=((((product_div(MS,(-MT),MR))* (FP/ MT))* MU)* MV)* MW;
		let NB=((MZ* FM)+ (NA* FV))- GD;
		let NC=((FN* MZ)+ (FX* NA))- GE;
		let ND=-NB;
		let NE=(ND* FI).exp();
		let NF=(FH+ (GM* NE)).sqrt();
		let NG=GP* (FH+ NF);
		let NH=NG.ln();
		let NI=NB+ (GI* NH);
		let NJ=NC+ ((GJ* NH)+ (((((((((NC* FW)* FI)+ (FJ* ND))* NE)* GM)* (FP/ (GO* NF)))* GP)* (FP/ NG))* GI));
		let NK=parameters[51]/ NI;
		let NM=(NL* (NK.ln())).exp();
		let NO=NN* NM;
		let NP=((((product_div(NJ,(-NK),NI))* (FP/ NK))* NL)* NM)* NN;
		let NR=NQ* FO;
		let NS=FQ* NQ;
		let NU=(NR+ (NT* FS)).exp();
		let NW=NV* NU;
		let NX=((NS+ (FT* NT))* NU)* NV;
		let NY=(NR+ JE).exp();
		let OA=NZ* NY;
		let OB=((NS+ JF)* NY)* NZ;
		let OD=(OC* FO).exp();
		let OF=OE* OD;
		let OG=((FQ* OC)* OD)* OE;
		let OH=JR* FI;
		let OJ=(OI* FO).exp();
		let OK=OJ- FH;
		let OL=(OH* OK).exp();
		let OM=parameters[6]/ OL;
		let ON=product_div(((((FJ* JR)* OK)+ (((FQ* OI)* OJ)* OH))* OL),(-OM),OL);
		let OV;
		let OW;
		if AF{
		let OP=parameters[101]+ (OO* FL);
		let OQ=(FC* OP)+ ((FC* OO)* FL);
		let OR=FH+ (FL* OP);
		OV=OR;
		OW=OQ;
		}else{
		let OT=(OS* FO).exp();
		let OU=(FQ* OS)* OT;
		OV=OT;
		OW=OU;
		}
		let OY=OX* OV;
		let OZ=OW* OX;
		let PB=PA* OV;
		let PC=(LE* FS).exp();
		let PD=PB* PC;
		let PE=((OW* PA)* PC)+ (((FT* LE)* PC)* PB);
		let PG=(PF* FO).exp();
		let PI=PH* PG;
		let PJ=((FQ* PF)* PG)* PH;
		let PL=(PK* FO).exp();
		let PN=PM* PL;
		let PO=((FQ* PK)* PL)* PM;
		let PQ=(PP* FO).exp();
		let PS=PR* PQ;
		let PT=((FQ* PP)* PQ)* PR;
		let PV=(PU* FO).exp();
		let PX=PW* PV;
		let PZ=FH+ (PY* FL);
		let QA=PX* PZ;
		let QB=((((FQ* PU)* PV)* PW)* PZ)+ ((FC* PY)* PX);
		BY=MX;
		BZ=JA;
		CA=IU;
		CB=FI;
		CC=FF;
		CD=MR;
		CE=KT;
		CF=KU;
		CG=JZ;
		CH=KF;
		CI=GZ;
		CJ=GS;
		CK=HC;
		CL=HS;
		CM=HM;
		CN=HV;
		CO=OF;
		CP=OM;
		CQ=LB;
		CR=JU;
		CS=JO;
		CT=PD;
		CU=OY;
		CV=LO;
		CW=LJ;
		CX=IB;
		CY=IH;
		CZ=JI;
		DA=MA;
		DB=MB;
		DC=MH;
		DD=PN;
		DE=OA;
		DF=NW;
		DG=NO;
		DH=NI;
		DI=PS;
		DJ=PI;
		DK=QA;
		DL=MY;
		DM=JB;
		DN=IV;
		DO=FJ;
		DP=FG;
		DQ=MS;
		DR=KV;
		DS=KW;
		DT=KA;
		DU=KG;
		DV=HA;
		DW=GT;
		DX=HD;
		DY=HT;
		DZ=HN;
		EA=HW;
		EB=OG;
		EC=ON;
		ED=LC;
		EE=JV;
		EF=JP;
		EG=PE;
		EH=OZ;
		EI=LP;
		EJ=LK;
		EK=IC;
		EL=II;
		EM=JJ;
		EN=MC;
		EO=MD;
		EP=MI;
		EQ=PO;
		ER=OB;
		ES=NX;
		ET=NP;
		EU=NJ;
		EV=PT;
		EW=PJ;
		EX=QB;
		}else{
		BY=AK;
		BZ=AL;
		CA=AM;
		CB=AN;
		CC=AO;
		CD=AP;
		CE=AQ;
		CF=AR;
		CG=AS;
		CH=AT;
		CI=AU;
		CJ=AV;
		CK=AW;
		CL=AX;
		CM=AY;
		CN=AZ;
		CO=BA;
		CP=BB;
		CQ=BC;
		CR=BD;
		CS=BE;
		CT=BF;
		CU=BG;
		CV=BH;
		CW=BI;
		CX=BJ;
		CY=BK;
		CZ=BL;
		DA=BM;
		DB=BN;
		DC=BO;
		DD=BP;
		DE=BQ;
		DF=BR;
		DG=BS;
		DH=BT;
		DI=BU;
		DJ=BV;
		DK=BW;
		DL=BX;
		DM=BX;
		DN=BX;
		DO=BX;
		DP=BX;
		DQ=BX;
		DR=BX;
		DS=BX;
		DT=BX;
		DU=BX;
		DV=BX;
		DW=BX;
		DX=BX;
		DY=BX;
		DZ=BX;
		EA=BX;
		EB=BX;
		EC=BX;
		ED=BX;
		EE=BX;
		EF=BX;
		EG=BX;
		EH=BX;
		EI=BX;
		EJ=BX;
		EK=BX;
		EL=BX;
		EM=BX;
		EN=BX;
		EO=BX;
		EP=BX;
		EQ=BX;
		ER=BX;
		ES=BX;
		ET=BX;
		EU=BX;
		EV=BX;
		EW=BX;
		EX=BX;
		}
		let EY=BY<= 1e-30f64;
		let QO;
		let QP;
		let QQ;
		let QR;
		let QS;
		let QT;
		if EY{
		let QD=BZ* QC;
		let QE=DM* QC;
		let QF=FH- QC;
		let QG=BZ* QF;
		let QH=DM* QF;
		let QJ=QI< 100f64;
		let QY;
		let QZ;
		if QJ{
		let QW=QG> QV;
		let RX;
		let RY;
		if QW{
		let RB=IX/ GM;
		let RC=QI- CA;
		let RD=DN* FW;
		let RE=FH- ((-0.8754687373538999f64/ IX).exp());
		let RF=CA* RE;
		let RG=DN* RE;
		let RI=RH* QG;
		let RJ=QH* RH;
		let RK=RB- IX;
		let RL=QI/ CA;
		let RM=(RK* (RL.ln())).exp();
		let RN=QG* RM;
		let RO=(QH* RM)+ (((((product_div(DN,(-RL),CA))* (FP/ RL))* RK)* RM)* QG);
		let RP=RF- D;
		let RQ=L3([0.0,RG,0.0]);
		let RR=L3([E[0],0.0,E[1]]);
		let RS=RP* CB;
		let RT=((RQ- RR)* CB)+ L3([0.0,(DO* RP),0.0]);
		let RV=RS< RU;
		let SE;
		let SF;
		if RV{
		let RZ=RS.exp();
		let SA=FH+ RZ;
		let SB=SA.ln();
		let SC=RF- (CC* SB);
		let SD=RQ- (L3([0.0,(DP* SB),0.0])+ (((RT* RZ)* (FP/ SA))* CC));
		SE=SC;
		SF=SD;
		}else{
		SE=D;
		SF=RR;
		}
		let SH=(SG* RC)+ (GM* CC);
		let SI=(RD* SG)+ (DP* GM);
		let SJ=(RC+ SE)/ SH;
		let SK=((L3([0.0,RD,0.0])+ SF)).product_sum_div(FP,L3([0.0,SI,0.0]),(-SJ),SH);
		let SL=SJ< RU;
		let ST;
		let SU;
		if SL{
		let SM=SJ.exp();
		let SN=FH+ SM;
		let SO=(-(RC+ RF))/ SH;
		let SP=SO.exp();
		let SQ=(SN.ln())- SP;
		let SR=(-RC)+ (SH* SQ);
		let SS=L3([0.0,(RD* FW),0.0])+ (L3([0.0,(SI* SQ),0.0])+ ((((SK* SM)* (FP/ SN))- L3([0.0,((product_sum_div(((RD+ RG)* FW),FP,SI,(-SO),SH))* SP),0.0]))* SH));
		ST=SR;
		SU=SS;
		}else{
		ST=SE;
		SU=SF;
		}
		let SV=D- SE;
		let SW=SE/ CA;
		let SX=L3([0.0,DN,0.0]);
		let SY=FH- SW;
		let SZ=ST/ CA;
		let TA=FH- SZ;
		let TB=TA.ln();
		let TC=(((SU).product_sum_div(FP,SX,(-SZ),CA))* FW)* (FP/ TA);
		let TD=FH- IX;
		let TE=FH- RB;
		let TF=(TB* TD).exp();
		let TG=FH- TF;
		let TH=((SY.ln())* TE).exp();
		let TI=FH- TH;
		let TJ=(TB* TE).exp();
		let TK=FH- TJ;
		let TL=((L3([0.0,(QH* TG),0.0])+ ((((TC* TD)* TF)* FW)* QG))/ TD)+ ((L3([0.0,(RO* TI),0.0])+ ((((((((SF).product_sum_div(FP,SX,(-SW),CA))* FW)* (FP/ SY))* TE)* TH)* FW)* RN))/ TE);
		let TM=(((QG* TG)/ TD)+ ((RN* TI)/ TE))- ((RN* TK)/ TE);
		let TN=(TM* CA)+ (RI* SV);
		let TO=(((TL- ((L3([0.0,(RO* TK),0.0])+ ((((TC* TE)* TJ)* FW)* RN))/ TE))* CA)+ L3([0.0,(DN* TM),0.0]))+ (L3([0.0,(RJ* SV),0.0])+ ((RR- SF)* RI));
		RX=TN;
		RY=TO;
		}else{
		RX=QV;
		RY=RW;
		}
		QY=RX;
		QZ=RY;
		}else{
		let QX=QG> QV;
		let UL;
		let UM;
		if QX{
		let TP=FH- ((-0.8754687373538999f64/ IX).exp());
		let TQ=CA* TP;
		let TR=TQ- D;
		let TS=L3([0.0,(DN* TP),0.0]);
		let TT=L3([E[0],0.0,E[1]]);
		let TU=TR* CB;
		let TV=((TS- TT)* CB)+ L3([0.0,(DO* TR),0.0]);
		let TW=TV* TU;
		let TY=((TU* TU)+ TX).sqrt();
		let TZ=(TU+ TY)* GP;
		let UA=TQ- (CC* TZ);
		let UB=TS- (L3([0.0,(DP* TZ),0.0])+ (((TV+ ((TW+ TW)* (FP/ (GO* TY))))* GP)* CC));
		let UC=UA/ CA;
		let UD=FH- UC;
		let UE=FH- IX;
		let UF=((UD.ln())* UE).exp();
		let UG=FH- UF;
		let UH=((CA* UG)/ UE)+ (RH* (D- UA));
		let UI=((L3([0.0,(DN* UG),0.0])+ ((((((((UB).product_sum_div(FP,L3([0.0,DN,0.0]),(-UC),CA))* FW)* (FP/ UD))* UE)* UF)* FW)* CA))/ UE)+ ((TT- UB)* RH);
		let UJ=QG* UH;
		let UK=L3([0.0,(QH* UH),0.0])+ (UI* QG);
		UL=UJ;
		UM=UK;
		}else{
		UL=QV;
		UM=RW;
		}
		QY=UL;
		QZ=UM;
		}
		QO=QD;
		QP=QV;
		QQ=QY;
		QR=QE;
		QS=RA;
		QT=QZ;
		}else{
		let QK=BY* QC;
		let QL=DL* QC;
		let QN=QM< 100f64;
		let UP;
		let UQ;
		if QN{
		let UN=QK> QV;
		let VN;
		let VO;
		if UN{
		let UU=MU/ GM;
		let UV=QM- CD;
		let UW=DQ* FW;
		let UX=FH- ((-0.8754687373538999f64/ MU).exp());
		let UY=CD* UX;
		let UZ=DQ* UX;
		let VA=RH* QK;
		let VB=QL* RH;
		let VC=UU- MU;
		let VD=QM/ CD;
		let VE=(VC* (VD.ln())).exp();
		let VF=QK* VE;
		let VG=(QL* VE)+ (((((product_div(DQ,(-VD),CD))* (FP/ VD))* VC)* VE)* QK);
		let VH=UY- I;
		let VI=L3([UZ,0.0,0.0]);
		let VJ=L3([0.0,J[0],J[1]]);
		let VK=VH* CB;
		let VL=((VI- VJ)* CB)+ L3([(DO* VH),0.0,0.0]);
		let VM=VK< RU;
		let VU;
		let VV;
		if VM{
		let VP=VK.exp();
		let VQ=FH+ VP;
		let VR=VQ.ln();
		let VS=UY- (CC* VR);
		let VT=VI- (L3([(DP* VR),0.0,0.0])+ (((VL* VP)* (FP/ VQ))* CC));
		VU=VS;
		VV=VT;
		}else{
		VU=I;
		VV=VJ;
		}
		let VW=(SG* UV)+ (GM* CC);
		let VX=(UW* SG)+ (DP* GM);
		let VY=(UV+ VU)/ VW;
		let VZ=((L3([UW,0.0,0.0])+ VV)).product_sum_div(FP,L3([VX,0.0,0.0]),(-VY),VW);
		let WA=VY< RU;
		let WI;
		let WJ;
		if WA{
		let WB=VY.exp();
		let WC=FH+ WB;
		let WD=(-(UV+ UY))/ VW;
		let WE=WD.exp();
		let WF=(WC.ln())- WE;
		let WG=(-UV)+ (VW* WF);
		let WH=L3([(UW* FW),0.0,0.0])+ (L3([(VX* WF),0.0,0.0])+ ((((VZ* WB)* (FP/ WC))- L3([((product_sum_div(((UW+ UZ)* FW),FP,VX,(-WD),VW))* WE),0.0,0.0]))* VW));
		WI=WG;
		WJ=WH;
		}else{
		WI=VU;
		WJ=VV;
		}
		let WK=I- VU;
		let WL=VU/ CD;
		let WM=L3([DQ,0.0,0.0]);
		let WN=FH- WL;
		let WO=WI/ CD;
		let WP=FH- WO;
		let WQ=WP.ln();
		let WR=(((WJ).product_sum_div(FP,WM,(-WO),CD))* FW)* (FP/ WP);
		let WS=FH- MU;
		let WT=FH- UU;
		let WU=(WQ* WS).exp();
		let WV=FH- WU;
		let WW=((WN.ln())* WT).exp();
		let WX=FH- WW;
		let WY=(WQ* WT).exp();
		let WZ=FH- WY;
		let XA=((L3([(QL* WV),0.0,0.0])+ ((((WR* WS)* WU)* FW)* QK))/ WS)+ ((L3([(VG* WX),0.0,0.0])+ ((((((((VV).product_sum_div(FP,WM,(-WL),CD))* FW)* (FP/ WN))* WT)* WW)* FW)* VF))/ WT);
		let XB=(((QK* WV)/ WS)+ ((VF* WX)/ WT))- ((VF* WZ)/ WT);
		let XC=(XB* CD)+ (VA* WK);
		let XD=(((XA- ((L3([(VG* WZ),0.0,0.0])+ ((((WR* WT)* WY)* FW)* VF))/ WT))* CD)+ L3([(DQ* XB),0.0,0.0]))+ (L3([(VB* WK),0.0,0.0])+ ((VJ- VV)* VA));
		VN=XC;
		VO=XD;
		}else{
		VN=QV;
		VO=RA;
		}
		UP=VN;
		UQ=VO;
		}else{
		let UO=QK> QV;
		let XZ;
		let YA;
		if UO{
		let XE=FH- ((-0.8754687373538999f64/ MU).exp());
		let XF=CD* XE;
		let XG=XF- I;
		let XH=L3([(DQ* XE),0.0,0.0]);
		let XI=L3([0.0,J[0],J[1]]);
		let XJ=XG* CB;
		let XK=((XH- XI)* CB)+ L3([(DO* XG),0.0,0.0]);
		let XL=XK* XJ;
		let XM=((XJ* XJ)+ TX).sqrt();
		let XN=(XJ+ XM)* GP;
		let XO=XF- (CC* XN);
		let XP=XH- (L3([(DP* XN),0.0,0.0])+ (((XK+ ((XL+ XL)* (FP/ (GO* XM))))* GP)* CC));
		let XQ=XO/ CD;
		let XR=FH- XQ;
		let XS=FH- MU;
		let XT=((XR.ln())* XS).exp();
		let XU=FH- XT;
		let XV=((CD* XU)/ XS)+ (RH* (I- XO));
		let XW=((L3([(DQ* XU),0.0,0.0])+ ((((((((XP).product_sum_div(FP,L3([DQ,0.0,0.0]),(-XQ),CD))* FW)* (FP/ XR))* XS)* XT)* FW)* CD))/ XS)+ ((XI- XP)* RH);
		let XX=QK* XV;
		let XY=L3([(QL* XV),0.0,0.0])+ (XW* QK);
		XZ=XX;
		YA=XY;
		}else{
		XZ=QV;
		YA=RA;
		}
		UP=XZ;
		UQ=YA;
		}
		let UR=FH- QC;
		let US=BY* UR;
		let UT=DL* UR;
		let YD;
		let YE;
		if QN{
		let YB=US> QV;
		let YY;
		let YZ;
		if YB{
		let YF=MU/ GM;
		let YG=QM- CD;
		let YH=DQ* FW;
		let YI=FH- ((-0.8754687373538999f64/ MU).exp());
		let YJ=CD* YI;
		let YK=DQ* YI;
		let YL=RH* US;
		let YM=UT* RH;
		let YN=YF- MU;
		let YO=QM/ CD;
		let YP=(YN* (YO.ln())).exp();
		let YQ=US* YP;
		let YR=(UT* YP)+ (((((product_div(DQ,(-YO),CD))* (FP/ YO))* YN)* YP)* US);
		let YS=YJ- D;
		let YT=L3([0.0,YK,0.0]);
		let YU=L3([E[0],0.0,E[1]]);
		let YV=YS* CB;
		let YW=((YT- YU)* CB)+ L3([0.0,(DO* YS),0.0]);
		let YX=YV< RU;
		let ZF;
		let ZG;
		if YX{
		let ZA=YV.exp();
		let ZB=FH+ ZA;
		let ZC=ZB.ln();
		let ZD=YJ- (CC* ZC);
		let ZE=YT- (L3([0.0,(DP* ZC),0.0])+ (((YW* ZA)* (FP/ ZB))* CC));
		ZF=ZD;
		ZG=ZE;
		}else{
		ZF=D;
		ZG=YU;
		}
		let ZH=(SG* YG)+ (GM* CC);
		let ZI=(YH* SG)+ (DP* GM);
		let ZJ=(YG+ ZF)/ ZH;
		let ZK=((L3([0.0,YH,0.0])+ ZG)).product_sum_div(FP,L3([0.0,ZI,0.0]),(-ZJ),ZH);
		let ZL=ZJ< RU;
		let ZT;
		let ZU;
		if ZL{
		let ZM=ZJ.exp();
		let ZN=FH+ ZM;
		let ZO=(-(YG+ YJ))/ ZH;
		let ZP=ZO.exp();
		let ZQ=(ZN.ln())- ZP;
		let ZR=(-YG)+ (ZH* ZQ);
		let ZS=L3([0.0,(YH* FW),0.0])+ (L3([0.0,(ZI* ZQ),0.0])+ ((((ZK* ZM)* (FP/ ZN))- L3([0.0,((product_sum_div(((YH+ YK)* FW),FP,ZI,(-ZO),ZH))* ZP),0.0]))* ZH));
		ZT=ZR;
		ZU=ZS;
		}else{
		ZT=ZF;
		ZU=ZG;
		}
		let ZV=D- ZF;
		let ZW=ZF/ CD;
		let ZX=L3([0.0,DQ,0.0]);
		let ZY=FH- ZW;
		let ZZ=ZT/ CD;
		let AAA=FH- ZZ;
		let AAB=AAA.ln();
		let AAC=(((ZU).product_sum_div(FP,ZX,(-ZZ),CD))* FW)* (FP/ AAA);
		let AAD=FH- MU;
		let AAE=FH- YF;
		let AAF=(AAB* AAD).exp();
		let AAG=FH- AAF;
		let AAH=((ZY.ln())* AAE).exp();
		let AAI=FH- AAH;
		let AAJ=(AAB* AAE).exp();
		let AAK=FH- AAJ;
		let AAL=((L3([0.0,(UT* AAG),0.0])+ ((((AAC* AAD)* AAF)* FW)* US))/ AAD)+ ((L3([0.0,(YR* AAI),0.0])+ ((((((((ZG).product_sum_div(FP,ZX,(-ZW),CD))* FW)* (FP/ ZY))* AAE)* AAH)* FW)* YQ))/ AAE);
		let AAM=(((US* AAG)/ AAD)+ ((YQ* AAI)/ AAE))- ((YQ* AAK)/ AAE);
		let AAN=(AAM* CD)+ (YL* ZV);
		let AAO=(((AAL- ((L3([0.0,(YR* AAK),0.0])+ ((((AAC* AAE)* AAJ)* FW)* YQ))/ AAE))* CD)+ L3([0.0,(DQ* AAM),0.0]))+ (L3([0.0,(YM* ZV),0.0])+ ((YU- ZG)* YL));
		YY=AAN;
		YZ=AAO;
		}else{
		YY=QV;
		YZ=RW;
		}
		YD=YY;
		YE=YZ;
		}else{
		let YC=US> QV;
		let ABK;
		let ABL;
		if YC{
		let AAP=FH- ((-0.8754687373538999f64/ MU).exp());
		let AAQ=CD* AAP;
		let AAR=AAQ- D;
		let AAS=L3([0.0,(DQ* AAP),0.0]);
		let AAT=L3([E[0],0.0,E[1]]);
		let AAU=AAR* CB;
		let AAV=((AAS- AAT)* CB)+ L3([0.0,(DO* AAR),0.0]);
		let AAW=AAV* AAU;
		let AAX=((AAU* AAU)+ TX).sqrt();
		let AAY=(AAU+ AAX)* GP;
		let AAZ=AAQ- (CC* AAY);
		let ABA=AAS- (L3([0.0,(DP* AAY),0.0])+ (((AAV+ ((AAW+ AAW)* (FP/ (GO* AAX))))* GP)* CC));
		let ABB=AAZ/ CD;
		let ABC=FH- ABB;
		let ABD=FH- MU;
		let ABE=((ABC.ln())* ABD).exp();
		let ABF=FH- ABE;
		let ABG=((CD* ABF)/ ABD)+ (RH* (D- AAZ));
		let ABH=((L3([0.0,(DQ* ABF),0.0])+ ((((((((ABA).product_sum_div(FP,L3([0.0,DQ,0.0]),(-ABB),CD))* FW)* (FP/ ABC))* ABD)* ABE)* FW)* CD))/ ABD)+ ((AAT- ABA)* RH);
		let ABI=US* ABG;
		let ABJ=L3([0.0,(UT* ABG),0.0])+ (ABH* US);
		ABK=ABI;
		ABL=ABJ;
		}else{
		ABK=QV;
		ABL=RW;
		}
		YD=ABK;
		YE=ABL;
		}
		QO=BZ;
		QP=UP;
		QQ=YD;
		QR=DM;
		QS=UQ;
		QT=YE;
		}
		let ABO;
		let ABP;
		if QU{
		let ABM=QO> QV;
		let ACM;
		let ACN;
		if ABM{
		let ABT=IX/ GM;
		let ABU=QI- CA;
		let ABV=DN* FW;
		let ABW=FH- ((-0.8754687373538999f64/ IX).exp());
		let ABX=CA* ABW;
		let ABY=DN* ABW;
		let ABZ=RH* QO;
		let ACA=QR* RH;
		let ACB=ABT- IX;
		let ACC=QI/ CA;
		let ACD=(ACB* (ACC.ln())).exp();
		let ACE=QO* ACD;
		let ACF=(QR* ACD)+ (((((product_div(DN,(-ACC),CA))* (FP/ ACC))* ACB)* ACD)* QO);
		let ACG=ABX- I;
		let ACH=L3([ABY,0.0,0.0]);
		let ACI=L3([0.0,J[0],J[1]]);
		let ACJ=ACG* CB;
		let ACK=((ACH- ACI)* CB)+ L3([(DO* ACG),0.0,0.0]);
		let ACL=ACJ< RU;
		let ACT;
		let ACU;
		if ACL{
		let ACO=ACJ.exp();
		let ACP=FH+ ACO;
		let ACQ=ACP.ln();
		let ACR=ABX- (CC* ACQ);
		let ACS=ACH- (L3([(DP* ACQ),0.0,0.0])+ (((ACK* ACO)* (FP/ ACP))* CC));
		ACT=ACR;
		ACU=ACS;
		}else{
		ACT=I;
		ACU=ACI;
		}
		let ACV=(SG* ABU)+ (GM* CC);
		let ACW=(ABV* SG)+ (DP* GM);
		let ACX=(ABU+ ACT)/ ACV;
		let ACY=((L3([ABV,0.0,0.0])+ ACU)).product_sum_div(FP,L3([ACW,0.0,0.0]),(-ACX),ACV);
		let ACZ=ACX< RU;
		let ADH;
		let ADI;
		if ACZ{
		let ADA=ACX.exp();
		let ADB=FH+ ADA;
		let ADC=(-(ABU+ ABX))/ ACV;
		let ADD=ADC.exp();
		let ADE=(ADB.ln())- ADD;
		let ADF=(-ABU)+ (ACV* ADE);
		let ADG=L3([(ABV* FW),0.0,0.0])+ (L3([(ACW* ADE),0.0,0.0])+ ((((ACY* ADA)* (FP/ ADB))- L3([((product_sum_div(((ABV+ ABY)* FW),FP,ACW,(-ADC),ACV))* ADD),0.0,0.0]))* ACV));
		ADH=ADF;
		ADI=ADG;
		}else{
		ADH=ACT;
		ADI=ACU;
		}
		let ADJ=I- ACT;
		let ADK=ACT/ CA;
		let ADL=L3([DN,0.0,0.0]);
		let ADM=FH- ADK;
		let ADN=ADH/ CA;
		let ADO=FH- ADN;
		let ADP=ADO.ln();
		let ADQ=(((ADI).product_sum_div(FP,ADL,(-ADN),CA))* FW)* (FP/ ADO);
		let ADR=FH- IX;
		let ADS=FH- ABT;
		let ADT=(ADP* ADR).exp();
		let ADU=FH- ADT;
		let ADV=((ADM.ln())* ADS).exp();
		let ADW=FH- ADV;
		let ADX=(ADP* ADS).exp();
		let ADY=FH- ADX;
		let ADZ=((L3([(QR* ADU),0.0,0.0])+ ((((ADQ* ADR)* ADT)* FW)* QO))/ ADR)+ ((L3([(ACF* ADW),0.0,0.0])+ ((((((((ACU).product_sum_div(FP,ADL,(-ADK),CA))* FW)* (FP/ ADM))* ADS)* ADV)* FW)* ACE))/ ADS);
		let AEA=(((QO* ADU)/ ADR)+ ((ACE* ADW)/ ADS))- ((ACE* ADY)/ ADS);
		let AEB=(AEA* CA)+ (ABZ* ADJ);
		let AEC=(((ADZ- ((L3([(ACF* ADY),0.0,0.0])+ ((((ADQ* ADS)* ADX)* FW)* ACE))/ ADS))* CA)+ L3([(DN* AEA),0.0,0.0]))+ (L3([(ACA* ADJ),0.0,0.0])+ ((ACI- ACU)* ABZ));
		ACM=AEB;
		ACN=AEC;
		}else{
		ACM=QV;
		ACN=RA;
		}
		ABO=ACM;
		ABP=ACN;
		}else{
		let ABN=QO> QV;
		let AEY;
		let AEZ;
		if ABN{
		let AED=FH- ((-0.8754687373538999f64/ IX).exp());
		let AEE=CA* AED;
		let AEF=AEE- I;
		let AEG=L3([(DN* AED),0.0,0.0]);
		let AEH=L3([0.0,J[0],J[1]]);
		let AEI=AEF* CB;
		let AEJ=((AEG- AEH)* CB)+ L3([(DO* AEF),0.0,0.0]);
		let AEK=AEJ* AEI;
		let AEL=((AEI* AEI)+ TX).sqrt();
		let AEM=(AEI+ AEL)* GP;
		let AEN=AEE- (CC* AEM);
		let AEO=AEG- (L3([(DP* AEM),0.0,0.0])+ (((AEJ+ ((AEK+ AEK)* (FP/ (GO* AEL))))* GP)* CC));
		let AEP=AEN/ CA;
		let AEQ=FH- AEP;
		let AER=FH- IX;
		let AES=((AEQ.ln())* AER).exp();
		let AET=FH- AES;
		let AEU=((CA* AET)/ AER)+ (RH* (I- AEN));
		let AEV=((L3([(DN* AET),0.0,0.0])+ ((((((((AEO).product_sum_div(FP,L3([DN,0.0,0.0]),(-AEP),CA))* FW)* (FP/ AEQ))* AER)* AES)* FW)* CA))/ AER)+ ((AEH- AEO)* RH);
		let AEW=QO* AEU;
		let AEX=L3([(QR* AEU),0.0,0.0])+ (AEV* QO);
		AEY=AEW;
		AEZ=AEX;
		}else{
		AEY=QV;
		AEZ=RA;
		}
		ABO=AEY;
		ABP=AEZ;
		}
		let ABQ=ABO+ QP;
		let ABR=ABP+ QS;
		let ABS=QO> QV;
		let AFX;
		let AFY;
		if ABS{
		let AFA=FH- ((-0.8754687373538999f64/ IX).exp());
		let AFB=CA* AFA;
		let AFC=AFB- I;
		let AFD=L3([(DN* AFA),0.0,0.0]);
		let AFE=AFC* CB;
		let AFF=((AFD- L3([0.0,J[0],J[1]]))* CB)+ L3([(DO* AFC),0.0,0.0]);
		let AFG=AFF* AFE;
		let AFH=((AFE* AFE)+ TX).sqrt();
		let AFI=(AFG+ AFG)* (FP/ (GO* AFH));
		let AFJ=(AFE+ AFH)* GP;
		let AFK=(AFF+ AFI)* GP;
		let AFL=AFJ/ AFH;
		let AFM=(AFK).product_sum_div(FP,AFI,(-AFL),AFH);
		let AFN=-IX;
		let AFO=(AFB- (CC* AFJ))/ CA;
		let AFP=FH- AFO;
		let AFQ=(AFN* (AFP.ln())).exp();
		let AFR=QO* AFQ;
		let AFS=L3([(QR* AFQ),0.0,0.0])+ ((((((((AFD- (L3([(DP* AFJ),0.0,0.0])+ (AFK* CC)))).product_sum_div(FP,L3([DN,0.0,0.0]),(-AFO),CA))* FW)* (FP/ AFP))* AFN)* AFQ)* QO);
		let AFT=RH* QO;
		let AFU=FH- AFL;
		let AFV=(AFR* AFL)+ (AFT* AFU);
		let AFW=((AFS* AFL)+ (AFM* AFR))+ (L3([((QR* RH)* AFU),0.0,0.0])+ ((AFM* FW)* AFT));
		AFX=AFV;
		AFY=AFW;
		}else{
		AFX=QV;
		AFY=RA;
		}
		let AGE;
		let AGF;
		if AC{
		let AFZ=CE- I;
		let AGA=L3([DR,0.0,0.0])- L3([0.0,J[0],J[1]]);
		let AGB=L4([AGA[0],AGA[1],AGA[2],0.0]);
		AGE=AFZ;
		AGF=AGB;
		}else{
		let AGC=P- CF;
		let AGD=L4([0.0,Q[0],Q[1],Q[2]])- L4([DS,0.0,0.0,0.0]);
		AGE=AGC;
		AGF=AGD;
		}
		let AGG=(AGF* CB)+ L4([(DO* AGE),0.0,0.0,0.0]);
		let AGH=(AGE* CB)- FH;
		let AGI=AGG* AGH;
		let AGJ=((AGH* AGH)+ TX).sqrt();
		let AGK=FH+ ((AGH+ AGJ)/ GH);
		let AGL=AGK* CC;
		let AGM=(((AGG+ ((AGI+ AGI)* (FP/ (GO* AGJ))))/ GH)* CC)+ L4([(DP* AGK),0.0,0.0,0.0]);
		let AGN=AGL/ CG;
		let AGO=L4([DT,0.0,0.0,0.0]);
		let AGQ=(AGP* (AGN.ln())).exp();
		let AGR=FH+ AGQ;
		let AGS=((AGR.ln())/ AGP).exp();
		let AGT=(AGL* CH)/ AGS;
		let AGU=(((AGM* CH)+ L4([(DU* AGL),0.0,0.0,0.0]))).product_sum_div(FP,((((((((AGM).product_sum_div(FP,AGO,(-AGN),CG))* (FP/ AGN))* AGP)* AGQ)* (FP/ AGR))/ AGP)* AGS),(-AGT),AGS);
		let AGW=(AGL- CG)/ AGV;
		let AGX=(AGM- AGO)/ AGV;
		let AGY=AGX* AGW;
		let AGZ=((AGW* AGW)+ parameters[66]).sqrt();
		let AHA=FH+ (GP* (AGW+ AGZ));
		let AHB=AGT* AHA;
		let AHC=(AGU* AHA)+ (((AGX+ ((AGY+ AGY)* (FP/ (GO* AGZ))))* GP)* AGT);
		let AHD=(AFX> QV)&& ABS;
		let AHJ;
		let AHK;
		let AHL;
		let AHM;
		if AHD{
		let AHE=QO/ AFX;
		let AHF=L3([QR,0.0,0.0]);
		let AHG=(AHF).product_sum_div(FP,AFY,(-AHE),AFX);
		let AHH=ABO/ QO;
		let AHI=(ABP).product_sum_div(FP,AHF,(-AHH),QO);
		AHJ=AHH;
		AHK=AHE;
		AHL=AHI;
		AHM=AHG;
		}else{
		AHJ=QV;
		AHK=FH;
		AHL=RA;
		AHM=RA;
		}
		let AHN=CI> QV;
		let AIM;
		let AIN;
		if AHN{
		let AHO=((-(CK.ln()))/ GW).exp();
		let AHP=FH- AHO;
		let AHQ=CJ* AHP;
		let AHR=AHQ- N;
		let AHS=L3([((DW* AHP)+ ((((((DX* (FP/ CK))* FW)/ GW)* AHO)* FW)* CJ)),0.0,0.0]);
		let AHT=L3([0.0,O[0],O[1]]);
		let AHU=AHR* CB;
		let AHV=((AHS- AHT)* CB)+ L3([(DO* AHR),0.0,0.0]);
		let AHW=AHV* AHU;
		let AHX=((AHU* AHU)+ TX).sqrt();
		let AHY=(AHU+ AHX)* GP;
		let AHZ=AHQ- (CC* AHY);
		let AIA=AHS- (L3([(DP* AHY),0.0,0.0])+ (((AHV+ ((AHW+ AHW)* (FP/ (GO* AHX))))* GP)* CC));
		let AIB=AHZ/ CJ;
		let AIC=FH- AIB;
		let AID=FH- GW;
		let AIE=((AIC.ln())* AID).exp();
		let AIF=FH- AIE;
		let AIG=N- AHZ;
		let AIH=((CJ* AIF)/ AID)+ (CK* AIG);
		let AII=((L3([(DW* AIF),0.0,0.0])+ ((((((((AIA).product_sum_div(FP,L3([DW,0.0,0.0]),(-AIB),CJ))* FW)* (FP/ AIC))* AID)* AIE)* FW)* CJ))/ AID)+ (L3([(DX* AIG),0.0,0.0])+ ((AHT- AIA)* CK));
		let AIJ=CI* AIH;
		let AIK=L3([(DV* AIH),0.0,0.0])+ (AII* CI);
		AIM=AIJ;
		AIN=AIK;
		}else{
		AIM=QV;
		AIN=AIL;
		}
		let AIO=AIM/ CI;
		let AIP=(AIN).product_sum_div(FP,L3([DV,0.0,0.0]),(-AIO),CI);
		let AIR;
		let AIS;
		let AIT;
		let AIU;
		if AF{
		let AIQ=CL> QV;
		let AJT;
		let AJU;
		if AIQ{
		let AIW=((-(CN.ln()))/ HQ).exp();
		let AIX=FH- AIW;
		let AIY=CM* AIX;
		let AIZ=AIY- N;
		let AJA=L3([((DZ* AIX)+ ((((((EA* (FP/ CN))* FW)/ HQ)* AIW)* FW)* CM)),0.0,0.0]);
		let AJB=L3([0.0,O[0],O[1]]);
		let AJC=AIZ* CB;
		let AJD=((AJA- AJB)* CB)+ L3([(DO* AIZ),0.0,0.0]);
		let AJE=AJD* AJC;
		let AJF=((AJC* AJC)+ TX).sqrt();
		let AJG=(AJC+ AJF)* GP;
		let AJH=AIY- (CC* AJG);
		let AJI=AJA- (L3([(DP* AJG),0.0,0.0])+ (((AJD+ ((AJE+ AJE)* (FP/ (GO* AJF))))* GP)* CC));
		let AJJ=AJH/ CM;
		let AJK=FH- AJJ;
		let AJL=FH- HQ;
		let AJM=((AJK.ln())* AJL).exp();
		let AJN=FH- AJM;
		let AJO=N- AJH;
		let AJP=((CM* AJN)/ AJL)+ (CN* AJO);
		let AJQ=((L3([(DZ* AJN),0.0,0.0])+ ((((((((AJI).product_sum_div(FP,L3([DZ,0.0,0.0]),(-AJJ),CM))* FW)* (FP/ AJK))* AJL)* AJM)* FW)* CM))/ AJL)+ (L3([(EA* AJO),0.0,0.0])+ ((AJB- AJI)* CN));
		let AJR=CL* AJP;
		let AJS=L3([(DY* AJP),0.0,0.0])+ (AJQ* CL);
		AJT=AJR;
		AJU=AJS;
		}else{
		AJT=QV;
		AJU=AIL;
		}
		let AJV=AJT/ CL;
		let AJW=(AJU).product_sum_div(FP,L3([DY,0.0,0.0]),(-AJV),CL);
		AIR=CM;
		AIS=AJV;
		AIT=DZ;
		AIU=AJW;
		}else{
		AIR=CJ;
		AIS=AIO;
		AIT=DW;
		AIU=AIP;
		}
		let AKP;
		let AKQ;
		if AIV{
		AKP=FH;
		AKQ=AIL;
		}else{
		let AJY=AJX* CC;
		let AJZ=DP* AJX;
		let AKA=L3([AIT,0.0,0.0]);
		let AKB=(AIR- N)/ AJY;
		let AKC=((AKA- L3([0.0,O[0],O[1]]))).product_sum_div(FP,L3([AJZ,0.0,0.0]),(-AKB),AJY);
		let AKD=AKC* AKB;
		let AKE=((AKB* AKB)+ TX).sqrt();
		let AKF=AKB+ AKE;
		let AKG=(AIR- ((AJY* AKF)* GP))/ AIR;
		let AKH=FH- AKG;
		let AKI=((((AKA- ((L3([(AJZ* AKF),0.0,0.0])+ ((AKC+ ((AKD+ AKD)* (FP/ (GO* AKE))))* AJY))* GP))).product_sum_div(FP,AKA,(-AKG),AIR))* FW)* (FP/ AKH);
		let AKK=(AKJ* (AKH.ln())).exp();
		let AKL=FH- AKK;
		let AKM=CO* AKL;
		let AKN=L3([(EB* AKL),0.0,0.0])+ ((((AKI* AKJ)* AKK)* FW)* CO);
		let AKO=(AKM.abs())>= 1e-3f64;
		let ALN;
		let ALO;
		if AKO{
		let ALI=AKM.exp();
		let ALJ=(ALI- FH)/ AKM;
		let ALK=((AKN* ALI)).product_sum_div(FP,AKN,(-ALJ),AKM);
		ALN=ALJ;
		ALO=ALK;
		}else{
		let ALL=AKN* GP;
		let ALM=FH+ (AKM* GP);
		ALN=ALM;
		ALO=ALL;
		}
		AKP=ALN;
		AKQ=ALO;
		}
		let AKR=(AKP* AIS)/ CP;
		let AKS=(((AKQ* AIS)+ (AIU* AKP))).product_sum_div(FP,L3([EC,0.0,0.0]),(-AKR),CP);
		let AKU=AHL/ AKT;
		let AKV=(L4([AKS[0],0.0,AKS[1],AKS[2]])+ L4([AKU[0],AKU[1],AKU[2],0.0]))* 20f64;
		let AKW=(20f64* ((FH+ AKR)+ (AHJ/ AKT)))- FH;
		let AKX=AKV* AKW;
		let AKY=((AKW* AKW)+ TX).sqrt();
		let AKZ=0.025f64* (FH+ ((AKW+ AKY)/ GH));
		let ALA=((AKV+ ((AKX+ AKX)* (FP/ (GO* AKY))))/ GH)* 0.025f64;
		let ALC=L3([ED,0.0,0.0]);
		let ALD=FH/ AHK;
		let ALF=(CQ+ (ALB* (AHK- FH)))+ (ALE* (ALD- FH));
		let ALG=(ALC+ (AHM* ALB))+ (((AHM).product_div((-ALD),AHK))* ALE);
		let ALU;
		let ALV;
		if ALH{
		let ALP=ALF/ CQ;
		let ALQ=FH+ (ALP- FH);
		let ALR=CR/ ALQ;
		let ALS=(L3([EE,0.0,0.0])).product_sum_div(FP,((ALG).product_sum_div(FP,ALC,(-ALP),CQ)),(-ALR),ALQ);
		ALU=ALR;
		ALV=ALS;
		}else{
		let ALT=L3([EE,0.0,0.0]);
		ALU=CR;
		ALV=ALT;
		}
		let ALX=ALW* CC;
		let ALY=N/ ALX;
		let ALZ=L3([0.0,O[0],O[1]]);
		let AMA=(ALZ).product_sum_div(FP,L3([(DP* ALW),0.0,0.0]),(-ALY),ALX);
		let AMB=ALY> RU;
		let AMD;
		let AME;
		let AMF;
		let AMG;
		if AMB{
		let AMC=FH+ (ALY- RU);
		AMD=AMC;
		AME=RU;
		AMF=AMA;
		AMG=AIL;
		}else{
		AMD=FH;
		AME=ALY;
		AMF=AIL;
		AMG=AMA;
		}
		let AMH=rspice_limexp(AME);
		let AMI=AMD* AMH;
		let AMJ=CS* AMI;
		let AMK=L3([(EF* AMI),0.0,0.0])+ (((AMF* AMH)+ ((AMG* AMH)* AMD))* CS);
		let AMM=AML* CC;
		let AMN=I/ AMM;
		let AMO=L3([0.0,J[0],J[1]]);
		let AMP=(AMO).product_sum_div(FP,L3([(DP* AML),0.0,0.0]),(-AMN),AMM);
		let AMQ=AMN> RU;
		let AMS;
		let AMT;
		let AMU;
		let AMV;
		if AMQ{
		let AMR=FH+ (AMN- RU);
		AMS=AMR;
		AMT=RU;
		AMU=AMP;
		AMV=RA;
		}else{
		AMS=FH;
		AMT=AMN;
		AMU=RA;
		AMV=AMP;
		}
		let AMW=rspice_limexp(AMT);
		let AMX=AMS* AMW;
		let AMY=CS* AMX;
		let AMZ=L3([(EF* AMX),0.0,0.0])+ (((AMU* AMW)+ ((AMV* AMW)* AMS))* CS);
		let AOD;
		let AOE;
		let AOF;
		let AOG;
		if ANA{
		let ANB=AMJ/ ALU;
		let ANC=L4([AMK[0],0.0,AMK[1],AMK[2]]);
		let ANE=AMZ/ AND;
		let ANF=ANB+ (AMY/ AND);
		let ANG=((ANC).product_sum_div(FP,L4([ALV[0],ALV[1],ALV[2],0.0]),(-ANB),ALU))+ L4([ANE[0],ANE[1],ANE[2],0.0]);
		let ANH=AMJ/ AHB;
		let ANI=AMJ* ANH;
		let ANJ=AMK* ANH;
		let ANK=CT/ CU;
		let ANL=ANI* ANK;
		let ANM=(((L4([ANJ[0],0.0,ANJ[1],ANJ[2]])+ (((ANC).product_sum_div(FP,AHC,(-ANH),AHB))* AMJ))* ANK)+ L4([((product_sum_div(EG,FP,EH,(-ANK),CU))* ANI),0.0,0.0,0.0]))* (FP/ ANL);
		let ANO=(ANN* (ANL.ln())).exp();
		let ANP=ANF+ ANO;
		let ANQ=ANG+ ((ANM* ANN)* ANO);
		let ANR=AMJ/ CU;
		let ANS=(AMK).product_sum_div(FP,L3([EH,0.0,0.0]),(-ANR),CU);
		let ANT=(ANF+ ANR)+ ANO;
		let ANU=(ANG+ L4([ANS[0],0.0,ANS[1],ANS[2]]))+ ((ANM* ANN)* ANO);
		AOD=ANP;
		AOE=ANT;
		AOF=ANQ;
		AOG=ANU;
		}else{
		let ANV=AMJ/ ALU;
		let ANW=AMZ/ AND;
		let ANX=ANV+ (AMY/ AND);
		let ANY=((L4([AMK[0],0.0,AMK[1],AMK[2]])).product_sum_div(FP,L4([ALV[0],ALV[1],ALV[2],0.0]),(-ANV),ALU))+ L4([ANW[0],ANW[1],ANW[2],0.0]);
		let ANZ=AMJ/ CU;
		let AOA=(AMK).product_sum_div(FP,L3([EH,0.0,0.0]),(-ANZ),CU);
		let AOB=ANX+ ANZ;
		let AOC=ANY+ L4([AOA[0],0.0,AOA[1],AOA[2]]);
		AOD=ANX;
		AOE=AOB;
		AOF=ANY;
		AOG=AOC;
		}
		let AOH=AKZ* AKZ;
		let AOI=ALA* AKZ;
		let AOJ=AOI+ AOI;
		let AOK=(AOH+ AOD).sqrt();
		let AOL=AKZ+ AOK;
		let AOM=ALA+ ((AOJ+ AOF)* (FP/ (GO* AOK)));
		let AON=(AOH+ AOE).sqrt();
		let AOO=AKZ+ AON;
		let AOP=ALA+ ((AOJ+ AOG)* (FP/ (GO* AON)));
		let AOQ=((AOE- AOD).abs())> 1e-8f64;
		let APE;
		let APF;
		if AOQ{
		let AOR=FH+ parameters[14];
		let AOS=(AHB/ AOR)/ AMJ;
		let AOT=((AHC/ AOR)).product_sum_div(FP,L4([AMK[0],0.0,AMK[1],AMK[2]]),(-AOS),AMJ);
		let AOU=AOO- AOL;
		let AOV=FH+ (AOS* AOU);
		let AOW=(FH- (AOS* AOL))/ AOV;
		let AOX=((((AOT* AOL)+ (AOM* AOS))* FW)).product_sum_div(FP,((AOT* AOU)+ ((AOP- AOM)* AOS)),(-AOW),AOV);
		let AOY=AOX* AOW;
		let AOZ=((AOW* AOW)+ 0.01f64).sqrt();
		let APB=(AOZ+ AOW)/ APA;
		let APC=(((AOY+ AOY)* (FP/ (GO* AOZ)))+ AOX)/ APA;
		APE=APB;
		APF=APC;
		}else{
		APE=QV;
		APF=APD;
		}
		let APK;
		let APL;
		if APG{
		let AQK;
		let AQL;
		if ANA{
		let APO=AMJ/ ALU;
		let APP=L4([AMK[0],0.0,AMK[1],AMK[2]]);
		let APQ=AMZ/ AND;
		let APR=AMJ/ CU;
		let APS=APR* APE;
		let APT=((AMK).product_sum_div(FP,L3([EH,0.0,0.0]),(-APR),CU))* APE;
		let APU=AMJ/ AHB;
		let APV=AMJ* APU;
		let APW=AMK* APU;
		let APX=CT/ CU;
		let APY=APV* APX;
		let APZ=(ANN* (APY.ln())).exp();
		let AQA=(((((L4([APW[0],0.0,APW[1],APW[2]])+ (((APP).product_sum_div(FP,AHC,(-APU),AHB))* AMJ))* APX)+ L4([((product_sum_div(EG,FP,EH,(-APX),CU))* APV),0.0,0.0,0.0]))* (FP/ APY))* ANN)* APZ;
		let AQB=((APO+ (AMY/ AND))+ (APS* APE))+ APZ;
		let AQC=((((APP).product_sum_div(FP,L4([ALV[0],ALV[1],ALV[2],0.0]),(-APO),ALU))+ L4([APQ[0],APQ[1],APQ[2],0.0]))+ (((L4([APT[0],0.0,APT[1],APT[2]])+ (APF* APR))* APE)+ (APF* APS)))+ AQA;
		AQK=AQB;
		AQL=AQC;
		}else{
		let AQD=AMJ/ ALU;
		let AQE=AMZ/ AND;
		let AQF=AMJ/ CU;
		let AQG=AQF* APE;
		let AQH=((AMK).product_sum_div(FP,L3([EH,0.0,0.0]),(-AQF),CU))* APE;
		let AQI=(AQD+ (AMY/ AND))+ (AQG* APE);
		let AQJ=(((L4([AMK[0],0.0,AMK[1],AMK[2]])).product_sum_div(FP,L4([ALV[0],ALV[1],ALV[2],0.0]),(-AQD),ALU))+ L4([AQE[0],AQE[1],AQE[2],0.0]))+ (((L4([AQH[0],0.0,AQH[1],AQH[2]])+ (APF* AQF))* APE)+ (APF* AQG));
		AQK=AQI;
		AQL=AQJ;
		}
		let AQM=(AOH+ AQK).sqrt();
		let AQN=AKZ+ AQM;
		let AQO=ALA+ ((AOJ+ AQL)* (FP/ (GO* AQM)));
		APK=AQN;
		APL=AQO;
		}else{
		let APH=-2f64* AKZ;
		let API=ALA* -2f64;
		let AQW;
		let AQX;
		if APJ{
		AQW=QV;
		AQX=APD;
		}else{
		let AQP=AMJ/ ALU;
		let AQQ=AMZ/ AND;
		let AQR=AMJ/ CU;
		let AQS=AQR* APE;
		let AQT=((AMK).product_sum_div(FP,L3([EH,0.0,0.0]),(-AQR),CU))* APE;
		let AQU=-((AQP+ (AMY/ AND))+ (AQS* APE));
		let AQV=((((L4([AMK[0],0.0,AMK[1],AMK[2]])).product_sum_div(FP,L4([ALV[0],ALV[1],ALV[2],0.0]),(-AQP),ALU))+ L4([AQQ[0],AQQ[1],AQQ[2],0.0]))+ (((L4([AQT[0],0.0,AQT[1],AQT[2]])+ (APF* AQR))* APE)+ (APF* AQS)))* FW;
		AQW=AQU;
		AQX=AQV;
		}
		let AQY=-AMJ;
		let AQZ=((AMK* FW)* AMJ)+ (AMK* AQY);
		let ARA=(AQY* AMJ)/ AHB;
		let ARB=(ARA* CT)/ CU;
		let ARC=APH* APH;
		let ARD=API* APH;
		let ARE=ARD+ ARD;
		let ARG=AQW- (ARC* ARF);
		let ARH=AQX- (ARE* ARF);
		let ARI=GH* APH;
		let ARK=(((ARI* ARC)/ ARJ)- ((APH* AQW)* ARF))+ ARB;
		let ARL=(((((API* GH)* ARC)+ (ARE* ARI))/ ARJ)- (((API* AQW)+ (AQX* APH))* ARF))+ ((((((L4([AQZ[0],0.0,AQZ[1],AQZ[2]])).product_sum_div(FP,AHC,(-ARA),AHB))* CT)+ L4([(EG* ARA),0.0,0.0,0.0]))).product_sum_div(FP,L4([EH,0.0,0.0,0.0]),(-ARB),CU));
		let ARM=ARL* ARK;
		let ARN=ARG* ARG;
		let ARO=ARH* ARG;
		let ARP=ARN* ARG;
		let ARQ=((ARO+ ARO)* ARG)+ (ARH* ARN);
		let ARR=((ARK* ARK)* 0.25f64)+ (ARP/ ARJ);
		let ARS=((ARM+ ARM)* 0.25f64)+ (ARQ/ ARJ);
		let ART=(ARR.abs())< 1e-10f64;
		let ARY;
		let ARZ;
		if ART{
		let ARU=(3f64* ARK)/ ARG;
		let ARV=ARU- (APH* ARF);
		let ARW=(((ARL* 3f64)).product_sum_div(FP,ARH,(-ARU),ARG))- (API* ARF);
		ARY=ARV;
		ARZ=ARW;
		}else{
		let ARX=ARR> QV;
		let ASP;
		let ASQ;
		if ARX{
		let ASA=(-ARK)* GP;
		let ASB=(ARL* FW)* GP;
		let ASC=ARR.sqrt();
		let ASD=ARS* (FP/ (GO* ASC));
		let ASE=ASA+ ASC;
		let ASF=ASB+ ASD;
		let ASG=ASE> QV;
		let ASX;
		let ASY;
		if ASG{
		let ASR=(ARF* (ASE.ln())).exp();
		let ASS=((ASF* (FP/ ASE))* ARF)* ASR;
		ASX=ASR;
		ASY=ASS;
		}else{
		let AST=-ASE;
		let ASU=(ARF* (AST.ln())).exp();
		let ASV=-ASU;
		let ASW=((((ASF* FW)* (FP/ AST))* ARF)* ASU)* FW;
		ASX=ASV;
		ASY=ASW;
		}
		let ASZ=ASA- ASC;
		let ATA=ASB- ASD;
		let ATB=ASZ> QV;
		let ATI;
		let ATJ;
		if ATB{
		let ATC=(ARF* (ASZ.ln())).exp();
		let ATD=((ATA* (FP/ ASZ))* ARF)* ATC;
		ATI=ATC;
		ATJ=ATD;
		}else{
		let ATE=-ASZ;
		let ATF=(ARF* (ATE.ln())).exp();
		let ATG=-ATF;
		let ATH=((((ATA* FW)* (FP/ ATE))* ARF)* ATF)* FW;
		ATI=ATG;
		ATJ=ATH;
		}
		let ATK=(ASX+ ATI)- (APH* ARF);
		let ATL=(ASY+ ATJ)- (API* ARF);
		ASP=ATK;
		ASQ=ATL;
		}else{
		let ASH=(-ARK)* GP;
		let ASI=-27f64/ ARP;
		let ASJ=ASI.sqrt();
		let ASK=ASH* ASJ;
		let ASL=ASK* ASK;
		let ASM=((((ARL* FW)* GP)* ASJ)+ ((((ARQ).product_div((-ASI),ARP))* (FP/ (GO* ASJ)))* ASH))* ASK;
		let ASN=ASM+ ASM;
		let ASO=ASK>= QV;
		let ATW;
		let ATX;
		if ASO{
		let ATM=FH- ASL;
		let ATN=ASL/ ATM;
		let ATO=ATN.sqrt();
		let ATP=1.5707963267948966f64- (ATO.atan());
		let ATQ=((((ASN).product_sum_div(FP,(ASN* FW),(-ATN),ATM))* (FP/ (GO* ATO)))* (FP/ (FP+ (ATO* ATO))))* FW;
		ATW=ATP;
		ATX=ATQ;
		}else{
		let ATR=FH- ASL;
		let ATS=ASL/ ATR;
		let ATT=ATS.sqrt();
		let ATU=(((ASN).product_sum_div(FP,(ASN* FW),(-ATS),ATR))* (FP/ (GO* ATT)))* (FP/ (FP+ (ATT* ATT)));
		let ATV=1.5707963267948966f64+ (ATT.atan());
		ATW=ATV;
		ATX=ATU;
		}
		let ATY=((-4f64* ARG)* ARF).sqrt();
		let ATZ=ARF* ATW;
		let AUA=ATZ.cos();
		let AUB=(ATY* AUA)- (APH* ARF);
		let AUC=(((((ARH* -4f64)* ARF)* (FP/ (GO* ATY)))* AUA)+ (((ATX* ARF)* (FW* (ATZ.sin())))* ATY))- (API* ARF);
		ASP=AUB;
		ASQ=AUC;
		}
		ARY=ASP;
		ARZ=ASQ;
		}
		APK=ARY;
		APL=ARZ;
		}
		let APN=APK< APM;
		let AUD;
		let AUE;
		if APN{
		AUD=APM;
		AUE=APD;
		}else{
		AUD=APK;
		AUE=APL;
		}
		let AUF=AMJ/ AUD;
		let AUG=(L4([AMK[0],0.0,AMK[1],AMK[2]])).product_sum_div(FP,AUE,(-AUF),AUD);
		let AUH=AMY/ AUD;
		let AUI=(L4([AMZ[0],AMZ[1],AMZ[2],0.0])).product_sum_div(FP,AUE,(-AUH),AUD);
		let AUJ=AUF< APM;
		let AUK;
		let AUL;
		if AUJ{
		AUK=APM;
		AUL=APD;
		}else{
		AUK=AUF;
		AUL=AUG;
		}
		let AUM=AUK- AUH;
		let AUN=AUL- AUI;
		let AUO=ALG* AUK;
		let AUP=AHB/ AUK;
		let AUQ=FH- AUP;
		let AUR=((AHC).product_sum_div(FP,AUL,(-AUP),AUK))* FW;
		let AUS=AUR* AUQ;
		let AUT=((AUQ* AUQ)+ parameters[60]).sqrt();
		let AUV=(AUQ+ AUT)/ AUU;
		let AUW=(AUR+ ((AUS+ AUS)* (FP/ (GO* AUT))))/ AUU;
		let AUX=CV* AUV;
		let AUY=AUX* AUV;
		let AUZ=AUK/ AHB;
		let AVB=(AVA* (AUZ.ln())).exp();
		let AVC=CW* AVB;
		let AVE=(L4([AUO[0],AUO[1],AUO[2],0.0])+ (AUL* ALF))+ ((((L4([(EJ* AVB),0.0,0.0,0.0])+ ((((((AUL).product_sum_div(FP,AHC,(-AUZ),AHB))* (FP/ AUZ))* AVA)* AVB)* CW))* AUK)+ (AUL* AVC))/ AVD);
		let AVF=((ALF* AUK)+ ((AVC* AUK)/ AVD))+ (AUY* AUK);
		let AVG=AVE+ (((((L4([(EI* AUV),0.0,0.0,0.0])+ (AUW* CV))* AUV)+ (AUW* AUX))* AUK)+ (AUL* AUY));
		let AVI=AVH* AUH;
		let AVJ=AUI* AVH;
		let AVQ;
		let AVR;
		if AVK{
		let AVM=AVL* CC;
		let AVN=N/ AVM;
		let AVO=(ALZ).product_sum_div(FP,L3([(DP* AVL),0.0,0.0]),(-AVN),AVM);
		let AVP=AVN> RU;
		let AVU;
		let AVV;
		let AVW;
		let AVX;
		if AVP{
		let AVT=FH+ (AVN- RU);
		AVU=AVT;
		AVV=RU;
		AVW=AVO;
		AVX=AIL;
		}else{
		AVU=FH;
		AVV=AVN;
		AVW=AIL;
		AVX=AVO;
		}
		let AVY=rspice_limexp(AVV);
		let AVZ=(AVU* AVY)- FH;
		let AWA=CX* AVZ;
		let AWB=L3([(EK* AVZ),0.0,0.0])+ (((AVW* AVY)+ ((AVX* AVY)* AVU))* CX);
		AVQ=AWA;
		AVR=AWB;
		}else{
		AVQ=QV;
		AVR=AIL;
		}
		let AWH;
		let AWI;
		if AVS{
		let AWD=AWC* CC;
		let AWE=N/ AWD;
		let AWF=(ALZ).product_sum_div(FP,L3([(DP* AWC),0.0,0.0]),(-AWE),AWD);
		let AWG=AWE> RU;
		let AWN;
		let AWO;
		let AWP;
		let AWQ;
		if AWG{
		let AWM=FH+ (AWE- RU);
		AWN=AWM;
		AWO=RU;
		AWP=AWF;
		AWQ=AIL;
		}else{
		AWN=FH;
		AWO=AWE;
		AWP=AIL;
		AWQ=AWF;
		}
		let AWR=rspice_limexp(AWO);
		let AWS=(AWN* AWR)- FH;
		let AWT=CY* AWS;
		let AWU=L3([(EL* AWS),0.0,0.0])+ (((AWP* AWR)+ ((AWQ* AWR)* AWN))* CY);
		AWH=AWT;
		AWI=AWU;
		}else{
		AWH=QV;
		AWI=AIL;
		}
		let AWJ=AVQ+ AWH;
		let AWK=AVR+ AWI;
		let AXA;
		let AXB;
		if AWL{
		let AWW=AWV* CC;
		let AWX=I/ AWW;
		let AWY=(AMO).product_sum_div(FP,L3([(DP* AWV),0.0,0.0]),(-AWX),AWW);
		let AWZ=AWX> RU;
		let AXG;
		let AXH;
		let AXI;
		let AXJ;
		if AWZ{
		let AXF=FH+ (AWX- RU);
		AXG=AXF;
		AXH=RU;
		AXI=AWY;
		AXJ=RA;
		}else{
		AXG=FH;
		AXH=AWX;
		AXI=RA;
		AXJ=AWY;
		}
		let AXK=rspice_limexp(AXH);
		let AXL=(AXG* AXK)- FH;
		let AXM=CZ* AXL;
		let AXN=L3([(EM* AXL),0.0,0.0])+ (((AXI* AXK)+ ((AXJ* AXK)* AXG))* CZ);
		AXA=AXM;
		AXB=AXN;
		}else{
		AXA=QV;
		AXB=RA;
		}
		let AXC=AWJ+ AXA;
		let AXD=L4([AXB[0],AXB[1],AXB[2],0.0]);
		let AXE=L4([AWK[0],0.0,AWK[1],AWK[2]])+ AXD;
		let AXQ;
		let AXR;
		if QU{
		let AXO=BZ> QV;
		let AYK;
		let AYL;
		if AXO{
		let AXS=IX/ GM;
		let AXT=QI- CA;
		let AXU=DN* FW;
		let AXV=FH- ((-0.8754687373538999f64/ IX).exp());
		let AXW=CA* AXV;
		let AXX=DN* AXV;
		let AXY=RH* BZ;
		let AXZ=DM* RH;
		let AYA=AXS- IX;
		let AYB=QI/ CA;
		let AYC=(AYA* (AYB.ln())).exp();
		let AYD=BZ* AYC;
		let AYE=(DM* AYC)+ (((((product_div(DN,(-AYB),CA))* (FP/ AYB))* AYA)* AYC)* BZ);
		let AYF=AXW- I;
		let AYG=L3([AXX,0.0,0.0]);
		let AYH=AYF* CB;
		let AYI=((AYG- AMO)* CB)+ L3([(DO* AYF),0.0,0.0]);
		let AYJ=AYH< RU;
		let AYU;
		let AYV;
		let AYW;
		let AYX;
		if AYJ{
		let AYM=AYH.exp();
		let AYN=AYI* AYM;
		let AYO=FH+ AYM;
		let AYP=AYM/ AYO;
		let AYQ=(AYN).product_sum_div(FP,AYN,(-AYP),AYO);
		let AYR=AYO.ln();
		let AYS=AXW- (CC* AYR);
		let AYT=AYG- (L3([(DP* AYR),0.0,0.0])+ ((AYN* (FP/ AYO))* CC));
		AYU=AYS;
		AYV=AYP;
		AYW=AYT;
		AYX=AYQ;
		}else{
		AYU=I;
		AYV=FH;
		AYW=AMO;
		AYX=RA;
		}
		let AYY=(SG* AXT)+ (GM* CC);
		let AYZ=(AXU* SG)+ (DP* GM);
		let AZA=(AXT+ AYU)/ AYY;
		let AZB=((L3([AXU,0.0,0.0])+ AYW)).product_sum_div(FP,L3([AYZ,0.0,0.0]),(-AZA),AYY);
		let AZC=AZA< RU;
		let AZN;
		let AZO;
		let AZP;
		let AZQ;
		if AZC{
		let AZD=AZA.exp();
		let AZE=AZB* AZD;
		let AZF=FH+ AZD;
		let AZG=AZD/ AZF;
		let AZH=(AZE).product_sum_div(FP,AZE,(-AZG),AZF);
		let AZI=(-(AXT+ AXW))/ AYY;
		let AZJ=AZI.exp();
		let AZK=(AZF.ln())- AZJ;
		let AZL=(-AXT)+ (AYY* AZK);
		let AZM=L3([(AXU* FW),0.0,0.0])+ (L3([(AYZ* AZK),0.0,0.0])+ (((AZE* (FP/ AZF))- L3([((product_sum_div(((AXU+ AXX)* FW),FP,AYZ,(-AZI),AYY))* AZJ),0.0,0.0]))* AYY));
		AZN=AZL;
		AZO=AZG;
		AZP=AZM;
		AZQ=AZH;
		}else{
		AZN=AYU;
		AZO=FH;
		AZP=AYW;
		AZQ=RA;
		}
		let AZR=AYU/ CA;
		let AZS=L3([DN,0.0,0.0]);
		let AZT=FH- AZR;
		let AZU=AZN/ CA;
		let AZV=FH- AZU;
		let AZW=-IX;
		let AZX=((AZV.ln())* AZW).exp();
		let AZY=BZ* AZX;
		let AZZ=AZY* AYV;
		let BAA=((((L3([(DM* AZX),0.0,0.0])+ (((((((AZP).product_sum_div(FP,AZS,(-AZU),CA))* FW)* (FP/ AZV))* AZW)* AZX)* BZ))* AYV)+ (AYX* AZY))* AZO)+ (AZQ* AZZ);
		let BAB=-AXS;
		let BAC=((AZT.ln())* BAB).exp();
		let BAD=AYD* BAC;
		let BAE=FH- AZO;
		let BAF=FH- AYV;
		let BAG=BAA+ (((L3([(AYE* BAC),0.0,0.0])+ (((((((AYW).product_sum_div(FP,AZS,(-AZR),CA))* FW)* (FP/ AZT))* BAB)* BAC)* AYD))* BAE)+ ((AZQ* FW)* BAD));
		let BAH=((AZZ* AZO)+ (BAD* BAE))+ (AXY* BAF);
		let BAI=BAG+ (L3([(AXZ* BAF),0.0,0.0])+ ((AYX* FW)* AXY));
		AYK=BAH;
		AYL=BAI;
		}else{
		AYK=QV;
		AYL=RA;
		}
		AXQ=AYK;
		AXR=AYL;
		}else{
		let AXP=BZ> QV;
		let BBE;
		let BBF;
		if AXP{
		let BAJ=FH- ((-0.8754687373538999f64/ IX).exp());
		let BAK=CA* BAJ;
		let BAL=BAK- I;
		let BAM=L3([(DN* BAJ),0.0,0.0]);
		let BAN=BAL* CB;
		let BAO=((BAM- AMO)* CB)+ L3([(DO* BAL),0.0,0.0]);
		let BAP=BAO* BAN;
		let BAQ=((BAN* BAN)+ TX).sqrt();
		let BAR=(BAP+ BAP)* (FP/ (GO* BAQ));
		let BAS=(BAN+ BAQ)* GP;
		let BAT=(BAO+ BAR)* GP;
		let BAU=BAS/ BAQ;
		let BAV=(BAT).product_sum_div(FP,BAR,(-BAU),BAQ);
		let BAW=(BAK- (CC* BAS))/ CA;
		let BAX=FH- BAW;
		let BAY=-IX;
		let BAZ=(BAY* (BAX.ln())).exp();
		let BBA=((((((((BAM- (L3([(DP* BAS),0.0,0.0])+ (BAT* CC)))).product_sum_div(FP,L3([DN,0.0,0.0]),(-BAW),CA))* FW)* (FP/ BAX))* BAY)* BAZ)* BAU)+ (BAV* BAZ);
		let BBB=(BAZ* BAU)+ (RH* (FH- BAU));
		let BBC=BZ* BBB;
		let BBD=L3([(DM* BBB),0.0,0.0])+ ((BBA+ ((BAV* FW)* RH))* BZ);
		BBE=BBC;
		BBF=BBD;
		}else{
		BBE=QV;
		BBF=RA;
		}
		AXQ=BBE;
		AXR=BBF;
		}
		let BBJ;
		let BBK;
		if AE{
		let BBG=CA- I;
		let BBH=L3([DN,0.0,0.0])- AMO;
		let BBI=BBG> QV;
		let BBS;
		let BBT;
		if BBI{
		let BBM=DA/ AXQ;
		let BBN=-BBM;
		let BBO=(L3([EN,0.0,0.0])).product_sum_div(FP,AXR,BBN,AXQ);
		let BBP=DA/ BZ;
		let BBQ=product_sum_div(EN,FP,DM,(-BBP),BZ);
		let BBR=BBG> BBP;
		let BCJ;
		let BCK;
		if BBR{
		let BBU=BBN/ BBP;
		let BBV=L3([BBQ,0.0,0.0]);
		let BBW=BBU.exp();
		let BBX=DB* BBW;
		let BBY=BBM/ BBP;
		let BBZ=FH+ BBY;
		let BCA=BBG- BBP;
		let BCB=BBP+ (BBZ* BCA);
		let BCC=BBX* BCB;
		let BCD=((L3([(EO* BBW),0.0,0.0])+ (((((BBO* FW)).product_sum_div(FP,BBV,(-BBU),BBP))* BBW)* DB))* BCB)+ ((BBV+ ((((BBO).product_sum_div(FP,BBV,(-BBY),BBP))* BCA)+ ((BBH- BBV)* BBZ)))* BBX);
		BCJ=BCC;
		BCK=BCD;
		}else{
		let BCE=DB* BBG;
		let BCF=BBN/ BBG;
		let BCG=BCF.exp();
		let BCH=BCE* BCG;
		let BCI=((L3([(EO* BBG),0.0,0.0])+ (BBH* DB))* BCG)+ (((((BBO* FW)).product_sum_div(FP,BBH,(-BCF),BBG))* BCG)* BCE);
		BCJ=BCH;
		BCK=BCI;
		}
		let BCL=AUK* BCJ;
		let BCM=BCK* AUK;
		let BCN=(AUL* BCJ)+ L4([BCM[0],BCM[1],BCM[2],0.0]);
		BBS=BCL;
		BBT=BCN;
		}else{
		BBS=QV;
		BBT=APD;
		}
		BBJ=BBS;
		BBK=BBT;
		}else{
		BBJ=QV;
		BBK=APD;
		}
		let BBL=DC> QV;
		let BDB;
		let BDC;
		if BBL{
		let BCP=AIP/ BCO;
		let BCR=AHL/ BCQ;
		let BCS=AUK/ ALU;
		let BCT=(((FH+ (AIO/ BCO))+ (AHJ/ BCQ))+ BCS)+ (AUH/ AND);
		let BCU=((L4([BCP[0],0.0,BCP[1],BCP[2]])+ L4([BCR[0],BCR[1],BCR[2],0.0]))+ ((AUL).product_sum_div(FP,L4([ALV[0],ALV[1],ALV[2],0.0]),(-BCS),ALU)))+ (AUI/ AND);
		let BCV=BCU* BCT;
		let BCW=((BCT* BCT)+ 0.01f64).sqrt();
		let BCX=GP* (BCT+ BCW);
		let BCY=DC/ BCX;
		let BCZ=(L4([EP,0.0,0.0,0.0])).product_sum_div(FP,((BCU+ ((BCV+ BCV)* (FP/ (GO* BCW))))* GP),(-BCY),BCX);
		let BDA=AXC> QV;
		let BDM;
		let BDN;
		if BDA{
		let BDH=BDG* BCY;
		let BDI=BDH* AXC;
		let BDJ=BDI* CB;
		let BDK=((((BCZ* BDG)* AXC)+ (AXE* BDH))* CB)+ L4([(DO* BDI),0.0,0.0,0.0]);
		let BDL=BDJ< 1e-6f64;
		let BDV;
		let BDW;
		if BDL{
		let BDO=FH- (GP* BDJ);
		let BDP=BCY* BDO;
		let BDQ=(BCZ* BDO)+ (((BDK* GP)* FW)* BCY);
		BDV=BDP;
		BDW=BDQ;
		}else{
		let BDR=BDJ+ FH;
		let BDS=BDR.ln();
		let BDT=(BCY* BDS)/ BDJ;
		let BDU=(((BCZ* BDS)+ ((BDK* (FP/ BDR))* BCY))).product_sum_div(FP,BDK,(-BDT),BDJ);
		BDV=BDT;
		BDW=BDU;
		}
		BDM=BDV;
		BDN=BDW;
		}else{
		BDM=BCY;
		BDN=BCZ;
		}
		BDB=BDM;
		BDC=BDN;
		}else{
		BDB=QV;
		BDC=APD;
		}
		let BDD=BDB+ DD;
		let BDE=BDC+ L4([EQ,0.0,0.0,0.0]);
		let BEK;
		let BEL;
		if BDF{
		let BDY=BDX* CC;
		let BDZ=DP* BDX;
		let BEA=D/ BDY;
		let BEB=rspice_limexp(BEA);
		let BEC=((L3([E[0],0.0,E[1]])).product_sum_div(FP,L3([0.0,BDZ,0.0]),(-BEA),BDY))* BEB;
		let BED=R/ BDY;
		let BEE=rspice_limexp(BED);
		let BEF=((L3([S[0],0.0,S[1]])).product_sum_div(FP,L3([0.0,BDZ,0.0]),(-BED),BDY))* BEE;
		let BEG=BEB- BEE;
		let BEH=DE* BEG;
		let BEI=L4([0.0,0.0,(ER* BEG),0.0])+ ((L4([BEC[0],0.0,BEC[1],BEC[2]])- L4([0.0,BEF[0],BEF[1],BEF[2]]))* DE);
		BEK=BEH;
		BEL=BEI;
		}else{
		BEK=QV;
		BEL=BEJ;
		}
		let BET;
		let BEU;
		if BEM{
		let BEO=BEN* CC;
		let BEP=R/ BEO;
		let BEQ=(L3([S[0],0.0,S[1]])).product_sum_div(FP,L3([0.0,(DP* BEN),0.0]),(-BEP),BEO);
		let BER=BEP> RU;
		let BEX;
		let BEY;
		let BEZ;
		let BFA;
		if BER{
		let BEW=FH+ (BEP- RU);
		BEX=BEW;
		BEY=RU;
		BEZ=BEQ;
		BFA=BES;
		}else{
		BEX=FH;
		BEY=BEP;
		BEZ=BES;
		BFA=BEQ;
		}
		let BFB=rspice_limexp(BEY);
		let BFC=(BEX* BFB)- FH;
		let BFD=DF* BFC;
		let BFE=L3([0.0,(ES* BFC),0.0])+ (((BEZ* BFB)+ ((BFA* BFB)* BEX))* DF);
		BET=BFD;
		BEU=BFE;
		}else{
		BET=QV;
		BEU=BES;
		}
		let BFH;
		let BFI;
		if BEV{
		let BFF=DG> QV;
		let BGE;
		let BGF;
		if BFF{
		let BFK=NL/ GM;
		let BFM=BFL- DH;
		let BFN=EU* FW;
		let BFO=FH- ((-0.8754687373538999f64/ NL).exp());
		let BFP=DH* BFO;
		let BFQ=EU* BFO;
		let BFR=RH* DG;
		let BFS=ET* RH;
		let BFT=BFK- NL;
		let BFU=BFL/ DH;
		let BFV=(BFT* (BFU.ln())).exp();
		let BFW=DG* BFV;
		let BFX=(ET* BFV)+ (((((product_div(EU,(-BFU),DH))* (FP/ BFU))* BFT)* BFV)* DG);
		let BFY=BFP- R;
		let BFZ=L3([0.0,BFQ,0.0]);
		let BGA=L3([S[0],0.0,S[1]]);
		let BGB=BFY* CB;
		let BGC=((BFZ- BGA)* CB)+ L3([0.0,(DO* BFY),0.0]);
		let BGD=BGB< RU;
		let BGL;
		let BGM;
		if BGD{
		let BGG=BGB.exp();
		let BGH=FH+ BGG;
		let BGI=BGH.ln();
		let BGJ=BFP- (CC* BGI);
		let BGK=BFZ- (L3([0.0,(DP* BGI),0.0])+ (((BGC* BGG)* (FP/ BGH))* CC));
		BGL=BGJ;
		BGM=BGK;
		}else{
		BGL=R;
		BGM=BGA;
		}
		let BGN=(SG* BFM)+ (GM* CC);
		let BGO=(BFN* SG)+ (DP* GM);
		let BGP=(BFM+ BGL)/ BGN;
		let BGQ=((L3([0.0,BFN,0.0])+ BGM)).product_sum_div(FP,L3([0.0,BGO,0.0]),(-BGP),BGN);
		let BGR=BGP< RU;
		let BGZ;
		let BHA;
		if BGR{
		let BGS=BGP.exp();
		let BGT=FH+ BGS;
		let BGU=(-(BFM+ BFP))/ BGN;
		let BGV=BGU.exp();
		let BGW=(BGT.ln())- BGV;
		let BGX=(-BFM)+ (BGN* BGW);
		let BGY=L3([0.0,(BFN* FW),0.0])+ (L3([0.0,(BGO* BGW),0.0])+ ((((BGQ* BGS)* (FP/ BGT))- L3([0.0,((product_sum_div(((BFN+ BFQ)* FW),FP,BGO,(-BGU),BGN))* BGV),0.0]))* BGN));
		BGZ=BGX;
		BHA=BGY;
		}else{
		BGZ=BGL;
		BHA=BGM;
		}
		let BHB=R- BGL;
		let BHC=BGL/ DH;
		let BHD=L3([0.0,EU,0.0]);
		let BHE=FH- BHC;
		let BHF=BGZ/ DH;
		let BHG=FH- BHF;
		let BHH=BHG.ln();
		let BHI=(((BHA).product_sum_div(FP,BHD,(-BHF),DH))* FW)* (FP/ BHG);
		let BHJ=FH- NL;
		let BHK=FH- BFK;
		let BHL=(BHH* BHJ).exp();
		let BHM=FH- BHL;
		let BHN=((BHE.ln())* BHK).exp();
		let BHO=FH- BHN;
		let BHP=(BHH* BHK).exp();
		let BHQ=FH- BHP;
		let BHR=((L3([0.0,(ET* BHM),0.0])+ ((((BHI* BHJ)* BHL)* FW)* DG))/ BHJ)+ ((L3([0.0,(BFX* BHO),0.0])+ ((((((((BGM).product_sum_div(FP,BHD,(-BHC),DH))* FW)* (FP/ BHE))* BHK)* BHN)* FW)* BFW))/ BHK);
		let BHS=(((DG* BHM)/ BHJ)+ ((BFW* BHO)/ BHK))- ((BFW* BHQ)/ BHK);
		let BHT=(BHS* DH)+ (BFR* BHB);
		let BHU=(((BHR- ((L3([0.0,(BFX* BHQ),0.0])+ ((((BHI* BHK)* BHP)* FW)* BFW))/ BHK))* DH)+ L3([0.0,(EU* BHS),0.0]))+ (L3([0.0,(BFS* BHB),0.0])+ ((BGA- BGM)* BFR));
		BGE=BHT;
		BGF=BHU;
		}else{
		BGE=QV;
		BGF=BES;
		}
		BFH=BGE;
		BFI=BGF;
		}else{
		let BFG=DG> QV;
		let BIQ;
		let BIR;
		if BFG{
		let BHV=FH- ((-0.8754687373538999f64/ NL).exp());
		let BHW=DH* BHV;
		let BHX=BHW- R;
		let BHY=L3([0.0,(EU* BHV),0.0]);
		let BHZ=L3([S[0],0.0,S[1]]);
		let BIA=BHX* CB;
		let BIB=((BHY- BHZ)* CB)+ L3([0.0,(DO* BHX),0.0]);
		let BIC=BIB* BIA;
		let BID=((BIA* BIA)+ TX).sqrt();
		let BIE=(BIA+ BID)* GP;
		let BIF=BHW- (CC* BIE);
		let BIG=BHY- (L3([0.0,(DP* BIE),0.0])+ (((BIB+ ((BIC+ BIC)* (FP/ (GO* BID))))* GP)* CC));
		let BIH=BIF/ DH;
		let BII=FH- BIH;
		let BIJ=FH- NL;
		let BIK=((BII.ln())* BIJ).exp();
		let BIL=FH- BIK;
		let BIM=((DH* BIL)/ BIJ)+ (RH* (R- BIF));
		let BIN=((L3([0.0,(EU* BIL),0.0])+ ((((((((BIG).product_sum_div(FP,L3([0.0,EU,0.0]),(-BIH),DH))* FW)* (FP/ BII))* BIJ)* BIK)* FW)* DH))/ BIJ)+ ((BHZ- BIG)* RH);
		let BIO=DG* BIM;
		let BIP=L3([0.0,(ET* BIM),0.0])+ (BIN* DG);
		BIQ=BIO;
		BIR=BIP;
		}else{
		BIQ=QV;
		BIR=BES;
		}
		BFH=BIQ;
		BFI=BIR;
		}
		let BIX;
		let BIY;
		if BFJ{
		let BIS=Q* AUM;
		let BIT=CA- I;
		let BIU=(L3([DN,0.0,0.0])- AMO)* BBJ;
		let BIV=(P* AUM)+ (BIT* BBJ);
		let BIW=(L4([0.0,BIS[0],BIS[1],BIS[2]])+ (AUN* P))+ (L4([BIU[0],BIU[1],BIU[2],0.0])+ (BBK* BIT));
		BIX=BIV;
		BIY=BIW;
		}else{
		BIX=QV;
		BIY=APD;
		}
		let BJU;
		let BJV;
		let BJW;
		let BJX;
		let BJY;
		let BJZ;
		let BKA;
		let BKB;
		let BKC;
		let BKD;
		let BKE;
		let BKF;
		if BIZ{
		let BJB=BJA- AVF;
		let BJC=L5([0.0,0.0,0.0,0.0,1f64]);
		let BJD=BJC- L5([AVG[0],AVG[1],AVG[2],AVG[3],0.0]);
		let BJF=(BJE* BJA)* LA;
		let BJG=(1f64* BJE)* LA;
		let BJI=BJH- AUK;
		let BJJ=L5([0.0,0.0,0.0,0.0,1f64]);
		let BJK=BJJ- L5([AUL[0],AUL[1],AUL[2],AUL[3],0.0]);
		let BJM=(BJL* BJH)* LA;
		let BJN=(1f64* BJL)* LA;
		BJU=BJA;
		BJV=BJH;
		BJW=BJB;
		BJX=BJF;
		BJY=BJI;
		BJZ=BJM;
		BKA=BJC;
		BKB=BJJ;
		BKC=BJD;
		BKD=BJG;
		BKE=BJK;
		BKF=BJN;
		}else{
		let BJO=L5([AVG[0],AVG[1],AVG[2],AVG[3],0.0]);
		let BJP=L5([AUL[0],AUL[1],AUL[2],AUL[3],0.0]);
		let BJQ=L5([0.0,0.0,0.0,0.0,1f64]);
		let BJR=L5([0.0,0.0,0.0,0.0,1f64]);
		BJU=AVF;
		BJV=AUK;
		BJW=BJA;
		BJX=QV;
		BJY=BJH;
		BJZ=QV;
		BKA=BJO;
		BKB=BJP;
		BKC=BJQ;
		BKD=BJS;
		BKE=BJR;
		BKF=BJT;
		}
		let BKI=C* BET;
		let BKJ=BEU* C;
		let BKK=C* BFH;
		let BKL=BFI* C;
		let BKM=C* QQ;
		let BKN=QT* C;
		let BKO=C* (BKG* D);
		let BKP=(E* BKG)* C;
		let BKQ=C* (BKH* U);
		let BKR=(V* BKH)* C;
		let BKS=C* (AXA- BBJ);
		let BKT=(AXD- BBK)* C;
		let BKU=C* (ABQ+ AVI);
		let BKV=(L4([ABR[0],ABR[1],ABR[2],0.0])+ AVJ)* C;
		let BKW=C* AWJ;
		let BKX=AWK* C;
		let BKY=C* (AIM+ BJU);
		let BKZ=(L5([AIN[0],0.0,AIN[1],AIN[2],0.0])+ BKA)* C;
		let BLA=C* (BJV- AUH);
		let BLB=(BKB- L5([AUI[0],AUI[1],AUI[2],AUI[3],0.0]))* C;
		let BLC=ctx.has_simparam("gmin");
		let BLE=if BLC{
		let BLD=ctx.simparam_required("gmin");
		BLD
		}else{
		QV
		};
		let BLF=M* BLE;
		let BLG=QV+ (BLE* L);
		let BLH=ctx.has_simparam("gmin");
		let BLJ=if BLH{
		let BLI=ctx.simparam_required("gmin");
		BLI
		}else{
		QV
		};
		let BLK=H* BLJ;
		let BLL=QV+ (BLJ* G);
		let BLM=(BEL* C)* FW;
		let BLN=QV+ (-(C* BEK));
		let BLO=BKJ* FW;
		let BLP=QV+ (-BKI);
		let BLQ=ddt(0, BKK);
		let BLS=(BKL* BLR)* FW;
		let BLT=-BKK;
		let BLU=BKL* FW;
		let BLV=QV+ (-BLQ);
		let BLW=ddt(1, BKM);
		let BLX=(BKN* BLR)* FW;
		let BLY=-BKM;
		let BLZ=BKN* FW;
		let BMA=QV+ (-BLW);
		let BMB=ddt(2, BKO);
		let BMC=(BKP* BLR)* FW;
		let BMD=-BKO;
		let BME=BKP* FW;
		let BMF=QV+ (-BMB);
		let BMG=ddt(3, BKQ);
		let BMH=(BKR* BLR)* FW;
		let BMI=-BKQ;
		let BMJ=BKR* FW;
		let BMK=QV+ (-BMG);
		let BMQ;
		let BMR;
		if BML{
		let BMM=W/ DI;
		let BMN=(L3([X[0],0.0,X[1]])).product_sum_div(FP,L3([0.0,EV,0.0]),(-BMM),DI);
		let BMO=QV+ BMM;
		BMQ=BMO;
		BMR=BMN;
		}else{
		BMQ=QV;
		BMR=BMP;
		}
		let BMX;
		let BMY;
		if BMS{
		let BMT=-(Y/ DJ);
		let BMU=((L3([Z[0],0.0,Z[1]])).product_sum_div(FP,L3([0.0,EW,0.0]),BMT,DJ))* FW;
		let BMV=QV+ BMT;
		BMX=BMV;
		BMY=BMU;
		}else{
		BMX=QV;
		BMY=BMW;
		}
		let BNE;
		let BNF;
		if BMZ{
		let BNA=-(AA/ BDD);
		let BNB=((L5([AB[0],0.0,0.0,AB[1],0.0])).product_sum_div(FP,L5([0.0,BDE[0],BDE[1],BDE[2],BDE[3]]),BNA,BDD))* FW;
		let BNC=QV+ BNA;
		BNE=BNC;
		BNF=BNB;
		}else{
		BNE=QV;
		BNF=BND;
		}
		let BNG=QV+ BKS;
		let BNH=ddt(4, BKU);
		let BNI=BKV* BLR;
		let BNJ=QV+ BNH;
		let BNK=QV+ BKW;
		let BNL=ddt(5, BKY);
		let BNM=BKZ* BLR;
		let BNN=QV+ BNL;
		let BNO=QV+ BLA;
		let BNV;
		let BNW;
		let BNX;
		let BNY;
		if BNP{
		BNV=QV;
		BNW=QV;
		BNX=BX;
		BNY=BX;
		}else{
		let BNR=BNQ* AH;
		let BNS=KM* BNQ;
		let BNT=ddt(6, BNR);
		let BNU=BNS* BLR;
		BNV=BNT;
		BNW=BNR;
		BNX=BNU;
		BNY=BNS;
		}
		let BOA;
		let BOB;
		let BOC;
		let BOD;
		if BNZ{
		BOA=BOM;
		BOB=QV;
		BOC=APD;
		BOD=BX;
		}else{
		let BON=AH/ DK;
		let BOO=L4([(product_sum_div(KM,FP,EX,(-BON),DK)),0.0,0.0,0.0])- BIY;
		let BOP=0f64+ (BON- BIX);
		let BOR;
		let BOS;
		if BOQ{
		BOR=BOP;
		BOS=BOO;
		}else{
		BOR=QV;
		BOS=APD;
		}
		let BOT=(ctx.checked_derivative_value(BOP, BOR))+ BNV;
		let BOU=BOS+ L4([BNX,0.0,0.0,0.0]);
		BOA=BOT;
		BOB=BNW;
		BOC=BOU;
		BOD=BNY;
		}
		let BOE=QV+ BJW;
		let BOF=ddt(7, BJX);
		let BOG=BKD* BLR;
		let BOH=QV+ BOF;
		let BOI=QV+ BJY;
		let BOJ=ddt(8, BJZ);
		let BOK=BKF* BLR;
		let BOL=QV+ BOJ;
		let BOV=BKX[2];
		let BOW=QV+ node_potentials[10];
		let BOX=QV+ node_potentials[11];
		let BOY=QV+ node_potentials[12];
		let BOZ=QV+ node_potentials[13];
		let BPA=QV+ node_potentials[14];
		let BPB=QV+ node_potentials[15];
		let BPD=QV+ BPC;
		let BPH;
		let BPI;
		if BPE!=0.0{
		let BPF=L2([KM,0.0]);
		BPH=AH;
		BPI=BPF;
		}else{
		let BPG=L2([0.0,1f64]);
		BPH=BPC;
		BPI=BPG;
		}
		let BPJ=L5([BPI[0],0.0,0.0,0.0,BPI[1]])- L5([BOC[0],BOC[1],BOC[2],BOC[3],0.0]);
		let BPK=-BOB;
		let BPL=QV+ (BPH- BOA);
		let BPM=BLF[0];
		let BPN=BLF[1];
		let BPO=BLK[0];
		let BPP=BLK[1];
		let BPQ=BLM[0];
		let BPR=BLM[1];
		let BPS=BLM[2];
		let BPT=BLM[3];
		let BPU=BLO[0];
		let BPV=BLO[1];
		let BPW=BLO[2];
		let BPX=BLS[0];
		let BPY=BLS[1];
		let BPZ=BLS[2];
		let BQA=BLX[0];
		let BQB=BLX[1];
		let BQC=BLX[2];
		let BQD=BMC[0];
		let BQE=BMC[1];
		let BQF=BMH[0];
		let BQG=BMH[1];
		let BQH=BMR[0];
		let BQI=BMR[1];
		let BQJ=BMR[2];
		let BQK=BMY[0];
		let BQL=BMY[1];
		let BQM=BMY[2];
		let BQN=BNF[0];
		let BQO=BNF[1];
		let BQP=BNF[2];
		let BQQ=BNF[3];
		let BQR=BNF[4];
		let BQS=BKT[0];
		let BQT=BKT[1];
		let BQU=BKT[2];
		let BQV=BKT[3];
		let BQW=BNI[0];
		let BQX=BNI[1];
		let BQY=BNI[2];
		let BQZ=BNI[3];
		let BRA=BKX[0];
		let BRB=BKX[1];
		let BRC=BNM[0];
		let BRD=BNM[1];
		let BRE=BNM[2];
		let BRF=BNM[3];
		let BRG=BNM[4];
		let BRH=BLB[0];
		let BRI=BLB[1];
		let BRJ=BLB[2];
		let BRK=BLB[3];
		let BRL=BLB[4];
		let BRM=BKC[0];
		let BRN=BKC[1];
		let BRO=BKC[2];
		let BRP=BKC[3];
		let BRQ=BKC[4];
		let BRR=BOG;
		let BRS=BKE[0];
		let BRT=BKE[1];
		let BRU=BKE[2];
		let BRV=BKE[3];
		let BRW=BKE[4];
		let BRX=BOK;
		let BRY=1f64;
		let BRZ=1f64;
		let BSA=1f64;
		let BSB=1f64;
		let BSC=1f64;
		let BSD=1f64;
		let BSE=1f64;
		let BSF=BPJ[0];
		let BSG=BPJ[1];
		let BSH=BPJ[2];
		let BSI=BPJ[3];
		let BSJ=BPJ[4];
		let BSK=BLU[0];
		let BSL=BLU[1];
		let BSM=BLU[2];
		let BSN=BLZ[0];
		let BSO=BLZ[1];
		let BSP=BLZ[2];
		let BSQ=BME[0];
		let BSR=BME[1];
		let BSS=BMJ[0];
		let BST=BMJ[1];
		let BSU=BKV[0];
		let BSV=BKV[1];
		let BSW=BKV[2];
		let BSX=BKV[3];
		let BSY=BKZ[0];
		let BSZ=BKZ[1];
		let BTA=BKZ[2];
		let BTB=BKZ[3];
		let BTC=BKZ[4];
		let BTD=BKD;
		let BTE=BKF;
		let BTF=(BOD* FW);
        if ctx.dynamic_operators_enabled() { self.event_state_candidate[0] = staged[88]; }
        if (staged[98] != 0.0) {
            stamper.stamp_potential_branch_local(Some(7), Some(2), 0, multiplicity);
        } else {
            stamper.stamp_inactive_potential_branch_local(0);
        }
        if (staged[99] != 0.0) {
            stamper.stamp_potential_branch_local(Some(5), Some(0), 1, multiplicity);
        } else {
            stamper.stamp_inactive_potential_branch_local(1);
        }
        if (staged[100] != 0.0) {
            stamper.stamp_potential_branch_local(Some(1), Some(6), 2, multiplicity);
        } else {
            stamper.stamp_inactive_potential_branch_local(2);
        }
        stamper.stamp_current_sparse_local::<2, 0>(
            Some(6),
            Some(7),
            multiplicity * (BLG),
            [6, 7],
            [BPM, BPN],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<2, 0>(
            Some(6),
            Some(5),
            multiplicity * (BLL),
            [5, 6],
            [BPO, BPP],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<4, 0>(
            Some(13),
            None,
            multiplicity * (BLN),
            [1, 3, 4, 5],
            [BPQ, BPR, BPS, BPT],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<3, 0>(
            Some(15),
            None,
            multiplicity * (BLP),
            [3, 4, 5],
            [BPU, BPV, BPW],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<3, 0>(
            Some(15),
            None,
            multiplicity * (BLV),
            [3, 4, 5],
            [BPX, BPY, BPZ],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<3, 0>(
            Some(11),
            None,
            multiplicity * (BMA),
            [1, 4, 5],
            [BQA, BQB, BQC],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<2, 0>(
            Some(11),
            None,
            multiplicity * (BMF),
            [1, 5],
            [BQD, BQE],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<2, 0>(
            Some(12),
            None,
            multiplicity * (BMK),
            [1, 2],
            [BQF, BQG],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<3, 0>(
            Some(7),
            Some(2),
            multiplicity * (BMQ),
            [2, 4, 7],
            [BQH, BQI, BQJ],
            [],
            [],
            multiplicity,
        );
        if staged[98] != 0.0 {
        stamper.stamp_potential_sparse_local::<0, 0>(
            0,
            staged[89],
            [],
            [],
            [],
            [],
        );
        }
        stamper.stamp_current_sparse_local::<3, 0>(
            Some(14),
            None,
            multiplicity * (BMX),
            [0, 4, 5],
            [BQK, BQL, BQM],
            [],
            [],
            multiplicity,
        );
        if staged[99] != 0.0 {
        stamper.stamp_potential_sparse_local::<0, 0>(
            1,
            staged[90],
            [],
            [],
            [],
            [],
        );
        }
        stamper.stamp_current_sparse_local::<5, 0>(
            Some(10),
            None,
            multiplicity * (BNE),
            [1, 4, 5, 6, 7],
            [BQN, BQO, BQP, BQQ, BQR],
            [],
            [],
            multiplicity,
        );
        if staged[100] != 0.0 {
        stamper.stamp_potential_sparse_local::<0, 0>(
            2,
            staged[91],
            [],
            [],
            [],
            [],
        );
        }
        stamper.stamp_current_sparse_local::<4, 0>(
            Some(6),
            Some(5),
            multiplicity * (BNG),
            [4, 5, 6, 7],
            [BQS, BQT, BQU, BQV],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<4, 0>(
            Some(6),
            Some(5),
            multiplicity * (BNJ),
            [4, 5, 6, 7],
            [BQW, BQX, BQY, BQZ],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<3, 0>(
            Some(6),
            Some(7),
            multiplicity * (BNK),
            [4, 6, 7],
            [BRA, BRB, BOV],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<5, 0>(
            Some(6),
            Some(7),
            multiplicity * (BNN),
            [4, 5, 6, 7, 8],
            [BRC, BRD, BRE, BRF, BRG],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<5, 0>(
            Some(5),
            Some(7),
            multiplicity * (BNO),
            [4, 5, 6, 7, 9],
            [BRH, BRI, BRJ, BRK, BRL],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<5, 0>(
            Some(8),
            None,
            multiplicity * (BOE),
            [4, 5, 6, 7, 8],
            [BRM, BRN, BRO, BRP, BRQ],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<1, 0>(
            Some(8),
            None,
            multiplicity * (BOH),
            [8],
            [BRR],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<5, 0>(
            Some(9),
            None,
            multiplicity * (BOI),
            [4, 5, 6, 7, 9],
            [BRS, BRT, BRU, BRV, BRW],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<1, 0>(
            Some(9),
            None,
            multiplicity * (BOL),
            [9],
            [BRX],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<0, 0>(
            Some(10),
            None,
            multiplicity * (staged[92]),
            [],
            [],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<0, 0>(
            Some(14),
            None,
            multiplicity * (staged[93]),
            [],
            [],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<0, 0>(
            Some(7),
            Some(2),
            multiplicity * (staged[94]),
            [],
            [],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<0, 0>(
            Some(6),
            Some(7),
            multiplicity * (staged[95]),
            [],
            [],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<0, 0>(
            Some(6),
            Some(7),
            multiplicity * (staged[96]),
            [],
            [],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<0, 0>(
            Some(5),
            Some(7),
            multiplicity * (staged[97]),
            [],
            [],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<1, 0>(
            Some(1),
            Some(6),
            multiplicity * (BOW),
            [10],
            [BRY],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<1, 0>(
            Some(10),
            None,
            multiplicity * (BOW),
            [10],
            [BRY],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<1, 0>(
            Some(1),
            Some(5),
            multiplicity * (BOX),
            [11],
            [BRZ],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<1, 0>(
            Some(11),
            None,
            multiplicity * (BOX),
            [11],
            [BRZ],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<1, 0>(
            Some(1),
            Some(2),
            multiplicity * (BOY),
            [12],
            [BSA],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<1, 0>(
            Some(12),
            None,
            multiplicity * (BOY),
            [12],
            [BSA],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<1, 0>(
            Some(1),
            Some(3),
            multiplicity * (BOZ),
            [13],
            [BSB],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<1, 0>(
            Some(13),
            None,
            multiplicity * (BOZ),
            [13],
            [BSB],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<1, 0>(
            Some(5),
            Some(0),
            multiplicity * (BPA),
            [14],
            [BSC],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<1, 0>(
            Some(14),
            None,
            multiplicity * (BPA),
            [14],
            [BSC],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<1, 0>(
            Some(3),
            Some(5),
            multiplicity * (BPB),
            [15],
            [BSD],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<1, 0>(
            Some(15),
            None,
            multiplicity * (BPB),
            [15],
            [BSD],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<1, 0>(
            Some(4),
            None,
            multiplicity * (BPD),
            [16],
            [BSE],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<5, 0>(
            Some(16),
            None,
            multiplicity * (BPL),
            [4, 5, 6, 7, 16],
            [BSF, BSG, BSH, BSI, BSJ],
            [],
            [],
            multiplicity,
        );
        self.canonical_reactive[0] = BLG;
        self.canonical_reactive[1] = BLL;
        self.canonical_reactive[2] = BLN;
        self.canonical_reactive[3] = BLP;
        self.canonical_reactive[4] = BLT;
        self.canonical_reactive[5] = BSK;
        self.canonical_reactive[6] = BSL;
        self.canonical_reactive[7] = BSM;
        self.canonical_reactive[8] = BLY;
        self.canonical_reactive[9] = BSN;
        self.canonical_reactive[10] = BSO;
        self.canonical_reactive[11] = BSP;
        self.canonical_reactive[12] = BMD;
        self.canonical_reactive[13] = BSQ;
        self.canonical_reactive[14] = BSR;
        self.canonical_reactive[15] = BMI;
        self.canonical_reactive[16] = BSS;
        self.canonical_reactive[17] = BST;
        self.canonical_reactive[18] = BMQ;
        self.canonical_reactive[19] = staged[89];
        self.canonical_reactive[20] = BMX;
        self.canonical_reactive[21] = staged[90];
        self.canonical_reactive[22] = BNE;
        self.canonical_reactive[23] = staged[91];
        self.canonical_reactive[24] = BNG;
        self.canonical_reactive[25] = BKU;
        self.canonical_reactive[26] = BSU;
        self.canonical_reactive[27] = BSV;
        self.canonical_reactive[28] = BSW;
        self.canonical_reactive[29] = BSX;
        self.canonical_reactive[30] = BNK;
        self.canonical_reactive[31] = BKY;
        self.canonical_reactive[32] = BSY;
        self.canonical_reactive[33] = BSZ;
        self.canonical_reactive[34] = BTA;
        self.canonical_reactive[35] = BTB;
        self.canonical_reactive[36] = BTC;
        self.canonical_reactive[37] = BNO;
        self.canonical_reactive[38] = BOE;
        self.canonical_reactive[39] = BJX;
        self.canonical_reactive[40] = BTD;
        self.canonical_reactive[41] = BOI;
        self.canonical_reactive[42] = BJZ;
        self.canonical_reactive[43] = BTE;
        self.canonical_reactive[44] = staged[92];
        self.canonical_reactive[45] = staged[93];
        self.canonical_reactive[46] = staged[94];
        self.canonical_reactive[47] = staged[95];
        self.canonical_reactive[48] = staged[96];
        self.canonical_reactive[49] = staged[97];
        self.canonical_reactive[50] = BOW;
        self.canonical_reactive[51] = BOW;
        self.canonical_reactive[52] = BOX;
        self.canonical_reactive[53] = BOX;
        self.canonical_reactive[54] = BOY;
        self.canonical_reactive[55] = BOY;
        self.canonical_reactive[56] = BOZ;
        self.canonical_reactive[57] = BOZ;
        self.canonical_reactive[58] = BPA;
        self.canonical_reactive[59] = BPA;
        self.canonical_reactive[60] = BPB;
        self.canonical_reactive[61] = BPB;
        self.canonical_reactive[62] = BPD;
        self.canonical_reactive[63] = BPK;
        self.canonical_reactive[64] = BTF;
    }

    pub fn stamp_reactive(&mut self, ctx: &GeneratedEvalContext<'_>, stamper: &mut GeneratedReactiveStamper<'_>) {
        let multiplicity = self.multiplicity;
        let cached = &*self.canonical_reactive;
        stamper.stamp_current_reactive_indexed_dense_local(
            Some(15),
            None,
            &[3, 4, 5],
            &[cached[5], cached[6], cached[7]],
            &[],
            &[],
            multiplicity,
        );
        stamper.stamp_current_reactive_indexed_dense_local(
            Some(11),
            None,
            &[1, 4, 5],
            &[cached[9], cached[10], cached[11]],
            &[],
            &[],
            multiplicity,
        );
        stamper.stamp_current_reactive_indexed_dense_local(
            Some(11),
            None,
            &[1, 5],
            &[cached[13], cached[14]],
            &[],
            &[],
            multiplicity,
        );
        stamper.stamp_current_reactive_indexed_dense_local(
            Some(12),
            None,
            &[1, 2],
            &[cached[16], cached[17]],
            &[],
            &[],
            multiplicity,
        );
        stamper.stamp_current_reactive_indexed_dense_local(
            Some(6),
            Some(5),
            &[4, 5, 6, 7],
            &[cached[26], cached[27], cached[28], cached[29]],
            &[],
            &[],
            multiplicity,
        );
        stamper.stamp_current_reactive_indexed_dense_local(
            Some(6),
            Some(7),
            &[4, 5, 6, 7, 8],
            &[cached[32], cached[33], cached[34], cached[35], cached[36]],
            &[],
            &[],
            multiplicity,
        );
        stamper.stamp_current_reactive_indexed_dense_local(
            Some(8),
            None,
            &[8],
            &[cached[40]],
            &[],
            &[],
            multiplicity,
        );
        stamper.stamp_current_reactive_indexed_dense_local(
            Some(9),
            None,
            &[9],
            &[cached[43]],
            &[],
            &[],
            multiplicity,
        );
        stamper.stamp_current_reactive_indexed_dense_local(
            Some(16),
            None,
            &[4],
            &[cached[64]],
            &[],
            &[],
            multiplicity,
        );
    }

}
