#![allow(dead_code, unused_assignments, unused_parens, unused_variables)]

use super::state::Instance;
use crate::device::veriloga_generated::{GeneratedDerivative, GeneratedEvalContext, GeneratedReactiveStamper, GeneratedStamper};

const LIMEXP_MAX: f64 = 5.54062238439351e34;
#[path = "stamp_blocks_0.rs"]
mod stamp_blocks_0;
#[path = "stamp_blocks_1.rs"]
mod stamp_blocks_1;

const THERMAL_VOLTAGE_PER_K: f64 = 1.380649e-23 / 1.602176634e-19;

#[inline]
fn eval_ddt<const STATE_COUNT: usize>(
    current: &mut [f64; STATE_COUNT],
    previous: &mut [f64; STATE_COUNT],
    older: &mut [f64; STATE_COUNT],
    initialized: &mut [bool; STATE_COUNT],
    derivative_current: &mut [f64; STATE_COUNT],
    derivative_previous: &mut [f64; STATE_COUNT],
    ddt_active: bool,
    ddt_scale: f64,
    ddt_previous_value_scale: f64,
    ddt_older_value_scale: f64,
    ddt_previous_derivative_scale: f64,
    slot: usize,
    value: f64,
) -> f64 {
    debug_assert!(slot < STATE_COUNT, "generated ddt state slot out of range");
    let previous_value = if initialized[slot] { previous[slot] } else { value };
    let older_value = if initialized[slot] { older[slot] } else { value };
    current[slot] = value;
    if ddt_active {
        let result = value * ddt_scale
            - previous_value * ddt_previous_value_scale
            - older_value * ddt_older_value_scale
            - derivative_previous[slot] * ddt_previous_derivative_scale;
        derivative_current[slot] = result;
        result
    } else {
        current[slot] = value;
        previous[slot] = value;
        older[slot] = value;
        derivative_current[slot] = 0.0;
        derivative_previous[slot] = 0.0;
        initialized[slot] = true;
        0.0
    }
}

#[inline]
fn ddt_jacobian(ddt_active: bool, ddt_scale: f64, derivative: f64) -> f64 {
    if ddt_active {
        derivative * ddt_scale
    } else {
        0.0
    }
}

#[inline]
fn eval_idt<const STATE_COUNT: usize>(
    current: &mut [f64; STATE_COUNT],
    previous: &mut [f64; STATE_COUNT],
    initialized: &mut [bool; STATE_COUNT],
    ddt_active: bool,
    idt_scale: f64,
    slot: usize,
    value: f64,
    ic: f64,
) -> f64 {
    debug_assert!(slot < STATE_COUNT, "generated idt state slot out of range");
    let previous_value = if initialized[slot] { previous[slot] } else { ic };
    let current_value = if ddt_active {
        previous_value + value * idt_scale
    } else {
        ic
    };
    current[slot] = current_value;
    if !ddt_active {
        previous[slot] = current_value;
        initialized[slot] = true;
    }
    current_value
}

#[inline]
fn idt_jacobian(timestep: f64, derivative: f64) -> f64 {
    if timestep.abs() > Instance::DDT_EPSILON {
        derivative * timestep
    } else {
        0.0
    }
}

#[derive(Default)]
pub(crate) struct StampLocals {
    pub(crate) var_a0: f64,
    pub(crate) var_a0_dn1: f64,
    pub(crate) var_a0_dn3: f64,
    pub(crate) var_a0_dn4: f64,
    pub(crate) var_a0_dn5: f64,
    pub(crate) var_a1: f64,
    pub(crate) var_a1_dn1: f64,
    pub(crate) var_a1_dn3: f64,
    pub(crate) var_a1_dn4: f64,
    pub(crate) var_a1_dn5: f64,
    pub(crate) var_a1_rv: f64,
    pub(crate) var_a1_um2: f64,
    pub(crate) var_a1_um2_dn1: f64,
    pub(crate) var_a1_um2_dn3: f64,
    pub(crate) var_a1_um2_dn4: f64,
    pub(crate) var_a1_um2_dn5: f64,
    pub(crate) var_a1_um2_rv: f64,
    pub(crate) var_a2: f64,
    pub(crate) var_a2_dn1: f64,
    pub(crate) var_a2_dn3: f64,
    pub(crate) var_a2_dn4: f64,
    pub(crate) var_a2_dn5: f64,
    pub(crate) var_a2_rv: f64,
    pub(crate) var_a2_um2: f64,
    pub(crate) var_a2_um2_dn1: f64,
    pub(crate) var_a2_um2_dn3: f64,
    pub(crate) var_a2_um2_dn4: f64,
    pub(crate) var_a2_um2_dn5: f64,
    pub(crate) var_a2_um2_rv: f64,
    pub(crate) var_a3: f64,
    pub(crate) var_a3_dn3: f64,
    pub(crate) var_a4: f64,
    pub(crate) var_a4_dn3: f64,
    pub(crate) var_a_um2: f64,
    pub(crate) var_a_um2_rv: f64,
    pub(crate) var_aa: f64,
    pub(crate) var_aa3d27: f64,
    pub(crate) var_aa3d27_dn1: f64,
    pub(crate) var_aa3d27_dn3: f64,
    pub(crate) var_aa3d27_dn4: f64,
    pub(crate) var_aa3d27_dn5: f64,
    pub(crate) var_aa_dn1: f64,
    pub(crate) var_aa_dn3: f64,
    pub(crate) var_aa_dn4: f64,
    pub(crate) var_aa_dn5: f64,
    pub(crate) var_acja: f64,
    pub(crate) var_acja__blk281: f64,
    pub(crate) var_acja__blk281_dn1: f64,
    pub(crate) var_acja__blk281_dn3: f64,
    pub(crate) var_acja__blk281_dn4: f64,
    pub(crate) var_acja__blk281_dn5: f64,
    pub(crate) var_acja__blk281_rv: f64,
    pub(crate) var_acja_dn1: f64,
    pub(crate) var_acja_dn3: f64,
    pub(crate) var_acja_dn4: f64,
    pub(crate) var_acja_dn5: f64,
    pub(crate) var_acja_rv: f64,
    pub(crate) var_afactor: f64,
    pub(crate) var_afactor_rv: f64,
    pub(crate) var_aisa: f64,
    pub(crate) var_aisa__blk224: f64,
    pub(crate) var_aisa__blk224_dn1: f64,
    pub(crate) var_aisa__blk224_dn3: f64,
    pub(crate) var_aisa__blk224_dn4: f64,
    pub(crate) var_aisa__blk224_dn5: f64,
    pub(crate) var_aisa_dn1: f64,
    pub(crate) var_aisa_dn3: f64,
    pub(crate) var_aisa_dn4: f64,
    pub(crate) var_aisa_dn5: f64,
    pub(crate) var_arg1: f64,
    pub(crate) var_arg1_dn1: f64,
    pub(crate) var_arg1_dn3: f64,
    pub(crate) var_arg1_dn4: f64,
    pub(crate) var_arg1_dn5: f64,
    pub(crate) var_arg2: f64,
    pub(crate) var_arg2_dn1: f64,
    pub(crate) var_arg2_dn3: f64,
    pub(crate) var_arg2_dn4: f64,
    pub(crate) var_arg2_dn5: f64,
    pub(crate) var_arga: f64,
    pub(crate) var_arga__blk283: f64,
    pub(crate) var_arga__blk283_dn1: f64,
    pub(crate) var_arga__blk283_dn3: f64,
    pub(crate) var_arga__blk283_dn4: f64,
    pub(crate) var_arga__blk283_dn5: f64,
    pub(crate) var_arga__blk283_rv: f64,
    pub(crate) var_arga_dn1: f64,
    pub(crate) var_arga_dn3: f64,
    pub(crate) var_arga_dn4: f64,
    pub(crate) var_arga_dn5: f64,
    pub(crate) var_arga_rv: f64,
    pub(crate) var_argp: f64,
    pub(crate) var_argp__blk284: f64,
    pub(crate) var_argp__blk284_dn1: f64,
    pub(crate) var_argp__blk284_dn3: f64,
    pub(crate) var_argp__blk284_dn4: f64,
    pub(crate) var_argp__blk284_dn5: f64,
    pub(crate) var_argp__blk284_rv: f64,
    pub(crate) var_argp_dn1: f64,
    pub(crate) var_argp_dn3: f64,
    pub(crate) var_argp_dn4: f64,
    pub(crate) var_argp_dn5: f64,
    pub(crate) var_argp_rv: f64,
    pub(crate) var_argx: f64,
    pub(crate) var_argx__blk219: f64,
    pub(crate) var_argx__blk219_dn3: f64,
    pub(crate) var_argx__blk226: f64,
    pub(crate) var_argx__blk226_dn3: f64,
    pub(crate) var_argx__blk235: f64,
    pub(crate) var_argx__blk235_dn3: f64,
    pub(crate) var_argx_dn3: f64,
    pub(crate) var_asq: f64,
    pub(crate) var_asq_dn3: f64,
    pub(crate) var_ats_i: f64,
    pub(crate) var_atseff: f64,
    pub(crate) var_atseff_dn1: f64,
    pub(crate) var_atseff_dn3: f64,
    pub(crate) var_atseff_dn4: f64,
    pub(crate) var_atseff_dn5: f64,
    pub(crate) var_atspo: f64,
    pub(crate) var_atspo_dn3: f64,
    pub(crate) var_avar: f64,
    pub(crate) var_avar2: f64,
    pub(crate) var_avar2_dn1: f64,
    pub(crate) var_avar2_dn3: f64,
    pub(crate) var_avar2_dn4: f64,
    pub(crate) var_avar2_dn5: f64,
    pub(crate) var_avar_dn3: f64,
    pub(crate) var_bb: f64,
    pub(crate) var_bb_dn1: f64,
    pub(crate) var_bb_dn3: f64,
    pub(crate) var_bb_dn4: f64,
    pub(crate) var_bb_dn5: f64,
    pub(crate) var_bvar: f64,
    pub(crate) var_bvar2: f64,
    pub(crate) var_bvar2_dn1: f64,
    pub(crate) var_bvar2_dn3: f64,
    pub(crate) var_bvar2_dn4: f64,
    pub(crate) var_bvar2_dn5: f64,
    pub(crate) var_bvar_dn1: f64,
    pub(crate) var_bvar_dn3: f64,
    pub(crate) var_bvar_dn4: f64,
    pub(crate) var_bvar_dn5: f64,
    pub(crate) var_cf1: f64,
    pub(crate) var_cf1_dn1: f64,
    pub(crate) var_cf1_dn3: f64,
    pub(crate) var_cf1_dn4: f64,
    pub(crate) var_cf1_dn5: f64,
    pub(crate) var_cf1_rv: f64,
    pub(crate) var_cf2: f64,
    pub(crate) var_cf2_dn1: f64,
    pub(crate) var_cf2_dn3: f64,
    pub(crate) var_cf2_dn4: f64,
    pub(crate) var_cf2_dn5: f64,
    pub(crate) var_cf2_rv: f64,
    pub(crate) var_cj1: f64,
    pub(crate) var_cj1_dn1: f64,
    pub(crate) var_cj1_dn3: f64,
    pub(crate) var_cj1_dn4: f64,
    pub(crate) var_cj1_dn5: f64,
    pub(crate) var_cj1_rv: f64,
    pub(crate) var_cj2: f64,
    pub(crate) var_cj2_dn1: f64,
    pub(crate) var_cj2_dn3: f64,
    pub(crate) var_cj2_dn4: f64,
    pub(crate) var_cj2_dn5: f64,
    pub(crate) var_cj2_rv: f64,
    pub(crate) var_cja_t: f64,
    pub(crate) var_cja_t_dn3: f64,
    pub(crate) var_cja_t_rv: f64,
    pub(crate) var_cjp_t: f64,
    pub(crate) var_cjp_t_dn3: f64,
    pub(crate) var_cjp_t_rv: f64,
    pub(crate) var_cth: f64,
    pub(crate) var_cth_rv: f64,
    pub(crate) var_cvar: f64,
    pub(crate) var_cvar_dn1: f64,
    pub(crate) var_cvar_dn3: f64,
    pub(crate) var_cvar_dn4: f64,
    pub(crate) var_cvar_dn5: f64,
    pub(crate) var_dd: f64,
    pub(crate) var_dd_dn1: f64,
    pub(crate) var_dd_dn3: f64,
    pub(crate) var_dd_dn4: f64,
    pub(crate) var_dd_dn5: f64,
    pub(crate) var_de: f64,
    pub(crate) var_de_dn3: f64,
    pub(crate) var_de_rv: f64,
    pub(crate) var_delr_rsh: f64,
    pub(crate) var_df: f64,
    pub(crate) var_df_rv: f64,
    pub(crate) var_dfe: f64,
    pub(crate) var_dfe_dn1: f64,
    pub(crate) var_dfe_dn3: f64,
    pub(crate) var_dfe_dn4: f64,
    pub(crate) var_dfe_dn5: f64,
    pub(crate) var_dfmin: f64,
    pub(crate) var_dfmin_dn3: f64,
    pub(crate) var_dfmin_rv: f64,
    pub(crate) var_dfsq: f64,
    pub(crate) var_dfsq_dn3: f64,
    pub(crate) var_dfsq_rv: f64,
    pub(crate) var_dore: f64,
    pub(crate) var_dore_dn1: f64,
    pub(crate) var_dore_dn3: f64,
    pub(crate) var_dore_dn4: f64,
    pub(crate) var_dore_dn5: f64,
    pub(crate) var_dp_i: f64,
    pub(crate) var_dp_i_dn3: f64,
    pub(crate) var_dp_i_rv: f64,
    pub(crate) var_dpee: f64,
    pub(crate) var_dpee_dn1: f64,
    pub(crate) var_dpee_dn3: f64,
    pub(crate) var_dpee_dn4: f64,
    pub(crate) var_dpee_dn5: f64,
    pub(crate) var_dpfctr: f64,
    pub(crate) var_dpfctr_dn1: f64,
    pub(crate) var_dpfctr_dn3: f64,
    pub(crate) var_dpfctr_dn4: f64,
    pub(crate) var_dpfctr_dn5: f64,
    pub(crate) var_drmu: f64,
    pub(crate) var_drmu_dn1: f64,
    pub(crate) var_drmu_dn3: f64,
    pub(crate) var_drmu_dn4: f64,
    pub(crate) var_drmu_dn5: f64,
    pub(crate) var_dt: f64,
    pub(crate) var_dt_dn3: f64,
    pub(crate) var_dt_et: f64,
    pub(crate) var_dt_et_dn3: f64,
    pub(crate) var_dt_et_rv: f64,
    pub(crate) var_dt_rv: f64,
    pub(crate) var_dufctr: f64,
    pub(crate) var_dufctr_dn3: f64,
    pub(crate) var_dv: f64,
    pub(crate) var_dv0: f64,
    pub(crate) var_dv0__blk268: f64,
    pub(crate) var_dv0__blk268_dn3: f64,
    pub(crate) var_dv0__blk268_rv: f64,
    pub(crate) var_dv0__blk286: f64,
    pub(crate) var_dv0__blk286_dn3: f64,
    pub(crate) var_dv0__blk286_rv: f64,
    pub(crate) var_dv0__blk299: f64,
    pub(crate) var_dv0__blk299_dn3: f64,
    pub(crate) var_dv0__blk299_rv: f64,
    pub(crate) var_dv0_dn3: f64,
    pub(crate) var_dv0_rv: f64,
    pub(crate) var_dv__blk275: f64,
    pub(crate) var_dv__blk275_dn1: f64,
    pub(crate) var_dv__blk275_dn3: f64,
    pub(crate) var_dv__blk275_dn4: f64,
    pub(crate) var_dv__blk275_dn5: f64,
    pub(crate) var_dv__blk275_rv: f64,
    pub(crate) var_dv__blk293: f64,
    pub(crate) var_dv__blk293_dn1: f64,
    pub(crate) var_dv__blk293_dn3: f64,
    pub(crate) var_dv__blk293_dn4: f64,
    pub(crate) var_dv__blk293_dn5: f64,
    pub(crate) var_dv__blk293_rv: f64,
    pub(crate) var_dv__blk306: f64,
    pub(crate) var_dv__blk306_dn1: f64,
    pub(crate) var_dv__blk306_dn3: f64,
    pub(crate) var_dv__blk306_dn4: f64,
    pub(crate) var_dv__blk306_dn5: f64,
    pub(crate) var_dv__blk306_rv: f64,
    pub(crate) var_dv_dn1: f64,
    pub(crate) var_dv_dn3: f64,
    pub(crate) var_dv_dn4: f64,
    pub(crate) var_dv_dn5: f64,
    pub(crate) var_dv_rv: f64,
    pub(crate) var_dvar: f64,
    pub(crate) var_dvar_dn1: f64,
    pub(crate) var_dvar_dn3: f64,
    pub(crate) var_dvar_dn4: f64,
    pub(crate) var_dvar_dn5: f64,
    pub(crate) var_dvh: f64,
    pub(crate) var_dvh__blk269: f64,
    pub(crate) var_dvh__blk269_dn1: f64,
    pub(crate) var_dvh__blk269_dn3: f64,
    pub(crate) var_dvh__blk269_dn4: f64,
    pub(crate) var_dvh__blk269_dn5: f64,
    pub(crate) var_dvh__blk269_rv: f64,
    pub(crate) var_dvh__blk287: f64,
    pub(crate) var_dvh__blk287_dn1: f64,
    pub(crate) var_dvh__blk287_dn3: f64,
    pub(crate) var_dvh__blk287_dn4: f64,
    pub(crate) var_dvh__blk287_dn5: f64,
    pub(crate) var_dvh__blk287_rv: f64,
    pub(crate) var_dvh__blk300: f64,
    pub(crate) var_dvh__blk300_dn1: f64,
    pub(crate) var_dvh__blk300_dn3: f64,
    pub(crate) var_dvh__blk300_dn4: f64,
    pub(crate) var_dvh__blk300_dn5: f64,
    pub(crate) var_dvh__blk300_rv: f64,
    pub(crate) var_dvh_dn1: f64,
    pub(crate) var_dvh_dn3: f64,
    pub(crate) var_dvh_dn4: f64,
    pub(crate) var_dvh_dn5: f64,
    pub(crate) var_dvh_rv: f64,
    pub(crate) var_ecorn_t: f64,
    pub(crate) var_ecorn_t_dn3: f64,
    pub(crate) var_ecorn_t_rv: f64,
    pub(crate) var_ecrit_t: f64,
    pub(crate) var_ecrit_t_dn3: f64,
    pub(crate) var_ecrit_t_rv: f64,
    pub(crate) var_ecrneff: f64,
    pub(crate) var_ecrneff_dn3: f64,
    pub(crate) var_expx: f64,
    pub(crate) var_expx__blk220: f64,
    pub(crate) var_expx__blk220_dn1: f64,
    pub(crate) var_expx__blk220_dn3: f64,
    pub(crate) var_expx__blk220_dn4: f64,
    pub(crate) var_expx__blk227: f64,
    pub(crate) var_expx__blk227_dn1: f64,
    pub(crate) var_expx__blk227_dn3: f64,
    pub(crate) var_expx__blk227_dn5: f64,
    pub(crate) var_expx__blk236: f64,
    pub(crate) var_expx__blk236_dn1: f64,
    pub(crate) var_expx__blk236_dn3: f64,
    pub(crate) var_expx__blk236_dn5: f64,
    pub(crate) var_expx_dn1: f64,
    pub(crate) var_expx_dn3: f64,
    pub(crate) var_expx_dn4: f64,
    pub(crate) var_fctr1: f64,
    pub(crate) var_fctr1_rv: f64,
    pub(crate) var_fctrm: f64,
    pub(crate) var_fctrm_dn1: f64,
    pub(crate) var_fctrm_dn3: f64,
    pub(crate) var_fctrm_dn4: f64,
    pub(crate) var_fctrm_dn5: f64,
    pub(crate) var_fctrp: f64,
    pub(crate) var_fctrp_dn1: f64,
    pub(crate) var_fctrp_dn3: f64,
    pub(crate) var_fctrp_dn4: f64,
    pub(crate) var_fctrp_dn5: f64,
    pub(crate) var_fouratsq: f64,
    pub(crate) var_fouratsq_dn1: f64,
    pub(crate) var_fouratsq_dn3: f64,
    pub(crate) var_fouratsq_dn4: f64,
    pub(crate) var_fouratsq_dn5: f64,
    pub(crate) var_fsatphi: f64,
    pub(crate) var_fsatphi_dn1: f64,
    pub(crate) var_fsatphi_dn3: f64,
    pub(crate) var_fsatphi_dn4: f64,
    pub(crate) var_fsatphi_dn5: f64,
    pub(crate) var_geff: f64,
    pub(crate) var_geff_dn1: f64,
    pub(crate) var_geff_dn3: f64,
    pub(crate) var_geff_dn4: f64,
    pub(crate) var_geff_dn5: f64,
    pub(crate) var_gf: f64,
    pub(crate) var_gf_dn3: f64,
    pub(crate) var_gmin: f64,
    pub(crate) var_gth: f64,
    pub(crate) var_gth_dn3: f64,
    pub(crate) var_guard104: f64,
    pub(crate) var_guard104_rv: f64,
    pub(crate) var_guard105: f64,
    pub(crate) var_guard105_rv: f64,
    pub(crate) var_guard110: f64,
    pub(crate) var_guard110_rv: f64,
    pub(crate) var_guard111: f64,
    pub(crate) var_guard111_rv: f64,
    pub(crate) var_guard112: f64,
    pub(crate) var_guard112_rv: f64,
    pub(crate) var_guard116: f64,
    pub(crate) var_guard116_rv: f64,
    pub(crate) var_guard117: f64,
    pub(crate) var_guard117_rv: f64,
    pub(crate) var_guard118: f64,
    pub(crate) var_guard118_rv: f64,
    pub(crate) var_guard119: f64,
    pub(crate) var_guard119_rv: f64,
    pub(crate) var_guard120: f64,
    pub(crate) var_guard120_rv: f64,
    pub(crate) var_guard122: f64,
    pub(crate) var_guard123: f64,
    pub(crate) var_guard124: f64,
    pub(crate) var_guard124_rv: f64,
    pub(crate) var_guard125: f64,
    pub(crate) var_guard125_rv: f64,
    pub(crate) var_guard126: f64,
    pub(crate) var_guard126_rv: f64,
    pub(crate) var_guard127: f64,
    pub(crate) var_guard128: f64,
    pub(crate) var_guard129: f64,
    pub(crate) var_guard130: f64,
    pub(crate) var_guard130_rv: f64,
    pub(crate) var_guard133: f64,
    pub(crate) var_guard133_rv: f64,
    pub(crate) var_guard136: f64,
    pub(crate) var_guard137: f64,
    pub(crate) var_guard137_rv: f64,
    pub(crate) var_guard138: f64,
    pub(crate) var_guard138_rv: f64,
    pub(crate) var_guard189: f64,
    pub(crate) var_guard189_rv: f64,
    pub(crate) var_guard190: f64,
    pub(crate) var_guard190_rv: f64,
    pub(crate) var_guard191: f64,
    pub(crate) var_guard191_rv: f64,
    pub(crate) var_guard192: f64,
    pub(crate) var_guard192_rv: f64,
    pub(crate) var_guard193: f64,
    pub(crate) var_guard193_rv: f64,
    pub(crate) var_guard194: f64,
    pub(crate) var_guard195: f64,
    pub(crate) var_guard196: f64,
    pub(crate) var_guard197: f64,
    pub(crate) var_guard198: f64,
    pub(crate) var_guard199: f64,
    pub(crate) var_guard200: f64,
    pub(crate) var_guard201: f64,
    pub(crate) var_guard202: f64,
    pub(crate) var_guard203: f64,
    pub(crate) var_guard204: f64,
    pub(crate) var_guard205: f64,
    pub(crate) var_guard206: f64,
    pub(crate) var_guard207: f64,
    pub(crate) var_guard214: f64,
    pub(crate) var_guard215: f64,
    pub(crate) var_guard216: f64,
    pub(crate) var_guard217: f64,
    pub(crate) var_guard221: f64,
    pub(crate) var_guard222: f64,
    pub(crate) var_guard223: f64,
    pub(crate) var_guard230: f64,
    pub(crate) var_guard231: f64,
    pub(crate) var_guard232: f64,
    pub(crate) var_guard233: f64,
    pub(crate) var_guard237: f64,
    pub(crate) var_guard238: f64,
    pub(crate) var_guard239: f64,
    pub(crate) var_guard240: f64,
    pub(crate) var_guard241: f64,
    pub(crate) var_guard242: f64,
    pub(crate) var_guard243: f64,
    pub(crate) var_guard249: f64,
    pub(crate) var_guard249_rv: f64,
    pub(crate) var_guard254: f64,
    pub(crate) var_guard254_rv: f64,
    pub(crate) var_guard265: f64,
    pub(crate) var_guard265_rv: f64,
    pub(crate) var_guard266: f64,
    pub(crate) var_guard266_rv: f64,
    pub(crate) var_guard267: f64,
    pub(crate) var_guard267_rv: f64,
    pub(crate) var_guard278: f64,
    pub(crate) var_guard278_rv: f64,
    pub(crate) var_guard279: f64,
    pub(crate) var_guard279_rv: f64,
    pub(crate) var_guard280: f64,
    pub(crate) var_guard280_rv: f64,
    pub(crate) var_guard285: f64,
    pub(crate) var_guard285_rv: f64,
    pub(crate) var_guard296: f64,
    pub(crate) var_guard296_rv: f64,
    pub(crate) var_guard297: f64,
    pub(crate) var_guard297_rv: f64,
    pub(crate) var_guard298: f64,
    pub(crate) var_guard298_rv: f64,
    pub(crate) var_guard309: f64,
    pub(crate) var_guard309_rv: f64,
    pub(crate) var_guard310: f64,
    pub(crate) var_guard310_rv: f64,
    pub(crate) var_guard311: f64,
    pub(crate) var_guard312: f64,
    pub(crate) var_ib1: f64,
    pub(crate) var_ib1_dn1: f64,
    pub(crate) var_ib1_dn3: f64,
    pub(crate) var_ib1_dn4: f64,
    pub(crate) var_ib2: f64,
    pub(crate) var_ib2_dn1: f64,
    pub(crate) var_ib2_dn3: f64,
    pub(crate) var_ib2_dn5: f64,
    pub(crate) var_id1: f64,
    pub(crate) var_id1_dn1: f64,
    pub(crate) var_id1_dn3: f64,
    pub(crate) var_id1_dn4: f64,
    pub(crate) var_id1_dn5: f64,
    pub(crate) var_id2: f64,
    pub(crate) var_id2_dn1: f64,
    pub(crate) var_id2_dn3: f64,
    pub(crate) var_id2_dn4: f64,
    pub(crate) var_id2_dn5: f64,
    pub(crate) var_iecrit: f64,
    pub(crate) var_iecrit_dn3: f64,
    pub(crate) var_iecrit_rv: f64,
    pub(crate) var_il_dple: f64,
    pub(crate) var_il_dple_rv: f64,
    pub(crate) var_ip1: f64,
    pub(crate) var_ip1_dn1: f64,
    pub(crate) var_ip1_dn3: f64,
    pub(crate) var_ip1_dn4: f64,
    pub(crate) var_ip1_dn5: f64,
    pub(crate) var_ip2: f64,
    pub(crate) var_ip2_dn1: f64,
    pub(crate) var_ip2_dn3: f64,
    pub(crate) var_ip2_dn4: f64,
    pub(crate) var_ip2_dn5: f64,
    pub(crate) var_irb: f64,
    pub(crate) var_irb_dn1: f64,
    pub(crate) var_irb_dn3: f64,
    pub(crate) var_irb_dn4: f64,
    pub(crate) var_irb_dn5: f64,
    pub(crate) var_irth: f64,
    pub(crate) var_irth_dn3: f64,
    pub(crate) var_is1: f64,
    pub(crate) var_is2: f64,
    pub(crate) var_isa_t: f64,
    pub(crate) var_isa_t_dn3: f64,
    pub(crate) var_isp_t: f64,
    pub(crate) var_isp_t_dn3: f64,
    pub(crate) var_ith: f64,
    pub(crate) var_ith_db0: f64,
    pub(crate) var_ith_db1: f64,
    pub(crate) var_ith_dn0: f64,
    pub(crate) var_ith_dn1: f64,
    pub(crate) var_ith_dn2: f64,
    pub(crate) var_ith_dn3: f64,
    pub(crate) var_ith_dn4: f64,
    pub(crate) var_ith_dn5: f64,
    pub(crate) var_iw_dpwe: f64,
    pub(crate) var_iw_dpwe_rv: f64,
    pub(crate) var_l_um: f64,
    pub(crate) var_l_um_rv: f64,
    pub(crate) var_lde: f64,
    pub(crate) var_lde_dn3: f64,
    pub(crate) var_lde_rv: f64,
    pub(crate) var_leff_um: f64,
    pub(crate) var_leff_um_rv: f64,
    pub(crate) var_leffe_um: f64,
    pub(crate) var_leffe_um_rv: f64,
    pub(crate) var_len: f64,
    pub(crate) var_len_rv: f64,
    pub(crate) var_lfactor: f64,
    pub(crate) var_lfactor_rv: f64,
    pub(crate) var_mmod: f64,
    pub(crate) var_mmod_rv: f64,
    pub(crate) var_mv: f64,
    pub(crate) var_mv0: f64,
    pub(crate) var_mv0__blk273: f64,
    pub(crate) var_mv0__blk273_dn3: f64,
    pub(crate) var_mv0__blk273_rv: f64,
    pub(crate) var_mv0__blk291: f64,
    pub(crate) var_mv0__blk291_dn3: f64,
    pub(crate) var_mv0__blk291_rv: f64,
    pub(crate) var_mv0__blk304: f64,
    pub(crate) var_mv0__blk304_dn3: f64,
    pub(crate) var_mv0__blk304_rv: f64,
    pub(crate) var_mv0_dn3: f64,
    pub(crate) var_mv0_rv: f64,
    pub(crate) var_mv__blk276: f64,
    pub(crate) var_mv__blk276_dn1: f64,
    pub(crate) var_mv__blk276_dn3: f64,
    pub(crate) var_mv__blk276_dn4: f64,
    pub(crate) var_mv__blk276_dn5: f64,
    pub(crate) var_mv__blk276_rv: f64,
    pub(crate) var_mv__blk294: f64,
    pub(crate) var_mv__blk294_dn1: f64,
    pub(crate) var_mv__blk294_dn3: f64,
    pub(crate) var_mv__blk294_dn4: f64,
    pub(crate) var_mv__blk294_dn5: f64,
    pub(crate) var_mv__blk294_rv: f64,
    pub(crate) var_mv__blk307: f64,
    pub(crate) var_mv__blk307_dn1: f64,
    pub(crate) var_mv__blk307_dn3: f64,
    pub(crate) var_mv__blk307_dn4: f64,
    pub(crate) var_mv__blk307_dn5: f64,
    pub(crate) var_mv__blk307_rv: f64,
    pub(crate) var_mv_dn1: f64,
    pub(crate) var_mv_dn3: f64,
    pub(crate) var_mv_dn4: f64,
    pub(crate) var_mv_dn5: f64,
    pub(crate) var_mv_rv: f64,
    pub(crate) var_nbv_t: f64,
    pub(crate) var_nbv_t_dn3: f64,
    pub(crate) var_nsteff: f64,
    pub(crate) var_nsteff_dn3: f64,
    pub(crate) var_nsteff_rv: f64,
    pub(crate) var_p1_um: f64,
    pub(crate) var_p1_um_rv: f64,
    pub(crate) var_p2_um: f64,
    pub(crate) var_p2_um_rv: f64,
    pub(crate) var_p_um: f64,
    pub(crate) var_p_um_rv: f64,
    pub(crate) var_pa_t: f64,
    pub(crate) var_pa_t_dn3: f64,
    pub(crate) var_pa_t_rv: f64,
    pub(crate) var_pcjp: f64,
    pub(crate) var_pcjp__blk282: f64,
    pub(crate) var_pcjp__blk282_dn3: f64,
    pub(crate) var_pcjp__blk282_rv: f64,
    pub(crate) var_pcjp_dn3: f64,
    pub(crate) var_pcjp_rv: f64,
    pub(crate) var_pe: f64,
    pub(crate) var_pe_dn1: f64,
    pub(crate) var_pe_dn3: f64,
    pub(crate) var_pe_dn4: f64,
    pub(crate) var_pe_dn5: f64,
    pub(crate) var_pe_rv: f64,
    pub(crate) var_phi_t: f64,
    pub(crate) var_phi_t0: f64,
    pub(crate) var_phi_t0_dn3: f64,
    pub(crate) var_phi_t0_rv: f64,
    pub(crate) var_phi_t_dn3: f64,
    pub(crate) var_phi_t_rv: f64,
    pub(crate) var_pisp: f64,
    pub(crate) var_pisp__blk225: f64,
    pub(crate) var_pisp__blk225_dn3: f64,
    pub(crate) var_pisp_dn3: f64,
    pub(crate) var_pnjia: f64,
    pub(crate) var_pnjia__blk228: f64,
    pub(crate) var_pnjia__blk228_dn1: f64,
    pub(crate) var_pnjia__blk228_dn3: f64,
    pub(crate) var_pnjia__blk228_dn4: f64,
    pub(crate) var_pnjia__blk228_dn5: f64,
    pub(crate) var_pnjia_dn1: f64,
    pub(crate) var_pnjia_dn3: f64,
    pub(crate) var_pnjia_dn4: f64,
    pub(crate) var_pnjia_dn5: f64,
    pub(crate) var_pnjip: f64,
    pub(crate) var_pnjip__blk229: f64,
    pub(crate) var_pnjip__blk229_dn1: f64,
    pub(crate) var_pnjip__blk229_dn3: f64,
    pub(crate) var_pnjip__blk229_dn5: f64,
    pub(crate) var_pnjip_dn1: f64,
    pub(crate) var_pnjip_dn3: f64,
    pub(crate) var_pnjip_dn4: f64,
    pub(crate) var_power: f64,
    pub(crate) var_power_db0: f64,
    pub(crate) var_power_db1: f64,
    pub(crate) var_power_dn0: f64,
    pub(crate) var_power_dn1: f64,
    pub(crate) var_power_dn2: f64,
    pub(crate) var_power_dn3: f64,
    pub(crate) var_power_dn4: f64,
    pub(crate) var_power_dn5: f64,
    pub(crate) var_pp_t: f64,
    pub(crate) var_pp_t_dn3: f64,
    pub(crate) var_pp_t_rv: f64,
    pub(crate) var_psiin: f64,
    pub(crate) var_psiin__blk135: f64,
    pub(crate) var_psiin__blk135_dn3: f64,
    pub(crate) var_psiin__blk135_rv: f64,
    pub(crate) var_psiin_dn3: f64,
    pub(crate) var_psiin_rv: f64,
    pub(crate) var_psiio: f64,
    pub(crate) var_psiio__blk134: f64,
    pub(crate) var_psiio__blk134_dn3: f64,
    pub(crate) var_psiio__blk134_rv: f64,
    pub(crate) var_psiio_dn3: f64,
    pub(crate) var_psiio_rv: f64,
    pub(crate) var_pvar: f64,
    pub(crate) var_pvar_dn1: f64,
    pub(crate) var_pvar_dn3: f64,
    pub(crate) var_pvar_dn4: f64,
    pub(crate) var_pvar_dn5: f64,
    pub(crate) var_pwq: f64,
    pub(crate) var_pwq__blk270: f64,
    pub(crate) var_pwq__blk270_rv: f64,
    pub(crate) var_pwq__blk288: f64,
    pub(crate) var_pwq__blk288_rv: f64,
    pub(crate) var_pwq__blk301: f64,
    pub(crate) var_pwq__blk301_rv: f64,
    pub(crate) var_pwq_rv: f64,
    pub(crate) var_qcp1: f64,
    pub(crate) var_qcp1_dn1: f64,
    pub(crate) var_qcp1_dn3: f64,
    pub(crate) var_qcp1_dn4: f64,
    pub(crate) var_qcp1_dn5: f64,
    pub(crate) var_qcp1_rv: f64,
    pub(crate) var_qcp2: f64,
    pub(crate) var_qcp2_dn1: f64,
    pub(crate) var_qcp2_dn3: f64,
    pub(crate) var_qcp2_dn4: f64,
    pub(crate) var_qcp2_dn5: f64,
    pub(crate) var_qcp2_rv: f64,
    pub(crate) var_qcth: f64,
    pub(crate) var_qcth_dn3: f64,
    pub(crate) var_qcth_rv: f64,
    pub(crate) var_qhi: f64,
    pub(crate) var_qhi__blk272: f64,
    pub(crate) var_qhi__blk272_dn1: f64,
    pub(crate) var_qhi__blk272_dn3: f64,
    pub(crate) var_qhi__blk272_dn4: f64,
    pub(crate) var_qhi__blk272_dn5: f64,
    pub(crate) var_qhi__blk272_rv: f64,
    pub(crate) var_qhi__blk290: f64,
    pub(crate) var_qhi__blk290_dn1: f64,
    pub(crate) var_qhi__blk290_dn3: f64,
    pub(crate) var_qhi__blk290_dn4: f64,
    pub(crate) var_qhi__blk290_dn5: f64,
    pub(crate) var_qhi__blk290_rv: f64,
    pub(crate) var_qhi__blk303: f64,
    pub(crate) var_qhi__blk303_dn1: f64,
    pub(crate) var_qhi__blk303_dn3: f64,
    pub(crate) var_qhi__blk303_dn4: f64,
    pub(crate) var_qhi__blk303_dn5: f64,
    pub(crate) var_qhi__blk303_rv: f64,
    pub(crate) var_qhi_dn1: f64,
    pub(crate) var_qhi_dn3: f64,
    pub(crate) var_qhi_dn4: f64,
    pub(crate) var_qhi_dn5: f64,
    pub(crate) var_qhi_rv: f64,
    pub(crate) var_qlo: f64,
    pub(crate) var_qlo__blk271: f64,
    pub(crate) var_qlo__blk271_dn1: f64,
    pub(crate) var_qlo__blk271_dn3: f64,
    pub(crate) var_qlo__blk271_dn4: f64,
    pub(crate) var_qlo__blk271_dn5: f64,
    pub(crate) var_qlo__blk271_rv: f64,
    pub(crate) var_qlo__blk289: f64,
    pub(crate) var_qlo__blk289_dn1: f64,
    pub(crate) var_qlo__blk289_dn3: f64,
    pub(crate) var_qlo__blk289_dn4: f64,
    pub(crate) var_qlo__blk289_dn5: f64,
    pub(crate) var_qlo__blk289_rv: f64,
    pub(crate) var_qlo__blk302: f64,
    pub(crate) var_qlo__blk302_dn1: f64,
    pub(crate) var_qlo__blk302_dn3: f64,
    pub(crate) var_qlo__blk302_dn4: f64,
    pub(crate) var_qlo__blk302_dn5: f64,
    pub(crate) var_qlo__blk302_rv: f64,
    pub(crate) var_qlo_dn1: f64,
    pub(crate) var_qlo_dn3: f64,
    pub(crate) var_qlo_dn4: f64,
    pub(crate) var_qlo_dn5: f64,
    pub(crate) var_qlo_rv: f64,
    pub(crate) var_qvar: f64,
    pub(crate) var_qvar_dn1: f64,
    pub(crate) var_qvar_dn3: f64,
    pub(crate) var_qvar_dn4: f64,
    pub(crate) var_qvar_dn5: f64,
    pub(crate) var_r0: f64,
    pub(crate) var_r0_dn3: f64,
    pub(crate) var_rc1_tnom: f64,
    pub(crate) var_rc2_tnom: f64,
    pub(crate) var_rm: f64,
    pub(crate) var_rm_dn1: f64,
    pub(crate) var_rm_dn3: f64,
    pub(crate) var_rm_dn4: f64,
    pub(crate) var_rm_dn5: f64,
    pub(crate) var_rmu: f64,
    pub(crate) var_rmu_dn1: f64,
    pub(crate) var_rmu_dn3: f64,
    pub(crate) var_rmu_dn4: f64,
    pub(crate) var_rmu_dn5: f64,
    pub(crate) var_rp: f64,
    pub(crate) var_rp_dn1: f64,
    pub(crate) var_rp_dn3: f64,
    pub(crate) var_rp_dn4: f64,
    pub(crate) var_rp_dn5: f64,
    pub(crate) var_rt: f64,
    pub(crate) var_rt_dn3: f64,
    pub(crate) var_rt_rv: f64,
    pub(crate) var_rvar: f64,
    pub(crate) var_rvar_dn1: f64,
    pub(crate) var_rvar_dn3: f64,
    pub(crate) var_rvar_dn4: f64,
    pub(crate) var_rvar_dn5: f64,
    pub(crate) var_sd: f64,
    pub(crate) var_sd_dn1: f64,
    pub(crate) var_sd_dn3: f64,
    pub(crate) var_sd_dn4: f64,
    pub(crate) var_sd_dn5: f64,
    pub(crate) var_sdflip: f64,
    pub(crate) var_sqrtm: f64,
    pub(crate) var_sqrtm_dn1: f64,
    pub(crate) var_sqrtm_dn3: f64,
    pub(crate) var_sqrtm_dn4: f64,
    pub(crate) var_sqrtm_dn5: f64,
    pub(crate) var_sqrtp: f64,
    pub(crate) var_sqrtp_dn1: f64,
    pub(crate) var_sqrtp_dn3: f64,
    pub(crate) var_sqrtp_dn4: f64,
    pub(crate) var_sqrtp_dn5: f64,
    pub(crate) var_tambc: f64,
    pub(crate) var_tambk: f64,
    pub(crate) var_tc1e: f64,
    pub(crate) var_tc1e_rv: f64,
    pub(crate) var_tc2e: f64,
    pub(crate) var_tc2e_rv: f64,
    pub(crate) var_tcr: f64,
    pub(crate) var_tcr_dn3: f64,
    pub(crate) var_tcr_rv: f64,
    pub(crate) var_tcrc: f64,
    pub(crate) var_tcrc_dn3: f64,
    pub(crate) var_tcvsat: f64,
    pub(crate) var_tcvsat_dn3: f64,
    pub(crate) var_tcvsat_rv: f64,
    pub(crate) var_tdevc: f64,
    pub(crate) var_tdevc_dn3: f64,
    pub(crate) var_tdevc_rv: f64,
    pub(crate) var_tdevk: f64,
    pub(crate) var_tdevk_dn3: f64,
    pub(crate) var_tdevk_rv: f64,
    pub(crate) var_tinik: f64,
    pub(crate) var_tinik_rv: f64,
    pub(crate) var_tmp: f64,
    pub(crate) var_tmp_dn1: f64,
    pub(crate) var_tmp_dn3: f64,
    pub(crate) var_tmp_dn4: f64,
    pub(crate) var_tmp_dn5: f64,
    pub(crate) var_uoff: f64,
    pub(crate) var_uoff_dn3: f64,
    pub(crate) var_v1c: f64,
    pub(crate) var_v1c_dn1: f64,
    pub(crate) var_v1c_dn3: f64,
    pub(crate) var_v1c_dn4: f64,
    pub(crate) var_v1c_dn5: f64,
    pub(crate) var_v1c_rv: f64,
    pub(crate) var_v1ci: f64,
    pub(crate) var_v1ci_dn1: f64,
    pub(crate) var_v1ci_dn4: f64,
    pub(crate) var_v1ci_dn5: f64,
    pub(crate) var_v1ci_rv: f64,
    pub(crate) var_v1cl: f64,
    pub(crate) var_v1cl_dn1: f64,
    pub(crate) var_v1cl_dn3: f64,
    pub(crate) var_v1cl_dn4: f64,
    pub(crate) var_v1cl_dn5: f64,
    pub(crate) var_v1cl_rv: f64,
    pub(crate) var_v1cx: f64,
    pub(crate) var_val1: f64,
    pub(crate) var_val1_dn1: f64,
    pub(crate) var_val1_dn3: f64,
    pub(crate) var_val1_dn4: f64,
    pub(crate) var_val1_dn5: f64,
    pub(crate) var_val2: f64,
    pub(crate) var_val2_dn1: f64,
    pub(crate) var_val2_dn3: f64,
    pub(crate) var_val2_dn4: f64,
    pub(crate) var_val2_dn5: f64,
    pub(crate) var_vbkd: f64,
    pub(crate) var_vbkd__blk234: f64,
    pub(crate) var_vbkd__blk234_dn1: f64,
    pub(crate) var_vbkd__blk234_dn3: f64,
    pub(crate) var_vbkd__blk234_dn5: f64,
    pub(crate) var_vbkd_dn1: f64,
    pub(crate) var_vbkd_dn3: f64,
    pub(crate) var_vbkd_dn4: f64,
    pub(crate) var_vbv_t: f64,
    pub(crate) var_vbv_t_dn3: f64,
    pub(crate) var_vc1: f64,
    pub(crate) var_vc1_dn1: f64,
    pub(crate) var_vc1_dn4: f64,
    pub(crate) var_vc1_rv: f64,
    pub(crate) var_vc2: f64,
    pub(crate) var_vc2_dn1: f64,
    pub(crate) var_vc2_dn5: f64,
    pub(crate) var_vc2_rv: f64,
    pub(crate) var_vcl: f64,
    pub(crate) var_vcl_dn1: f64,
    pub(crate) var_vcl_dn3: f64,
    pub(crate) var_vcl_dn4: f64,
    pub(crate) var_vcl_dn5: f64,
    pub(crate) var_vcl_rv: f64,
    pub(crate) var_vl: f64,
    pub(crate) var_vl0: f64,
    pub(crate) var_vl0__blk274: f64,
    pub(crate) var_vl0__blk274_dn3: f64,
    pub(crate) var_vl0__blk274_rv: f64,
    pub(crate) var_vl0__blk292: f64,
    pub(crate) var_vl0__blk292_dn3: f64,
    pub(crate) var_vl0__blk292_rv: f64,
    pub(crate) var_vl0__blk305: f64,
    pub(crate) var_vl0__blk305_dn3: f64,
    pub(crate) var_vl0__blk305_rv: f64,
    pub(crate) var_vl0_dn3: f64,
    pub(crate) var_vl0_rv: f64,
    pub(crate) var_vl__blk277: f64,
    pub(crate) var_vl__blk277_dn1: f64,
    pub(crate) var_vl__blk277_dn3: f64,
    pub(crate) var_vl__blk277_dn4: f64,
    pub(crate) var_vl__blk277_dn5: f64,
    pub(crate) var_vl__blk277_rv: f64,
    pub(crate) var_vl__blk295: f64,
    pub(crate) var_vl__blk295_dn1: f64,
    pub(crate) var_vl__blk295_dn3: f64,
    pub(crate) var_vl__blk295_dn4: f64,
    pub(crate) var_vl__blk295_dn5: f64,
    pub(crate) var_vl__blk295_rv: f64,
    pub(crate) var_vl__blk308: f64,
    pub(crate) var_vl__blk308_dn1: f64,
    pub(crate) var_vl__blk308_dn3: f64,
    pub(crate) var_vl__blk308_dn4: f64,
    pub(crate) var_vl__blk308_dn5: f64,
    pub(crate) var_vl__blk308_rv: f64,
    pub(crate) var_vl_dn1: f64,
    pub(crate) var_vl_dn3: f64,
    pub(crate) var_vl_dn4: f64,
    pub(crate) var_vl_dn5: f64,
    pub(crate) var_vl_rv: f64,
    pub(crate) var_vmax_a: f64,
    pub(crate) var_vmax_a_dn3: f64,
    pub(crate) var_vmax_b: f64,
    pub(crate) var_vmax_b_dn3: f64,
    pub(crate) var_vmax_p: f64,
    pub(crate) var_vmax_p_dn3: f64,
    pub(crate) var_vpo: f64,
    pub(crate) var_vpo_dn3: f64,
    pub(crate) var_vpo_rv: f64,
    pub(crate) var_vpoe: f64,
    pub(crate) var_vpoe_dn3: f64,
    pub(crate) var_vpoe_rv: f64,
    pub(crate) var_vrb: f64,
    pub(crate) var_vrb_dn4: f64,
    pub(crate) var_vrb_dn5: f64,
    pub(crate) var_vrb_rv: f64,
    pub(crate) var_vrbeff: f64,
    pub(crate) var_vrbeff_dn1: f64,
    pub(crate) var_vrbeff_dn3: f64,
    pub(crate) var_vrbeff_dn4: f64,
    pub(crate) var_vrbeff_dn5: f64,
    pub(crate) var_vrbi: f64,
    pub(crate) var_vrbi_dn4: f64,
    pub(crate) var_vrbi_dn5: f64,
    pub(crate) var_vrbi_rv: f64,
    pub(crate) var_vsat: f64,
    pub(crate) var_vsat_dn1: f64,
    pub(crate) var_vsat_dn3: f64,
    pub(crate) var_vsat_dn4: f64,
    pub(crate) var_vsat_dn5: f64,
    pub(crate) var_vsatphi: f64,
    pub(crate) var_vsatphi_dn1: f64,
    pub(crate) var_vsatphi_dn3: f64,
    pub(crate) var_vsatphi_dn4: f64,
    pub(crate) var_vsatphi_dn5: f64,
    pub(crate) var_w_um: f64,
    pub(crate) var_w_um_rv: f64,
    pub(crate) var_wd_um: f64,
    pub(crate) var_wd_um_rv: f64,
    pub(crate) var_weff_um: f64,
    pub(crate) var_weff_um_rv: f64,
    pub(crate) var_wid: f64,
    pub(crate) var_wid_rv: f64,
    pub(crate) var_xleff: f64,
    pub(crate) var_xleff_rv: f64,
    pub(crate) var_yvar: f64,
    pub(crate) var_yvar_dn1: f64,
    pub(crate) var_yvar_dn3: f64,
    pub(crate) var_yvar_dn4: f64,
    pub(crate) var_yvar_dn5: f64,
}

impl Instance {
    pub fn stamp(&mut self, ctx: &GeneratedEvalContext<'_>, stamper: &mut GeneratedStamper<'_>) {
        let p = Box::as_ref(&self.params);
        let nodes = &(*self).nodes;
        let branches = &(*self).branches;
        let bi0 = ctx.branch_current(branches[0]);
        let bi1 = ctx.branch_current(branches[1]);
        let multiplicity = (*self).multiplicity;
        let timestep = (*self).timestep;
        let ddt_state_current = self.ddt_state_current.as_mut();
        let ddt_state_previous = self.ddt_state_previous.as_mut();
        let ddt_state_older = self.ddt_state_older.as_mut();
        let ddt_state_initialized = self.ddt_state_initialized.as_mut();
        let ddt_derivative_current = self.ddt_derivative_current.as_mut();
        let ddt_derivative_previous = self.ddt_derivative_previous.as_mut();
        let ddt_active = self.ddt_coefficients.active;
        let ddt_scale = self.ddt_coefficients.derivative_scale;
        let ddt_previous_value_scale = self.ddt_coefficients.previous_value_scale;
        let ddt_older_value_scale = self.ddt_coefficients.older_value_scale;
        let ddt_previous_derivative_scale = self.ddt_coefficients.previous_derivative_scale;
        let mut locals = StampLocals::default();

        Self::stamp_transient_block_0(ctx, p, multiplicity, &mut locals);
        Self::stamp_transient_block_1(ctx, p, nodes, &mut locals);
        Self::stamp_transient_block_2(p, &mut locals);
        Self::stamp_transient_block_3(p, &mut locals);
        Self::stamp_transient_block_4(p, &mut locals);
        Self::stamp_transient_block_5(p, &mut locals);
        Self::stamp_transient_block_6(p, &mut locals);
        Self::stamp_transient_block_7(ctx, p, nodes, branches, &mut locals);
        Self::stamp_transient_block_8(p, &mut locals);
        Self::stamp_transient_block_9(p, &mut locals);
        Self::stamp_transient_block_10(p, &mut locals);

        stamper.stamp_potential_branch_local(
            Some(0),
            Some(4),
            0,
            multiplicity,
        );
        stamper.stamp_potential_branch_local(
            Some(2),
            Some(5),
            1,
            multiplicity,
        );

        Self::stamp_transient_equations_block_0(stamper, multiplicity, &mut locals);
        let (eq5_e153, eq5_e153_d_n3, eq5_e153_d_b0,) = {
    if (locals.var_guard311 != 0.0) {
        let eq5_e149: f64 = (bi0 * locals.var_rc1_tnom);
        let eq5_e151: f64 = (eq5_e149 * locals.var_tcrc);
        let eq5_e151_d_n3: f64 = (eq5_e149 * locals.var_tcrc_dn3);
        let eq5_e151_d_b0: f64 = (locals.var_rc1_tnom * locals.var_tcrc);
        (eq5_e151, eq5_e151_d_n3, eq5_e151_d_b0,)
    } else {
        (0.0, 0.0, 0.0,)
    }
};
        let eq5_value: f64 = eq5_e153;
        stamper.stamp_potential_node1_branch1_local(
            0,
            eq5_value,
            3,
            eq5_e153_d_n3,
            0,
            eq5_e153_d_b0,
        );
        Self::stamp_transient_equations_block_1(ctx, stamper, nodes, multiplicity, &mut locals);
        let (eq7_e170, eq7_e170_d_n3, eq7_e170_d_b1,) = {
    if (locals.var_guard312 != 0.0) {
        let eq7_e166: f64 = (bi1 * locals.var_rc2_tnom);
        let eq7_e168: f64 = (eq7_e166 * locals.var_tcrc);
        let eq7_e168_d_n3: f64 = (eq7_e166 * locals.var_tcrc_dn3);
        let eq7_e168_d_b1: f64 = (locals.var_rc2_tnom * locals.var_tcrc);
        (eq7_e168, eq7_e168_d_n3, eq7_e168_d_b1,)
    } else {
        (0.0, 0.0, 0.0,)
    }
};
        let eq7_value: f64 = eq7_e170;
        stamper.stamp_potential_node1_branch1_local(
            1,
            eq7_value,
            3,
            eq7_e170_d_n3,
            1,
            eq7_e170_d_b1,
        );
        Self::stamp_transient_equations_block_2(ctx, stamper, nodes, multiplicity, ddt_active, ddt_scale, ddt_previous_value_scale, ddt_older_value_scale, ddt_previous_derivative_scale, ddt_state_current, ddt_state_previous, ddt_state_older, ddt_state_initialized, ddt_derivative_current, ddt_derivative_previous, &mut locals);
    }

    pub fn stamp_reactive(&mut self, ctx: &GeneratedEvalContext<'_>, stamper: &mut GeneratedReactiveStamper<'_>) {
        let p = Box::as_ref(&self.params);
        let nodes = &(*self).nodes;
        let branches = &(*self).branches;
        let multiplicity = (*self).multiplicity;
        let mut locals = StampLocals::default();

        Self::stamp_reactive_block_0(ctx, p, multiplicity, &mut locals);
        Self::stamp_reactive_block_1(ctx, p, nodes, &mut locals);
        Self::stamp_reactive_block_2(p, &mut locals);
        Self::stamp_reactive_block_3(p, &mut locals);
        Self::stamp_reactive_block_4(p, &mut locals);
        Self::stamp_reactive_block_5(p, &mut locals);

        Self::stamp_reactive_equations_block_0(stamper, nodes, multiplicity, &mut locals);
    }
}
