// @generated by rspice-veriloga; do not edit.
#![allow(dead_code, non_snake_case, unused_imports, unused_mut, unused_parens, unused_variables)]

use super::state::{CanonicalModelValues, Instance, PARAMETER_MODEL_FLAGS};
use rspice_veriloga_runtime::{GeneratedEvalContext, GeneratedReactiveStamper, GeneratedStamper, install_generated_stage_values, L2, L3, L4, L6, L8, rspice_eval_ddt, rspice_eval_idt, rspice_limexp, rspice_limited_exp, rspice_limited_exp_derivative};
use std::collections::HashMap;
use std::sync::{Arc, Mutex, OnceLock, Weak};
pub(super) const CANONICAL_MODEL_STAGE_SLOTS: [u32; 37] = [65, 66, 67, 2, 1, 0, 24, 26, 44, 5, 85, 6, 86, 87, 8, 10, 12, 13, 14, 15, 16, 92, 22, 93, 23, 94, 28, 29, 95, 30, 31, 96, 32, 33, 61, 62, 63];
pub(super) const CANONICAL_INSTANCE_STAGE_SLOTS: [u32; 43] = [72, 73, 74, 75, 25, 27, 76, 78, 79, 54, 77, 80, 36, 81, 3, 4, 7, 9, 90, 91, 11, 19, 18, 55, 56, 48, 97, 34, 35, 89, 104, 105, 57, 58, 106, 59, 107, 109, 110, 111, 112, 113, 114];
pub(super) const CANONICAL_TEMPERATURE_STAGE_SLOTS: [u32; 35] = [17, 68, 69, 70, 71, 45, 82, 39, 83, 84, 41, 43, 46, 21, 88, 20, 37, 38, 40, 42, 98, 47, 99, 49, 108, 100, 101, 102, 50, 51, 103, 52, 53, 60, 64];

pub(super) fn canonical_model_preprocess(
    parameters: &[f64],
    parameter_given: &[bool],
    multiplicity: f64,
    staged: &[f64],
    temperature: f64,
    thermal_voltage: f64,
) -> [f64; 37] {
		let J = parameters[63];
		let L = parameters[64];
		let N = 0f64;
		let U = parameters[71];
		let X = parameters[72];
		let AD = parameters[90];
		let AI = parameters[73];
		let AN = parameters[80];
	    let mut oM = 0.0;
	    let mut oO = false;
	    let mut oP = 0.0;
	    let mut oQ = false;
	    let mut oR = false;
	    let mut oS = 0.0;
	    let mut oAE = 0.0;
	    let mut oAG = 0.0;
	    let mut oAJ = 0.0;
	    let mut oAK = 0.0;
	    let mut oAL = 0.0;
	    let mut oAO = 0.0;
	    let mut oAP = 0.0;
	    let mut oAQ = 0.0;
	    let mut oAT = 0.0;
		let A = 1003f64 != parameters[20];
		let B = 1f64 != parameters[17];
		let C = 1f64 < parameters[18];
		let D = ((1f64 - (0.01f64 * parameters[23])) * parameters[22]) * 1e6f64;
		let E = D * D;
		let F = 273.15f64 + parameters[28];
		let G = parameters[35] + 1f64;
		let H = 0f64 * E;
		let I = 0f64 * E;
		let K = J > 1f64;
		if K {
			let M = 2f64 * L;
			oM = M;
		} else {
			let O = J > N;
			oO = O;
			if O {
				let P = 2f64 * L;
				oP = P;
			}
		}
		if K {
			let Q = J > 2f64;
			oQ = Q;
		} else {
			let R = J > N;
			oR = R;
			if R {
				let S = 2f64 * parameters[46];
				oS = S;
			}
		}
		let T = parameters[66] > N;
		let V = U * H;
		let W = U * I;
		let Y = X * H;
		let Z = X * I;
		let AA = -parameters[21];
		let AB = parameters[92] - 1f64;
		let AC = parameters[69] > N;
		if AC {
			let AE = -AD;
			oAE = AE;
		}
		let AF = parameters[76] > N;
		if AF {
			let AG = -AD;
			oAG = AG;
		}
		let AH = X > N;
		if AH {
			let AJ = 0.5f64 * AI;
			oAJ = AJ;
			let AK = -0.5f64 * AI;
			oAK = AK;
			let AL = parameters[74] - 1f64;
			oAL = AL;
		}
		let AM = parameters[79] > N;
		if AM {
			let AO = 0.5f64 * AN;
			oAO = AO;
			let AP = -0.5f64 * AN;
			oAP = AP;
			let AQ = parameters[81] - 1f64;
			oAQ = AQ;
		}
		let AR = parameters[83] > N;
		if AR {
			let AT = parameters[27] / parameters[84];
			oAT = AT;
		}
		let AS = parameters[60] > N;
    [A as u8 as f64, B as u8 as f64, C as u8 as f64, D, F, G, H, I, K as u8 as f64, oM, oO as u8 as f64, oP, oQ as u8 as f64, oR as u8 as f64, oS, T as u8 as f64, V, W, Y, Z, AA, AC as u8 as f64, oAE, AF as u8 as f64, oAG, AH as u8 as f64, oAJ, oAK, AM as u8 as f64, oAO, oAP, AR as u8 as f64, oAT, AS as u8 as f64, AB, oAL, oAQ]
}

pub(super) fn canonical_instance_preprocess(
    parameters: &[f64],
    parameter_given: &[bool],
    multiplicity: f64,
    staged: &[f64],
    temperature: f64,
    thermal_voltage: f64,
) -> [f64; 43] {
		let A = 1f64;
		let B = staged[2];
		let L = parameters[5];
		let M = 0f64;
		let O = parameters[8];
		let V = parameters[127];
		let Y = parameters[16];
		let Z = parameters[119];
		let AA = parameters[122];
		let AB = parameters[125];
		let AC = multiplicity;
		let AF = parameters[120];
		let AG = parameters[123];
		let AH = parameters[126];
		let AJ = parameters[118];
		let AK = parameters[121];
		let AL = parameters[124];
		let BG = parameters[53];
		let BM = parameters[15];
		let BP = staged[44] != 0.0;
		let BR = staged[86] != 0.0;
		let BS = staged[87] != 0.0;
		let BY = staged[10] != 0.0;
		let CA = parameters[67];
		let CB = parameters[66];
		let CN = parameters[78];
		let CQ = parameters[79];
		let CV = parameters[65];
		let DA = parameters[26];
		let DD = parameters[13];
		let DK = 0f64;
		let DL = 0f64;
		let DM = 0f64;
		let DN = 0f64;
	    let mut oAN = false;
	    let mut oAV = false;
	    let mut oAZ = false;
	    let mut oBU = 0.0;
	    let mut oBX = 0.0;
	    let mut oCI = 0.0;
	    let mut oCW = 0.0;
	    let mut oCX = 0.0;
	    let mut oDI = false;
	    let mut oDJ = false;
		let C = parameters[0] * B;
		let D = parameters[1] * B;
		let E = C < parameters[31];
		let F = C > parameters[32];
		let G = D < parameters[29];
		let H = D > parameters[30];
		let I = parameters[4] * B;
		let J = parameters[7] * B;
		let K = D * C;
		let N = L > M;
		let P = O > M;
		let Q = (N as u8 as f64) + (P as u8 as f64);
		let R = (2f64 * D) + (Q * C);
		let S = 0.5f64 * Q;
		let T = (((C + parameters[38]) + (parameters[39] / C)) + (parameters[42] * (A - (((-C) / parameters[41]).exp())))) / (A - ((parameters[40] * (parameters[2] * B)) / K));
		let U = D + (S * (parameters[43] + (parameters[44] / C)));
		let W;
		let X;
		if V != 0.0 {
			W = U;
			X = T;
		} else {
			W = D;
			X = C;
		}
		let AO;
		let AP;
		let AQ;
		if Y != 0.0 {
			let AD = AC * W;
			let AE = (T + (Z * AA)) + ((parameters[11] * AB) / (AD.sqrt()));
			let AI = (U + (AF * AG)) + ((parameters[12] * AH) / ((AC * X).sqrt()));
			let AM = (0.01f64 * ((AJ * AK) + ((parameters[10] * AL) / ((AD * X).sqrt())))).exp();
			AO = AE;
			AP = AI;
			AQ = AM;
		} else {
			let AN = (Z != M) && ((AB > M) || (AA > M));
			oAN = AN;
			let AU = if AN {
				let AS = AB / ((AC * W).sqrt());
				let AT = T + (Z * (((AA * AA) + (AS * AS)).sqrt()));
				AT
			} else {
				T
			};
			let AV = (AF != M) && ((AH > M) || (AG > M));
			oAV = AV;
			let AY = if AV {
				let AW = AH / ((AC * X).sqrt());
				let AX = U + (AF * (((AG * AG) + (AW * AW)).sqrt()));
				AX
			} else {
				U
			};
			let AZ = (AJ != M) && ((AL > M) || (AK > M));
			oAZ = AZ;
			let BC = if AZ {
				let BA = AL / (((AC * W) * X).sqrt());
				let BB = ((0.01f64 * AJ) * (((AK * AK) + (BA * BA)).sqrt())).exp();
				BB
			} else {
				A
			};
			AO = AU;
			AP = AY;
			AQ = BC;
		}
		let AR = AO <= M;
		let BD = AP <= M;
		let BE = AP + parameters[45];
		let BF = BE <= M;
		let BH;
		let BI;
		if BG != 0.0 {
			BH = AO;
			BI = AP;
		} else {
			BH = C;
			BI = D;
		}
		let BJ = A / (BH.powf(parameters[56]));
		let BK = A / (BI.powf(parameters[58]));
		let BL = ((parameters[54] * (A + (parameters[55] * BJ))) * (A + (parameters[57] * BK))) * (A + ((parameters[59] * BJ) * BK));
		let BO = if BM != 0.0 {
			M
		} else {
			let BN = parameters[49] + ((((parameters[50] * BI) + (parameters[51] * BH)) + parameters[52]) / (BI * BH));
			BN
		};
		let BQ = parameters[47] / (A + (parameters[48] / AP));
		if BP {
			if BR {
				let BU = -BQ;
				oBU = BU;
			}
		} else {
			let BX = if BS {
				let BV = (4f64 * BQ) * BQ;
				BV
			} else {
				let BW = (4f64 * BQ) * BQ;
				BW
			};
			oBX = BX;
		}
		let BT = (parameters[37] * AQ) * (AP / AO);
		let BZ = BY && N;
		let CD = if BZ {
			let CC = (CB + (CA / C)) / L;
			CC
		} else {
			M
		};
		let CE = BY && P;
		let CG = if CE {
			let CF = (CB + (CA / C)) / O;
			CF
		} else {
			M
		};
		let CK = if BM != 0.0 {
			M
		} else {
			let CH = L + O;
			let CI = ((parameters[110] + (parameters[111] * R)) + (parameters[112] * K)) + (parameters[113] * CH);
			oCI = CI;
			let CJ = ((parameters[114] + (parameters[115] * R)) + (parameters[116] * K)) + (parameters[117] * CH);
			CJ
		};
		let CL = (parameters[93] + (parameters[97] / AO)) + ((S * (parameters[95] + (parameters[99] / AO))) / AP);
		let CM = (parameters[94] + (parameters[98] / AO)) + ((S * (parameters[96] + (parameters[100] / AO))) / AP);
		let CO = staged[12] + (CN * I);
		let CP = staged[13] + (CN * J);
		let CR = staged[14] + (CQ * I);
		let CS = staged[15] + (CQ * J);
		let CT = !(BM != 0.0);
		let CU = (staged[33] != 0.0) && CT;
		if CU {
			let CW = (4f64 * CV) * CV;
			oCW = CW;
			let CX = 2f64 * CV;
			oCX = CX;
		}
		let CY = CR > M;
		let CZ = CS > M;
		let DB = (CD / AC) <= DA;
		let DC = (CG / AC) <= DA;
		let DE;
		let DF;
		let DG;
		let DH;
		if DD != 0.0 {
			let DI = CD > M;
			oDI = DI;
			let DJ = CG > M;
			oDJ = DJ;
			DE = DK;
			DF = DL;
			DG = DM;
			DH = DN;
		} else {
			DE = M;
			DF = M;
			DG = M;
			DH = M;
		}
    [E as u8 as f64, F as u8 as f64, G as u8 as f64, H as u8 as f64, I, J, oAN as u8 as f64, oAV as u8 as f64, oAZ as u8 as f64, AO, AR as u8 as f64, BD as u8 as f64, BE, BF as u8 as f64, BL, BO, oBU, BT, BZ as u8 as f64, CE as u8 as f64, oCI, CL, CM, CO, CP, CT as u8 as f64, CU as u8 as f64, oCW, oCX, oBX, CY as u8 as f64, CZ as u8 as f64, CK, CD, DB as u8 as f64, CG, DC as u8 as f64, oDI as u8 as f64, oDJ as u8 as f64, DE, DF, DG, DH]
}

pub(super) fn canonical_temperature_preprocess(
    parameters: &[f64],
    parameter_given: &[bool],
    multiplicity: f64,
    staged: &[f64],
    temperature: f64,
    thermal_voltage: f64,
) -> [f64; 35] {
		let A = 1f64;
		let C = 273.15f64;
		let H = parameters[35];
		let J = parameters[36];
		let O = staged[1];
		let U = 0.1f64;
		let Z = parameters[15];
		let AA = staged[4];
		let AC = 0f64;
		let AJ = staged[44] != 0.0;
		let AO = staged[85] != 0.0;
		let AT = parameters[46];
		let AV = staged[86] != 0.0;
		let AW = staged[87] != 0.0;
		let BI = staged[89];
		let BJ = parameters[109];
		let BM = parameters[63];
	    let mut oK = false;
	    let mut oAD = false;
	    let mut oBN = 0.0;
	    let mut oBO = 0.0;
	    let mut oBQ = false;
	    let mut oBT = false;
	    let mut oBV = false;
	    let mut oBX = 0.0;
	    let mut oBY = 0.0;
	    let mut oBZ = false;
	    let mut oCC = 0.0;
	    let mut oCD = 0.0;
	    let mut oCE = 0.0;
		let B = temperature + parameters[9];
		let D = B - C;
		let E = D < parameters[24];
		let F = D > parameters[25];
		let G = D < staged[0];
		let L;
		if G {
			let I = H + (((D - H) - A).exp());
			L = I;
		} else {
			let K = D > (J - A);
			oK = K;
			let S = if K {
				let R = J - (((J - D) - A).exp());
				R
			} else {
				D
			};
			L = S;
		}
		let M = L + C;
		let N = (1.3806505e-23f64 * M) / 1.60217653e-19f64;
		let P = M / O;
		let Q = M - O;
		let T = staged[3] * (A + (Q * (parameters[103] + (Q * parameters[104]))));
		let V = T > U;
		let W = if V {
			T
		} else {
			U
		};
		let X = W.sqrt();
		let Y = X / (W + 1e4f64);
		let AB = AA < Y;
		let AF;
		let AG;
		if AB {
			let AD = AA > AC;
			oAD = AD;
			let AK = if AD {
				AA
			} else {
				AC
			};
			let AL = Y * Y;
			AF = AL;
			AG = AK;
		} else {
			let AE = AA * AA;
			AF = AE;
			AG = AA;
		}
		let AH = W * 0.5f64;
		let AI = (0.5f64 / AF) - AH;
		let AP;
		let AQ;
		if AJ {
			let AM = AI - (staged[5] / AF);
			let AN = (0.1666666666666667f64 / AF) - AH;
			AP = AM;
			AQ = AN;
		} else {
			let AS = if AO {
				let AR = AI - ((staged[6] / AF).sqrt());
				AR
			} else {
				AI
			};
			AP = AS;
			AQ = AC;
		}
		let AX;
		let AY;
		if AJ {
			let AU = AT * N;
			let BE = if AV {
				let BC = (0.55f64 * N) * (A + ((staged[7] / N).exp()));
				BC
			} else {
				let BD = 1.1f64 * N;
				BD
			};
			AX = AU;
			AY = BE;
		} else {
			let BH = if AW {
				let BF = staged[8] * N;
				BF
			} else {
				let BG = AT * N;
				BG
			};
			AX = BH;
			AY = BI;
		}
		let AZ = A - (AG * X);
		let BA = staged[9] * AZ;
		let BB = BA <= 1e-99f64;
		let BL = if Z != 0.0 {
			AC
		} else {
			let BK = staged[11] * (P.powf(BJ));
			BK
		};
		if BM != 0.0 {
			let BN = BA * AZ;
			oBN = BN;
		}
		if BM == 0.0 {
			let BO = -0.4f64 * W;
			oBO = BO;
		}
		let BP = AJ && (AG > 1e-9f64);
		if BP {
			let BQ = BM > 2f64;
			oBQ = BQ;
		}
		let BR = BL > AC;
		let BS = (BR && parameters[14] != 0.0) && (staged[48] != 0.0);
		if BS {
			let BT = BJ == AC;
			oBT = BT;
			if !BT {
				let BW;
				if G {
					let BU = H + (((D - H) - A).exp());
					BW = BU;
				} else {
					let BV = D > (J - A);
					oBV = BV;
					let CB = if BV {
						let CA = J - (((J - D) - A).exp());
						CA
					} else {
						D
					};
					BW = CB;
				}
				let BX = BW + C;
				oBX = BX;
				let BY = BJ + A;
				oBY = BY;
				let BZ = (BY.abs()) > U;
				oBZ = BZ;
				if BZ {
					let CC = BL * BX;
					oCC = CC;
					let CD = BY - 1f64;
					oCD = CD;
				} else {
					let CE = 0.5f64 * BJ;
					oCE = CE;
				}
			}
		}
		let CG = if BR {
			let CF = A / BL;
			CF
		} else {
			AC
		};
    [B, E as u8 as f64, F as u8 as f64, G as u8 as f64, oK as u8 as f64, N, V as u8 as f64, W, AB as u8 as f64, oAD as u8 as f64, AF, AI, AG, BA, BB as u8 as f64, oBN, AP, AX, oBO, AQ, BP as u8 as f64, AY, oBQ as u8 as f64, BL, BR as u8 as f64, BS as u8 as f64, oBT as u8 as f64, oBV as u8 as f64, oBX, oBY, oBZ as u8 as f64, oCC, oCE, CG, oCD]
}


static CANONICAL_MODEL_CACHE: OnceLock<Mutex<HashMap<Box<[u64]>, Weak<CanonicalModelValues>>>> = OnceLock::new();

fn canonical_model_cache() -> &'static Mutex<HashMap<Box<[u64]>, Weak<CanonicalModelValues>>> {
    CANONICAL_MODEL_CACHE.get_or_init(|| Mutex::new(HashMap::new()))
}

fn canonical_model_cache_lookup(key: &[u64]) -> Option<Arc<CanonicalModelValues>> {
    let mut cache = canonical_model_cache()
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner());
    let found = cache.get(key).and_then(Weak::upgrade);
    if found.is_none() {
        cache.remove(key);
    }
    found
}

fn canonical_model_cache_intern(
    key: Box<[u64]>,
    candidate: Arc<CanonicalModelValues>,
) -> Arc<CanonicalModelValues> {
    let mut cache = canonical_model_cache()
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner());
    if let Some(existing) = cache.get(key.as_ref()).and_then(Weak::upgrade) {
        return existing;
    }
    cache.retain(|_, values| values.strong_count() > 0);
    cache.insert(key, Arc::downgrade(&candidate));
    candidate
}

impl Instance {
    fn canonical_model_key(&self) -> Box<[u64]> {
        let mut key = Vec::with_capacity(222);
        for index in 0..Self::PARAMETER_COUNT {
            if PARAMETER_MODEL_FLAGS[index] {
                key.push(self.params.values[index].to_bits());
                key.push(u64::from(self.param_given[index]));
            }
        }
        key.into_boxed_slice()
    }

    fn canonical_install_model_values(&mut self, values: Arc<CanonicalModelValues>) {
        install_generated_stage_values(&mut self.canonical_staged[..], values.as_ref(), &CANONICAL_MODEL_STAGE_SLOTS);
        self.canonical_model_values = Some(values);
    }

    fn canonical_model_stage(&mut self, ctx: &GeneratedEvalContext<'_>) {
        if self.canonical_model_values.is_some() {
            return;
        }
        let key = self.canonical_model_key();
        if let Some(values) = canonical_model_cache_lookup(key.as_ref()) {
            self.canonical_install_model_values(values);
            return;
        }
        let produced: CanonicalModelValues = canonical_model_preprocess(
            &self.params.values,
            &self.param_given[..],
            self.multiplicity,
            &self.canonical_staged[..],
            ctx.temperature(),
            ctx.thermal_voltage(),
        );
        let values = canonical_model_cache_intern(key, Arc::new(produced));
        self.canonical_install_model_values(values);
    }

    fn canonical_instance_stage(&mut self, ctx: &GeneratedEvalContext<'_>) {
        if self.canonical_instance_valid {
            return;
        }
        let produced = canonical_instance_preprocess(
            &self.params.values,
            &self.param_given[..],
            self.multiplicity,
            &self.canonical_staged[..],
            ctx.temperature(),
            ctx.thermal_voltage(),
        );
        install_generated_stage_values(&mut self.canonical_staged[..], &produced, &CANONICAL_INSTANCE_STAGE_SLOTS);
        self.canonical_instance_valid = true;
    }

    fn canonical_temperature_stage(&mut self, ctx: &GeneratedEvalContext<'_>) {
        let temperature = ctx.temperature();
        let thermal_voltage = ctx.thermal_voltage();
        if self.canonical_temperature_valid
            && self.canonical_temperature == temperature
            && self.canonical_thermal_voltage == thermal_voltage
        {
            return;
        }
        let produced = canonical_temperature_preprocess(
            &self.params.values,
            &self.param_given[..],
            self.multiplicity,
            &self.canonical_staged[..],
            ctx.temperature(),
            ctx.thermal_voltage(),
        );
        install_generated_stage_values(&mut self.canonical_staged[..], &produced, &CANONICAL_TEMPERATURE_STAGE_SLOTS);
        self.canonical_temperature = temperature;
        self.canonical_thermal_voltage = thermal_voltage;
        self.canonical_temperature_valid = true;
    }

    fn canonical_timestep_stage(&mut self, ctx: &GeneratedEvalContext<'_>) {
        let produced: [f64; 1] = {
            let multiplicity = self.multiplicity;
            let staged = &*self.canonical_staged;
            [0.0]
        };
    }

    pub fn stamp(&mut self, ctx: &GeneratedEvalContext<'_>, stamper: &mut GeneratedStamper<'_>) {
        self.canonical_model_stage(ctx);
        self.canonical_instance_stage(ctx);
        self.canonical_temperature_stage(ctx);
        self.canonical_timestep_stage(ctx);
        let parameters = &self.params.values;
        let multiplicity = self.multiplicity;
        let staged = &*self.canonical_staged;
        let node_potentials = [ctx.node_voltage(self.nodes[0]), ctx.node_voltage(self.nodes[1]), ctx.node_voltage(self.nodes[2]), ctx.node_voltage(self.nodes[3]), ctx.node_voltage(self.nodes[4]), ctx.node_voltage(self.nodes[5])];
        let branch_unknown_flows = [ctx.branch_current(self.branches[0]), ctx.branch_current(self.branches[1])];
        let ddt_scale_value = self.ddt_coefficients.derivative_scale;
        let ddt_scale = move || ddt_scale_value;
        let ddt_state = self.stamp_state.as_mut();
        let ddt_active = self.ddt_coefficients.active;
        let ddt_coefficients = self.ddt_coefficients;
        let mut ddt = |slot: usize, value: f64| -> f64 {
            rspice_eval_ddt(
                &mut ddt_state.ddt_current,
                &mut ddt_state.ddt_previous,
                &mut ddt_state.ddt_older,
                &mut ddt_state.ddt_initialized,
                &mut ddt_state.ddt_derivative_current,
                &mut ddt_state.ddt_derivative_previous,
                ddt_active,
                ddt_coefficients.derivative_scale,
                ddt_coefficients.previous_value_scale,
                ddt_coefficients.older_value_scale,
                ddt_coefficients.previous_derivative_scale,
                slot,
                value,
            )
        };
			let A = 0f64;
			let C = 1f64;
			let D = node_potentials[5];
			let E = node_potentials[4];
			let F = staged[16];
			let I = node_potentials[1];
			let N = node_potentials[3];
			let Q = parameters[35];
			let S = 1f64;
			let V = parameters[36];
			let AA = 1.3806505e-23f64;
			let AB = 1.60217653e-19f64;
			let AE = staged[1];
			let AI = staged[18];
			let AN = -1f64;
			let AT = 0.01f64;
			let AV = 0.1f64;
			let BA = parameters[63];
			let BB = staged[20];
			let BF = staged[21];
			let BL = parameters[102];
			let BV = parameters[92];
			let BY = staged[92] != 0.0;
			let BZ = staged[22];
			let CB = 1f64;
			let CC = parameters[91];
			let CD = parameters[70];
			let CF = parameters[69];
			let CJ = parameters[27];
			let CP = 0f64;
			let CU = staged[93] != 0.0;
			let CV = staged[23];
			let CX = parameters[77];
			let CZ = parameters[76];
			let DM = staged[24];
			let DP = staged[25];
			let DT = staged[26];
			let DW = staged[27];
			let EA = staged[94] != 0.0;
			let EC = 2f64;
			let EE = staged[28];
			let EH = staged[29];
			let EO = 3f64;
			let ER = parameters[90];
			let EX = 4f64;
			let EZ = 2f64;
			let FA = 0.5f64;
			let FG = parameters[73];
			let FI = parameters[74];
			let FJ = parameters[72];
			let FQ = staged[95] != 0.0;
			let FT = staged[30];
			let FW = staged[31];
			let GQ = parameters[80];
			let GS = parameters[81];
			let GT = parameters[79];
			let HA = staged[96] != 0.0;
			let HB = parameters[106];
			let HD = parameters[83];
			let HH = parameters[85];
			let HO = staged[97] != 0.0;
			let HR = parameters[107];
			let IC = parameters[62];
			let ID = 1e3f64;
			let IO = staged[36];
			let IR = 1e5f64;
			let IT = parameters[61];
			let IX = parameters[60];
			let JG = staged[34];
			let JJ = staged[35];
			let JM = parameters[65];
			let KH = -1f64;
			let KQ = staged[37];
			let KS = staged[38];
			let LK = staged[39];
			let LX = L3([0f64; 3]);
			let MA = staged[41];
			let NF = 0.3333333333333333f64;
			let NP = 0.25f64;
			let NX = staged[98] != 0.0;
			let OU = 1e4f64;
			let QI = staged[43];
			let RH = staged[46];
			let RP = staged[47];
			let SD = parameters[64];
			let TV = parameters[47];
			let UV = staged[99] != 0.0;
			let WA = L4([0f64; 4]);
			let XF = L3([0f64; 3]);
			let ZV = parameters[84];
			let AAB = L3([0f64; 3]);
			let AAM = branch_unknown_flows[0];
			let AAS = branch_unknown_flows[1];
			let AAX = staged[100] != 0.0;
			let ADQ = staged[101] != 0.0;
			let ADT = L8([0f64; 8]);
			let AEE = staged[49];
			let AEJ = staged[103] != 0.0;
			let AEK = staged[50];
			let AEM = staged[51];
			let AEN = staged[52];
			let AER = staged[53];
			let AEX = staged[104] != 0.0;
			let AFA = staged[105] != 0.0;
			let AFP = parameters[68];
			let AFS = parameters[75];
			let AIF = parameters[82];
			let AKR = staged[55];
			let AKT = staged[56];
			let AKZ = staged[57];
			let ALC = staged[106] != 0.0;
			let AQO = staged[58];
			let AQS = L3([0f64; 3]);
			let AQW = L2([0f64; 2]);
			let ARB = staged[107] != 0.0;
			let ARC = staged[59];
			let ARG = L3([0f64; 3]);
			let ARK = L2([0f64; 2]);
			let ARQ = ddt_scale();
			let ARW = parameters[13];
			let ARZ = 0f64;
			let ASB = 0f64;
			let B = ctx.simparam_or("gmin", A);
			let G = F * (D - E);
			let H = (L2([0.0, 1f64]) - L2([1f64, 0.0])) * F;
			let J = F * (I - E);
			let K = (L2([1f64, 0.0]) - L2([0.0, 1f64])) * F;
			let L = F * (I - D);
			let M = (L2([1f64, 0.0]) - L2([0.0, 1f64])) * F;
			let O = (staged[17] + N) - 273.15f64;
			let P = O < staged[0];
			let X;
			let Y;
			if P {
				let R = ((O - Q) - C).exp();
				let T = S * R;
				let U = Q + R;
				X = U;
				Y = T;
			} else {
				let W = O > (V - C);
				let AR;
				let AS;
				if W {
					let AO = ((V - O) - C).exp();
					let AP = V - AO;
					let AQ = ((S * AN) * AO) * AN;
					AR = AP;
					AS = AQ;
				} else {
					AR = O;
					AS = S;
				}
				X = AR;
				Y = AS;
			}
			let Z = X + 273.15f64;
			let AC = (AA * Z) / AB;
			let AD = (Y * AA) / AB;
			let AF = Z / AE;
			let AG = Y / AE;
			let AH = Z - AE;
			let AJ = staged[19] + (AH * AI);
			let AK = (Y * AJ) + ((Y * AI) * AH);
			let AL = C + (AH * AJ);
			let AM = AL < 0.11f64;
			let AY;
			let AZ;
			if AM {
				let AU = ((10f64 * (AL - AT)) - C).exp();
				let AW = ((AK * 10f64) * AU) * AV;
				let AX = AT + (AV * AU);
				AY = AX;
				AZ = AW;
			} else {
				AY = AL;
				AZ = AK;
			}
			let BJ;
			let BK;
			if BA != 0.0 {
				let BC = BB * AY;
				let BD = C / BC;
				let BE = (((AZ * BB) * BD) * AN) / BC;
				BJ = BD;
				BK = BE;
			} else {
				let BG = BF * AY;
				let BH = C / BG;
				let BI = (((AZ * BF) * BH) * AN) / BG;
				BJ = BH;
				BK = BI;
			}
			let BM = parameters[101] + (AH * BL);
			let BN = (Y * BM) + ((Y * BL) * AH);
			let BO = C + (AH * BM);
			let BP = BO < 0.11f64;
			let BT;
			let BU;
			if BP {
				let BQ = ((10f64 * (BO - AT)) - C).exp();
				let BR = ((BN * 10f64) * BQ) * AV;
				let BS = AT + (AV * BQ);
				BT = BS;
				BU = BR;
			} else {
				BT = BO;
				BU = BN;
			}
			let BW = AF.powf(BV);
			let BX = AG * (BV * (AF.powf(staged[61])));
			let CQ;
			let CR;
			let CS;
			let CT;
			if BY {
				let CA = (BZ * (C - AF)) / AC;
				let CE = ((CA + (CC * (AF.ln()))) / CD).exp();
				let CG = CF * CE;
				let CH = (((((((AG * AN) * BZ) - (AD * CA)) / AC) + ((AG * (CB / AF)) * CC)) / CD) * CE) * CF;
				let CI = CD * AC;
				let CK = CJ / CG;
				let CL = C + CK;
				let CM = CL.ln();
				let CN = CI * CM;
				let CO = ((AD * CD) * CM) + (((((CH * CK) * AN) / CG) * (CB / CL)) * CI);
				CQ = CG;
				CR = CN;
				CS = CH;
				CT = CO;
			} else {
				CQ = A;
				CR = A;
				CS = CP;
				CT = CP;
			}
			let DI;
			let DJ;
			let DK;
			let DL;
			if CU {
				let CW = (CV * (C - AF)) / AC;
				let CY = ((CW + (CC * (AF.ln()))) / CX).exp();
				let DA = CZ * CY;
				let DB = (((((((AG * AN) * CV) - (AD * CW)) / AC) + ((AG * (CB / AF)) * CC)) / CX) * CY) * CZ;
				let DC = CX * AC;
				let DD = CJ / DA;
				let DE = C + DD;
				let DF = DE.ln();
				let DG = DC * DF;
				let DH = ((AD * CX) * DF) + (((((DB * DD) * AN) / DA) * (CB / DE)) * DC);
				DI = DA;
				DJ = DG;
				DK = DB;
				DL = DH;
			} else {
				DI = A;
				DJ = A;
				DK = CP;
				DL = CP;
			}
			let DN = DM * CQ;
			let DO = CS * DM;
			let DQ = DP * DI;
			let DR = DK * DP;
			let DS = DN + DQ;
			let DU = DT * CQ;
			let DV = CS * DT;
			let DX = DW * DI;
			let DY = DK * DW;
			let DZ = DU + DX;
			let FM;
			let FN;
			let FO;
			let FP;
			if EA {
				let EB = AC / AF;
				let ED = EC * EB;
				let EF = (EE * AF) / AC;
				let EG = EF.exp();
				let EI = (EH * AF) / AC;
				let EJ = EI.exp();
				let EK = EG - EJ;
				let EL = EK.ln();
				let EM = ED * EL;
				let EN = ((((AD - (AG * EB)) / AF) * EC) * EL) + (((((((AG * EE) - (AD * EF)) / AC) * EG) - ((((AG * EH) - (AD * EI)) / AC) * EJ)) * (CB / EK)) * ED);
				let EP = EO * AC;
				let EQ = AF.ln();
				let ES = ((EM * AF) - (EP * EQ)) - (ER * (AF - C));
				let ET = (((EN * AF) + (AG * EM)) - (((AD * EO) * EQ) + ((AG * (CB / AF)) * EP))) - (AG * ER);
				let EU = EC * AC;
				let EV = (-ES) / AC;
				let EW = EV.exp();
				let EY = (C + (EX * EW)).sqrt();
				let FB = FA * (C + EY);
				let FC = FB.ln();
				let FD = ((AD * EC) * FC) + (((((((((ET * AN) - (AD * EV)) / AC) * EW) * EX) * (CB / (EZ * EY))) * FA) * (CB / FB)) * EU);
				let FE = ES + (EU * FC);
				let FF = ET + FD;
				let FH = FG / FE;
				let FK = FJ * (FH.powf(FI));
				let FL = ((((FF * FH) * AN) / FE) * (FI * (FH.powf(staged[62])))) * FJ;
				FM = FK;
				FN = FE;
				FO = FL;
				FP = FF;
			} else {
				FM = A;
				FN = FG;
				FO = CP;
				FP = CP;
			}
			let GW;
			let GX;
			let GY;
			let GZ;
			if FQ {
				let FR = AC / AF;
				let FS = EC * FR;
				let FU = (FT * AF) / AC;
				let FV = FU.exp();
				let FX = (FW * AF) / AC;
				let FY = FX.exp();
				let FZ = FV - FY;
				let GA = FZ.ln();
				let GB = FS * GA;
				let GC = ((((AD - (AG * FR)) / AF) * EC) * GA) + (((((((AG * FT) - (AD * FU)) / AC) * FV) - ((((AG * FW) - (AD * FX)) / AC) * FY)) * (CB / FZ)) * FS);
				let GD = EO * AC;
				let GE = AF.ln();
				let GF = ((GB * AF) - (GD * GE)) - (ER * (AF - C));
				let GG = (((GC * AF) + (AG * GB)) - (((AD * EO) * GE) + ((AG * (CB / AF)) * GD))) - (AG * ER);
				let GH = EC * AC;
				let GI = (-GF) / AC;
				let GJ = GI.exp();
				let GK = (C + (EX * GJ)).sqrt();
				let GL = FA * (C + GK);
				let GM = GL.ln();
				let GN = ((AD * EC) * GM) + (((((((((GG * AN) - (AD * GI)) / AC) * GJ) * EX) * (CB / (EZ * GK))) * FA) * (CB / GL)) * GH);
				let GO = GF + (GH * GM);
				let GP = GG + GN;
				let GR = GQ / GO;
				let GU = GT * (GR.powf(GS));
				let GV = ((((GP * GR) * AN) / GO) * (GS * (GR.powf(staged[63])))) * GT;
				GW = GU;
				GX = GO;
				GY = GV;
				GZ = GP;
			} else {
				GW = A;
				GX = GQ;
				GY = CP;
				GZ = CP;
			}
			let HI;
			let HJ;
			let HK;
			let HL;
			let HM;
			let HN;
			if HA {
				let HC = parameters[105] + (AH * HB);
				let HE = HD * (C + (AH * HC));
				let HF = ((Y * HC) + ((Y * HB) * AH)) * HD;
				let HG = HE > A;
				let HP;
				let HQ;
				if HG {
					HP = HE;
					HQ = HF;
				} else {
					HP = A;
					HQ = CP;
				}
				let HS = HH * (C + (HR * AH));
				let HT = (Y * HR) * HH;
				let HU = HS * AC;
				let HV = (HT * AC) + (AD * HS);
				let HW = (-HP) / HU;
				let HX = HW.exp();
				let HY = HX + staged[32];
				let HZ = HY.ln();
				let IA = HU * HZ;
				let IB = (HV * HZ) + ((((((HQ * AN) - (HV * HW)) / HU) * HX) * (CB / HY)) * HU);
				HI = HP;
				HJ = HS;
				HK = IA;
				HL = HQ;
				HM = HT;
				HN = IB;
			} else {
				HI = HD;
				HJ = HH;
				HK = C;
				HL = CP;
				HM = CP;
				HN = CP;
			}
			let IE;
			let IF;
			let IG;
			let IH;
			let II;
			let IJ;
			let IK;
			let IL;
			let IM;
			let IN;
			if HO {
				let JB;
				let JC;
				let JD;
				let JE;
				if IC != 0.0 {
					let IU = IT * BW;
					let IV = IU * AY;
					let IW = ((BX * IT) * AY) + (AZ * IU);
					let IY = IX * BW;
					let IZ = IY * AY;
					let JA = ((BX * IX) * AY) + (AZ * IY);
					JB = IV;
					JC = IZ;
					JD = IW;
					JE = JA;
				} else {
					JB = IT;
					JC = IX;
					JD = CP;
					JE = CP;
				}
				let JF = JD * JB;
				let JH = JG * JC;
				let JI = ((JB * JB) + (JH * JC)).sqrt();
				let JK = JI - (JJ * JC);
				let JL = (((JF + JF) + (((JE * JG) * JC) + (JE * JH))) * (CB / (EZ * JI))) - (JE * JJ);
				let JN = (JM * JK) / JC;
				let JO = ((JL * JM) - (JE * JN)) / JC;
				let JP = JL * JK;
				let JQ = JC * JC;
				let JR = JE * JC;
				let JS = (JK * JK) / JQ;
				let JT = (JS + (EX * JN)).sqrt();
				let JU = ((((JP + JP) - ((JR + JR) * JS)) / JQ) + (JO * EX)) * (CB / (EZ * JT));
				let JV = JC - JB;
				let JW = JE - JD;
				let JX = C / JC;
				let JY = ((JE * JX) * AN) / JC;
				IE = JV;
				IF = JX;
				IG = JK;
				IH = JN;
				II = JT;
				IJ = JW;
				IK = JY;
				IL = JL;
				IM = JO;
				IN = JU;
			} else {
				IE = ID;
				IF = A;
				IG = A;
				IH = A;
				II = A;
				IJ = CP;
				IK = CP;
				IL = CP;
				IM = CP;
				IN = CP;
			}
			let IP = IO * IE;
			let IQ = IJ * IO;
			let IS = IP > IR;
			let JZ;
			let KA;
			if IS {
				JZ = IR;
				KA = CP;
			} else {
				JZ = IP;
				KA = IQ;
			}
			let KB = G < A;
			let KL;
			let KM;
			let KN;
			let KO;
			let KP;
			if KB {
				let KC = -L;
				let KD = M * AN;
				let KE = -G;
				let KF = H * AN;
				let KG = L3([KD[0], 0.0, KD[1]]);
				KL = KC;
				KM = KE;
				KN = KH;
				KO = KG;
				KP = KF;
			} else {
				let KI = -J;
				let KJ = K * AN;
				let KK = L3([KJ[0], KJ[1], 0.0]);
				KL = KI;
				KM = G;
				KN = C;
				KO = KK;
				KP = H;
			}
			let KR = KL > KQ;
			let LB;
			let LC;
			if KR {
				let KT = ((KQ - KL) / KS).exp();
				let KU = C + KT;
				let KV = KQ - (KS * (KU.ln()));
				let KW = (((((KO * AN) / KS) * KT) * (CB / KU)) * KS) * AN;
				LB = KV;
				LC = KW;
			} else {
				let KX = ((KL - KQ) / KS).exp();
				let KY = C + KX;
				let KZ = KL - (KS * (KY.ln()));
				let LA = KO - ((((KO / KS) * KX) * (CB / KY)) * KS);
				LB = KZ;
				LC = LA;
			}
			let LH;
			let LI;
			if BA != 0.0 {
				let LD = KQ - LB;
				let LE = LC * AN;
				let LF = KM < LD;
				let LN = if LF {
					KM
				} else {
					LD
				};
				let LO = LB < (-0.4f64 * (LK + LN));
				let LP;
				let LQ;
				if LO {
					let LS;
					let LT;
					if LF {
						let LR = L3([0.0, KP[0], KP[1]]);
						LS = KM;
						LT = LR;
					} else {
						LS = LD;
						LT = LE;
					}
					let LU = -0.4f64 * (LK + LS);
					let LV = LT * -0.4f64;
					LP = LU;
					LQ = LV;
				} else {
					LP = LB;
					LQ = LC;
				}
				LH = LP;
				LI = LQ;
			} else {
				let LG = LB < staged[40];
				let LY;
				let LZ;
				if LG {
					let LW = -0.4f64 * LK;
					LY = LW;
					LZ = LX;
				} else {
					LY = LB;
					LZ = LC;
				}
				LH = LY;
				LI = LZ;
			}
			let LJ = LI * EC;
			let LL = LK + (EC * LH);
			let LM = IF > A;
			let NV;
			let NW;
			if LM {
				let MB = MA * LL;
				let MC = (MB * LL) - LL;
				let MD = EO * MA;
				let ME = -1f64 + (MD * LL);
				let MF = LL / JZ;
				let MG = MA * (2.25f64 + MF);
				let MH = (1.5f64 * MA) / JZ;
				let MI = EX * JZ;
				let MJ = (MI * JZ) / MA;
				let MK = (((KA * EX) * JZ) + (KA * MI)) / MA;
				let ML = MC * MJ;
				let MM = ((((LJ * MA) * LL) + (LJ * MB)) - LJ) * MJ;
				let MN = L4([MM[0], 0.0, MM[1], MM[2]]) + L4([0.0, (MK * MC), 0.0, 0.0]);
				let MO = ME * MJ;
				let MP = (LJ * MD) * MJ;
				let MQ = L4([MP[0], 0.0, MP[1], MP[2]]) + L4([0.0, (MK * ME), 0.0, 0.0]);
				let MR = MG * MJ;
				let MS = ((((L4([LJ[0], 0.0, LJ[1], LJ[2]]) - L4([0.0, (KA * MF), 0.0, 0.0])) / JZ) * MA) * MJ) + L4([0.0, (MK * MG), 0.0, 0.0]);
				let MT = MH * MJ;
				let MU = ((((KA * MH) * AN) / JZ) * MJ) + (MK * MH);
				let MV = MT * MT;
				let MW = MU * MT;
				let MX = MW + MW;
				let MY = -MR;
				let MZ = MS * AN;
				let NA = (MT * MO) - (EX * ML);
				let NB = (L4([0.0, (MU * MO), 0.0, 0.0]) + (MQ * MT)) - (MN * EX);
				let NC = EX * MR;
				let ND = MQ * MO;
				let NE = MZ * MY;
				let NG = NA - ((MY * MY) * NF);
				let NH = NB - ((NE + NE) * NF);
				let NI = NA + (EC * NG);
				let NJ = (((NC * ML) - (MO * MO)) - (ML * MV)) - ((MY * NI) / 9f64);
				let NK = (((((MS * EX) * ML) + (MN * NC)) - (ND + ND)) - ((MN * MV) + L4([0.0, (MX * ML), 0.0, 0.0]))) - (((MZ * NI) + ((NB + (NH * EC)) * MY)) / 9f64);
				let NL = NG * NG;
				let NM = NH * NG;
				let NN = (NL * NG) / 27f64;
				let NO = (((NM + NM) * NG) + (NH * NL)) / 27f64;
				let NQ = NP * NJ;
				let NR = ((NQ * NJ) + NN).sqrt();
				let NS = ((((NK * NP) * NJ) + (NK * NQ)) + NO) * (CB / (EZ * NR));
				let NT = NJ < A;
				let OG;
				let OH;
				let OI;
				let OJ;
				if NT {
					let NY = (-0.5f64 * NJ) + NR;
					let NZ = (NK * -0.5f64) + NS;
					let OA = (-NN) / NY;
					let OB = ((NO * AN) - (NZ * OA)) / NY;
					OG = NY;
					OH = OA;
					OI = NZ;
					OJ = OB;
				} else {
					let OC = (-0.5f64 * NJ) - NR;
					let OD = (NK * -0.5f64) - NS;
					let OE = (-NN) / OC;
					let OF = ((NO * AN) - (OD * OE)) / OC;
					OG = OE;
					OH = OC;
					OI = OF;
					OJ = OD;
				}
				let OK = OG > 1e-6f64;
				let OO;
				let OP;
				if OK {
					let OL = OG.powf(NF);
					let OM = OI * (NF * (OG.powf(-0.6666666666666667f64)));
					OO = OL;
					OP = OM;
				} else {
					let ON = OG < -1e-6f64;
					let OX;
					let OY;
					if ON {
						let OR = -OG;
						let OS = -(OR.powf(NF));
						let OT = ((OI * AN) * (NF * (OR.powf(-0.6666666666666667f64)))) * AN;
						OX = OS;
						OY = OT;
					} else {
						let OV = OU * OG;
						let OW = OI * OU;
						OX = OV;
						OY = OW;
					}
					OO = OX;
					OP = OY;
				}
				let OQ = OH > 1e-6f64;
				let PC;
				let PD;
				if OQ {
					let OZ = OH.powf(NF);
					let PA = OJ * (NF * (OH.powf(-0.6666666666666667f64)));
					PC = OZ;
					PD = PA;
				} else {
					let PB = OH < -1e-6f64;
					let PV;
					let PW;
					if PB {
						let PQ = -OH;
						let PR = -(PQ.powf(NF));
						let PS = ((OJ * AN) * (NF * (PQ.powf(-0.6666666666666667f64)))) * AN;
						PV = PR;
						PW = PS;
					} else {
						let PT = OU * OH;
						let PU = OJ * OU;
						PV = PT;
						PW = PU;
					}
					PC = PV;
					PD = PW;
				}
				let PE = NP * MV;
				let PF = MX * NP;
				let PG = ((PE - MR) + ((OO + PC) - (MY * NF))).sqrt();
				let PH = ((L4([0.0, PF, 0.0, 0.0]) - MS) + ((OP + PD) - (MZ * NF))) * (CB / (EZ * PG));
				let PI = PH * PG;
				let PJ = ((0.75f64 * MV) - (PG * PG)) - (EC * MR);
				let PK = (L4([0.0, (MX * 0.75f64), 0.0, 0.0]) - (PI + PI)) - (MS * EC);
				let PL = (((MT * MR) - (EC * MO)) - (PE * MT)) / PG;
				let PM = ((((L4([0.0, (MU * MR), 0.0, 0.0]) + (MS * MT)) - (MQ * EC)) - L4([0.0, ((PF * MT) + (MU * PE)), 0.0, 0.0])) - (PH * PL)) / PG;
				let PN = PJ + PL;
				let PO = PK + PM;
				let PP = PN > A;
				let QG;
				let QH;
				if PP {
					let PX = PN.sqrt();
					let PY = (-0.25f64 * MT) + (FA * (PX + PG));
					let PZ = L4([0.0, (MU * -0.25f64), 0.0, 0.0]) + (((PO * (CB / (EZ * PX))) + PH) * FA);
					QG = PY;
					QH = PZ;
				} else {
					let QA = PJ - PL;
					let QB = (PK - PM) * QA;
					let QC = ((QA * QA) + 1e-4f64).sqrt();
					let QD = QC.sqrt();
					let QE = (-0.25f64 * MT) + (FA * (QD - PG));
					let QF = L4([0.0, (MU * -0.25f64), 0.0, 0.0]) + (((((QB + QB) * (CB / (EZ * QC))) * (CB / (EZ * QD))) - PH) * FA);
					QG = QE;
					QH = QF;
				}
				NV = QG;
				NW = QH;
			} else {
				let NU = LH > staged[42];
				let RA;
				let RB;
				if NU {
					let QJ = QI - LH;
					let QK = LI * AN;
					let QL = MA * QJ;
					let QM = QK * MA;
					let QN = EC * (C - (EC * QL));
					let QO = (C - (1.5f64 * QL)).sqrt();
					let QP = (C - (EO * QL)) + QO;
					let QQ = (QN * QJ) / QP;
					let QR = (((((QM * EC) * AN) * EC) * QJ) + (QK * QN)) - ((((QM * EO) * AN) + (((QM * 1.5f64) * AN) * (CB / (EZ * QO)))) * QQ);
					let QS = QR / QP;
					RA = QQ;
					RB = QS;
				} else {
					let QT = EO * MA;
					let QU = QT * LL;
					let QV = LJ * QT;
					let QW = (C + QU).sqrt();
					let QX = 4.5f64 * MA;
					let QY = ((C - QU) + QW) / QX;
					let QZ = ((QV * AN) + (QV * (CB / (EZ * QW)))) / QX;
					RA = QY;
					RB = QZ;
				}
				let RC = L4([RB[0], 0.0, RB[1], RB[2]]);
				NV = RA;
				NW = RC;
			}
			let RX;
			let RY;
			let RZ;
			let SA;
			let SB;
			let SC;
			if NX {
				let RD = NV + staged[45];
				let RE = LL + NV;
				let RF = L4([LJ[0], 0.0, LJ[1], LJ[2]]) + NW;
				let RG = RE.sqrt();
				let RI = RH * RG;
				let RJ = (RF * (CB / (EZ * RG))) * RH;
				let TO;
				let TP;
				if LM {
					let SF = RD / IO;
					let SG = NW / IO;
					let SH = L4([0.0, IL, 0.0, 0.0]);
					let SI = FA * (SF - IG);
					let SJ = SI * IF;
					let SK = (((SG - SH) * FA) * IF) + L4([0.0, (IK * SI), 0.0, 0.0]);
					let SL = FA * (SF + IG);
					let SM = SL * IF;
					let SN = (((SG + SH) * FA) * IF) + L4([0.0, (IK * SL), 0.0, 0.0]);
					let SO = SK * SJ;
					let SP = L4([0.0, IM, 0.0, 0.0]);
					let SQ = ((SJ * SJ) + IH).sqrt();
					let SR = ((SO + SO) + SP) * (CB / (EZ * SQ));
					let SS = SN * SM;
					let ST = ((SM * SM) + IH).sqrt();
					let SU = ((SS + SS) + SP) * (CB / (EZ * ST));
					let SV = SJ / SQ;
					let SW = SM / ST;
					let SX = FA * (SV + SW);
					let SY = (SX * IF) / IO;
					let SZ = EC * RI;
					let TA = C - RI;
					let TB = SZ * TA;
					let TC = C + ((SQ + ST) - II);
					let TD = (SY * RD) / TC;
					let TE = (((((((((SK - (SR * SV)) / SQ) + ((SN - (SU * SW)) / ST)) * FA) * IF) + L4([0.0, (IK * SX), 0.0, 0.0])) / IO) * RD) + (NW * SY)) - (((SR + SU) - L4([0.0, IN, 0.0, 0.0])) * TD);
					let TF = C - TD;
					let TG = (TB * TF) / RD;
					let TH = TG.sqrt();
					let TI = (((((((RJ * EC) * TA) + ((RJ * AN) * SZ)) * TF) + (((TE / TC) * AN) * TB)) - (NW * TG)) / RD) * (CB / (EZ * TH));
					TO = TH;
					TP = TI;
				} else {
					let TJ = EC * RI;
					let TK = C - RI;
					let TL = (TJ * TK) / RD;
					let TM = TL.sqrt();
					let TN = (((((RJ * EC) * TK) + ((RJ * AN) * TJ)) - (NW * TL)) / RD) * (CB / (EZ * TM));
					TO = TM;
					TP = TN;
				}
				let TQ = TO * TO;
				let TR = TP * TO;
				let TS = (MA * RE) / TQ;
				let TT = TS - RD;
				let TU = (((RF * MA) - ((TR + TR) * TS)) / TQ) - NW;
				let TW = TV + RD;
				let TX = (TV * NV) / TW;
				let TY = ((NW * TV) - (NW * TX)) / TW;
				let TZ = RP + TX;
				let UA = EX * TZ;
				let UB = UA * TZ;
				let UC = ((TY * EX) * TZ) + (TY * UA);
				let UD = EC * KM;
				let UE = UD * RD;
				let UF = (KP * EC) * RD;
				let UG = L4([0.0, 0.0, UF[0], UF[1]]) + (NW * UD);
				let UH = KM - RD;
				let UI = L4([0.0, 0.0, KP[0], KP[1]]);
				let UJ = UH * UH;
				let UK = (UI - NW) * UH;
				let UL = UK + UK;
				let UM = (UJ + UB).sqrt();
				let UN = KM + RD;
				let UO = UN * UN;
				let UP = (UI + NW) * UN;
				let UQ = UP + UP;
				let UR = (UO + UB).sqrt();
				let US = UM + UR;
				let UT = UE / US;
				let UU = (UG - ((((UL + UC) * (CB / (EZ * UM))) + ((UQ + UC) * (CB / (EZ * UR)))) * UT)) / US;
				let VH;
				let VI;
				if UV {
					let UW = (TV * UT) / TW;
					let UX = ((UU * TV) - (NW * UW)) / TW;
					let UY = RP + UW;
					let UZ = EX * UY;
					let VA = UZ * UY;
					let VB = ((UX * EX) * UY) + (UX * UZ);
					let VC = (UJ + VA).sqrt();
					let VD = (UO + VA).sqrt();
					let VE = VC + VD;
					let VF = UE / VE;
					let VG = (UG - ((((UL + VB) * (CB / (EZ * VC))) + ((UQ + VB) * (CB / (EZ * VD)))) * VF)) / VE;
					VH = VF;
					VI = VG;
				} else {
					VH = UT;
					VI = UU;
				}
				let VJ = (TT + VH).sqrt();
				let VK = C - (TO * VJ);
				let VL = ((TP * VJ) + (((TU + VI) * (CB / (EZ * VJ))) * TO)) * AN;
				let WB;
				let WC;
				if LM {
					let VM = VH / IO;
					let VN = VI / IO;
					let VO = L4([0.0, IL, 0.0, 0.0]);
					let VP = FA * (VM - IG);
					let VQ = VP * IF;
					let VR = FA * (VM + IG);
					let VS = VR * IF;
					let VT = ((((VN - VO) * FA) * IF) + L4([0.0, (IK * VP), 0.0, 0.0])) * VQ;
					let VU = L4([0.0, IM, 0.0, 0.0]);
					let VV = ((VQ * VQ) + IH).sqrt();
					let VW = ((((VN + VO) * FA) * IF) + L4([0.0, (IK * VR), 0.0, 0.0])) * VS;
					let VX = ((VS * VS) + IH).sqrt();
					let VY = (VV + VX) - II;
					let VZ = ((((VT + VT) + VU) * (CB / (EZ * VV))) + (((VW + VW) + VU) * (CB / (EZ * VX)))) - L4([0.0, IN, 0.0, 0.0]);
					WB = VY;
					WC = VZ;
				} else {
					WB = A;
					WC = WA;
				}
				RX = VK;
				RY = WB;
				RZ = VH;
				SA = VL;
				SB = WC;
				SC = VI;
			} else {
				let RK = EC * KM;
				let RL = (KP * EC) * NV;
				let RM = KM - NV;
				let RN = L4([0.0, 0.0, KP[0], KP[1]]);
				let RO = (RN - NW) * RM;
				let RQ = ((RM * RM) + RP).sqrt();
				let RR = KM + NV;
				let RS = (RN + NW) * RR;
				let RT = ((RR * RR) + RP).sqrt();
				let RU = RQ + RT;
				let RV = (RK * NV) / RU;
				let RW = ((L4([0.0, 0.0, RL[0], RL[1]]) + (NW * RK)) - ((((RO + RO) * (CB / (EZ * RQ))) + ((RS + RS) * (CB / (EZ * RT)))) * RV)) / RU;
				let WR;
				let WS;
				if LM {
					let WD = RV / IO;
					let WE = RW / IO;
					let WF = L4([0.0, IL, 0.0, 0.0]);
					let WG = FA * (WD - IG);
					let WH = WG * IF;
					let WI = FA * (WD + IG);
					let WJ = WI * IF;
					let WK = ((((WE - WF) * FA) * IF) + L4([0.0, (IK * WG), 0.0, 0.0])) * WH;
					let WL = L4([0.0, IM, 0.0, 0.0]);
					let WM = ((WH * WH) + IH).sqrt();
					let WN = ((((WE + WF) * FA) * IF) + L4([0.0, (IK * WI), 0.0, 0.0])) * WJ;
					let WO = ((WJ * WJ) + IH).sqrt();
					let WP = (WM + WO) - II;
					let WQ = ((((WK + WK) + WL) * (CB / (EZ * WM))) + (((WN + WN) + WL) * (CB / (EZ * WO)))) - L4([0.0, IN, 0.0, 0.0]);
					WR = WP;
					WS = WQ;
				} else {
					WR = A;
					WS = WA;
				}
				let WT = (LL + RV).sqrt();
				let WU = C - (RH * WT);
				let WV = (((L4([LJ[0], 0.0, LJ[1], LJ[2]]) + RW) * (CB / (EZ * WT))) * RH) * AN;
				RX = WU;
				RY = WR;
				RZ = RV;
				SA = WV;
				SB = WS;
				SC = RW;
			}
			let SE = RX < SD;
			let WW;
			let WX;
			if SE {
				WW = SD;
				WX = WA;
			} else {
				WW = RX;
				WX = SA;
			}
			let WY = C + RY;
			let WZ = (BJ * WW) / WY;
			let XA = KN * WZ;
			let XB = XA * RZ;
			let XC = (((((L4([0.0, (BK * WW), 0.0, 0.0]) + (WX * BJ)) - (SB * WZ)) / WY) * KN) * RZ) + (SC * XA);
			let XD = DS > A;
			let XG;
			let XH;
			if XD {
				let XE = DN > A;
				let XN;
				let XO;
				if XE {
					let XJ = CD * AC;
					let XK = C / XJ;
					let XL = (((AD * CD) * XK) * AN) / XJ;
					let XM = J < CR;
					let XY;
					let XZ;
					if XM {
						let XQ = K * XK;
						let XR = (J * XK).exp();
						let XS = (L3([XQ[0], 0.0, XQ[1]]) + L3([0.0, (XL * J), 0.0])) * XR;
						XY = XR;
						XZ = XS;
					} else {
						let XT = (CR * XK).exp();
						let XU = J - CR;
						let XV = C + (XU * XK);
						let XW = XT * XV;
						let XX = L3([0.0, ((((CT * XK) + (XL * CR)) * XT) * XV), 0.0]) + ((((L3([K[0], 0.0, K[1]]) - L3([0.0, CT, 0.0])) * XK) + L3([0.0, (XL * XU), 0.0])) * XT);
						XY = XW;
						XZ = XX;
					}
					let YA = XY - C;
					let YB = DN * YA;
					let YC = L3([0.0, (DO * YA), 0.0]) + (XZ * DN);
					XN = YB;
					XO = YC;
				} else {
					XN = A;
					XO = XF;
				}
				let XP = DQ > A;
				let YH;
				let YI;
				if XP {
					let YD = CX * AC;
					let YE = C / YD;
					let YF = (((AD * CX) * YE) * AN) / YD;
					let YG = J < DJ;
					let YU;
					let YV;
					if YG {
						let YM = K * YE;
						let YN = (J * YE).exp();
						let YO = (L3([YM[0], 0.0, YM[1]]) + L3([0.0, (YF * J), 0.0])) * YN;
						YU = YN;
						YV = YO;
					} else {
						let YP = (DJ * YE).exp();
						let YQ = J - DJ;
						let YR = C + (YQ * YE);
						let YS = YP * YR;
						let YT = L3([0.0, ((((DL * YE) + (YF * DJ)) * YP) * YR), 0.0]) + ((((L3([K[0], 0.0, K[1]]) - L3([0.0, DL, 0.0])) * YE) + L3([0.0, (YF * YQ), 0.0])) * YP);
						YU = YS;
						YV = YT;
					}
					let YW = YU - C;
					let YX = DQ * YW;
					let YY = L3([0.0, (DR * YW), 0.0]) + (YV * DQ);
					YH = YX;
					YI = YY;
				} else {
					YH = A;
					YI = XF;
				}
				let YJ = XN + YH;
				let YK = XO + YI;
				let YL = HI > A;
				let ZH;
				let ZI;
				if YL {
					let YZ = -HI;
					let ZA = HL * AN;
					let ZB = YZ - J;
					let ZC = L3([0.0, ZA, 0.0]) - L3([K[0], 0.0, K[1]]);
					let ZD = HJ * AC;
					let ZE = C / ZD;
					let ZF = ((((HM * AC) + (AD * HJ)) * ZE) * AN) / ZD;
					let ZG = ZB < HK;
					let ZT;
					let ZU;
					if ZG {
						let ZM = (ZB * ZE).exp();
						let ZN = ((ZC * ZE) + L3([0.0, (ZF * ZB), 0.0])) * ZM;
						ZT = ZM;
						ZU = ZN;
					} else {
						let ZO = (HK * ZE).exp();
						let ZP = ZB - HK;
						let ZQ = C + (ZP * ZE);
						let ZR = ZO * ZQ;
						let ZS = L3([0.0, ((((HN * ZE) + (ZF * HK)) * ZO) * ZQ), 0.0]) + ((((ZC - L3([0.0, HN, 0.0])) * ZE) + L3([0.0, (ZF * ZP), 0.0])) * ZO);
						ZT = ZR;
						ZU = ZS;
					}
					let ZW = -ZV;
					let ZX = (YZ * ZE).exp();
					let ZY = ZW * (ZT - ZX);
					let ZZ = (ZU - L3([0.0, (((ZA * ZE) + (ZF * YZ)) * ZX), 0.0])) * ZW;
					ZH = ZY;
					ZI = ZZ;
				} else {
					ZH = A;
					ZI = XF;
				}
				let ZJ = K * B;
				let ZK = (YJ + ZH) + (B * J);
				let ZL = (YK + ZI) + L3([ZJ[0], 0.0, ZJ[1]]);
				XG = ZK;
				XH = ZL;
			} else {
				XG = A;
				XH = XF;
			}
			let XI = DZ > A;
			let AAC;
			let AAD;
			if XI {
				let AAA = DU > A;
				let ABC;
				let ABD;
				if AAA {
					let AAY = CD * AC;
					let AAZ = C / AAY;
					let ABA = (((AD * CD) * AAZ) * AN) / AAY;
					let ABB = L < CR;
					let ABN;
					let ABO;
					if ABB {
						let ABF = M * AAZ;
						let ABG = (L * AAZ).exp();
						let ABH = (L3([ABF[0], 0.0, ABF[1]]) + L3([0.0, (ABA * L), 0.0])) * ABG;
						ABN = ABG;
						ABO = ABH;
					} else {
						let ABI = (CR * AAZ).exp();
						let ABJ = L - CR;
						let ABK = C + (ABJ * AAZ);
						let ABL = ABI * ABK;
						let ABM = L3([0.0, ((((CT * AAZ) + (ABA * CR)) * ABI) * ABK), 0.0]) + ((((L3([M[0], 0.0, M[1]]) - L3([0.0, CT, 0.0])) * AAZ) + L3([0.0, (ABA * ABJ), 0.0])) * ABI);
						ABN = ABL;
						ABO = ABM;
					}
					let ABP = ABN - C;
					let ABQ = DU * ABP;
					let ABR = L3([0.0, (DV * ABP), 0.0]) + (ABO * DU);
					ABC = ABQ;
					ABD = ABR;
				} else {
					ABC = A;
					ABD = AAB;
				}
				let ABE = DX > A;
				let ABW;
				let ABX;
				if ABE {
					let ABS = CX * AC;
					let ABT = C / ABS;
					let ABU = (((AD * CX) * ABT) * AN) / ABS;
					let ABV = L < DJ;
					let ACJ;
					let ACK;
					if ABV {
						let ACB = M * ABT;
						let ACC = (L * ABT).exp();
						let ACD = (L3([ACB[0], 0.0, ACB[1]]) + L3([0.0, (ABU * L), 0.0])) * ACC;
						ACJ = ACC;
						ACK = ACD;
					} else {
						let ACE = (DJ * ABT).exp();
						let ACF = L - DJ;
						let ACG = C + (ACF * ABT);
						let ACH = ACE * ACG;
						let ACI = L3([0.0, ((((DL * ABT) + (ABU * DJ)) * ACE) * ACG), 0.0]) + ((((L3([M[0], 0.0, M[1]]) - L3([0.0, DL, 0.0])) * ABT) + L3([0.0, (ABU * ACF), 0.0])) * ACE);
						ACJ = ACH;
						ACK = ACI;
					}
					let ACL = ACJ - C;
					let ACM = DX * ACL;
					let ACN = L3([0.0, (DY * ACL), 0.0]) + (ACK * DX);
					ABW = ACM;
					ABX = ACN;
				} else {
					ABW = A;
					ABX = AAB;
				}
				let ABY = ABC + ABW;
				let ABZ = ABD + ABX;
				let ACA = HI > A;
				let ACW;
				let ACX;
				if ACA {
					let ACO = -HI;
					let ACP = HL * AN;
					let ACQ = ACO - L;
					let ACR = L3([0.0, ACP, 0.0]) - L3([M[0], 0.0, M[1]]);
					let ACS = HJ * AC;
					let ACT = C / ACS;
					let ACU = ((((HM * AC) + (AD * HJ)) * ACT) * AN) / ACS;
					let ACV = ACQ < HK;
					let ADI;
					let ADJ;
					if ACV {
						let ADB = (ACQ * ACT).exp();
						let ADC = ((ACR * ACT) + L3([0.0, (ACU * ACQ), 0.0])) * ADB;
						ADI = ADB;
						ADJ = ADC;
					} else {
						let ADD = (HK * ACT).exp();
						let ADE = ACQ - HK;
						let ADF = C + (ADE * ACT);
						let ADG = ADD * ADF;
						let ADH = L3([0.0, ((((HN * ACT) + (ACU * HK)) * ADD) * ADF), 0.0]) + ((((ACR - L3([0.0, HN, 0.0])) * ACT) + L3([0.0, (ACU * ADE), 0.0])) * ADD);
						ADI = ADG;
						ADJ = ADH;
					}
					let ADK = -ZV;
					let ADL = (ACO * ACT).exp();
					let ADM = ADK * (ADI - ADL);
					let ADN = (ADJ - L3([0.0, (((ACP * ACT) + (ACU * ACO)) * ADL), 0.0])) * ADK;
					ACW = ADM;
					ACX = ADN;
				} else {
					ACW = A;
					ACX = AAB;
				}
				let ACY = M * B;
				let ACZ = (ABY + ACW) + (B * L);
				let ADA = (ABZ + ACX) + L3([ACY[0], 0.0, ACY[1]]);
				AAC = ACZ;
				AAD = ADA;
			} else {
				AAC = A;
				AAD = AAB;
			}
			let AAE = H * XB;
			let AAF = K * XG;
			let AAG = (XH * J) + L3([AAF[0], 0.0, AAF[1]]);
			let AAH = M * AAC;
			let AAI = (AAD * L) + L3([AAH[0], 0.0, AAH[1]]);
			let AAJ = (((XC * G) + L4([0.0, 0.0, AAE[0], AAE[1]])) + L4([AAG[0], AAG[1], AAG[2], 0.0])) + L4([AAI[0], AAI[1], 0.0, AAI[2]]);
			let AAK = node_potentials[0] - E;
			let AAL = L2([1f64, 0.0]) - L2([0.0, 1f64]);
			let AAN = AAL * AAM;
			let AAO = L3([0.0, 0.0, (1f64 * AAK)]) + L3([AAN[0], AAN[1], 0.0]);
			let AAP = L6([0.0, AAJ[0], AAJ[1], AAJ[2], AAJ[3], 0.0]) + L6([AAO[0], 0.0, 0.0, AAO[1], 0.0, AAO[2]]);
			let AAQ = node_potentials[2] - D;
			let AAR = L2([1f64, 0.0]) - L2([0.0, 1f64]);
			let AAT = AAR * AAS;
			let AAU = L3([0.0, 0.0, (1f64 * AAQ)]) + L3([AAT[0], AAT[1], 0.0]);
			let AAV = ((((XB * G) + (XG * J)) + (AAC * L)) + (AAM * AAK)) + (AAS * AAQ);
			let AAW = L8([AAP[0], AAP[1], 0.0, AAP[2], AAP[3], AAP[4], AAP[5], 0.0]) + L8([0.0, 0.0, AAU[0], 0.0, 0.0, AAU[1], 0.0, AAU[2]]);
			let ADU;
			let ADV;
			let ADW;
			let ADX;
			if AAX {
				let ADO = -AAV;
				let ADP = AAW * AN;
				let AEH;
				let AEI;
				if ADQ {
					let AEF = AEE * N;
					let AEG = S * AEE;
					AEH = AEF;
					AEI = AEG;
				} else {
					let AEV;
					let AEW;
					if AEJ {
						let AEL = C + (N / AEK);
						let AEO = (AEN * ((AEL.powf(AEM)) - C)) / AEM;
						let AEP = (((S / AEK) * (AEM * (AEL.powf(staged[64])))) * AEN) / AEM;
						AEV = AEO;
						AEW = AEP;
					} else {
						let AEQ = AEE * N;
						let AES = C + ((AER * N) / AEK);
						let AET = AEQ * AES;
						let AEU = ((S * AEE) * AES) + (((S * AER) / AEK) * AEQ);
						AEV = AET;
						AEW = AEU;
					}
					AEH = AEV;
					AEI = AEW;
				}
				ADU = AEH;
				ADV = ADO;
				ADW = AEI;
				ADX = ADP;
			} else {
				let ADR = 1e6f64 * N;
				let ADS = S * 1e6f64;
				ADU = ADR;
				ADV = A;
				ADW = ADS;
				ADX = ADT;
			}
			let ADY = F * XB;
			let ADZ = XC * F;
			let AEA = F * XG;
			let AEB = XH * F;
			let AEC = F * AAC;
			let AED = AAD * F;
			let AEY;
			let AEZ;
			if AEX {
				let AFG;
				let AFH;
				if BA != 0.0 {
					let AFB = J + QI;
					let AFC = K * AFB;
					let AFD = ((AFB * AFB) + 0.04f64).sqrt();
					let AFE = FA * ((J - QI) + AFD);
					let AFF = (K + ((AFC + AFC) * (CB / (EZ * AFD)))) * FA;
					AFG = AFE;
					AFH = AFF;
				} else {
					AFG = J;
					AFH = K;
				}
				let AFI = DM * FM;
				let AFJ = FO * DM;
				let AFK = DP * GW;
				let AFL = GY * DP;
				let AFM = AFI > A;
				let AFU;
				let AFV;
				if AFM {
					let AFN = -FN;
					let AFO = FP * AN;
					let AFQ = AFN * AFP;
					let AFR = AFO * AFP;
					let AFT = AFS <= A;
					let AHB;
					let AHC;
					if AFT {
						let AFX = AFG + AFQ;
						let AFY = L3([AFH[0], 0.0, AFH[1]]);
						let AFZ = AFY + L3([0.0, AFR, 0.0]);
						let AGA = AFX > A;
						let AHV;
						let AHW;
						let AHX;
						let AHY;
						if AGA {
							let AHD = C - AFP;
							let AHE = AHD.powf((-FI));
							let AHF = C - (AHE * AHD);
							let AHG = C - FI;
							let AHH = (FN * AHF) / AHG;
							let AHI = FA * FI;
							let AHJ = FN * AHD;
							let AHK = (AHI * AFX) / AHJ;
							let AHL = C + AHK;
							let AHM = (AFX * AHL) * AHE;
							let AHN = ((AFZ * AHL) + ((((AFZ * AHI) - L3([0.0, ((FP * AHD) * AHK), 0.0])) / AHJ) * AFX)) * AHE;
							let AHO = L3([0.0, ((FP * AHF) / AHG), 0.0]);
							AHV = AHH;
							AHW = AHM;
							AHX = AHO;
							AHY = AHN;
						} else {
							let AHP = AFG / FN;
							let AHQ = C - AHP;
							let AHR = C - FI;
							let AHS = C - (AHQ.powf(AHR));
							let AHT = (FN * AHS) / AHR;
							let AHU = (L3([0.0, (FP * AHS), 0.0]) + ((((((AFY - L3([0.0, (FP * AHP), 0.0])) / FN) * AN) * (AHR * (AHQ.powf((AHR - CB))))) * AN) * FN)) / AHR;
							AHV = AHT;
							AHW = A;
							AHX = AHU;
							AHY = XF;
						}
						let AHZ = AHV + AHW;
						let AIA = AHX + AHY;
						AHB = AHZ;
						AHC = AIA;
					} else {
						let AGB = AFR * AFQ;
						let AGC = (EX * AFS) * AFS;
						let AGD = ((AFQ * AFQ) + AGC).sqrt();
						let AGE = AFG + AFQ;
						let AGF = L3([AFH[0], 0.0, AFH[1]]);
						let AGG = L3([0.0, AFR, 0.0]);
						let AGH = AGF + AGG;
						let AGI = AGH * AGE;
						let AGJ = ((AGE * AGE) + AGC).sqrt();
						let AGK = (FA * (AGE - AGJ)) - AFQ;
						let AGL = ((AGH - ((AGI + AGI) * (CB / (EZ * AGJ)))) * FA) - AGG;
						let AGM = AGK / FN;
						let AGN = C - AGM;
						let AGO = C - FI;
						let AGP = AGN.powf(AGO);
						let AGQ = C - AFP;
						let AGR = AGQ.powf((-FI));
						let AGS = (AFG - AGK) + (-0.5f64 * (AFQ + AGD));
						let AGT = (AGF - AGL) + L3([0.0, ((AFR + ((AGB + AGB) * (CB / (EZ * AGD)))) * -0.5f64), 0.0]);
						let AGU = AGR * AGS;
						let AGV = FA * FI;
						let AGW = FN * AGQ;
						let AGX = (AGV * AGS) / AGW;
						let AGY = C + AGX;
						let AGZ = ((AFN * AGP) / AGO) + (AGU * AGY);
						let AHA = ((L3([0.0, (AFO * AGP), 0.0]) + (((((AGL - L3([0.0, (FP * AGM), 0.0])) / FN) * AN) * (AGO * (AGN.powf((AGO - CB))))) * AFN)) / AGO) + (((AGT * AGR) * AGY) + ((((AGT * AGV) - L3([0.0, ((FP * AGQ) * AGX), 0.0])) / AGW) * AGU));
						AHB = AGZ;
						AHC = AHA;
					}
					AFU = AHB;
					AFV = AHC;
				} else {
					AFU = A;
					AFV = XF;
				}
				let AFW = AFK > A;
				let AIH;
				let AII;
				if AFW {
					let AIB = -GX;
					let AIC = GZ * AN;
					let AID = AIB * AFP;
					let AIE = AIC * AFP;
					let AIG = AIF <= A;
					let AJP;
					let AJQ;
					if AIG {
						let AIL = AFG + AID;
						let AIM = L3([AFH[0], 0.0, AFH[1]]);
						let AIN = AIM + L3([0.0, AIE, 0.0]);
						let AIO = AIL > A;
						let AKJ;
						let AKK;
						let AKL;
						let AKM;
						if AIO {
							let AJR = C - AFP;
							let AJS = AJR.powf((-GS));
							let AJT = C - (AJS * AJR);
							let AJU = C - GS;
							let AJV = (GX * AJT) / AJU;
							let AJW = FA * GS;
							let AJX = GX * AJR;
							let AJY = (AJW * AIL) / AJX;
							let AJZ = C + AJY;
							let AKA = (AIL * AJZ) * AJS;
							let AKB = ((AIN * AJZ) + ((((AIN * AJW) - L3([0.0, ((GZ * AJR) * AJY), 0.0])) / AJX) * AIL)) * AJS;
							let AKC = L3([0.0, ((GZ * AJT) / AJU), 0.0]);
							AKJ = AJV;
							AKK = AKA;
							AKL = AKC;
							AKM = AKB;
						} else {
							let AKD = AFG / GX;
							let AKE = C - AKD;
							let AKF = C - GS;
							let AKG = C - (AKE.powf(AKF));
							let AKH = (GX * AKG) / AKF;
							let AKI = (L3([0.0, (GZ * AKG), 0.0]) + ((((((AIM - L3([0.0, (GZ * AKD), 0.0])) / GX) * AN) * (AKF * (AKE.powf((AKF - CB))))) * AN) * GX)) / AKF;
							AKJ = AKH;
							AKK = A;
							AKL = AKI;
							AKM = XF;
						}
						let AKN = AKJ + AKK;
						let AKO = AKL + AKM;
						AJP = AKN;
						AJQ = AKO;
					} else {
						let AIP = AIE * AID;
						let AIQ = (EX * AIF) * AIF;
						let AIR = ((AID * AID) + AIQ).sqrt();
						let AIS = AFG + AID;
						let AIT = L3([AFH[0], 0.0, AFH[1]]);
						let AIU = L3([0.0, AIE, 0.0]);
						let AIV = AIT + AIU;
						let AIW = AIV * AIS;
						let AIX = ((AIS * AIS) + AIQ).sqrt();
						let AIY = (FA * (AIS - AIX)) - AID;
						let AIZ = ((AIV - ((AIW + AIW) * (CB / (EZ * AIX)))) * FA) - AIU;
						let AJA = AIY / GX;
						let AJB = C - AJA;
						let AJC = C - GS;
						let AJD = AJB.powf(AJC);
						let AJE = C - AFP;
						let AJF = AJE.powf((-GS));
						let AJG = (AFG - AIY) + (-0.5f64 * (AID + AIR));
						let AJH = (AIT - AIZ) + L3([0.0, ((AIE + ((AIP + AIP) * (CB / (EZ * AIR)))) * -0.5f64), 0.0]);
						let AJI = AJF * AJG;
						let AJJ = FA * GS;
						let AJK = GX * AJE;
						let AJL = (AJJ * AJG) / AJK;
						let AJM = C + AJL;
						let AJN = ((AIB * AJD) / AJC) + (AJI * AJM);
						let AJO = ((L3([0.0, (AIC * AJD), 0.0]) + (((((AIZ - L3([0.0, (GZ * AJA), 0.0])) / GX) * AN) * (AJC * (AJB.powf((AJC - CB))))) * AIB)) / AJC) + (((AJH * AJF) * AJM) + ((((AJH * AJJ) - L3([0.0, ((GZ * AJE) * AJL), 0.0])) / AJK) * AJI));
						AJP = AJN;
						AJQ = AJO;
					}
					AIH = AJP;
					AII = AJQ;
				} else {
					AIH = A;
					AII = XF;
				}
				let AIJ = (AFI * AFU) + (AFK * AIH);
				let AIK = (L3([0.0, (AFJ * AFU), 0.0]) + (AFV * AFI)) + (L3([0.0, (AFL * AIH), 0.0]) + (AII * AFK));
				AEY = AIJ;
				AEZ = AIK;
			} else {
				AEY = A;
				AEZ = XF;
			}
			let AKP;
			let AKQ;
			if AFA {
				let ALI;
				let ALJ;
				if BA != 0.0 {
					let ALD = L + QI;
					let ALE = M * ALD;
					let ALF = ((ALD * ALD) + 0.04f64).sqrt();
					let ALG = FA * ((L - QI) + ALF);
					let ALH = (M + ((ALE + ALE) * (CB / (EZ * ALF)))) * FA;
					ALI = ALG;
					ALJ = ALH;
				} else {
					ALI = L;
					ALJ = M;
				}
				let ALK = DT * FM;
				let ALL = FO * DT;
				let ALM = DW * GW;
				let ALN = GY * DW;
				let ALO = ALK > A;
				let ALU;
				let ALV;
				if ALO {
					let ALP = -FN;
					let ALQ = FP * AN;
					let ALR = ALP * AFP;
					let ALS = ALQ * AFP;
					let ALT = AFS <= A;
					let ANB;
					let ANC;
					if ALT {
						let ALX = ALI + ALR;
						let ALY = L3([ALJ[0], 0.0, ALJ[1]]);
						let ALZ = ALY + L3([0.0, ALS, 0.0]);
						let AMA = ALX > A;
						let ANV;
						let ANW;
						let ANX;
						let ANY;
						if AMA {
							let AND = C - AFP;
							let ANE = AND.powf((-FI));
							let ANF = C - (ANE * AND);
							let ANG = C - FI;
							let ANH = (FN * ANF) / ANG;
							let ANI = FA * FI;
							let ANJ = FN * AND;
							let ANK = (ANI * ALX) / ANJ;
							let ANL = C + ANK;
							let ANM = (ALX * ANL) * ANE;
							let ANN = ((ALZ * ANL) + ((((ALZ * ANI) - L3([0.0, ((FP * AND) * ANK), 0.0])) / ANJ) * ALX)) * ANE;
							let ANO = L3([0.0, ((FP * ANF) / ANG), 0.0]);
							ANV = ANH;
							ANW = ANM;
							ANX = ANO;
							ANY = ANN;
						} else {
							let ANP = ALI / FN;
							let ANQ = C - ANP;
							let ANR = C - FI;
							let ANS = C - (ANQ.powf(ANR));
							let ANT = (FN * ANS) / ANR;
							let ANU = (L3([0.0, (FP * ANS), 0.0]) + ((((((ALY - L3([0.0, (FP * ANP), 0.0])) / FN) * AN) * (ANR * (ANQ.powf((ANR - CB))))) * AN) * FN)) / ANR;
							ANV = ANT;
							ANW = A;
							ANX = ANU;
							ANY = AAB;
						}
						let ANZ = ANV + ANW;
						let AOA = ANX + ANY;
						ANB = ANZ;
						ANC = AOA;
					} else {
						let AMB = ALS * ALR;
						let AMC = (EX * AFS) * AFS;
						let AMD = ((ALR * ALR) + AMC).sqrt();
						let AME = ALI + ALR;
						let AMF = L3([ALJ[0], 0.0, ALJ[1]]);
						let AMG = L3([0.0, ALS, 0.0]);
						let AMH = AMF + AMG;
						let AMI = AMH * AME;
						let AMJ = ((AME * AME) + AMC).sqrt();
						let AMK = (FA * (AME - AMJ)) - ALR;
						let AML = ((AMH - ((AMI + AMI) * (CB / (EZ * AMJ)))) * FA) - AMG;
						let AMM = AMK / FN;
						let AMN = C - AMM;
						let AMO = C - FI;
						let AMP = AMN.powf(AMO);
						let AMQ = C - AFP;
						let AMR = AMQ.powf((-FI));
						let AMS = (ALI - AMK) + (-0.5f64 * (ALR + AMD));
						let AMT = (AMF - AML) + L3([0.0, ((ALS + ((AMB + AMB) * (CB / (EZ * AMD)))) * -0.5f64), 0.0]);
						let AMU = AMR * AMS;
						let AMV = FA * FI;
						let AMW = FN * AMQ;
						let AMX = (AMV * AMS) / AMW;
						let AMY = C + AMX;
						let AMZ = ((ALP * AMP) / AMO) + (AMU * AMY);
						let ANA = ((L3([0.0, (ALQ * AMP), 0.0]) + (((((AML - L3([0.0, (FP * AMM), 0.0])) / FN) * AN) * (AMO * (AMN.powf((AMO - CB))))) * ALP)) / AMO) + (((AMT * AMR) * AMY) + ((((AMT * AMV) - L3([0.0, ((FP * AMQ) * AMX), 0.0])) / AMW) * AMU));
						ANB = AMZ;
						ANC = ANA;
					}
					ALU = ANB;
					ALV = ANC;
				} else {
					ALU = A;
					ALV = AAB;
				}
				let ALW = ALM > A;
				let AOG;
				let AOH;
				if ALW {
					let AOB = -GX;
					let AOC = GZ * AN;
					let AOD = AOB * AFP;
					let AOE = AOC * AFP;
					let AOF = AIF <= A;
					let APO;
					let APP;
					if AOF {
						let AOK = ALI + AOD;
						let AOL = L3([ALJ[0], 0.0, ALJ[1]]);
						let AOM = AOL + L3([0.0, AOE, 0.0]);
						let AON = AOK > A;
						let AQI;
						let AQJ;
						let AQK;
						let AQL;
						if AON {
							let APQ = C - AFP;
							let APR = APQ.powf((-GS));
							let APS = C - (APR * APQ);
							let APT = C - GS;
							let APU = (GX * APS) / APT;
							let APV = FA * GS;
							let APW = GX * APQ;
							let APX = (APV * AOK) / APW;
							let APY = C + APX;
							let APZ = (AOK * APY) * APR;
							let AQA = ((AOM * APY) + ((((AOM * APV) - L3([0.0, ((GZ * APQ) * APX), 0.0])) / APW) * AOK)) * APR;
							let AQB = L3([0.0, ((GZ * APS) / APT), 0.0]);
							AQI = APU;
							AQJ = APZ;
							AQK = AQB;
							AQL = AQA;
						} else {
							let AQC = ALI / GX;
							let AQD = C - AQC;
							let AQE = C - GS;
							let AQF = C - (AQD.powf(AQE));
							let AQG = (GX * AQF) / AQE;
							let AQH = (L3([0.0, (GZ * AQF), 0.0]) + ((((((AOL - L3([0.0, (GZ * AQC), 0.0])) / GX) * AN) * (AQE * (AQD.powf((AQE - CB))))) * AN) * GX)) / AQE;
							AQI = AQG;
							AQJ = A;
							AQK = AQH;
							AQL = AAB;
						}
						let AQM = AQI + AQJ;
						let AQN = AQK + AQL;
						APO = AQM;
						APP = AQN;
					} else {
						let AOO = AOE * AOD;
						let AOP = (EX * AIF) * AIF;
						let AOQ = ((AOD * AOD) + AOP).sqrt();
						let AOR = ALI + AOD;
						let AOS = L3([ALJ[0], 0.0, ALJ[1]]);
						let AOT = L3([0.0, AOE, 0.0]);
						let AOU = AOS + AOT;
						let AOV = AOU * AOR;
						let AOW = ((AOR * AOR) + AOP).sqrt();
						let AOX = (FA * (AOR - AOW)) - AOD;
						let AOY = ((AOU - ((AOV + AOV) * (CB / (EZ * AOW)))) * FA) - AOT;
						let AOZ = AOX / GX;
						let APA = C - AOZ;
						let APB = C - GS;
						let APC = APA.powf(APB);
						let APD = C - AFP;
						let APE = APD.powf((-GS));
						let APF = (ALI - AOX) + (-0.5f64 * (AOD + AOQ));
						let APG = (AOS - AOY) + L3([0.0, ((AOE + ((AOO + AOO) * (CB / (EZ * AOQ)))) * -0.5f64), 0.0]);
						let APH = APE * APF;
						let API = FA * GS;
						let APJ = GX * APD;
						let APK = (API * APF) / APJ;
						let APL = C + APK;
						let APM = ((AOB * APC) / APB) + (APH * APL);
						let APN = ((L3([0.0, (AOC * APC), 0.0]) + (((((AOY - L3([0.0, (GZ * AOZ), 0.0])) / GX) * AN) * (APB * (APA.powf((APB - CB))))) * AOB)) / APB) + (((APG * APE) * APL) + ((((APG * API) - L3([0.0, ((GZ * APD) * APK), 0.0])) / APJ) * APH));
						APO = APM;
						APP = APN;
					}
					AOG = APO;
					AOH = APP;
				} else {
					AOG = A;
					AOH = AAB;
				}
				let AOI = (ALK * ALU) + (ALM * AOG);
				let AOJ = (L3([0.0, (ALL * ALU), 0.0]) + (ALV * ALK)) + (L3([0.0, (ALN * AOG), 0.0]) + (AOH * ALM));
				AKP = AOI;
				AKQ = AOJ;
			} else {
				AKP = A;
				AKQ = AAB;
			}
			let AKS = K * AKR;
			let AKU = M * AKT;
			let AKV = F * (AEY + (AKR * J));
			let AKW = (AEZ + L3([AKS[0], 0.0, AKS[1]])) * F;
			let AKX = F * (AKP + (AKT * L));
			let AKY = (AKQ + L3([AKU[0], 0.0, AKU[1]])) * F;
			let ALA = N * AKZ;
			let ALB = S * AKZ;
			let AQX;
			let AQY;
			let AQZ;
			let ARA;
			if ALC {
				let AQP = AAM * AQO;
				let AQQ = AQP * BT;
				let AQR = L2([0.0, ((1f64 * AQO) * BT)]) + L2([(BU * AQP), 0.0]);
				AQX = AQQ;
				AQY = A;
				AQZ = AQR;
				ARA = AQS;
			} else {
				let AQT = AQO * BT;
				let AQU = AAK / AQT;
				let AQV = (L3([AAL[0], 0.0, AAL[1]]) - L3([0.0, ((BU * AQO) * AQU), 0.0])) / AQT;
				AQX = A;
				AQY = AQU;
				AQZ = AQW;
				ARA = AQV;
			}
			let ARL;
			let ARM;
			let ARN;
			let ARO;
			if ARB {
				let ARD = AAS * ARC;
				let ARE = ARD * BT;
				let ARF = L2([0.0, ((1f64 * ARC) * BT)]) + L2([(BU * ARD), 0.0]);
				ARL = ARE;
				ARM = A;
				ARN = ARF;
				ARO = ARG;
			} else {
				let ARH = ARC * BT;
				let ARI = AAQ / ARH;
				let ARJ = (L3([AAR[0], 0.0, AAR[1]]) - L3([0.0, ((BU * ARC) * ARI), 0.0])) / ARH;
				ARL = A;
				ARM = ARI;
				ARN = ARK;
				ARO = ARJ;
			}
			let ARP = ddt(0, AKV);
			let ARR = AKW * ARQ;
			let ARS = ddt(1, AKX);
			let ART = AKY * ARQ;
			let ARU = ddt(2, ALA);
			let ARV = ALB * ARQ;
			let ARX;
			let ARY;
			if ARW != 0.0 {
				let ASA = if XD {
					ARZ
				} else {
					A
				};
				let ASC = if XI {
					ASB
				} else {
					A
				};
				ARX = ASA;
				ARY = ASC;
			} else {
				ARX = A;
				ARY = A;
			}
			let ASD = ADZ[3];
			let ASE = ADZ[1];
			let ASF = ADZ[0];
			let ASG = ADZ[2];
			let ASH = AEB[0];
			let ASI = AEB[1];
			let ASJ = AEB[2];
			let ASK = AED[0];
			let ASL = AED[1];
			let ASM = AED[2];
			let ASN = ADW;
			let ASO = ADX[0];
			let ASP = ADX[1];
			let ASQ = ADX[2];
			let ASR = ADX[3];
			let ASS = ADX[4];
			let AST = ADX[5];
			let ASU = ADX[6];
			let ASV = ADX[7];
			let ASW = AQZ[0];
			let ASX = AQZ[1];
			let ASY = ARA[0];
			let ASZ = ARA[1];
			let ATA = ARA[2];
			let ATB = ARN[0];
			let ATC = ARN[1];
			let ATD = ARO[0];
			let ATE = ARO[1];
			let ATF = ARO[2];
			let ATG = ARR[0];
			let ATH = ARR[1];
			let ATI = ARR[2];
			let ATJ = ART[0];
			let ATK = ART[1];
			let ATL = ART[2];
			let ATM = ARV;
			let ATN = AKW[0];
			let ATO = AKW[1];
			let ATP = AKW[2];
			let ATQ = AKY[0];
			let ATR = AKY[1];
			let ATS = AKY[2];
			let ATT = ALB;
        stamper.stamp_current_sparse_local::<4, 0>(
            Some(5),
            Some(4),
            multiplicity * (ADY),
            [1, 3, 4, 5],
            [ASF, ASE, ASG, ASD],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<3, 0>(
            Some(1),
            Some(4),
            multiplicity * (AEA),
            [1, 3, 4],
            [ASH, ASI, ASJ],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<3, 0>(
            Some(1),
            Some(5),
            multiplicity * (AEC),
            [1, 3, 5],
            [ASK, ASL, ASM],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<1, 0>(
            Some(3),
            None,
            multiplicity * (ADU),
            [3],
            [ASN],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<6, 2>(
            Some(3),
            None,
            multiplicity * (ADV),
            [0, 1, 2, 3, 4, 5],
            [ASO, ASP, ASQ, ASR, ASS, AST],
            [0, 1],
            [ASU, ASV],
            multiplicity,
        );
        stamper.stamp_potential_branch_local(Some(0), Some(4), 0, multiplicity);
        stamper.stamp_potential_sparse_local::<1, 1>(
            0,
            AQX,
            [3],
            [ASW],
            [0],
            [ASX],
        );
        stamper.stamp_current_sparse_local::<3, 0>(
            Some(0),
            Some(4),
            multiplicity * (AQY),
            [0, 3, 4],
            [ASY, ASZ, ATA],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_potential_branch_local(Some(2), Some(5), 1, multiplicity);
        stamper.stamp_potential_sparse_local::<1, 1>(
            1,
            ARL,
            [3],
            [ATB],
            [1],
            [ATC],
        );
        stamper.stamp_current_sparse_local::<3, 0>(
            Some(2),
            Some(5),
            multiplicity * (ARM),
            [2, 3, 5],
            [ATD, ATE, ATF],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<3, 0>(
            Some(1),
            Some(4),
            multiplicity * (ARP),
            [1, 3, 4],
            [ATG, ATH, ATI],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<3, 0>(
            Some(1),
            Some(5),
            multiplicity * (ARS),
            [1, 3, 5],
            [ATJ, ATK, ATL],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<1, 0>(
            Some(3),
            None,
            multiplicity * (ARU),
            [3],
            [ATM],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<0, 0>(
            Some(5),
            Some(4),
            multiplicity * (staged[111]),
            [],
            [],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<0, 0>(
            Some(5),
            Some(4),
            multiplicity * (staged[112]),
            [],
            [],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<0, 0>(
            Some(0),
            Some(4),
            multiplicity * (staged[113]),
            [],
            [],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<0, 0>(
            Some(2),
            Some(5),
            multiplicity * (staged[114]),
            [],
            [],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<0, 0>(
            Some(1),
            Some(4),
            multiplicity * (ARX),
            [],
            [],
            [],
            [],
            multiplicity,
        );
        stamper.stamp_current_sparse_local::<0, 0>(
            Some(1),
            Some(5),
            multiplicity * (ARY),
            [],
            [],
            [],
            [],
            multiplicity,
        );
        self.canonical_reactive[0] = ADY;
        self.canonical_reactive[1] = AEA;
        self.canonical_reactive[2] = AEC;
        self.canonical_reactive[3] = ADU;
        self.canonical_reactive[4] = ADV;
        self.canonical_reactive[5] = AQX;
        self.canonical_reactive[6] = AQY;
        self.canonical_reactive[7] = ARL;
        self.canonical_reactive[8] = ARM;
        self.canonical_reactive[9] = AKV;
        self.canonical_reactive[10] = ATN;
        self.canonical_reactive[11] = ATO;
        self.canonical_reactive[12] = ATP;
        self.canonical_reactive[13] = AKX;
        self.canonical_reactive[14] = ATQ;
        self.canonical_reactive[15] = ATR;
        self.canonical_reactive[16] = ATS;
        self.canonical_reactive[17] = ALA;
        self.canonical_reactive[18] = ATT;
        self.canonical_reactive[19] = staged[111];
        self.canonical_reactive[20] = staged[112];
        self.canonical_reactive[21] = staged[113];
        self.canonical_reactive[22] = staged[114];
        self.canonical_reactive[23] = ARX;
        self.canonical_reactive[24] = ARY;
    }

    pub fn stamp_reactive(&mut self, ctx: &GeneratedEvalContext<'_>, stamper: &mut GeneratedReactiveStamper<'_>) {
        let multiplicity = self.multiplicity;
        let cached = &*self.canonical_reactive;
        stamper.stamp_current_reactive_indexed_dense_local(
            Some(1),
            Some(4),
            &[1, 3, 4],
            &[cached[10], cached[11], cached[12]],
            &[],
            &[],
            multiplicity,
        );
        stamper.stamp_current_reactive_indexed_dense_local(
            Some(1),
            Some(5),
            &[1, 3, 5],
            &[cached[14], cached[15], cached[16]],
            &[],
            &[],
            multiplicity,
        );
        stamper.stamp_current_reactive_indexed_dense_local(
            Some(3),
            None,
            &[3],
            &[cached[18]],
            &[],
            &[],
            multiplicity,
        );
    }

}
