// @generated by rspice-veriloga; do not edit.
//! Precompiled generated Verilog-A model. Do not edit.

#![allow(clippy::all, unused_assignments)]

#[rustfmt::skip]
#[allow(non_snake_case)]
#[path = "hicuml0_v2p1p0__hicuml0va__91cb3377/mod.rs"]
pub mod hicuml0_v2p1p0__hicuml0va__91cb3377;
