// @generated by rspice-veriloga; do not edit.
#![allow(dead_code, non_snake_case, unused_parens, unused_variables)]

use super::state::Instance;
use rspice_veriloga_runtime::GeneratedEvalContext;
pub use rspice_veriloga_runtime::{GeneratedNoiseDescriptor, GeneratedNoiseEndpoint, GeneratedNoiseEvaluation, GeneratedNoiseEvaluationError, GeneratedNoiseEvaluationRef, GeneratedNoiseKind, GeneratedNoiseVisitor};

use super::stamp::{canonical_model_preprocess, CANONICAL_MODEL_STAGE_SLOTS, canonical_instance_preprocess, CANONICAL_INSTANCE_STAGE_SLOTS, canonical_temperature_preprocess, CANONICAL_TEMPERATURE_STAGE_SLOTS};
use rspice_veriloga_runtime::{install_generated_stage_values, rspice_limited_exp};
pub static NOISE_SOURCES: [GeneratedNoiseDescriptor; 14] = [
    GeneratedNoiseDescriptor { mechanism: "WHITE_S_SI_RS", label: Some("rs"), kind: GeneratedNoiseKind::White, equation: 8, is_current: true, branch_ordinal: None, pos: GeneratedNoiseEndpoint { local_node: Some(2), name: "s", is_internal: false }, neg: GeneratedNoiseEndpoint { local_node: Some(5), name: "si", is_internal: true }, table_len: 0, table_log_interp: false },
    GeneratedNoiseDescriptor { mechanism: "WHITE_D_DI_RD", label: Some("rd"), kind: GeneratedNoiseKind::White, equation: 10, is_current: true, branch_ordinal: None, pos: GeneratedNoiseEndpoint { local_node: Some(0), name: "d", is_internal: false }, neg: GeneratedNoiseEndpoint { local_node: Some(4), name: "di", is_internal: true }, table_len: 0, table_log_interp: false },
    GeneratedNoiseDescriptor { mechanism: "WHITE_G_GI_RG", label: Some("rg"), kind: GeneratedNoiseKind::White, equation: 12, is_current: true, branch_ordinal: None, pos: GeneratedNoiseEndpoint { local_node: Some(1), name: "g", is_internal: false }, neg: GeneratedNoiseEndpoint { local_node: Some(6), name: "gi", is_internal: true }, table_len: 0, table_log_interp: false },
    GeneratedNoiseDescriptor { mechanism: "WHITE_B_BI_RB", label: Some("rb"), kind: GeneratedNoiseKind::White, equation: 14, is_current: true, branch_ordinal: None, pos: GeneratedNoiseEndpoint { local_node: Some(3), name: "b", is_internal: false }, neg: GeneratedNoiseEndpoint { local_node: Some(7), name: "bi", is_internal: true }, table_len: 0, table_log_interp: false },
    GeneratedNoiseDescriptor { mechanism: "WHITE_B_BSI_RSB", label: Some("rsb"), kind: GeneratedNoiseKind::White, equation: 16, is_current: true, branch_ordinal: None, pos: GeneratedNoiseEndpoint { local_node: Some(3), name: "b", is_internal: false }, neg: GeneratedNoiseEndpoint { local_node: Some(9), name: "bsi", is_internal: true }, table_len: 0, table_log_interp: false },
    GeneratedNoiseDescriptor { mechanism: "WHITE_B_BDI_RDB", label: Some("rdb"), kind: GeneratedNoiseKind::White, equation: 18, is_current: true, branch_ordinal: None, pos: GeneratedNoiseEndpoint { local_node: Some(3), name: "b", is_internal: false }, neg: GeneratedNoiseEndpoint { local_node: Some(8), name: "bdi", is_internal: true }, table_len: 0, table_log_interp: false },
    GeneratedNoiseDescriptor { mechanism: "WHITE_BI_BSI_SHOT_IBS", label: Some("shot ibs"), kind: GeneratedNoiseKind::White, equation: 20, is_current: true, branch_ordinal: None, pos: GeneratedNoiseEndpoint { local_node: Some(7), name: "bi", is_internal: true }, neg: GeneratedNoiseEndpoint { local_node: Some(9), name: "bsi", is_internal: true }, table_len: 0, table_log_interp: false },
    GeneratedNoiseDescriptor { mechanism: "WHITE_BI_BDI_SHOT_IBD", label: Some("shot ibd"), kind: GeneratedNoiseKind::White, equation: 22, is_current: true, branch_ordinal: None, pos: GeneratedNoiseEndpoint { local_node: Some(7), name: "bi", is_internal: true }, neg: GeneratedNoiseEndpoint { local_node: Some(8), name: "bdi", is_internal: true }, table_len: 0, table_log_interp: false },
    GeneratedNoiseDescriptor { mechanism: "WHITE_DI_SI_THERMAL_NOISE_IN_CHANNEL_TH_NOI_1", label: Some("THERMAL NOISE IN CHANNEL (TH_NOI=1)"), kind: GeneratedNoiseKind::White, equation: 40, is_current: true, branch_ordinal: None, pos: GeneratedNoiseEndpoint { local_node: Some(4), name: "di", is_internal: true }, neg: GeneratedNoiseEndpoint { local_node: Some(5), name: "si", is_internal: true }, table_len: 0, table_log_interp: false },
    GeneratedNoiseDescriptor { mechanism: "FLICKER_DI_SI_FLICKER_NOISE_IN_CHANNEL", label: Some("FLICKER NOISE IN CHANNEL"), kind: GeneratedNoiseKind::Flicker, equation: 41, is_current: true, branch_ordinal: None, pos: GeneratedNoiseEndpoint { local_node: Some(4), name: "di", is_internal: true }, neg: GeneratedNoiseEndpoint { local_node: Some(5), name: "si", is_internal: true }, table_len: 0, table_log_interp: false },
    GeneratedNoiseDescriptor { mechanism: "WHITE_NOI_GND_AUXILIARY_NOISE_SOURCE_FOR_CORRELATION_CORRELATED_PART_NQS_NOI_1", label: Some("AUXILIARY NOISE SOURCE FOR CORRELATION, CORRELATED PART (NQS_NOI=1)"), kind: GeneratedNoiseKind::White, equation: 43, is_current: true, branch_ordinal: None, pos: GeneratedNoiseEndpoint { local_node: Some(10), name: "noi", is_internal: true }, neg: GeneratedNoiseEndpoint { local_node: None, name: "0", is_internal: false }, table_len: 0, table_log_interp: false },
    GeneratedNoiseDescriptor { mechanism: "FLICKER_BI_GND_INDUCED_BULK_NOISE_NQS_NOI_1", label: Some("INDUCED BULK NOISE (NQS_NOI=1)"), kind: GeneratedNoiseKind::Flicker, equation: 46, is_current: true, branch_ordinal: None, pos: GeneratedNoiseEndpoint { local_node: Some(7), name: "bi", is_internal: true }, neg: GeneratedNoiseEndpoint { local_node: None, name: "0", is_internal: false }, table_len: 0, table_log_interp: false },
    GeneratedNoiseDescriptor { mechanism: "WHITE_GI_GND_GATE_SHOT_NOISE", label: Some("GATE SHOT NOISE"), kind: GeneratedNoiseKind::White, equation: 47, is_current: true, branch_ordinal: None, pos: GeneratedNoiseEndpoint { local_node: Some(6), name: "gi", is_internal: true }, neg: GeneratedNoiseEndpoint { local_node: None, name: "0", is_internal: false }, table_len: 0, table_log_interp: false },
    GeneratedNoiseDescriptor { mechanism: "FLICKER_GI_GND_GATE_FLICKER_NOISE", label: Some("GATE FLICKER NOISE"), kind: GeneratedNoiseKind::Flicker, equation: 48, is_current: true, branch_ordinal: None, pos: GeneratedNoiseEndpoint { local_node: Some(6), name: "gi", is_internal: true }, neg: GeneratedNoiseEndpoint { local_node: None, name: "0", is_internal: false }, table_len: 0, table_log_interp: false },
];

impl Instance {
    pub fn evaluate_noise_sources(&self, ctx: &GeneratedEvalContext<'_>, visitor: &mut dyn GeneratedNoiseVisitor) -> Result<(), GeneratedNoiseEvaluationError> {
        if !self.multiplicity.is_finite() || self.multiplicity <= 0.0 {
            return Err(GeneratedNoiseEvaluationError::InvalidMultiplicity { value: self.multiplicity });
        }
        let mut prepared = [0.0; 215];
        let produced = canonical_model_preprocess(
            &self.params.values,
            &self.param_given[..],
            self.multiplicity,
            &prepared[..],
            ctx.temperature(),
            ctx.thermal_voltage(),
        );
        install_generated_stage_values(&mut prepared[..], &produced, &CANONICAL_MODEL_STAGE_SLOTS);
        let produced = canonical_instance_preprocess(
            &self.params.values,
            &self.param_given[..],
            self.multiplicity,
            &prepared[..],
            ctx.temperature(),
            ctx.thermal_voltage(),
        );
        install_generated_stage_values(&mut prepared[..], &produced, &CANONICAL_INSTANCE_STAGE_SLOTS);
        let produced = canonical_temperature_preprocess(
            &self.params.values,
            &self.param_given[..],
            self.multiplicity,
            &prepared[..],
            ctx.temperature(),
            ctx.thermal_voltage(),
        );
        install_generated_stage_values(&mut prepared[..], &produced, &CANONICAL_TEMPERATURE_STAGE_SLOTS);
        let parameters = &self.params.values;
        let temperature = ctx.temperature();
        let staged = &prepared[..];
        let node_potentials = [ctx.node_voltage(self.nodes[0]), ctx.node_voltage(self.nodes[1]), ctx.node_voltage(self.nodes[2]), ctx.node_voltage(self.nodes[3]), ctx.node_voltage(self.nodes[4]), ctx.node_voltage(self.nodes[5]), ctx.node_voltage(self.nodes[6]), ctx.node_voltage(self.nodes[7]), ctx.node_voltage(self.nodes[8]), ctx.node_voltage(self.nodes[9]), ctx.node_voltage(self.nodes[10])];
			let A = 0f64;
			let B = 1f64;
			let C = parameters[24];
			let D = 2f64;
			let E = parameters[3];
			let F = parameters[11];
			let G = staged[21];
			let H = staged[79];
			let J = 0.5f64;
			let K = staged[178] != 0.0;
			let L = staged[179] != 0.0;
			let M = staged[180] != 0.0;
			let N = staged[181] != 0.0;
			let O = 3f64;
			let P = staged[50];
			let Q = temperature;
			let S = staged[29];
			let V = staged[78];
			let W = 4f64;
			let Y = staged[72];
			let Z = staged[159];
			let AA = staged[160];
			let AB = staged[73];
			let AC = staged[75];
			let AD = staged[68];
			let AE = staged[35];
			let AF = staged[157] != 0.0;
			let AG = 0.3333333333333333f64;
			let AH = 0.6666666666666666f64;
			let AI = staged[71];
			let AJ = staged[43];
			let AK = staged[31];
			let AL = node_potentials[7];
			let AV = staged[36];
			let AX = 1e-6f64;
			let BF = staged[41];
			let BI = staged[38];
			let BZ = 0.25f64;
			let CG = 1e-4f64;
			let CM = staged[45];
			let CR = staged[184] != 0.0;
			let CS = staged[49];
			let DM = staged[55];
			let DN = staged[58];
			let DO = staged[51];
			let DT = staged[56];
			let HE = parameters[83];
			let HG = parameters[86];
			let HM = 1e-3f64;
			let HT = staged[134];
			let HU = staged[135];
			let HV = staged[205] != 0.0;
			let HX = staged[206] != 0.0;
			let HZ = staged[207] != 0.0;
			let IB = staged[208] != 0.0;
			let ID = staged[209] != 0.0;
			let JU = 1e-24f64;
			let JZ = staged[212] != 0.0;
			let LC = staged[171];
			let LF = 1e-54f64;
			let MD = parameters[17];
			let MF = parameters[100];
			let MI = -2f64;
			let I = H * G;
			if K {
				if !L {
					if M {
						loop {
							if !N {
								break;
							}
						}
					}
				}
			}
			let R = 1.3807e-23f64 * Q;
			let T = Q - staged[5];
			let U = T * T;
			let X = 5.5228e-23f64 * Q;
			let AM = node_potentials[5] - AL;
			let AN = node_potentials[4] - AL;
			let AO = node_potentials[6] - AL;
			let AP = (F * AN) >= (F * AM);
			let AQ;
			let AR;
			if AP {
				AQ = B;
				AR = A;
			} else {
				AQ = A;
				AR = B;
			}
			let AS = (F * ((AQ * AN) + (AR * AM))) / S;
			let AT = (F * ((AQ * AM) + (AR * AN))) / S;
			let AU = (F * AO) / S;
			let AW = AK + AT;
			let AY = AK + AS;
			let AZ = staged[32] * (((J * (AW + (((AW * AW) + AX).sqrt()))).sqrt()) + ((J * (AY + (((AY * AY) + AX).sqrt()))).sqrt()));
			let BA = B - AZ;
			let BB = AV + (AE * ((BA - AZ) + staged[34]));
			let BC = staged[37] * BA;
			let BD = BC / AV;
			let BE = BC / BB;
			let BG = BD * BD;
			let BH = BE * BE;
			let BJ = AU - BI;
			let BK = BJ / AV;
			let BL = BJ / BB;
			let BM = BJ / staged[39];
			let BN = BK * J;
			let BO = BN - (O * (B + (BD * 0.7071067811865476f64)));
			let BP = 6f64 * BK;
			let BQ = BO + (((BO * BO) + BP).sqrt());
			let BR = BN - staged[40];
			let BS = BR + (((BR * BR) + BP).sqrt());
			let BT = BJ < A;
			let CF;
			let CJ;
			if BT {
				let BU = (BQ - BK) / BD;
				let BV = -(((B - BQ) + (BU * BU)).ln());
				let BW = (BS - BK) / BF;
				let BX = -(((B - BS) + (BW * BW)).ln());
				CF = BV;
				CJ = BX;
			} else {
				let BY = B - ((-BQ).exp());
				let CA = (((BL - BY) + (BH * BZ)).sqrt()) - (BE * J);
				let CB = (CA * CA) + BY;
				let CC = B - ((-BS).exp());
				let CD = (((BM - CC) + (staged[42] * BZ)).sqrt()) - (BF * J);
				let CE = (CD * CD) + CC;
				CF = CB;
				CJ = CE;
			}
			let CH = CF - CG;
			let CI = (J * ((CF + CG) + (((CH * CH) + 0.01f64).sqrt()))).sqrt();
			let CK = CF - AJ;
			let CL = BB + (BC / (D * CI));
			let CN = AT - AS;
			let CO = J * ((AT + AS) - (((CN * CN) + CM).sqrt()));
			let CP = CK - CO;
			let CQ = J * ((CK + CO) - (((CP * CP) + CM).sqrt()));
			let CU = if CR {
				A
			} else {
				let CT = (staged[48] * (D + ((staged[46] * CQ) / staged[47]))) * ((((CS + AT) - CQ) * ((CS + AS) - CQ)).sqrt());
				CT
			};
			let CV = CK + CU;
			let CW = (CV - AT) / P;
			let CX = CW > -0.6f64;
			let DH = if CX {
				let CY = BZ * ((CW - 1.4f64) + (((CW * (CW - 0.394036f64)) + 9.662671f64).sqrt()));
				let CZ = D * CY;
				let DA = (CW - (CZ + (CY.ln()))) / (CZ + B);
				let DB = (CY * (B + (DA * (B + (0.07f64 * DA))))) * P;
				DB
			} else {
				let DC = J * ((CW - 0.201491f64) - (((CW * (CW + 0.402982f64)) + 2.446562f64).sqrt()));
				let DD = DC.exp();
				let DE = D * DD;
				let DF = (CW - (DE + DC)) / (DE + B);
				let DG = (DD * (B + (DF * (B + (0.483f64 * DF))))) * P;
				DG
			};
			let DI = DH * DH;
			let DJ = DI + DH;
			let DK = DJ + BZ;
			let DL = DH + J;
			let DP = DO * DH;
			let DQ = (DO * DJ) / ((staged[52] + DP) + ((staged[53] + (W * DP)).sqrt()));
			let DR = DH - DQ;
			let DS = DR * DR;
			let DU = (CK - ((((D * DQ) + (DQ.ln())) * (B + (DM * DR))) / (((B + ((staged[57] * DS) / (0.1f64 + (DT * DR)))) + (DN * DS)).sqrt()))) - AT;
			let DV = DU - O;
			let DW = J * ((DU + O) + (((DV * DV) + W).sqrt()));
			let DX = DH + B;
			let DY = AS - AT;
			let DZ = W * ((staged[59] * ((W * DQ) + parameters[65])) / DX);
			let EA = DY * ((B + (DZ / DW)).sqrt());
			let EB = EA + DW;
			let EC = DZ * DW;
			let ED = EA - DW;
			let EE = (J * ((((EB * EB) + EC).sqrt()) - (((ED * ED) + EC).sqrt()))) + AT;
			let EF = staged[61] * (AS - EE);
			let EG = staged[66] * ((((staged[63] + EF) + ((((EF * EF) + (staged[64] * EF)) + B).sqrt())) / staged[65]).ln());
			let EH = (CV - EE) / P;
			let EI = EH > -0.6f64;
			let ES = if EI {
				let EJ = BZ * ((EH - 1.4f64) + (((EH * (EH - 0.394036f64)) + 9.662671f64).sqrt()));
				let EK = D * EJ;
				let EL = (EH - (EK + (EJ.ln()))) / (EK + B);
				let EM = (EJ * (B + (EL * (B + (0.07f64 * EL))))) * P;
				EM
			} else {
				let EN = J * ((EH - 0.201491f64) - (((EH * (EH + 0.402982f64)) + 2.446562f64).sqrt()));
				let EO = EN.exp();
				let EP = D * EO;
				let EQ = (EH - (EP + EN)) / (EP + B);
				let ER = (EO * (B + (EQ * (B + (0.483f64 * EQ))))) * P;
				ER
			};
			let ET = ES * ES;
			let EU = ET + ES;
			let EV = EU + BZ;
			let EW = ES + J;
			let EX = DH + ES;
			let EY = DH - ES;
			let EZ = EY * EY;
			let FA = EX + B;
			let FB = B / (FA * FA);
			let FC = DJ - EU;
			let FD = (CF - DH) - ES;
			let FE = FD - CG;
			let FF = (J * ((FD + CG) + (((FE * FE) + 0.01f64).sqrt()))).sqrt();
			let FV = if AF {
				let FG = staged[67] + (BD / (CI + FF));
				let FH = J + ((AE * FF) / BD);
				let FI = FG / (FH + (((FH * FH) + ((FG * EX) / AD)).sqrt()));
				FI
			} else {
				let FJ = B + (BD / (CI + FF));
				FJ
			};
			let FK = BK - CJ;
			let FL = 2.121320343559643f64 * BD;
			let FO = if BT {
				let FM = BK - CF;
				FM
			} else {
				let FN = (BK / (B + AE)) - BQ;
				FN
			};
			let FP = staged[69] * BG;
			let FQ = ((BZ * FO) * FO) + FP;
			let FR = (FL * FL) + FP;
			let FS = (rspice_limited_exp((AH * ((((J * (FQ + (((FQ * FQ) + AX).sqrt()))).sqrt()) - (J * FO)).ln())))) - (rspice_limited_exp((AH * ((((J * (FR + (((FR * FR) + AX).sqrt()))).sqrt()) - FL).ln()))));
			let FT = FK + (staged[70] * FS);
			let FU = CF > D;
			let GM = if FU {
				let FW = ((AI * FV) * AG) * ((EX + DH) + (((J * ((B + (0.8f64 * DH)) + (1.2f64 * ES))) * EZ) * FB));
				FW
			} else {
				A
			};
			let GN = if FU {
				let FX = ((AI * FV) * AG) * ((EX + ES) + (((J * ((B + (0.8f64 * ES)) + (1.2f64 * DH))) * EZ) * FB));
				FX
			} else {
				A
			};
			let GP;
			if FU {
				let GQ = if AF {
					let FY = FT + ((D * DH) * AI);
					let FZ = FT + ((D * ES) * AI);
					let GA = (BZ + (FY / AD)).sqrt();
					let GB = (BZ + (FZ / AD)).sqrt();
					let GC = GA + GB;
					let GD = GC * GC;
					let GE = ((FY / (B + (D * GA))) + (FZ / (B + (D * GB)))) + (((AI * AG) * (EZ / (GD * GC))) * (((0.8f64 * (GD + (GA * GB))) / FA) + (D / AD)));
					GE
				} else {
					let GF = ((FT + DH) + ES) + (((AI * AG) * EZ) / FA);
					GF
				};
				GP = GQ;
			} else {
				let GG = CF > A;
				let GR;
				if GG {
					let GI = if AF {
						let GH = FT / (J + ((BZ + (FT / AD)).sqrt()));
						GH
					} else {
						FT
					};
					GR = GI;
				} else {
					let GJ = parameters[12] > A;
					let GL = if GJ {
						let GK = FT / (J + ((BZ - (FT / AD)).sqrt()));
						GK
					} else {
						FT
					};
					GR = GL;
				}
				GP = GR;
			}
			let GO = GM + GN;
			let GS = CL * parameters[40];
			let GT = (CL * (B - Y)) - B;
			let GU = (BE * CI) + GT;
			let GV = DL * EW;
			let GW = DL + EW;
			let GX = AC * (((GU * GU) + ((GT * GT) * ((((B + DJ) + DJ) + EU) + EU))) - ((((2.6666666666666665f64 * GT) * GU) * ((DK + GV) + EV)) / GW));
			let GY = ((B + ((AB * BE) * staged[74])) + ((AC * BH) * AJ)) / (((B + (AB * ((GP - GO) + ((Y * CL) * GO)))) + GX) + (parameters[39] / ((B + (GS * DH)) * (B + (GS * ES)))));
			let GZ = (staged[77] * GY) / (((B + (((D * staged[76]) * EZ) / (0.1f64 + (DT * EY)))) + (DN * EZ)).sqrt());
			let HA = D * FV;
			let HB = G - EG;
			let HC = (((((HA * V) * GZ) * AI) * H) / HB) * staged[28];
			let HD = HC / S;
			let HF = HE == A;
			let HK = if HF {
				B
			} else {
				let HH = (DW - DY) - HG;
				let HI = (DY - (DW - (J * (HH + (((HH * HH) + ((W * HG) * DW)).sqrt()))))) / (((B / (B + ((parameters[82] * (G.sqrt())) / (GO + D)))) / HE) * (B + ((B + (parameters[84] * G)) * (rspice_limited_exp(((parameters[85] * DY) * S))))));
				let HJ = B + HI;
				HJ
			};
			let HL = FC * (HC * HK);
			let HN = (B + (parameters[180] * T)) + (parameters[181] * U);
			let HO = staged[126] * HN;
			let HP = staged[127] * HN;
			let HQ = staged[128] * HN;
			let HR = staged[129] * HN;
			let HS = staged[130] * HN;
			let HW = if HV {
				HO
			} else {
				HM
			};
			let HY = if HX {
				HP
			} else {
				HM
			};
			let IA = if HZ {
				HQ
			} else {
				HM
			};
			let IC = if IB {
				HR
			} else {
				HM
			};
			let IE = if ID {
				HS
			} else {
				HM
			};
			let IF = X / HT;
			let IG = X / HU;
			let IH = X / HW;
			let II = X / HY;
			let IJ = X / IA;
			let IK = X / IC;
			let IL = X * (staged[140] / IE);
			let IM = D * DH;
			let IN = ((CF > A) && AF) || ((CF < A) && (staged[158] != 0.0));
			let IU;
			let JF;
			if IN {
				let IO = FT + IM;
				let IP = (BZ + (IO / AD)).sqrt();
				let IQ = J + IP;
				let IR = IO / IQ;
				let IS = (D / IQ) * (B - (IO / (((D * IP) * IQ) * AD)));
				IU = IR;
				JF = IS;
			} else {
				let IT = FT + IM;
				IU = IT;
				JF = D;
			}
			let IV = (IU.abs()) / Z;
			let IW = IV < B;
			let JA = if IW {
				let IX = (B - IV).sqrt();
				let IY = ((-AA) * ((B / (B + IX)) + IX)).exp();
				IY
			} else {
				let IZ = ((-AA) / IV).exp();
				IZ
			};
			let JB = (DH * IU) * JA;
			let JC = (AT == AS) || (IU == A);
			let JP;
			if JC {
				let JD = JB * FV;
				JP = JD;
			} else {
				let JE = (EU - DJ) / (IM + B);
				let JG = JE * ((B / DH) + (JF / IU));
				let JL;
				if IW {
					let JH = IU > A;
					let JM = if JH {
						let JI = (((JE * JF) * (AA / Z)) * (O + IV)) / (W + ((D * ((B - IV).sqrt())) * (D + IV)));
						JI
					} else {
						let JJ = ((((-JE) * JF) * (AA / Z)) * (O + IV)) / (W + ((D * ((B - IV).sqrt())) * (D + IV)));
						JJ
					};
					JL = JM;
				} else {
					let JK = ((JF * JE) * AA) / (IV * IU);
					JL = JK;
				}
				let JN = ((FV * JB) * (D + JG)) / (D - JL);
				JP = JN;
			}
			let JO = AU > BI;
			let LU;
			if JO {
				let JQ = (((((D * parameters[92]) * H) * G) * V) / staged[161]) * JP;
				LU = JQ;
			} else {
				LU = A;
			}
			let JR = X * HD;
			let JS = B + (DM * EY);
			let JT = DM * FC;
			let JV = J * JT;
			let JW = (((AG * ((DI + (DH * ES)) + ET)) + ((JT * JT) * BZ)) + ((BZ * (JT + B)) * EX)) + ((((((JT - B) * 0.125f64) * DN) * FC) * FA) * ((if JU >= (((DL - JV) / (EW - JV)).abs()) { JU } else { (((DL - JV) / (EW - JV)).abs()) }).ln()));
			let JX = JR * ((D / ((JS * JS) * FA)) * JW);
			let JY = (HD * EY) / CL;
			let LY;
			if JZ {
				let KA = (parameters[99] * ((parameters[101] * ((if JU >= (JY.abs()) { JU } else { (JY.abs()) }).ln())).exp())) / ((I * C) * AI);
				LY = KA;
			} else {
				let KB = (R * H) * HB;
				let KC = C * AI;
				let KD = (6.586429491216e-86f64 * (parameters[102] * 1.6e25f64)) / ((((KB * KC) * KC) * FV) * FV);
				let KE = ((parameters[103] * (((HA * S) * C) * AI)) * GZ) / C;
				let KF = (D * S) / (parameters[106] * HB);
				let KG = FC != A;
				let KL = if KG {
					let KH = B + (KF * EY);
					let KI = (KF * FC) / (D * KH);
					let KJ = KE / D;
					let KK = ((((B / ((D * FC) * FC)) * (FC / ((KH * KH) * KH))) * ((if JU >= ((DL - KI) / (EW - KI)) { JU } else { ((DL - KI) / (EW - KI)) }).ln())) + (KE / (DX + ES))) + (KJ * KJ);
					KK
				} else {
					A
				};
				let KM = ((KD * KL) * HL) * HL;
				let KP;
				let KQ;
				if KG {
					let KN = (parameters[104] * 2.566404e-38f64) / (((KB * C) * AI) * FV);
					let KO = (B / (DX + ES)) * (B + (((DH / ES).ln()) / (D * EY)));
					KP = KN;
					KQ = KO;
				} else {
					KP = A;
					KQ = A;
				}
				let KR = HD / ((B + ((HT * HD) * DH)) + ((HU * HD) * ES));
				let KS = (KM + (((KP * KQ) * HL) * HL)) + ((((((DI + ET) * KR) * KR) * parameters[107]) * HL) * HL);
				LY = KS;
			}
			let KT = ((GZ / C) * S) / staged[169];
			let KU = KT != A;
			let KW = if KU {
				let KV = B / KT;
				KV
			} else {
				A
			};
			let KX = GW * GW;
			let KY = KX * GW;
			let KZ = (D * (((DK - (0.75f64 * GW)) + GV) + EV)) / (O * GW);
			let LA = (((16f64 * ((DK * DK) + (EV * EV))) + ((80f64 * GV) * (EV + DK))) + ((168f64 * DK) * EV)) - (15f64 * ((DK * DL) + (EV * EW)));
			let LB = ((KW * KW) * (LA - ((75f64 * GV) * GW))) / ((staged[170] * KY) * KX);
			let LD = (LB * LC) * LC;
			let LE = ((KW / staged[172]) * ((DL - EW) * ((DK + (W * GV)) + EV))) / KY;
			let LG = LB > LF;
			let LH = if LG {
				LB
			} else {
				LF
			};
			let LI = LD > LF;
			let LJ = if LI {
				LD
			} else {
				LF
			};
			let LK = KZ > LF;
			let LL = if LK {
				KZ
			} else {
				LF
			};
			let LM = (LL != A) && (LH != A);
			let LO = if LM {
				let LN = LE / ((LL * LH).sqrt());
				LN
			} else {
				A
			};
			let LP = LL * (B - (LO * LO));
			let LQ = LP > A;
			let LR = if LQ {
				LP
			} else {
				A
			};
			let LS = LJ > A;
			let LT = if LS {
				LJ
			} else {
				A
			};
			let LV = LU > A;
			let MA;
			let MJ;
			if LV {
				let LW = 3.204e-19f64 * LU;
				let LX = (parameters[105] * LU) * LU;
				MA = LX;
				MJ = LW;
			} else {
				MA = A;
				MJ = A;
			}
			let LZ = LY / E;
			let MB = MA / E;
			let MC = E * JR;
			let ME = ((E * JX) * parameters[18]) + ((MC * LR) * MD);
			let MG = MC * MD;
			let MH = ((((JR * LT) * MD) * D) * 3.141592653589793f64) / E;
			let MK = E * MJ;
        {
            let psd = IF;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 0, quantity: "psd", value: psd }); }
            let psd = psd.abs();
            let exponent: Option<f64> = None;
            let table_operands = [];
            let psd = psd * self.multiplicity;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 0, quantity: "scaled psd", value: psd }); }
            if !visitor.visit(0, GeneratedNoiseEvaluationRef { active: true, psd, exponent, table_operands: &table_operands }) { return Ok(()); }
        }
        {
            let psd = IG;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 1, quantity: "psd", value: psd }); }
            let psd = psd.abs();
            let exponent: Option<f64> = None;
            let table_operands = [];
            let psd = psd * self.multiplicity;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 1, quantity: "scaled psd", value: psd }); }
            if !visitor.visit(1, GeneratedNoiseEvaluationRef { active: true, psd, exponent, table_operands: &table_operands }) { return Ok(()); }
        }
        {
            let psd = IH;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 2, quantity: "psd", value: psd }); }
            let psd = psd.abs();
            let exponent: Option<f64> = None;
            let table_operands = [];
            let psd = psd * self.multiplicity;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 2, quantity: "scaled psd", value: psd }); }
            if !visitor.visit(2, GeneratedNoiseEvaluationRef { active: true, psd, exponent, table_operands: &table_operands }) { return Ok(()); }
        }
        {
            let psd = II;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 3, quantity: "psd", value: psd }); }
            let psd = psd.abs();
            let exponent: Option<f64> = None;
            let table_operands = [];
            let psd = psd * self.multiplicity;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 3, quantity: "scaled psd", value: psd }); }
            if !visitor.visit(3, GeneratedNoiseEvaluationRef { active: true, psd, exponent, table_operands: &table_operands }) { return Ok(()); }
        }
        {
            let psd = IJ;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 4, quantity: "psd", value: psd }); }
            let psd = psd.abs();
            let exponent: Option<f64> = None;
            let table_operands = [];
            let psd = psd * self.multiplicity;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 4, quantity: "scaled psd", value: psd }); }
            if !visitor.visit(4, GeneratedNoiseEvaluationRef { active: true, psd, exponent, table_operands: &table_operands }) { return Ok(()); }
        }
        {
            let psd = IK;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 5, quantity: "psd", value: psd }); }
            let psd = psd.abs();
            let exponent: Option<f64> = None;
            let table_operands = [];
            let psd = psd * self.multiplicity;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 5, quantity: "scaled psd", value: psd }); }
            if !visitor.visit(5, GeneratedNoiseEvaluationRef { active: true, psd, exponent, table_operands: &table_operands }) { return Ok(()); }
        }
        {
            let psd = IL;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 6, quantity: "psd", value: psd }); }
            let psd = psd.abs();
            let exponent: Option<f64> = None;
            let table_operands = [];
            let psd = psd * self.multiplicity;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 6, quantity: "scaled psd", value: psd }); }
            if !visitor.visit(6, GeneratedNoiseEvaluationRef { active: true, psd, exponent, table_operands: &table_operands }) { return Ok(()); }
        }
        {
            let psd = IL;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 7, quantity: "psd", value: psd }); }
            let psd = psd.abs();
            let exponent: Option<f64> = None;
            let table_operands = [];
            let psd = psd * self.multiplicity;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 7, quantity: "scaled psd", value: psd }); }
            if !visitor.visit(7, GeneratedNoiseEvaluationRef { active: true, psd, exponent, table_operands: &table_operands }) { return Ok(()); }
        }
        {
            let psd = ME;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 8, quantity: "psd", value: psd }); }
            let psd = psd.abs();
            let exponent: Option<f64> = None;
            let table_operands = [];
            let psd = psd * self.multiplicity;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 8, quantity: "scaled psd", value: psd }); }
            if !visitor.visit(8, GeneratedNoiseEvaluationRef { active: true, psd, exponent, table_operands: &table_operands }) { return Ok(()); }
        }
        {
            let psd = LZ;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 9, quantity: "psd", value: psd }); }
            let psd = psd.abs();
            let exponent: Option<f64> = Some(MF);
            if let Some(value) = exponent { if !value.is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 9, quantity: "exponent", value }); } }
            let table_operands = [];
            let psd = psd * self.multiplicity;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 9, quantity: "scaled psd", value: psd }); }
            if !visitor.visit(9, GeneratedNoiseEvaluationRef { active: true, psd, exponent, table_operands: &table_operands }) { return Ok(()); }
        }
        {
            let psd = MG;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 10, quantity: "psd", value: psd }); }
            let psd = psd.abs();
            let exponent: Option<f64> = None;
            let table_operands = [];
            let psd = psd * self.multiplicity;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 10, quantity: "scaled psd", value: psd }); }
            if !visitor.visit(10, GeneratedNoiseEvaluationRef { active: true, psd, exponent, table_operands: &table_operands }) { return Ok(()); }
        }
        {
            let psd = MH;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 11, quantity: "psd", value: psd }); }
            let psd = psd.abs();
            let exponent: Option<f64> = Some(MI);
            if let Some(value) = exponent { if !value.is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 11, quantity: "exponent", value }); } }
            let table_operands = [];
            let psd = psd * self.multiplicity;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 11, quantity: "scaled psd", value: psd }); }
            if !visitor.visit(11, GeneratedNoiseEvaluationRef { active: true, psd, exponent, table_operands: &table_operands }) { return Ok(()); }
        }
        {
            let psd = MK;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 12, quantity: "psd", value: psd }); }
            let psd = psd.abs();
            let exponent: Option<f64> = None;
            let table_operands = [];
            let psd = psd * self.multiplicity;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 12, quantity: "scaled psd", value: psd }); }
            if !visitor.visit(12, GeneratedNoiseEvaluationRef { active: true, psd, exponent, table_operands: &table_operands }) { return Ok(()); }
        }
        {
            let psd = MB;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 13, quantity: "psd", value: psd }); }
            let psd = psd.abs();
            let exponent: Option<f64> = Some(B);
            if let Some(value) = exponent { if !value.is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 13, quantity: "exponent", value }); } }
            let table_operands = [];
            let psd = psd * self.multiplicity;
            if !(psd).is_finite() { return Err(GeneratedNoiseEvaluationError::NonFinite { index: 13, quantity: "scaled psd", value: psd }); }
            if !visitor.visit(13, GeneratedNoiseEvaluationRef { active: true, psd, exponent, table_operands: &table_operands }) { return Ok(()); }
        }
        Ok(())
    }
}
